### ISSUE TITLE
New Feature-- Video/Audio Playing Indicator, and a Big Thank You to Piror

### ISSUE THREAD

**Issue by alphaa10** [piroor/treestyletab#1004]
Piror-- 
Thank you for the new, default "Video/Audio Playing" (VAP) indicator. That icon, which appears only when a video clip (or audio) starts to play, is the perfect accessory to Tree Style Tab. 
Until VAP, we were forced to load Firefox with potentially dozens of open video tabs fighting for bandwidth at the same instant. Without the Video/Audio Playing indicator, starting a Firefox session could be a cacophony of voices and music. 
With VAP, we quickly can isolate which tabs are trying to play, and silence them, if desired.
Please see attached image of the new VAP indicator.
![151127 tst ver 0 16 2015 111001 shows video-audio playing](https://cloud.githubusercontent.com/assets/4928126/11448288/1ac20ccc-9523-11e5-9862-ffd405e40bf7.png)

![151127 tst ver 0 16 2015 111001 shows video-audio playing](https://cloud.githubusercontent.com/assets/4928126/11448261/90adf938-9522-11e5-8d79-46efe77c6f7d.png)

**Comment by piroor** [comment]
Could you describe the problem with the form?: "steps to reproduce", "expected result" and "actual result".

**Comment by alphaa10** [comment]
Piroor, when I emailed you before, you told me to use GitHub for all concerns. 
Today, my concern is only to thank you for a much-needed feature.
Where should we make suggestions for additional features?

**Comment by piroor** [comment]
> Piroor, when I emailed you before, you told me to use GitHub for all concerns. 

OK, I see. I think I asked you to post your bug reports or feature requests to here, because web-based tracking is better than email-based. Emails are very private, but this issue tracker is public and any people who has same request can comment to the issue. And, each issue can have its own status as "closed" or "opened" on this issue tracker - it's very required for me to manage too much topics including other my addon projects. Because it is not a simple message board or a forum, other type posts seem to be not suitable here.

> Where should we make suggestions for additional features?

If the feature request is very clear, it will help me that you post a request with the form same to a bug report: "steps to reproduce", "expected result", and "actual result". Moreover descriptions why the new feature is required and how it useful will also help me to understand its need.

**Comment by alphaa10** [comment]
OK, understood.
