### ISSUE TITLE
new tabs not visible when tab bar has a scrollbar.

### ISSUE THREAD

**Issue by justdave** [piroor/treestyletab#1006]
When you open a URL from another app, a new tab is appended to the end of the tab list, and it appears an attempt to scroll to that tab is made, however, it's off-by-one and the newly-opened tab is just below the visible viewport so you can't see it. Scrolling up the height of one tab brings it into view.  From visual appearance it looks like the scroll position is being set to the top of the tab instead of the bottom of it, so that the top edge of the tab ends up being the bottom of the viewport.

**Comment by justdave** [comment]
FWIW, this happens any time a new tab is created if there is a scrollbar present and the prefs are set to open new tabs at the bottom, no matter the source of the new tab (even Cmd+T for a new tab does it).

**Comment by piroor** [comment]
I think this can be caused on a slow environment. When there is 10 tabs with scrollbar and a new tab is just added, the height of the container box (the tab bar) is just for 10 tabs, and the new 11th tab expands the height of the tab bar slowly. If the expansion is finished before TST scrolls the tab bar to the tab, TST successfully shows the new tab in the viewport. However, if the expansion is finished after TST's smooth scroll of the tab bar is finished, TST fails to scroll the tab bar for the new tab, because the height of the tab bar is still not enough to show the new tab completely...

**Comment by piroor** [comment]
Or, if you use other tab related addon like Tab Mix Plus, it can cause this problem. Could you confirm that this happen with no other addon?

**Comment by justdave** [comment]
I don't have any other tab-related addons except for "Tab Groups" which is the old core Panorama feature just moved out of core into an addon.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
