### ISSUE TITLE
After updating TreeStyleTab from 0.15 to 0.16, buttons eating space of tab area

### ISSUE THREAD

**Issue by vi** [piroor/treestyletab#1011]
![1](https://cloud.githubusercontent.com/assets/173219/11779418/09f49f26-a26c-11e5-93ce-e36c5668b602.png)

Those are add new tab, list tabs, cloes tab and pan visible tabs buttons.

I'd prefer them to be arranged horizontally instead.

**Comment by piroor** [comment]
It's an expected behavior for toolbar items placed in the tab bar. If you see horizontally arranged items in the tab bar, it should be done by another addon.

**Comment by vi** [comment]
In 0.15 there was only one button (hence eating less space). Why has it changed in 0.16?

I see "Remove from Toolbar" in context menu of only one button (Open new tab) - the only one I actually click (because of there is Ctrl+Click and I don't know keyboard shortcut analogue). For other extra buttons I don't see "Remove from Toolbar" option...

**Comment by piroor** [comment]
It is the "all tabs" button, builtin feature of Firefox itself. Even if TST is not installed, you cannot remove the button from the tab bar, since Firefox 28.

 * [mozilla-central: browser/base/content/browser.xul@99137d6d4061 (annotated)](http://hg.mozilla.org/mozilla-central/annotate/99137d6d4061/browser/base/content/browser.xul#l576 "mozilla-central: browser/base/content/browser.xul@99137d6d4061 (annotated)")
 * [878551 – The list-all-tabs widget is missing an icon and misbehaves when moved](https://bugzilla.mozilla.org/show_bug.cgi?id=878551 "878551 – The list-all-tabs widget is missing an icon and misbehaves when moved")

**Comment by piroor** [comment]
In the screenshot (and in your description), unknown toolbar button items seems appear in your toolbar. I think they are provided by another addon.

**Comment by vi** [comment]
There are no unknown buttons on screenshots. From top to bottom, they are:

* Add new tab
* List all tabs
* Close tab (without icon)
* Pan visible tabs (left and right arrows)

Close tab is redundant (there are already close buttons near each tab). I don't use typically "List all tabs..." and panning buttons are also reduntant in presence of the scrollbar.

**Comment by piroor** [comment]
I mean that there seems to be extra buttons added by other addons, not Firefox's builtin. My Firefox doesn't have no such "Close tab" and "Pan visible tabs" buttons as customizable items. If they are provided by Tab Mix Plus or something, this problem is possibly hard to be fixed because conflict of addons is very complex issue, especially with Tab Mix Plus (because TMP is very large addon and I have very few motivation to struggle with this issue since I never use TMP...)

**Comment by vi** [comment]
I'll try to disable TabMixPlus and see again.
