### ISSUE TITLE
Feature request: having a temporary bookmark on the tree

### ISSUE THREAD

**Issue by ooker777** [piroor/treestyletab#1025]
Sometimes I have to open a bunch of links just to see which one I need to focus on. At those times, it would be nice to have a sign next to the tab I want to be back later. Something like this: 

![2016-01-19 14_47_54-issues piroor_treestyletab](https://cloud.githubusercontent.com/assets/6695517/12412940/9b9516e6-bebd-11e5-8991-0e624b0d8fd8.png)

A little star would be prettier. What do you think?

**Comment by piroor** [comment]
I think TST never implement the feature, because it is completely unrelated to the concept: "tree of tabs".

Instead it should be done by another addon which is designed to do just the thing. Then I'll make TST compatible to it. Sadly I don't know such existing addon because I didn't need such feature yet. Possibly you have to create it by yourself. Note, I created TST initially just for myself and the prime user of TST is still myself. Like me, you'll need to create new addon to satisfy yourself, if there is no existing addon.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
