### ISSUE TITLE
[Enhancement] Auto-hide Tab Bar on Width

### ISSUE THREAD

**Issue by orbisvicis** [piroor/treestyletab#1035]
I'd appreciate an option somewhat like:

```
For Normal Window Mode:
* Auto Hide tab bar when window width is less than ___ pixels
* ...
```

When I want to work with two windows side-by-side, the tab bar takes too much space. I have to right click the tab bar and select "auto-hide tab bar" when this happens, and undo the procedure when I'm done. This suggested feature would just automate this behaviour somewhat.

**Comment by piroor** [comment]
Sounds good!

**Comment by pshute** [comment]
This is exactly what I want, and for exactly the same reason. Windows 10's Snap Assist makes it very convenient to get Firefox onto half a screen, but often the Tree Style Tab menu takes up too much room at that width. Auto Hide fixes that, but it's painful to use (especially with VNC via my iPad), so I don't want it enabled when the Firefox window is wider.

The option to not Auto Hide in full screen mode (F11) is an ok workaround, but I don't particularly like working in full screen mode.

If this feature is added, it might be useful if there is an option to select a fraction of the screen width as the trigger, rather than just a pixel width.

**Comment by pshute** [comment]
I've decided to stop using full screen and "No auto hide in full screen" workaround. I don't like that I can't see the menu bar. I haven't been able to find a plugin that enables the menu bar in full screen mode. (Probably because it partly defeats the purpose of full screen mode.)

Good workaround apart from that.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
