### ISSUE TITLE
Apply "Open new blank tab as ..." option for "Ctrl-T"

### ISSUE THREAD

**Issue by mnieber** [piroor/treestyletab#1038]
Currently, to add a blank tab to a Tree, I press `Ctrl+T` to open a new tab window, and then move it into the desired Tree. What I would like to do is to right-click the Tree and choose `Add new Tab`, which should insert a blank Tab into that Tree (as a child of the Tree). This would be more direct and less fiddly.

**Comment by mnieber** [comment]
I see that I can use the option to add blank tabs always as a child of the current tab. The sequence is then to select a parent tab and then press `ctrl+t`, which is just as good.

**Comment by piroor** [comment]
Did you close this unexpectedly?

If you like, you can assign "open new child tab" to middle-click on the "+" button. Sadly, you cannot do similar config for the keyboard shortcut like Ctrl-Shift-T - it is already used for "undo close tab".

**Comment by mnieber** [comment]
I closed it because I thought I found an alternative solution, but for some reason it is not working: new blank tabs created with `ctrl+t` do not become a child of the current tab.

So yes, it might still make sense to have a context menu option to insert a blank tab, where clicking this menu option would be equivalent to clicking the tab and pressing `ctrl+t`.

**Comment by piroor** [comment]
BTW my another addon New Tab from Location Bar https://addons.mozilla.org/firefox/addon/new-tab-from-location-bar/ possibly helps you. It provides ability to open new child tab when you type an URL into the location bar.

And, if you hope to open a link or an URL text in the current page as new sibling tab, you can do it by drag  the link (or the URL text) and drop it between existing tabs.

**Comment by aldanor** [comment]
I'm trying to figure whether `Ctrl-T` could be made to open tabs as either children or sibling, whichever. 

Currently, I have it set as (new version on FF58)

```
New Tab Behaviour > Open new blank tab as > a sibling of a current tab
```

... and it doesn't seem to do anything, `Ctrl-T` would always open tabs at the very bottom of the tree. Is this to be expected?

**Comment by piroor** [comment]
The option works for the "new tab" button in the sidebar. We need to do something more for Ctrl-T case.,,

**Comment by piroor** [comment]
Currently it is impossible to know the reason why a new tab is opened. So we need to suppose to the reason from something available hints. For example: Adding new option like `[ ] Consider a new tab with the url [about:newtab (*textbox)] as "opened as new blank tab by a keyboard operation"`.

**Comment by aldanor** [comment]
Yea maybe something like that. Note that new tabs can be overridden (e.g. 'New Tab Override' extension) to something like `about:home` which is what some people prefer. For most, it would be `about:newtab` I guess.

**Comment by piroor** [comment]
Done by recent commits.

**Comment by piroor** [comment]
There is another problem that a new next sibling tab breaks tree structure, hmm...

**Comment by piroor** [comment]
Recent commits fixes the invalid positioning problem, and we've reached at the goal: Apply "Open new blank tab as ..." option for "Ctrl-T".

One left problem is: if you hit Ctrl-T multiple times quickly, then they will be uncontrolled, because such new tabs are opened with a URL "about:blank" instead of "about:newtab". Firefox always prepares one new blank tab with the URL "about:newtab" in the background for quick response, and after you actually open a new blank tab, there is no more prepared new tab. If you hit new Ctrl-T before the next "about:newtab" tab is completely prepared, Firefox opens an "about:blank" tab and loads "about:newtab" after the tab is opened. Then we cannot detect the tab is actually opened by Ctrl-T or opened by other reasons like bookmarks. (Actually new tab opened from bookmark is also created with "about:blank" URL at first.) Sadly there is no solution to resolve this problem, this is a limitation of WebExtensions API system.

**Comment by aldanor** [comment]
That's probably "ok" since spamming Ctrl-T is a questionable exercise anyway... Just out of wonder, how quickly is "quickly"?

**Comment by piroor** [comment]
Currently I have no answer - we need to research the trigger to prepare new blank tab in the background.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
