### ISSUE TITLE
Alt-enter in preferences

### ISSUE THREAD

**Issue by lalomartins** [piroor/treestyletab#1040]
In the preferences panel, there are settings for what happens when I open a new tab in a variety of ways (awesome). But the way I usually do it is with alt-enter in the address bar, and there's no setting for that :crying_cat_face: Not super high priority, but would be nice.

**Comment by piroor** [comment]
TST doesn't provide any option for the feature but my another addon "New Tab from Location Bar" https://addons.mozilla.org/firefox/addon/new-tab-from-location-bar/ provides a similar option. I hope that it may help you.

**Comment by lalomartins** [comment]
That's nice, and I'll give it a try. **But**, opening new tabs with alt-enter is built into the browser, so TST should certainly support it; I can't agree with the “out of purpose” tag. From a design perspective, there's no substantial difference between location-alt-enter and ctrl-t.

**Comment by lalomartins** [comment]
I tried the other extension. It doesn't do anything remotely like what I want.

**Comment by piroor** [comment]
The tag means "it is done by another addon" for now. (I think I should create a new tag.)

**Comment by lalomartins** [comment]
Then it's incorrect, because it's not at all done by the other addon :smile_cat:

**Comment by lalomartins** [comment]
The other extension does some clever heuristic based on whether the new URL is in the same site… or you can make it always open in a new tab. In both cases, alt inverts the behaviour (although I had to look in the source code to discover that). None of these things is what I need.

Let me try to explain the use case.

Until last week, when I was working on a project, I'd switch to that project's tab group, and work there. Opening a new tab (no matter how I do it) would almost all of the time be related to the current work, and it would open at the end of the current group, which is almost always what I want.

Now, tab groups are going away, so I'm trying alternatives. TST provides what I needed plus a lot more, so it's so far my favourite. So now, when I'm working on a project, I'll be in that project's subtree. Then, most of the interaction I do with new tabs works exactly how I want, with two exceptions:

1. When I want to look up something new, I press ctrl-L, type something, then alt-enter. This goes to the end of the tab bar; it should go to the end of the current tree level. This operation is almost completely equivalent to opening a new tab by ctrl-T, so it stands to reason it should follow the “Open new blank tab as” setting, or at least have its own preference.

2. (Unrelated to this ticket) ctrl-click/middle-click on a link opens as a child, I'd prefer a sibling.

**Comment by lalomartins** [comment]
Anyway, I'm getting used to ctrl-T instead, so not too high priority. But for consistency, I still think it should be the case.

**Comment by piroor** [comment]
OK, I agree that TST should have the option. However I won't implement it by my hand (for now), because I already created another addon "New Tab from Location Bar" which opens new child tabs without the Alt key - it is revolutionary solution for me. In my usecase, I always open new child tabs for same domain and new orphan tabs for URLs not related to the current tab. Even if the new option appear on TST, I won't use it - because I already know there is more useful solution for me. Currently I have very very less time to maintain addons, so I hope to concentrate about things I really need.

But, It is also true that not all TST users think so - including you. So I've decided to introduce new tag "need contribution" for such topics: "TST should have the feature but I have less motivation". Please fork this repository under your account, implement the feature by your hand, and send it as a pull request :) Then I'll merge it. Or, I possibly rewrite the code to match to existing codes - it will take only lesser time than implementing  it by my hand from scratch.

**Comment by lalomartins** [comment]
That's a great tag to have :+1: I might give it a shot, although Firefox code scares me. I already had a look around your sources, anyway.

Thanks.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
