### ISSUE TITLE
Bookmarks Always Open As Independent Tabs

### ISSUE THREAD

**Issue by JonnyTsGitHub** [piroor/treestyletab#1083]
## Short description

Until recently (about 2 weeks ago - might have coincided with FF 44, but I'm not 100% sure) when I opened a bookmark as a new tab it would behave according to the new tab settings in the TreeStyleTab options.  Now, however, it always opens at the bottom as an independent tab, regardless of my settings.  New blank tabs DO obey the settings.

Note: I have TabMixPlus installed and have it set to always open my bookmarks in a new tab, which is why this is particularly problematic for me - because it happens every time I open a bookmark.  It also happens when I used TabMixPlus' Duplicate Tab feature (which I very often use to start making a new tree).

That said, I have tried this with TabMixPlus disabled, and even with a new profile (using the cmdline from the guidelines) and it repros in both cases using the standard middle-click workflow.
## Steps to reproduce
1.  Set the "Open new blank tab as:" setting to "as sibling of the current tab"
2.  Select a tab at least one level deep
3.  Middle click a bookmark
## Expected result

Tab opens as a sibling of the current tab
## Actual result

Tab opens at the bottom as an independent tab
## Environment
- Platform (OS): Windows 8.1 Enterprise
- Version of Firefox: 44.0.2
- Version (or revision) of Tree Style Tab: 0.16.2016021602

**Comment by piroor** [comment]
The option "Open new blank tab as" controls new tabs opened by a keyboard shortcut Ctrl-T or left-click on the "+" button. New tabs for bookmarks won't be controlled by the option, and TST doesn't provide another option for the purpose. It's intentional. If you hope to control the location of new tabs from bookmarks, another addon is required. As you know TMP is one of choices.

I don't use TMP but I heard that latest development version of TMP includes some fixes about compatibility issue with recent versions of TST.

**Comment by Vanav** [comment]
Related to #1033.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.
