### ISSUE TITLE
Can't control if clicking on the link opens as a child or sibling

### ISSUE THREAD

**Issue by salilsurendran** [piroor/treestyletab#1090]
## Short description

I would like to control as to when I click on a link if the new tab opens as a child of the current tab or a sibling.
## Steps to reproduce
1. Go to any tab.
2. Ctrl + click on any link in that tab
3. It will always open as a child.
## Expected result

I would like to have an option in the preferences where I can do a  click and the new tab opens as a sibling.
## Actual result

Always opens as a child tab
## Environment
- Platform (OS): Mac
- Version of Firefox: 45.0
- Version (or revision) of Tree Style Tab: 0.17.2016030402

**Comment by Ainoss** [comment]
It will be perfect if user could control in which position (child or sibling) link in new tab will be opened. For example, additional context menu button **Open as a child tab**. Now I found only preference `extensions.treestyletab.autoAttach.fromCurrent` , but it is global option, not useful enough.
Thanks.

**Comment by piroor** [comment]
There are some secret preferences to control new tabs from links in the current tab:

 * `extensions.treestyletab.autoAttach`=`false`
 * `extensions.treestyletab.autoAttach.fromCurrent` = `2` (or `3`)

Anyway I have no plan to add any other major option like that, because I won't use the behavior. Currently these preferences are available, but they are possibly removed in the future, if something critical problem is reported around the mode.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
