### ISSUE TITLE
Focused tab text unreadable with dark themes since Gnome 3.20

### ISSUE THREAD

**Issue by jplatte** [piroor/treestyletab#1116]
## Short description

Since I upgraded to Gnome 3.20, the tab background on the focused tab is way too light. Also, the tab separators have a very high contrast to the tab background, which I'm pretty sure wasn't the case before and doesn't look very good. This only happens with dark themes.

## Steps to reproduce

1. Install Tree Style Tab on arch linux (should also work on other distros with Gnome 3.20).
2. Enable a dark theme:
   * Enable the "Global Dark Theme" option in gnome-tweak-tool with the theme being set to one that supports that option OR
   * Install [`gtk-theme-arc`][arc-pkg] and set the active theme to "Arc Dark" OR
   * Install the Firefox Theme [Arc Dark][arc-dark-ff]
3. Start Firefox

## Expected result

A slightly lighter background color for the focused tab, with the text still being white.

## Actual result

A very light background color for the focused tab, with the text still being white:

![treestyletab-arc-dark](https://cloud.githubusercontent.com/assets/951129/15092355/85923b8a-1467-11e6-96a5-16bce1283d6c.png)

## Environment

 * Platform (OS): arch linux
 * Version of Firefox: 46.0.1
 * Version (or revision) of Tree Style Tab: 0.17.2016050300a204843

[arc-pkg]: https://aur.archlinux.org/packages/gtk-theme-arc/
[arc-dark-ff]: https://addons.mozilla.org/de/firefox/addon/arc-dark-theme/

**Comment by slizzered** [comment]
Happens also with **light** themes for me:
I can reproduce a very similar behavior with the standard *Adwaita* theme using no custom configuration at all. The focused tab is (exactly) as dark as the text.

This only happens when having the **tabs on the side** (right side in my case). When the tabs are set to the top, everything looks ok.

### Example: 

![untitled](https://cloud.githubusercontent.com/assets/903310/15406793/30e68dd4-1e08-11e6-99ac-20c860ca6dfb.png)

### Environment

 - Platform (OS): arch linux
 - Version of Firefox: 46.0.1
 - Version (or revision) of Tree Style Tab: 0.17.201605031101

**Comment by piroor** [comment]
Is this different to #1103?

**Comment by jplatte** [comment]
Oh wow, I seriously commented on the old bug report, forgot about that later and opened another one? Sorry :D
