### ISSUE TITLE
Performance and confirmation when restoring a bookmarks folder => tabs

### ISSUE THREAD

**Issue by orthoceros** [piroor/treestyletab#1154]
## Short description

Restoring a bookmark folder with many (>25) flat tabs as a tabs tree is too slow (blocks Firefox for minutes), because all tab contents are loaded immediately and simultaneously from the web.
## Steps to reproduce
- create a tab tree node
- add several child tabs (maybe hierarchical child-child-tabs...)
- bookmark the tab tree 
- later, restore the created bookmark folder with the flat tabs (by dragging&dropping it into your current tabs tree)
## Actual result
- Bookmarks are restored with the correct hierarchical structure, but all tabs start loading their contents from the web immediately.
- It takes several minutes (!) until FireFox is usable again (as 35 tabs are being loaded simultaneously...).
## Expected result
- Just restore the tabs and their title from bookmarks, without triggering the loading of their actual contents. (I.e. clone the behavior when Firefox starts and restores your last tabs, or when you restore a session using the session manager add-on: Here no tab content is loaded, before the user actually clicks on it.) This could lead to a considerable speedup...
- Optional: Additionally implement a simple confirmation question when restoring a bookmarks folder containing too many tabs. Like: "You are about to restore a tabs tree containing xx >50 tabs from a bookmark folder. Are you sure? This could take a while..." (the cutoff 50 is just a suggestion and could become a user parameter).
## Environment
- Platform (OS): Win 10 x64
- Version of Firefox: 47.0.1
- Version (or revision) of Tree Style Tab: 0.17.2016061501

PS: Thanks for TST! ;)

**Comment by piroor** [comment]
All tabs opened from bookmarks are always loaded by Firefox itself, even if you don't use TST. I think some other addons possibly help you. For example:

 * https://addons.mozilla.org/firefox/addon/max-loaded-tabs/
 * https://addons.mozilla.org/firefox/addon/load-tab-on-select/

I didn't confirmed they can work with TST or not. If you meet something errors, please report it as a compatibility issue report for TST with the addon, instead of adding new comment to this issue.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
