### ISSUE TITLE
TST working with multiprocess Firefox?

### ISSUE THREAD

**Issue by Decme** [piroor/treestyletab#1158]
Is tree style tabs compatible with multiprocess Firefox yet (e10s)?

**Comment by TheSweetLily** [comment]
Yes. Has been for a really long time.

**Comment by Decme** [comment]
Cool thanks. I'm using tab mix plus too and the TMP session manager - I've read this could be an issue, is this still the case?

**Comment by TheSweetLily** [comment]
Mh, I think I've seen some bug reports mentioned here, but I don't use those addons, so I can't really say, sorry.
You can always just try and see what happens.

**Comment by piroor** [comment]
The combination of TST with TMP's built-in session management feature is strongly unnrecommended, because TST is basically designed to work with Firefox's built-in session management feature. Because there are too many hard problems around TMP's one, I gave up to research bugs around it.

I recommend you to migrate from TMP's one to Firefox's one, because TMP's own session management seems just a legacy for too old Firefox which have no session management feature. If you still see any problem without TMP's session management, please report it to me again.

**Comment by bleedinge** [comment]
Well, I've just installed Firefox 49.0.1 and started with a clean profile and e10s works.

Now, installing the signed version of the package and restarting firefox, e10s appears as disabled.

In this thread it is mentioned that it should be working. Is it still the case?

**Comment by Fanolian** [comment]
@bleedinge In the current phrase, Firefox 49 will enable e10s only if you don't have any extensions installed, or with a very limited set of whitelisted extensions (only 9 actually). TST is not one of them.
[Souce](https://wiki.mozilla.org/Firefox/Meeting/13-Sep-2016#E10s)

You can force enable e10s if you want. Or you can wait till Firefox 50 when e10s rollout [enters the next phrase](https://wiki.mozilla.org/Electrolysis#Add-ons_Schedule)

FYI, TST may stop working with e10s again in the future due to [CPOW usages](https://bugzilla.mozilla.org/show_bug.cgi?id=1283681), but TST is now in _that_ whitelist.

**Comment by cartazio** [comment]
@Fanolian  @piroor  how do i force firefox to use e10s plus tree style both? (overall both together make firefox compelling for me to revisit :) ).

**Comment by piroor** [comment]
TST2 works with e10s.
