### ISSUE TITLE
indent/outdent a specific tab/subtree (also duplicate tab with indent)

### ISSUE THREAD

**Issue by reikred** [piroor/treestyletab#1179]
I have found myself wishing for a way more easily to control the indentation level of a tab (or a group of tabs), often after creating it . Something like the following
1. indent a tab, indent tab-and-children
2. outdent a tab, outdent-tab-and-children
3. duplicate one tab with the duplicate being indented one level

These could be available  context menu options, and perhaps also keyboard shortcuts, if that is practical
1. indent: ctrl-tab and alt-tab (w. children)
2. outdent: shift-ctrl-tab and shift_alt-tab (w.. children)
3. duplicate one tab  w. indent: maybe ctrl-c/ctrl-v?

Anyone else think this would be useful?

**Comment by zekeblue** [comment]
I do.  Takes patience and a bit of trial and error to move tabs precisely in these cases.  Your idea would make it easier.

**Comment by piroor** [comment]
Ctrl-Tab/Shift-Ctrl-Tab are already in use to switch focus on tabs. Alt-Tab/Shift-Alt-Tab also - they are handled by the platform (Windows). And other addons also provide various keyboard shortcuts. Because I don't want to dive into the hell of keyboard shortcut conflicts, I have no plan to add any extra keyboard shortcut to modify tree structures...

**Comment by piroor** [comment]
The largest reason why I have less motivation to implement such keyboard shortcuts is: generally TST is not designed for people who want to control tree structure by hand. In other words, the prime user me mainly just uses trees which are constructed by TST automatically. Of course TST supports modifications of tree structures by drag and drop of tabs, but I think that that is just an appendix feature. I hope to spend more time to fix various problems around my usecase, instead of around manual tree modifications I never do...

**Comment by piroor** [comment]
Anyway, because TST provide some APIs to modify tree structure, and you'll be able to define custom commands based on them for something another addon like KeySnail.

**Comment by reikred** [comment]
How about just optionally having the proposed tab indent/outdent functions available on the context menu? Is that also something each user should do on their own?

(sorry for the delay, I did not check responses for several days)

**Comment by piroor** [comment]
Such optional features won't be maintained by me because I don't use it. Currently I have very few time to maintain my addons, so my hands are already full with problems around features I ordinarily use. I believe that the feature you told should be implemented into a forked version of TST or a separate addon which uses TST's APIs to operate tree of tabs. When any new API (to call TST's built-in feature) is required for the feature, I'll implement those APIs if possible.

**Comment by reikred** [comment]
Okay, thanks. My skills when it comes to writing or hacking extensions are almost non-existent, unfortunately.

**Comment by piroor** [comment]
That was true for me - I was not a developer and I learned many things to maintain an abandoned addon which was made by another person and I heavily used. I hope that this becomes the first step for Firefox add-on development...

**Comment by char101** [comment]
You can use the snippets in the [wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts) with [keyconfig](https://addons.mozilla.org/en-US/firefox/addon/dorando-keyconfig/). It doesn't always work though, sometimes pressing the assigned shortcut does nothing.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
