### ISSUE TITLE
Compatability with Pale Moon?

### ISSUE THREAD

**Issue by handy1957** [piroor/treestyletab#1181]
I am using Pale Moon 26.4.0 and because of compatibility issues I am forced to use version
 0.14.2014051101.1-signed

The only problem I have found is that when dragging a tab to another monitor it no longer 
opens in the monitor it is dragged to.  You can see it dragging but 
instead it opens a new window in the main monitor that Pale Moon is residing in.

If I disable Tree Style Tab 0.14.2014051101.1-signed the behavior corrects itself.

If I create a new profile and install just Tree Style Tab 0.14.2014051101.1-signed 
I can recreate the issue.  If I uninstall the problem ceases.

My environment is Windows XP Pro SP3 using Pale Moon 26.4.0

Is it possible to fix this for Pale Moon, or to actually make the newest version available for Pale Moon?

**Comment by piroor** [comment]
Sorry, TST is not maintained for officially supported versions of Firefox. I recommend you to use TST with one of these choices:

 * Firefox ESR45.x
 * Firefox 48 and latest released version
 * Firefox 49 beta and latest beta version
 * Firefox Developer Edition (Aurora)
 * Nightly

Because Firefox introduces changes around its internal APIs and syntax of JavaScript, the cost to maintain TST for multiple versions of Firefox increases day by day. To avoid the apocalypse, I need to keep codes clean by deleting of obsolete codes for old Firefox.

If you really need TST for Pale Moon, then it is good time to fork this project.   Possibly the forked TST for Pale Moon will live long time and this TST will die in early future together with XUL..

**Comment by supermariomd** [comment]
> Sorry, TST is maintained only for officially supported versions of Firefox.
:(

> If you really need TST for Pale Moon, then it is good time to fork this project. 
We "very really" need TST for Pale Moon.

Now, for Pale Moon ver.27 is the difference on internal APIs and syntax of JavaScript with Firefox?

**Comment by piroor** [comment]
Forked version of TST for Pale Moon is now available:
https://github.com/oinkin/treestyletab
https://github.com/oinkin/treestyletab/releases
