### ISSUE TITLE
Strange style for pinned tabs using Metal theme

### ISSUE THREAD

**Issue by talklittle** [piroor/treestyletab#1191]
## Short description
The pinned tab style, using Metal theme, becomes squashed when clicked.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set the TST Metal theme.
 4. Pin a tab.
 5. Click pinned tab.

## Expected result
The tab should be highlighted and remain same size.

## Actual result
The pinned tab gravity and size changes.

Before click:
<img width="206" alt="screen shot 2016-09-12 at 1 21 53 pm" src="https://cloud.githubusercontent.com/assets/87961/18451569/5c821e24-78ec-11e6-8fca-60e77e731d78.png">

After click:
<img width="209" alt="screen shot 2016-09-12 at 1 22 05 pm" src="https://cloud.githubusercontent.com/assets/87961/18451579/673e6b6a-78ec-11e6-88c4-55224986c7df.png">

## Environment

 * Platform (OS): OSX 10.11.6
 * Version of Firefox: 48.0.1 and 50.0a2
 * Version (or revision) of Tree Style Tab: 0.18.2016090802 and Nightly "12-Sep-2016 01:12"

**Comment by piroor** [comment]
I is a hard problem to be solved by me, because I have no ordinarily accessible macOS machine for now. So I need contribution from macOS users themselves. FYI: The appearance of tab elements are controlled by CSS rules, and you can inspect what CSS declarations are actually applied now, via the Browser Toolbox. (See MDN to know how to activate it.)

**Comment by talklittle** [comment]
Thanks for the advice. I will attempt to debug further. I found out it is also occurring on Ubuntu 16.04.
