### ISSUE TITLE
White window title on FirefoxDeveloperEdition's dark theme

### ISSUE THREAD

**Issue by nikolay** [piroor/treestyletab#1196]
## Short description

After I installed the add-on, all window titles are now white (they were dark before).
## Steps to reproduce
1. Install FirefoxDeveloperEdition
2. Install TST
## Expected result
- Dark window titles
## Actual result
- White window titles
## Environment
- Platform (OS): macOS 10.12 Sierra
- Version of Firefox: FirefoxDeveloperEdition v50.0a2 (2016-09-13)
- Version (or revision) of Tree Style Tab: 0.18.2016090802

**Comment by piroor** [comment]
Is this same to #1186 ?

**Comment by nikolay** [comment]
@piroor Not the same. It should look all dark like here: https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/press-uk/files/2014/11/FirefoxBrowser-DevEdition.jpg

**Comment by nikolay** [comment]
And now it's all white with no full-screen button: http://d.pr/i/1je26/1gacC6d7

**Comment by piroor** [comment]
Does this problem appear on lately update, or it exists for a long time?

I think that the main "problem" is inevasible from the disabled "tabs in titlebar" feature which is blocked by TST. Because TST moves the tab bar from the top of the window to aside, the navigation toolbar moves up to the top of the window, and some window buttons (closebox, etc.) become unclickable. To prevent such a problem, we have two choices: 1) disable the "tabs in titlebar" feature totally, or 2) apply pretty styling for such cases. TST basically does the 1st choice because I cannot write well-tested styling rules for all supported platforms Windows/macOS(OS X)/Linux and all supported versions of Firefox (45 ESR, 48, 49 beta, 50 aurora, and 51 nightly.)

However, recently I've added a secret preference `extensions.treestyletab.blockTabsInTitlebar` to allow TST to activate the "tabs in titlebar" mode. If you like, turn it to `false` then you'll get a black title bar filled with the navigation bar. And then you'll have to write your custom userChrome.css to insert extra margin between the window top and the stage.

**Comment by nikolay** [comment]
@piroor I agree that it's too much work, but setting it to `false` actually breaks the whole thing: http://d.pr/i/1bKJN/54qyeTBO

**Comment by piroor** [comment]
Hmm. Then I need contribution about this problem.

from https://github.com/piroor/treestyletab/issues/1191#issuecomment-246541859 :

> It is a hard problem to be solved by me, because I have no ordinarily accessible macOS machine for now. So I need contribution from macOS users themselves. FYI: The appearance of tab elements are controlled by CSS rules, and you can inspect what CSS declarations are actually applied now, via the Browser Toolbox. (See MDN to know how to activate it.)

**Comment by nikolay** [comment]
@piroor I am not using the metal theme though - I'm using the theme's default.

**Comment by piroor** [comment]
The comment describes only two things: my current status (I cannot solve this problem by my hand for now) and how to inspect Firefox UI by your hand to know the reason why it is broken.

**Comment by piroor** [comment]
And I hope to merge any patch to solve this problem...

**Comment by nikolay** [comment]
@piroor Thanks for your great plugin! I will try to see if I can do it myself!

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
