### ISSUE TITLE
Feature request: placeholder tabs

### ISSUE THREAD

**Issue by theres-waldo** [piroor/treestyletab#1197]
It would be really nice if Tree Style Tab would allow the creation of "placeholder tabs". These would look just like tabs in the tab tree, but instead of being actual tabs, they would just have an editable label that would show up in place of the website title.

This would allow categorizing your real tabs into named categories, with the placeholder as root.

Placeholder tabs couldn't be activated, as there is no website backing them.

**Comment by tuvok** [comment]
I just wanted to request exactly same thing and found this request from 16h ago :)

I have tons of open tabs. Many of them left there, to remember to do something later, or to buy something when the right time comes - I use tabs instead of bookmarks, it's more natural just to leave something open.

Possibility of making tab categories / directories as requested above would be a great feature. I imagine, that while working on one thing I could open new tabs below such category-tab, and hold stuff connected to one topic in one place.

**Comment by GDXN** [comment]
they exist, create tab and put in the url: "about:treestyletab-group"

**Comment by tuvok** [comment]
Thank you very much :)
I've just checked and yes, in fact it works... and it's awesome.

**Comment by theres-waldo** [comment]
Yes, about:treestyletab-group is exactly what I was looking for. Thanks a lot!
