### ISSUE TITLE
Appearence for the left (?)

### ISSUE THREAD

**Issue by GeekinaCave** [piroor/treestyletab#1213]
Hi, there is any way of invert appearance of tabs but for the leftside vertical tab bar, for tabs be indented from left side?

**Comment by piroor** [comment]
Do you mean: activate "Invert tab appearance" not only for the rightside tab bar but also for leftside tab bar? Then I won't add the option because "inverted leftside tab bar" seems very odd. Rightside and non-inverted tab bar is also odd so I implemented the inverted appearance feature only for rightside in old days as an option instead of fixed behavior, to allow people to deactivate the hacky feature to avoid problems from unexpected reasons. So I have no reason to introduce such an odd appearance for leftside tab bar.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
