### ISSUE TITLE
Show regular tab bar on auto hide

### ISSUE THREAD

**Issue by laggingreflex** [piroor/treestyletab#1232]
Autohide currently hides the tab view completely. Would it be possible to switch to the regular tab bar (at the top) when this happens?

**Comment by piroor** [comment]
It is impossible because TST doesn't provide extra vertical tab bar, instead it just rotates the Firefox's tab bar from horizontal to vertical.

**Comment by laggingreflex** [comment]
I see. Could there be an option to rotate (from left to top) on autohide then? I know it's in the options.. but somehow it could happen automatically and in link to the autohide option?

**Comment by chronometric** [comment]
@laggingreflex Not a bad idea, I can see how you might want to save some horizontal real estate if you only have one or two tabs open. My first reaction was to wonder how many people would "go back" to non-vertical/hierarchical tabs in this way, but I can picture myself doing this...if my FF wasn't filled with 600 tabs at all times ^^;

Since the good piroor doesn't go for shortcut buttons, I'll suggest you look into **Autohotkey** if you want to pursue this. It's basically an (incredibly powerful) keyboard-shortcut-based macro engine. And there's almost always several ways to make it automate some kind of windows function, if you're willing to research and/or experiment.

To give you a broad idea, to address this need, you might create a keyboard shortcut to execute:

> 1. Enter the Addon options by ALT-T to get into Tools menu and press down or A / shortcut CTRL+SHIFT+A
> 2. Click on TST options by
>>2a. Clicking on the "Extensions" tab button via bitmap screenscan recognition, or other shortcut I don't know
>>2b. TAB x4, then "down arrow" X number of times to get to TST / or bitmap screenscan search combined with scrolling
>>2c. TAB x3 to "Options," then SPACE
> 3. In TST options: left/right to "New Tab" tab, then TAB down the radio buttons to "Open in a Tree," then down arrow to the FF default (horizontal).

You might even be able to rig up something automatic by grepping or scanning one of the tab count plugins, to automatically switch to horizontal tabs if it matches a number from, say, 1-4. 

Autohotkey can be pretty daunting, with info in forums, guides, articles, blogs, videos, and repositories. I just chanced on a curated list called [awesome-AutoHotkey](https://github.com/ahkscript/awesome-AutoHotkey), which has a really excellent list of links for beginning and comprehensive study.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
