### ISSUE TITLE
Child tabs shrink when drag & drop parent tab to bookmark menu

### ISSUE THREAD

**Issue by kkot** [piroor/treestyletab#1237]
## Short description

When parent tab is dragged to bookmark menu child tabs are shrinked to very small height (2px).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some page.
 4. Create sub tabs by opening links in tabs.
 5. Drag and drop parent tab to bookmark menu.
 6. Choose that only parent tab should be bookmarked.

## Expected result

Child tabs stay as they were.

## Actual result

![Screenshot](http://i.imgur.com/xruKCkx.png)

## Environment

 * Platform (OS): 
 * Version of Firefox: 
50.0, 51.0beta, 52.0a2
 * Version (or revision) of Tree Style Tab: 
2016111701, also nightly (13-Dec-2016)

**Comment by kkot** [comment]
I tested it on nightly build from 13-Dec-2016 and bug is still there.

**Comment by piroor** [comment]
It was an experimental feature introduced at the last released version, but I've removed the "shrink" behavior by the commit 6bed204 because it is too troublesome. Instead, now dragged tree is automatically collapsed while dragging. You can disable the behavior: go to `about:config` and set `extensions.treestyletab.shrinkOtherDraggedTabs` to `false`.
