### ISSUE TITLE
would you merge: "Reload Tab(s)" / normal pinned tab PRs?

### ISSUE THREAD

**Issue by colemickens** [piroor/treestyletab#1247]
If I sent a PR for reloading a tab or a set of selected tabs, would you consider it, or not interested?

Also, same question if I made it so that pinned tabs wouldn't turn into a tiny square and instead... had some other visual indicator? Basically they stay a full row like other tabs, but still have "pinned tab" semantics. Maybe just a `&emdash;` before the `<title>` of the tab?

(Thanks for this extension, by the way!)

**Comment by piroor** [comment]
> If I sent a PR for reloading a tab or a set of selected tabs, would you consider it, or not interested?

"Reload This Tree" menuitem in the tab context menu may be merged. However, I think that my another addon "Multiple Tab Handler" may help you to reload selected multiple tabs.

> Also, same question if I made it so that pinned tabs wouldn't turn into a tiny square and instead... had some other visual indicator? Basically they stay a full row like other tabs, but still have "pinned tab" semantics. Maybe just a &emdash; before the <title> of the tab?

You'll see unfaviconized pinned tabs with a secret preference. Go to "about:config" and set `browser.sessionstore.restore_pinned_tabs_on_demand` to `false`. And you'll be able to use userChrome.css to change appearance of such pinned tabs. How about that?

**Comment by colemickens** [comment]
The "Multiple Tab Handler" extension seems to add a lot, but I think it will be fine.

As for the `restore_pinned_tabs_on_demand` seems to just change the behavior of when the tab content is reloaded after the browser is reset. Based on this thread on reddit, it seems hard to achieve what I want: https://www.reddit.com/r/firefox/comments/228y84/change_width_of_pinned_tabs/

But it seems you understood my intent, since "unfaviconized pinned tabs" is exactly what I want, so maybe it is still possible?

**Comment by CrashNBurn71** [comment]
@colemickens I think piro meant, change "*extensions.treestyletab.pinnedTab.faviconized*" to **false**

Multiple Tab Handler basically adds the ability to perform most any tab-action on Trees or  Selected Tabs. *Tree Style Tab* without MTH isn't nearly as slick and useful.  

e.g. Collapse a Tree, <Long|Slow click> on the Tree Parent, The Parent Tab and all of it's children are *selected*. As well you can set the *selection context-menu* to always show after a selection is made.

Since MTH is also by Piro, there's rarely if ever any conflict between them, and they basically made to work together. Unfortunately MTH's Copy URL/Title is currently broken.

**Comment by colemickens** [comment]
MTH = good enough for my needs.

I'm going to assume that this preference (`extensions.treestyletab.pinnedTab.faviconized`) is the one I was seeking.

With that, my wants are already satisfied so I'll close this. Thanks for the great pair of extensions @piroor
