### ISSUE TITLE
Fix support with Firefox Tab Center feature in Tree Style Tab extension

### ISSUE THREAD

**Issue by MurzNN** [piroor/treestyletab#1255]
Mozilla starts test pilot with vertical tabs here https://testpilot.firefox.com/experiments/tab-center
And  Tree Style Tab extension don't work with them. 
Can you add support Tree Style Tab extension with this new Firefox feature?

**Comment by piroor** [comment]
I won't make TST compatible with Tab Center from some reasons.

 * Tab Center is not an WebExtensions addon (for now) and it will be restructured or abandoned until Firefox 57. The cost to support Tab Center will come to nothing soon.
 * TST and Tab Center totally conflict to each other because both addons try to modify appearance of the tab bar from horizontal to vertical. If they become compatible, that means TST is completely redesigned as an extension for Tab Center itself. In other words, new TST for TC won't be an independent addon. Instead, it will be just a patch to solve the issue: https://github.com/bwinton/TabCenter/issues/989

**Comment by piroor** [comment]
And I hope to migrate TST to WebExtensions. It is tracked at #1224.
