### ISSUE TITLE
Mute tab is broken

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [piroor/treestyletab#1290]
## Short description
Muting the sound in the tab does not work.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Restart Firefox.
 4. In the context menu of the tab, mute the sound.

## Expected result
The sound in the tab is turned off, the icon of the deactivated speaker appears.

## Actual result
Nothing.

## Environment

 * Platform (OS): Ubuntu Linux 17.04
 * Version of Firefox: 54.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 0.19.2017061601

**Comment by piroor** [comment]
This doesn't happen for me. My environment's information from about:support:

~~~
Application Basics
------------------

Name: Firefox
Version: 54.0.1
Build ID: 20170613123534
Update Channel: default
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
OS: Linux 4.4.0-77-generic
Multiprocess Windows: 1/1 (Enabled by default)
Google Key: Found
Mozilla Location Service Key: Found
Safe Mode: false


Extensions
----------

Name: Application Update Service Helper
Version: 2.0
Enabled: true
ID: aushelper@mozilla.org

Name: Firefox Screenshots
Version: 6.6.0
Enabled: true
ID: screenshots@mozilla.org

Name: Multi-process staged rollout
Version: 1.50
Enabled: true
ID: e10srollout@mozilla.org

Name: Pocket
Version: 1.0.5
Enabled: true
ID: firefox@getpocket.com

Name: Tree Style Tab
Version: 0.19.2017061601
Enabled: true
ID: treestyletab@piro.sakura.ne.jp

Name: Web Compat
Version: 1.1
Enabled: true
ID: webcompat@mozilla.org
~~~

**Comment by piroor** [comment]
Hmm, could you confirm that "Mute Tab" works correctly without TST again?

And, could you research with the Browser Console (Ctrl-Shift-J)? Steps:

 1. Start Firefox.
 2. Ctrl-Shift-J to open the Browser Console.
 3. Load any page which play any audio.
 4. Start to play any audio to activate the "Mute" menuitem.
 5. Click a trashbox icon in the browser console to clear old output.
 6. Right-click on the tab and choose "Mute Tab".

If you see any output in the console after 6th step, please copy them and paste to here. Otherwise, please retry with debug output of TST: go to "about:config" and set "extensions.treestyletab.debug.all" to "true". Then you'll see more output, so please try above 6 steps again.

**Comment by MMeent** [comment]
This is something that happens to me as well. FF 54, TST latest stable (0.19.2017061601).

It does not mute the tab if it is not playing any sound at the moment, which is behaviour that works in unmodded firefox (though I last tested this in FF 53)

**Comment by piroor** [comment]
I misunderstood that the problem appears while I'm playing any sound. *Before* playing sound, the "Mute" command doesn't work with TST. Thanks!

**Comment by piroor** [comment]
9dd39ce should fix this.

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
Please, issue a fix, otherwise this error makes MuteLinks (https://addons.mozilla.org/ru/firefox/addon/mutelinks/) unworkable.

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
Thanks, now works correctly.
