### ISSUE TITLE
Sudden Change in New Tab Creation

### ISSUE THREAD

**Issue by Pops-Hosting** [piroor/treestyletab#1294]
## Expected result
CRM should open up in new parent tab.

## Actual result
CRM opens in child of current tab.

## Environment

 * Platform (OS): Windows 7 Enterprise
 * Version of Firefox: 52.2.0 (32-bit)
 * Version (or revision) of Tree Style Tab: Latest (auto updates)

**Comment by sumyungguy** [comment]
Please give steps to reproduce the problem. Is there some addon, that makes the tabs open? Do you have Tab Mix Plus or similar addon installed?

**Comment by zaroth** [comment]
I might add to this issue, as it also popped up for me recently. The cause, after narrowing down installed add-ons, turned out to be FVD Speed Dial: https://addons.mozilla.org/en-US/firefox/addon/fvd-speed-dial/ . 

Confirmed it by creating a fresh Firefox profile with:

- just Tree Style Tab installed - TST new tab settings work as expected
- both TST and FVD SD installed - TST new tab always opens as child, regardles of setting

Since I had to choose between these conflicting add-ons, the choice was easy - as no other add-on comes close to usefulness of TST for me. However it is quite inconvenient, since these 2 add-ons have worked together without issues for me for years. The problem started after an update earlier this year, I think maybe around February...? Not sure

**Comment by sumyungguy** [comment]
I briefly looked at the source code for FVD Speed Dial, but I wasn't able to understand how they're opening tabs, and I don't want to install it to test because it changes a lot of about:config settings.

It might be related to issue #1264. One thing you could try is to check your setting of "When you open a link in a new tab, switch to it immediately" in Preferences-->General. If tabs open as a child when it's checked, but as independent when it's not, then it's probably #1264.

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
