### ISSUE TITLE
Use photon icons for media elements

### ISSUE THREAD

**Issue by Keith94** [piroor/treestyletab#1375]
Any chance you could add the native photon icons for mute/unmute/play ? See http://design.firefox.com/icons/viewer/#media

**Comment by piroor** [comment]
Because some TST themes use system color, fixed-dark icons will become invisible in some environment. The most effective solution "context-fill" is not available yet by default (see also #1326 - most discussions are written in Japanese), so I think this change is premature for now.

See also:

 * [752638 - make the context-fill and context-stroke SVG paint values work in marker content](https://bugzilla.mozilla.org/show_bug.cgi?id=752638 "752638 - make the context-fill and context-stroke SVG paint values work in marker content")
 * [832483 - Let context-fill, context-stroke values be used as colours](https://bugzilla.mozilla.org/show_bug.cgi?id=832483 "832483 - Let context-fill, context-stroke values be used as colours")

**Comment by piroor** [comment]
Sorry I misunderstood totally. Now TST uses photon icons for the sound button by 36d5644.

**Comment by piroor** [comment]
I forgot to set `svg.context-properties.content.enabled` to `true` by myself... With default configuration of Firefox, those SVG icons become invisible on dark-colored themes. I've reverted changes for now.

**Comment by piroor** [comment]
Until context-fill is activated for addons, I mark this as "bug of Firefox itself" and stay open.

**Comment by piroor** [comment]
I've changed the decision. Now those icons have readable colors in the theme "Plain Dark", so I close this.
