### ISSUE TITLE
[feature request] focus last selected tab

### ISSUE THREAD

**Issue by mr-rak** [piroor/treestyletab#1385]
Please add function focus last selected tab - if close a tab, the previously selected one will be selected. This function has no alternative on WebExtensions addons.

**Comment by piroor** [comment]
I won't implement it to TST because it is not related "tree of tabs". It should be done by something separate addon, for all people including who don't want to use vertical tab bar.

By the way, TST 2.0 has an API to help such an addon working together.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#prevent-focus-changing-when-the-current-tab-is-closed

**Comment by rhendric** [comment]
For anyone else who might want this: I'm using [Select After Closing Current](https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/) with Tree Style Tab and it works great.

**Comment by piroor** [comment]
I close this because outdated.
