### ISSUE TITLE
[Bug] TST does not respect browser.tabs.warnOnCloseOtherTabs

### ISSUE THREAD

**Issue by ben-watt-es** [piroor/treestyletab#1388]
## Short description
Using the latest 2.0 nightly (as of 28/09/2017), right-clicking on the tree and selecting "Close Other Tabs" closes them all without warning. This happens on Firefox Developer and nightly editions.

Using the same context menu option in the top tab bar does bring up the warning.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Make sure browser.tabs.warnOnCloseOtherTabs and browser.tabs.warnOnClose are set to true in about:config
 4. Open some tabs
 5. Right click on the tab tree
 6. Close Other Tabs
 7. No warning is displayed

## Expected result
A warning is displayed, letting the user confirm that they want to close all other tabs

## Actual result
All other tabs are closed without warning

## Environment

 * Platform (OS): MacOS Sierra 10.12.1
 * Version of Firefox: Developer 57.0b3 (64bit), Nightly 58.0a1 (64bit)
 * Version (or revision) of Tree Style Tab:  35d2e0c ? Nightly installed on 28/09/2017

**Comment by piroor** [comment]
Dup of #1337 (there is no English description, sorry)

TST 2.0's context menu is just a fake, so we need to implement all features including the warning by self. However, I hope to remove the fake context menu feature after any new WebExtensions API to open tab context menu on sidebar tabs. Because I think these fake context menu features are just tentative solution, priority to maintain it is very row. (Instead I hope to spent more time to migrate other addons.)

**Comment by piroor** [comment]
I close this as a duplicated issue.
