### ISSUE TITLE
[feature request] Move to previously selected tab on current tab click

### ISSUE THREAD

**Issue by p0358** [piroor/treestyletab#1393]
I'd like to see a very useful feature which was available in similiar addon Tab Tree (https://addons.mozilla.org/pl/firefox/addon/tab-tree/) - option to move to previously selected tab on current tab click, it was very useful and I find it hard to use the extension without it. Shouldn't be hard to implement hopefully.

**Comment by piroor** [comment]
It won't be done by TST because it is not related to "tree". Instead it should be done by a separate addon for the purpose for every people including who don't want to use vertical tab bar.

TST provides ability to listen click event on tabs via API, so such an addon can work with TST together.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked

**Comment by piroor** [comment]
I close this because outdated.
