### ISSUE TITLE
Cannot distinguish alert-ing tabs

### ISSUE THREAD

**Issue by nanto** [piroor/treestyletab#1404]
## Short description

When a document in a background tab shows a modal dialog by `window.alert()`, `window.confirm()` or `window.prompt()`, the tab should indicate the modal dialog.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open two tabs.
 4. In one of the tabs, open web console and execute `setTimeout(() => alert('Hello'), 5000);`.
 5. Switch to another tab within 5 seconds.

## Expected result

The tab with `alert()` looks different from other tabs. (IIRC, legacy TST shows such tabs with bold font.)

## Actual result

The tab with `alert()` looks same as other tabs. (Built-in tab shows blue light below favicon.)

![image](https://user-images.githubusercontent.com/82213/31056052-caa0d9c4-a706-11e7-87cb-e549c164754c.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58.0a1 (2017-10-01) (64-bit)
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment]
It is impossible by addons for now because there is no WebExtensions API to know the change. I've filed a bug for this: [1405463 - Need ability to listen tab's highlighted status by &quot;attention&quot; via browser.tabs.onUpdated](https://bugzilla.mozilla.org/show_bug.cgi?id=1405463 "1405463 - Need ability to listen tab's highlighted status by &quot;attention&quot; via browser.tabs.onUpdated")

**Comment by piroor** [comment]
The issue was already filed as [1405463 - Need ability to listen tab's highlighted status by &quot;attention&quot; via browser.tabs.onUpdated](https://bugzilla.mozilla.org/show_bug.cgi?id=1405463 "1405463 - Need ability to listen tab's highlighted status by &quot;attention&quot; via browser.tabs.onUpdated")

**Comment by nanto** [comment]
This issue seems to be fixed. Blue light is shown on the TST's tab too.

![image](https://user-images.githubusercontent.com/82213/52912020-00975100-32ef-11e9-9ae8-6a7cd8621381.png)
