### ISSUE TITLE
Under certain conditions, tab focus switches to wrong tab

### ISSUE THREAD

**Issue by gnite** [piroor/treestyletab#1410]
## Short description

In a very particular set of circumstances the focus doesn't go where it's supposed to.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set 'Insertion position of new child tabs' to 'Insert to the top of the tree, as first child'.
 4. Open a tab (A) and at least three child tabs (let's say A1, A2, A3, where A3 is on top)
 5. Switch focus to the top most child A3
 6. Close this tab (A3)

## Expected result

Focus stays within the same level of the tree, ie. it goes to A2.

## Actual result

Focus goes up a level to its parent tab A.

## Additional information

 1. If you then go to A2 and close it, things go as they are supposed to, focus goes to A1
 2. If you first switch to any other tab before switching to A3, things go as they are supposed to, focus after closing A3 goes to A2.
 3. To summarize: this only happens when going straight to the top most tab and closing it without first going to another tab, and only with the setting mentioned in the steps. With the default settings this does not happen.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 57 dev
 * Version (or revision) of Tree Style Tab: 2.0.1

**Comment by piroor** [comment]
Confirmed. Hmm, this seems to be caused by the "cack to opener" feature of Firefox itself. If you click other tabs before you close the tab A3, then TST focuses to the tab A2 as expected.

**Comment by piroor** [comment]
The result is actually produced by Firefox's feature for me. After I turn `browser.tabs.selectOwnerOnClose` to `false` on `about:config`, the problem doesn't happen for me.

Thus this is an expected behavior of Firefox itself and I think TST should not break the feature. I think this issue should be closed as "wontfix" or "worksforme" and I recommend you to disable the secret preference by hand.

**Comment by gnite** [comment]
Thanks for the workaround, but to be frank I don't agree with you. Maybe this is correct behavior with the normal tab bar, but with a vertical tree this seems rather confusing, especially that it only happens when tabs are inserted on top and only when you open three or more children, so I do not think anyone would expect this to work as it does now. But that's just my opinion, and since the setting you mentioned does fix it I'm satisfied with it as it is and happy to close the issue. Oh and by the way thanks for doing this all, TST is by far my most favorite firefox addon.

**Comment by piroor** [comment]
Hmm, you're correct. Actually the feature doesn't work (broken) for "append new child as the last" mode...

**Comment by piroor** [comment]
After I researched, I've realized that Firefox's "selectOwnerOnClose" is very very chaosful.
https://dxr.mozilla.org/mozilla-central/rev/97efdde466f18cf580fda9673cf4c38ee21fc7b7/browser/base/content/tabbrowser.xml#2834
I think this is the reason why this feature works only for "insert new child to top" mode, but I couldn't understand the logic clearly.

**Comment by piroor** [comment]
If TST is not installed, when the current tab is closed:

 * basically the next (right) tab will be focused.
 * however, if the tab has "owner",it will be focused instead of the right tab.
   * the owner tab must be one of preceding tabs, because Firefox never open tab leftside (by default).

So, "next tab is focused after the current tab is focused" is the best trigger to control focus of tabs by TST. However, it seems too late - too slow, and it avoids quick response for user action.

**Comment by piroor** [comment]
Ah, but there is one exception #1409. The user can select the next/right tab.

**Comment by piroor** [comment]
Anyway, except the problem told at #1409 and https://bugzilla.mozilla.org/show_bug.cgi?id=1405262, rules at https://github.com/piroor/treestyletab/issues/1410#issuecomment-333906877 seems effective.

**Comment by piroor** [comment]
By the commit 058bbeb, TST 2.0 more respect Firefox's behavior from `browser.tabs.selectOwnerOnClose`.
