### ISSUE TITLE
"Undo Closed Tab" tab contest is always enabled even if no closed tab list

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#1427]
## Short description
SSIA

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a web page in new tab
 4. Close the tab
 5. Popup TST-we context menu
    --- observe "Undo Closed Tab" menu
 6. Perform "Undo Closed Tab" 
7 . Repeat steps from 5

## Expected result
"Undo Closed Tab" tab contest should be disabled if there is no closed tab

## Actual result
"Undo Closed Tab" tab contest is always enabled

## Environment

 * Platform (OS): Win10
 * Version of Firefox: Nightly 58.0a1 Build ID 	20171005100211
 * Version (or revision) of Tree Style Tab:  2.0.2

**Comment by piroor** [comment]
Because I have too few time to maintain addons and I believe that the fake context menu should be just a temporary implementation until any WebExtensions API to show native context menu become available, I have very less motivation to maintain features of the menu itself. Thus I need PR to fix such a problem - instead I hope to spend more time to fix other bugs or to migrate more other addons.

**Comment by piroor** [comment]
I close this because outdated.
