### ISSUE TITLE
Switching to tab when holding left mouse-down has a delay

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1442]
## Short description

Switching to tab when holding left mouse-down has about a half-second delay. The switch should happen immediately upon mouse-down like the vanilla tab bar. This only applies for mouse-down; mouse-click works just fine.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Hold down mousedown on a tab

## Expected result

Switches to tab immediately.

## Actual result

Switches to tab after about half a second.

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b5
 * Version (or revision) of Tree Style Tab: 2.02

**Comment by piroor** [comment]
This is an intentional behavior for combination with other addons especially my Multiple Tab Handler. It provides ability to select tabs by dragging on them (like file icons on the desktop), however it also blocks drag-and-drop of tabs to move themselves, so 1) if you drag the tab immediately, it is moved by TST. 2) if you drag tabs after a long-press, it triggers to select tabs by dragging. To provide this feature based on custom APIs, I decided to define the delay by TST side.

**Comment by lbmaian** [comment]
I'm not sure I follow. On the vanilla tab bar, holding down left-click on a tab immediately selects it, yet still allows dragging it, and it prevents dragging tabs onto themselves.

Is this delay a workaround?

**Comment by piroor** [comment]
Sorry I misunderstood my old design. c13c37d should fix this problem.

**Comment by lbmaian** [comment]
Confirmed fixed on my end.

**Comment by lbmaian** [comment]
BTW should I be closing my own issues once they're fixed, or leave them open for you to close?

**Comment by piroor** [comment]
I apologize to your confusion. Basically I hope reporters to close issues if they confirm that the problem is actually fixed. Because I hastily closed some previous issues, but some issues were actually not fixed and I had to reopen them by self (because issues closed by the project owner cannot be reopened by the reporter.)
