### ISSUE TITLE
Wrong trees collapsed/expanded in certain duplicate tab edge cases

### ISSUE THREAD

**Issue by lbmaian** [piroor/treestyletab#1454]
## Short description
Wrong trees collapsed/expanded in certain duplicate tab edge cases.

Follow-up on #1437 

Note that duplicating via TST tab context menu and via middle-clicking reload button or Firefox tab context menu still subtly differ in behavior as a result of this (see below cases).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.

### Case I
 3. Tree structure:
```
A
\- B (manually collapsed from A)
```
 4. Duplicate A via middle-clicking reload button or Firefox tab context menu (NOT TST tab context menu)

#### Expected result
```
A
\- B (still collapsed)
A_dup
```

#### Actual result
```
A
\- B
A_dup
```

### Case II
 3. Tree structure:
```
A
\- B (collapsed)
C
\- D
```
 4. Duplicate A via TST tab context menu (NOT middle-clicking reload button nor Firefox tab context menu)

#### Expected result
```
A
\- B (collapsed)
A_dup
C
\- D
```

#### Actual result
```
A
\- B
A_dup
C
\- D (collapsed)
```

### Case III
 3. Ensure TST option "Except focus moving caused by current tab closing" is enabled
 4. Tree structure:
```
A
\- B (collapsed)
C
\- D
```
 5. Close tabs C and D:
```
A
\- B (collapsed)
```
 6. Duplicate A via TST tab context menu (NOT middle-clicking reload button nor Firefox tab context menu)

#### Expected result
```
A
\- B (collapsed)
A_dup
```

#### Actual result
```
A
\- B
A_dup
```

## Environment

 * Platform (OS): Windows 10 Pro, Version 1709, Build 16299.15
 * Version of Firefox: Developer Edition 57.0b6
 * Version (or revision) of Tree Style Tab: Latest nightly as of commit 14e4a24c6299dc7c509f837e5365c6ee7ede2164

**Comment by piroor** [comment]
This seems to be caused by this scenario:

 1. The duplicated tab is created next to the active tab A.
 2. TST automatically attach the tab from its position, as the first child of A.
 3. Newly attached tab to the collapsed tree of A triggers expansion of the tree.
 4. After that TST successfully detects the tab is duplicated by Firefox and move it to expected position (next sibling of A).

Because we need to wait that session information of the duplicated tab become available, the step 4 must happen after 1, 2 and 3 for now.

**Comment by piroor** [comment]
Recent commits should fix this.

**Comment by lbmaian** [comment]
Confirmed fixed for me.
