### ISSUE TITLE
Option to use middle click to open the last closed tab

### ISSUE THREAD

**Issue by AlexEndris** [piroor/treestyletab#1470]
this was actually a feature from tab mix plus. Would be cool to have this option

**Comment by piroor** [comment]
It won't be implememted by TST itself because it is not related to "tree" and it is not a behavior of Firefox itself. Instead TST provides API for such needs, so I hope someone develops an addon based on the API.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-the-non-tab-area-is-clicked

**Comment by AlexEndris** [comment]
Oh, I missed that. Thanks for pointing that out!

**Comment by AlexEndris** [comment]
@piroor Just for your information. I just created my wanted middleclick functionality and submitted it to AMO: https://addons.mozilla.org/en-GB/firefox/addon/tst-middleclick/

**Comment by piroor** [comment]
Thanks a lot! To be honest I personally used the feature (not with TMP but I used another addon) and I gave up to implement by self due to my limited time resource.

**Comment by AlexEndris** [comment]
Cool! I'm more than happy to support you this way ;).
