### ISSUE TITLE
Allow never closing an entire tree when closing a collapsed tree

### ISSUE THREAD

**Issue by Katrix** [piroor/treestyletab#1474]
## Short description

Currently with TST if you close a collapsed tree, it will close all the tabs in the tree too. What I ask for is a config to disable this. I also suspect that it could be part of the reason for bugs like #1418, where you navigate away from a tab tree, close the parent tab, and because the tree is collapsed, the child tabs are also closed.

## Steps to reproduce

 1. Open a few new tabs 
 2. Organize them in a tree
 3. Collapse them
 4. Close the parent tab, 

## Expected result
The first child tab is promoted as parent

## Actual result
All tabs are closed

## Environment

 * Platform (OS):  Windows 10 64-bit
 * Version of Firefox:  58.0a1 (2017-10-14) (64-bit)
 * Version (or revision) of Tree Style Tab: WE 2017-10-15

**Comment by piroor** [comment]
Sorry I have no plan to change this behavior, because I believe it seems to be natural from their appearance.

**Comment by Katrix-** [comment]
I have to agree there. Would it be possible to make it a config, or make a tab closed outside a tree (no appearance which makes it seem natural) behave differently?

**Comment by nshtg** [comment]
Yet I agree with Katrix-, an option to do this would be nice.

**Comment by piroor** [comment]
Because there are some mistakes, unexpectedly the config did not work as expected: "When a parent tab is moved or closed by someone from outside of the tree" => "Treat it as a parent only when the tree sidebar is visible". By recent commits, now the config should work as expected. When you choose this option, you'll see the behavior like you told when TST's sidebar is invisible.

If you mean that a new option to do same thing for "close tab by middle click on Firefox's native tab bar, even if the sidebar is visible", I have to do more changes.

**Comment by awused** [comment]
> If you mean that a new option to do same thing for "close tab by middle click on Firefox's native tab bar, even if the sidebar is visible", I have to do more changes.

This is definitely the option I want. Right now it's too easy to close a large tree by mistake and end up unable to restore it.

**Comment by irvinm** [comment]
@piroor please close this. (I assume you have not changes your mind on this one)

**Comment by piroor** [comment]
This was already implemented as the option "Treat as a parent tab by operations inside the tree sidebar. / Treat just as a solo tab, by operations outside the tree sidebar." and with recent changes context menu commands on the sidebar are also treated as "operations inside the tree sidebar".
