### ISSUE TITLE
Sometimes you must press twice to open TST

### ISSUE THREAD

**Issue by shelt** [piroor/treestyletab#1503]
## Short description
If you close the sidebar with the sidebar's X button, or by opening bookmarks or history, `gSidebarOpenState` is not updated, and thus the extension thinks the sidebar is still open. At that point, you must press the toolbar button (or F1) **twice** to open the sidebar.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Press F1 to open the sidebar (if it isn't already open)
 4. Close the sidebar with the X button at the top of it
 5. Press the toolbar button or F1 once

## Expected result
The sidebar opens

## Actual result
Nothing

## Alternatively

If you open TST's debug log (from about:debugging) and query gSidebarOpenState before and after performing step 4, you can see that it still thinks the sidebar is open. 

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: 2.0.7

**Comment by shelt** [comment]
To be clear, by "thinks the sidebar is still open", I mean the `if` statement in `onToolbarButtonClick` evaluates to `true` when it should be `false`, because the sidebar is *not* open.

**Comment by piroor** [comment]
Due to some technical limitations, TST cannot detect when the sidebar is hidden. Thus [TST tries to update status of sidebars on every 500msec](https://github.com/piroor/treestyletab/blob/master/webextensions/background/background.js#L127). If you hit F1 key or click the toolbar button before the status is updated, this problem will happen. ("500msec" is the default value. You'll see actual current interval as the value of `sidebarOpenStateUpdateInterval`, on the TST's configurations. Turn the "Debug mode" checkbox to checked, then you'll see complete list of internal configs.)

**Comment by shelt** [comment]
Sorry, I was using the release rather than the devbuild. Thanks for getting back to me.
