### ISSUE TITLE
[feature request] extra class on tabs with the same URL as the active tab

### ISSUE THREAD

**Issue by blakebutcher** [piroor/treestyletab#1512]
I would like to be able to style tabs if they have the same URL as the currently active tab.

I usually accumulate a lot of duplicate tabs and this would make finding them much easier. I've tried other extensions that close or avoid duplicates but they don't suit my workflow. If I could style duplicates of the current tab that would help a lot.

I'm using Tree Style Tab 2.0.7 + Firefox 57

**Comment by piroor** [comment]
I think it should be done by an addon developed for the purpose, because it seems to be useful for all peole who don't use "tree".
TST provides APIs to set custom classes to tabs, so such an addon can give custom style definitions for tabs in TST's sidebar panel.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#apis-to-set-custom-state-for-tabs

**Comment by blakebutcher** [comment]
Thanks, that makes sense.

I'm hoping this motivates me into making my first Firefox extension
