### ISSUE TITLE
Tree temporarily loses indentations

### ISSUE THREAD

**Issue by gnite** [piroor/treestyletab#1518]
Ok so this is a bit of a strange one and I have failed to recreate it in a clean profile. Nonetheless the results are very consistent in my main profile. Rather than explain I thought I better record it, so here it goes: https://streamable.com/s6xs1

As you can see in the recording this only happens in the fifth level, not in the fourth. And I believe this bug was introduced in version 2.1.1, I haven't encountered it previously.

**Comment by gnite** [comment]
My clean profile was still on 2.1.0 when I tested before and didn't show any problems, now it also updated to 2.1.1 and shows the exact same symptoms as shown in the video. Closing tabs on level 5 and up removes the indentations.

**Comment by lewisaronmilne** [comment]
I am also having this issue.

**Comment by adavier** [comment]
I too am suffering from this. It seemed to be introduced in either 2.1.1 or 2.1.2. Unfortunately I can't find any specific cause either.

**Comment by adavier** [comment]
I too am suffering from this. It seemed to be introduced in either 2.1.1 or 2.1.2. Unfortunately I can't find any specific cause either.

**Comment by piroor** [comment]
The case described at https://streamable.com/s6xs1 should be fixed on 2.1.2.  It was triggered when the tab which is the last largest indent depth is closed. @adavier is your case different from this?

**Comment by adavier** [comment]
I'll have to do some more investigation later. But visually the issue I
very similar but it only seems to occur in 2.12 not 2.11. I'll have another
look tomorrow.

On 12 Nov 2017 2:06 a.m., "piroor" <notifications@github.com> wrote:

The case described at https://streamable.com/s6xs1 should be fixed on
2.1.2. It was triggered when the tab which is the last largest indent depth
is closed. @adavier <https://github.com/adavier> is your case different
from this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/piroor/treestyletab/issues/1518#issuecomment-343708283>,
or mute the thread

**Comment by gnite** [comment]
I can confirm that 2.1.2 fixes the issue in my case, thanks.

**Comment by adavier** [comment]
I have looked into it a bit more and it does indeed appear to be fixed in 2.1.2. I must have gotten mixed up when I was trying previous versions to see what caused it.

**Comment by piroor** [comment]
I close this because outdated.
