### ISSUE TITLE
Allow to create a group without a main tab

### ISSUE THREAD

**Issue by Salamandar** [piroor/treestyletab#1520]
Use case : 

I have several Youtube tabs (musics i'd like to listen to someday) that I want to be grouped.

But I don't need a "parent tab" (for now it's the YT homepage), i'd prefer to have a "folder" without a dummy tab that is visible in the tabs bar and that may be accidently closed.

**Comment by piroor** [comment]
TST is basically designed to operate tree of tabs, not for grouping. The group (dummy) tab is made just for grouping of tabs opened from a bookmark folder.

However you can create such a tab manually, from bookmarks. Please create a new bookmark with a URI "about:treestyletab-group?Default Title" and open it as a new tab.

**Comment by as3mbus** [comment]
the following workaround sometimes, "went wrong" and slow my firefox into a freeze, instead of creating new dummy Tab. (need to kill the firefox manually)
IMHO this dummy tab is still did needed to give a name to a certain tree group. 
it'll be some kind of frustrating to forgot where you put your tab inside a tree.if you have many tree scattered with tab title as it's indicator. 
or maybe there a way to name a parent tab to another name
