### ISSUE TITLE
closing parent of collapsed tree removes also children even when parent is closed from outside sidebar

### ISSUE THREAD

**Issue by kkot** [piroor/treestyletab#1521]
## Short description

Collapsed children tabs are closed together with parent tab also when parent is closed from outside sidebar tree (standard bar tab or mouse gesture).

I have this options selected:
![obraz](https://user-images.githubusercontent.com/1009806/32734553-ab5263f0-c892-11e7-9c19-5825ee72a2ba.png)
One label says from outside sidebar other when sidebar is visible so it is misleading.

![obraz](https://user-images.githubusercontent.com/1009806/32746190-245583aa-c8b5-11e7-883a-af384290f81e.png)

It sometimes causes me to lose unintentionally many open tabs.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select option "When a parent tab is closed: Promote the first child tab as the new parent".
 4. Open a page.
 5. Open link in the page so that tab will have a child
 6. Collapse tree.
 7. Close parent using standard tabs bar or Gesturefy.

## Expected result

Only parent is closed. Child is not closed.

## Actual result

Parent and child are closed.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  57.0
 * Version (or revision) of Tree Style Tab: 2.1.2

**Comment by piroor** [comment]
It is an intentional behavior, not a bug. Collapsed tree is always closed with collapsed descendants, except the sidebar is invisible and TST is configured to "When a parent tab is moved or closed by someone from outside of the tree => Treat it as a parent only when the tree sidebar is visible".

**Comment by kkot** [comment]
@piroor Would it be possible to check if tab was "closed by someone from outside of the tree" (as in description). I mean closing using standard top tab bar or mouse gesture. Even if sidebar is visible I still sometimes close it using mouse gestures and not intentionally close child tabs.

**Comment by piroor** [comment]
Hmm, I think this little bit difficult topic.

Basically, when I'm using TST, I completely ignore Firefox's horizontal tab bar. So, in my case, I expect that both mouse gesture and Ctrl-W (it is shortcut of Firefox itself, so it seems "action on outside of TST sidebar") should close collapsed parent and all its descendants for me.

So I think wee need one more choice for your case. They should be:

 * When a parent tab is moved or closed by someone from outside of the tree sidebar (<= updated label)
   * Treat it as a parent always. Move or close all descendant tabs also together, even if the tree sidebar is invisible. (<= updated label)
   * Treat it as a parent always. Move or close all descendant tabs also together, only when the tree sidebar is visible. (<= updated label)
   * Treat it as a parent only when the action is triggered inside the tree sidebar. Otherwise treat the tab as an independent one. (<= new, for your case)

To do that, we need to introduce more changes around handling of browser.tabs.onRemoved, to detect that the event is triggered by self or someone.

**Comment by kkot** [comment]
@piroor Thanks for explanation. I updated description to better reflect what my problem is.

**Comment by piroor** [comment]
By 33ff6dc now configuration item labels are updated, but the third option is not implemented yet.

**Comment by piroor** [comment]
The option is now available on 2.2.1.

**Comment by kkot** [comment]
Incredible. I wound not believe it would be fixed this fast (if at all). Works great for me now. Both with Gesturefy and standard tab bar. Thank you.
