### ISSUE TITLE
High cpu occupation under firefox 57 and mac os X

### ISSUE THREAD

**Issue by yingfeng** [piroor/treestyletab#1535]
## Short description
In my macbook pro, the tree style tab under firefox 57 will trigger a higher cpu usage constantly even if all tabs have been closed. 

## Reproduction
There's only one addon installed(tree style tab). I frequently opened a series of web page tabs randomly. Then CPU will grow up to 100%. After I stopped opening new tabs, the CPU will decrease, but still maintain around 35%. Even if I closed all tabs with a single blank tab left, the CPU of firefox keeps that high constantly except that I disable tree style tab, then the CPU will be reduced to near zero, while after I re-enable the tree style tab, everything is fine. As a result, whenever I've met the CPU occupation issue of firefox 57, I have to disable and re-enable the tree style tab addon manually. 

## Environment

 * Platform (OS): Mac OS X 10.12.6
 * Version of Firefox:  57
 * Version (or revision) of Tree Style Tab: 2.2.3

**Comment by Omen-of-Peace** [comment]
While perhaps not as bad as what you describe, I've also noticed increased CPU usage when using TST vs not using it.

MacOS 10.13.1
Firefox 57 betas
TST 2.2.3 to 2.2.8

I'm now on Firefox 58 and it seems slightly better (CPU usage decreases faster once the tabs are open).

**Comment by piroor** [comment]
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1417460 ?

**Comment by Lej77** [comment]
I have noticed that sometimes firefox will have about 30% CPU usage while not doing anything. Closing the Tree Style Tab sidebar and reopening it fixes it for me though.

**Comment by Lej77** [comment]
I think I know what causes this now. I was testing infinite loading tabs for [Issue 1384](https://github.com/piroor/treestyletab/issues/1384) and I found that closing a tab before it has finished loading causes the sidebar to bug and use about 30% CPU until it is restarted (closed and reopened).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open some new tabs (performance issue is worsened by more tabs) (I did about 80).
 4. Wait for them to load or close and reopen firefox.
 5. Open a web page (so that tab loading animation starts) and close it immediately (before loading animation completes). Keyboard shortcut: `ctrl+w` is useful to quickly close the tab.
6. Observe higher than normal CPU usage. The more open tabs the higher.
7. Close and reopen TST sidebar.
8. Obeserve normal CPU usage.

**Comment by yingfeng** [comment]
This issue disappeared with treestyletab 2.30.0 and firefox 57.01

**Comment by aurelg** [comment]
It's still a problem here w/ Tree Style Tab 2.4.3 and Firefox Quantum Developer Edition 58.0b12 (64-bits) on Archlinux. When Tree Style Tab is hidden, the load is normal (i.e. a few CPU %). When Tree Style Tab is shown, the load raises to ~30% CPU (Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz).
