### ISSUE TITLE
Throbber animation is not synchronized on Firefox 57

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#1543]
Throbber animation is not synchronized for multiple loading tabs on Firefox 57.
This is caused by `dom.animations-api.core.enabled`. It is `false` by default on Firefox 57.
On Nightly it is `true` by default and animation is synchronized.

This issue is just for tracking until the preference becomes `true` by default on released Firefox.

**Comment by Lej77** [comment]
This could also be solved by having one hidden throbber behind the "tabbar" element. This throbber could be animated only when there was any visible tab loading. Then you could add a event listener to the "animationiteration" event on the hidden throbber. When that fired you could synchronize all tab throbbers by restarting their animation using something like: 
`new Promise((resolve, reject) => { document.body.classList.add("stop-animations"); resolve(); }).then(() => document.body.classList.remove("stop-animations"));`

You would only need to restart them if their was any unsynchronized throbbers so it wouldn't really be noticeable.

To show synchronized throbbers on throbbers started after the first one I used the following CSS on a placeholder throbber element to copy the appearance of a synchronized throbber:
`-webkit-mask: -moz-element(#main-tab-throbber-wrapper) no-repeat;`

I couldn't use the first hidden throbber for that though since the animation of the throbbers on the tabs were slightly delayed compared to it. So I simply created a second hidden throbber whose animation was restarted with the tabs' throbbers. 

This placeholder took quite a lot of CPU though (about 25%) so it should be replaced with a synchronized throbber as soon as possible.

Also it is important to know that hiding a throbber seems to cause high CPU usage in most cases. The only way I found to do it was to place another element over it. Using `opacity: 0;` or `display: none;` or `left: -100%;` causes about 25% CPU (on my quad core) whenever the throbber is animated.

I don't know if you have the time to implement this though since it seems you have already solved it for later firefox versions. Thought I should mention it though since it seems to be an OK workaround.

**Comment by piroor** [comment]
I think that the SVG version throbber is not suitable in release version because "content-fill" is not available yet by default...

**Comment by Lej77** [comment]
@piroor Using a SVG throbber isn't really needed to synchronize the throbbers using the above code. The main idea is to copy the appearance of a hidden synchronized throbber using:
```CSS
-webkit-mask: -moz-element(#hidden-throbber-id) no-repeat;
```
Then use that until the synchronized throbber animations completes an iteration at which point all throbbers animations are restarted and any unsynchronized throbbers can stop using the appearance of the hidden throbber.

**Comment by piroor** [comment]
Ah, OK, I totally misunderstood. I didn't know that Firefox can apply an animated element as a mask. Now throbber implementation is totally updated based on your awesome idea. Thanks a lot!!

**Comment by Lej77** [comment]
@piroor I think it works for `background` as well if that is helpful. 
```CSS
background: -moz-element(#hidden-throbber-id) no-repeat;
```

**Comment by piroor** [comment]
Thanks. But current `mask` method seems good to apply different color for throbbers of foreground and background tabs.

**Comment by Lej77** [comment]
@piroor I tested the TST Development build (2.2.11.5891) and compared the throbbers to the TST Release version (2.2.11). I did the testing on Firefox Nightly 59 on Windows 10. I noticed that the throbbers were synchronized and also a lot smoother (less lag) on the dev build then on the release build. CPU usage was higher though on the dev build:

| Number of Loading Tabs | CPU with TST Sidebar Closed | CPU with TST (Release) Sidebar Open | CPU with TST (Development) Sidebar Open |
| ------------- | ------------- | ------------- | ------------- |
| 1                   | 1.5% - 2%    | 2.5% - 3%     | 8%                |
| 10                 | 7%               | 9%                | 19%              |
| 25                 | 8%               | 11%              | 30%              |

Note: I have a quad code processor (4 threads / 4 cores).

To get infinite loading tabs I used the program ["iperf-2.0.9-win64"](https://iperf.fr/iperf-download.php) with the command `iperf.exe -s -p 8888` and then I opened tabs with the URL [localhost:8888](url).

Also I did NOT hide Firefox's tab bar using userChrome.css.

**Comment by piroor** [comment]
On the dev version, we can try many numbers of loading animations by running `getAllTabs().forEach(tab => { tab.classList.remove('complete'); tab.classList.add('loading') }); updateLoadingState()` on addon debugger.

I've confirmed that this change actually increased CPU usage. Thins became worse... should I go back to previous implementation, to reduce CPU usage?

**Comment by Lej77** [comment]
@piroor I thought some more about this. Do you think that the masking is performance heavy? Since we only need two colors we could have two hidden throbbers with different colors and copy the appearance of the one with the correct color using something like:
```CSS
.tab .loading .active {
  background: -moz-element(#hidden-throbber-active-id) no-repeat;
}
.tab .loading {
  background: -moz-element(#hidden-throbber-id) no-repeat;
}
```
 
If that doesn't help we could minimize the time we copy the appearance using something like what I suggested in my example code. Basically replace the copied appearance with an animated throbber when the synchronized throbbers complete an iteration and the `"animationiteration"` event fires.

**Comment by piroor** [comment]
Here is an implementation based on "background": https://github.com/piroor/treestyletab/tree/without-masking Currently this version is a combination of masking and background, to apply theme-specific color for throbber. On my environment CPU usage seems same to the master (=all throbbers are rendered with masking).

**Comment by piroor** [comment]
Because I couldn't understand full of your example, I extracted only limited parts. I try to introduce full of them.

**Comment by Lej77** [comment]
@piroor So masking doesn't seem to use much CPU. Then I think we should implement my second suggestion and minimize the time we use `-moz-element`. We could use the copy appearance method while a `placeholders` class is added to a tab and switch over to the old animation method when that class is removed.

The JavaScript could look something like this:

```JavaScript
const kHiddenThrobberId = "hidden-throbber-id";
const kThrobberPlaceholderInUse = "throbber-placeholders-used";
const kStopThrobberAnimations = "stop-throbber-animations";
const kTabPlaceholderThrobber = "placeholder-throbber";



document.getElementById(kHiddenThrobberId).addEventListener("animationiteration", () => {
    if (!document.documentElement.classList.contains(kThrobberPlaceholderInUse))
        return;

    if (removePlaceholders(getAllTabs())) {
        // Placeholder removed. Synchronize tabs.
        restartThrobberAnimations();
    }
});

function restartThrobberAnimations() {
    // Restart/resync animations:
    new Promise((resolve, reject) => {
        try { document.body.classList.add(kStopThrobberAnimations); }
        finally { resolve(); }
    }).then(() => document.body.classList.remove(kStopThrobberAnimations));
}

function removePlaceholders(tabs) {
    let placeholderRemoved = false;
    for (let tab of tabs) {
        if (tab.classList.contains(kTabPlaceholderThrobber)) {
            tab.classList.remove(kTabPlaceholderThrobber);
            placeholderRemoved = true;
        }
    }
    document.documentElement.classList.remove(kThrobberPlaceholderInUse);
    return placeholderRemoved;
}




function startLoading(tab) {    
    tab.classList.add(kTabPlaceholderThrobber);
    tab.classList.add("loading");
    document.documentElement.classList.add("have-loading-tab");
    document.documentElement.classList.add(kThrobberPlaceholderInUse);
}

function stopLoading(tab) {
    tab.classList.remove("loading");
    tab.classList.remove(kTabPlaceholderThrobber);

    let anyLoadingTabs = false;
    for (let tab of getAllTabs()) {
        if (tab.classList.contains("loading")) {
            anyLoadingTabs = true;
            break;
        }
    }
    if (!anyLoadingTabs) {
        document.documentElement.classList.remove("have-loading-tab");
    }
}
```

**Comment by piroor** [comment]
Thanks again, finally I've understood how you apply synchronized animation. By recent changes CPU usage is reduced for me!

**Comment by Lej77** [comment]
Updated performance testing with new development version. CPU usage seems a lot better and I think its good enough to use now.

| Number of Loading Tabs | CPU with TST Sidebar Closed | CPU with TST (release-2.2.11) Sidebar Open | CPU with TST (dev-2.2.11.5891) Sidebar Open | CPU with TST (dev-2.2.11.5896) Sidebar Open
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 1                   | 1.5% - 2%    | 2.5% - 3%     | 8%                | 6%                |
| 10                 | 7%               | 9%                | 19%              | 12%              |
| 25                 | 8%               | 11%              | 30%              | 15%              |

**Comment by Lej77** [comment]
@piroor Also I think I found a bug. If you have tabs loading and then close and reopen the sidebar the throbbers don't appear on the loading tabs.

**Comment by piroor** [comment]
Oops. 888038d should fix it. Thanks!
