### ISSUE TITLE
How to backup the tree?

### ISSUE THREAD

**Issue by scarfa** [piroor/treestyletab#1552]
I want to backup all my tabs with indentation intact in case Firefox 57 crashes and and it doesn't restore my session or for some reason some other addons mess up my tabs hierarchy and I have to start over. I tried to bookmark all the tabs and restore but it doesn't save the indentation information. Is there a way? I'm on windows.

**Comment by piroor** [comment]
TST's tree structure is stored as a part of Firefox's session information. You just need to backup `*.jsonlz4` files in your profile directory. (You'll go to the directory via `about:support`.)

**Comment by piroor** [comment]
Or, [Tab Session Manager](https://addons.mozilla.org/firefox/addon/tab-session-manager/) will help you.

**Comment by scarfa** [comment]
> TST's tree structure is stored as a part of Firefox's session information. You just need to backup *.jsonlz4 files in your profile directory. (You'll go to the directory via about:support.)

Then use your [migration tool](https://github.com/piroor/treestyletab/wiki/How-to-convert-session-information-from-old-TST-0.19.x-to-new-TST-2.x) on it correct?

> Or, Tab Session Manager will help you.

It has a few recent bad reviews, I'm not sure I can trust it. I don't know what your feelings are.

Curious if you ever plan on having something in the TST settings to backup tree like the old versions?

**Comment by piroor** [comment]
> Then use your migration tool on it correct?

No, it just reads tree information of TST 0.19.x stored in given file and rewrites for TST 2.x. It doesn't create backup of sessions.

> It has a few recent bad reviews, I'm not sure I can trust it. I don't know what your feelings are.

I think that the addon seems well-made enough, based on WebExtensions APIs. In other words, even if anyone develop such an addon, it won't become far better than the existing Tab Session Manager, due to strong restrictions of WebExtensions APIs - it is just my opinion. Thus I have no plan to implement any session management feature by TST itself.
