### ISSUE TITLE
Toggle hotkey

### ISSUE THREAD

**Issue by oxk4r01** [piroor/treestyletab#156]
Is there some hotkey for open close treestyletab?

**Comment by lydell** [comment]
Hi! I’ve used the proposed code in this issue for a long time in a custom keyboard shortcut, and it has worked great! However, since TST 0.16.2016021201 I’ve got a slight problem. Here’s how to reproduce it:

1. Create a new profile.
2. Install latest TST.
3. Enable the “Auto hide > for Normal Window Mode > Auto Hide tab bar” option.
4. Run the following code from the browser console: `gBrowser.treeStyleTab.showTabbar()`. Notice how the tab bar shows as expected.
5. Go back to the main Firefox window by pressing `alt+tab` or clicking the title bar. Notice how the tab bar stays open as expected.
6. Press seemingly any key, for example “a”.

Expected: Nothing happens. This is how things used to work before TST 0.16.2016021201.
Actual: The tab bar hides.

Note: If you show the tab bar by moving the mouse to the edge of the screen and the press “a” the tab bar stays open as expected.

I’d really like the tab bar _not_ to hide when I press any key, because I have another custom keyboard shortcut that operates on the tabs and that shortcut is not useful if the tab bar is hidden.

Is there a way to do this? Is there some specific change in the mentioned TST version that causes it?

**Comment by lydell** [comment]
The following code is in the [wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-keyboard-shortcuts#toggle-showhide-the-tab-bar):

```js
if (gBrowser.treeStyleTab.tabbarShown) {
  gBrowser.treeStyleTab.hideTabbar();
} else {
  gBrowser.treeStyleTab.showTabbar();
}
```

A super easy way to try that out is by creating a new keyboard shortcut with the [keyconfig](http://forums.mozillazine.org/viewtopic.php?t=72994) extension. I used `alt+m` when testing this.

The code is supposed to toggle the tab bar. This is not the case anymore.

1. Press alt+m. The tab bar is shown as expected.
2. Press alt+m again while the tab bar is shown.

Expected: The tab bar hides. (That’s how it used to work.)

Actual: The tab bar flashes and then remains shown. This is because when I press down alt, the tab bar hides (since TST seems to hide it when you press any key). When I press m, the in the custom shortcut code detects that the tab bar is hidden and therefore re-shows it. Basically, the `if` check will _always_ be `false`.

Something has to be done about this in TST, or the wiki must be updated. Any thoughts, @piroor? I think this is pretty important since I got the impression that this is the most requested/used keyboard shortcut. (Providing a public API and letting people implement their own keyboard shortcuts is a great choice, BTW! :+1: )
