### ISSUE TITLE
[feature request] Better Design for Tab Container Selector

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1571]
## Description
The current Tab Container Selector doesn't look very good. Other addons that have support for container tabs have the same layout for selecting tab containers.

## TST

![tree style tabs](https://user-images.githubusercontent.com/31554212/32979736-3edcb0c8-cc5b-11e7-9c7c-62f579051ec1.png)

## Examples of other Extensions

[Firefox Multi-Account Containers – Tillägg för Firefox](https://addons.mozilla.org/sv-SE/firefox/addon/multi-account-containers/ "Firefox Multi-Account Containers – Tillägg för Firefox")
![multi-account containers](https://user-images.githubusercontent.com/31554212/32979680-669fc6aa-cc5a-11e7-8efd-d05e8088f1ac.png)

[Containers Drawer – Tillägg för Firefox](https://addons.mozilla.org/sv-SE/firefox/addon/containers-drawer/ "Containers Drawer – Tillägg för Firefox")
![containers drawer](https://user-images.githubusercontent.com/31554212/32979727-20afb73a-cc5b-11e7-9519-a6f2e8053631.png)

[Containerise – Tillägg för Firefox](https://addons.mozilla.org/sv-SE/firefox/addon/containerise/ "Containerise – Tillägg för Firefox")
![containerise](https://user-images.githubusercontent.com/31554212/32979728-2569ace0-cc5b-11e7-96d4-55d622bed260.png)

[Tab Center Redux – Tillägg för Firefox](https://addons.mozilla.org/sv-SE/firefox/addon/tab-center-redux/ "Tab Center Redux – Tillägg för Firefox")
![tab center redux](https://user-images.githubusercontent.com/31554212/32979730-28d975ae-cc5b-11e7-8bc2-aba75bca1461.png)

**Comment by piroor** [comment]
I agree that current implementation doesn't look good. When I started to develop TST2, the container selector was a built-in feature of Firefox itself, so I decided to implement it  anyway in very limited time. However, now the feature has been separated as an addon, and I think there is less reason to implement such an UI by TST itself. Now there are two choices:

 A. Write more codes for it.
 B. Remove it from TST's sidebar and recommend to use other addons together for people.

Because I have limited development resource, I hope to keep TST simple. If no one contributes to doing A, I think B is reasonable decision. How do you think?

**Comment by Lej77** [comment]
Of course you should decide if you have the time to do it and any menu is better than none. But [Containers Drawer's](https://github.com/jonathanKingston/container-drawer) code looks quite simple. 

Couldn't you just copy all of its code and place the html code in a html element that is collapsed normally?

**Comment by piroor** [comment]
Thanks, I'll try it later. (But any pull request is welcome!)

**Comment by gilgwath** [comment]
Hello. While redesigning the container selector please make sure that if the sidebar is on the right side of the screen, the selector has to extend to the left. Right now it just disappears behind the screens edge. Should I open a separate issue for this?

**Comment by gagarine** [comment]
In my opinion this container selector is disturbing for new user. They don't understand his purpose and what it actually do. I think such selector should only exist if https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ or an alternative is installed.

So it's great of TST works with container, but this features should not show-up for peoples that didn't ask for it.

**Comment by piroor** [comment]
Hmm, I think there are some viewpoints for this:

 * To keep TST simple and feature-oriented, I want to remove the container selector from TST.
   * For compatibility to Firefox's tab bar, there is no reason to put the container selector in TST's sidebar, because Firefox doesn't have the UI anymore by default.
 * We can install something addons like Firefox Multi Account Containers and put its button to the Firefox's tab bar.
   * But it is impossible to put the button to TST's sidebar, because they are different addons and the sidebar is not a customizable toolbar area.
   * For compatibility to the UX from Firefox + Firefox Multi Account Containers, TST need to include optional container selector and disable it by default, activate it when TST detects Firefox Multi Account Containers or other similar addon is installed.
     * But it is too complex. Moreover, people who don't install such an addon will never see TST's optional container selector. In other words, even if I implement rich container selector, it will be deadstock.

So, my idea is:

 * I don't implement any rich container selector to TST, except it is contributed by someone.
 * I add a new option to control visibility of the container selector. It is unchecked by default so the container selector is invisible by default.

How about that?

**Comment by SXZ1** [comment]
Don't forget containers are built-in in Nightly. Just hover the mouse over new tab button, click and hold left mouse button. Result:
![image](https://user-images.githubusercontent.com/26294581/33395529-e065714c-d556-11e7-8c83-d28aac2601b0.png)

**Comment by piroor** [comment]
Oh... I misunderstood that Firefox turned the UI completely to optional addon.

**Comment by piroor** [comment]
The long-press of the new tab botton is unlocked when there is any addon which have permission for contextual identities. It is available not only on Nightly, on Firefox 57 + TST also.

However, TST just requires such a permission only to know color of each container and tab's container (via `cookieStoreId`). Unlocking of the container feature is unintentional side effect. So I think that disabling container selector on TST sidebar by default seems still reasonable.

**Comment by durbanpoison** [comment]
@piroor thank you very much for making this add-on freely available! I consider it to be 99.9% perfect for me. I make heavy use of containers and having the button in TST for opening a new tab in a specific container was very convenient. Going outside TST to open a new tab adds unwanted friction to using the add-on. I would like to voice my support and appreciation in advance for adding a container selector on the new tab button in TST, should you or someone else have time to implement this. Apologies if this is the wrong venue to voice support for this feature.

**Comment by piroor** [comment]
Done by recent commits.
