### ISSUE TITLE
Please introduce a stable branch on addons.mozilla.org

### ISSUE THREAD

**Issue by kparal** [piroor/treestyletab#1574]
Today or yesterday, some TST update utterly broke most rudimentary stuff for me. I'm regularly seeing a child tab being placed at a completely wrong location (e.g. under a different tree), but still behaving like part of the correct tree (when collapsing the right tree, this tab also disappears from the wrong tree). Furthermore, once I quit and restart the browser once this happens, on the next start my trees are completely messed up - tabs are moved to a completely different trees randomly, meaning I have to reorganize all my 100+ tabs, spending 10+ minutes on that (and I don't have any other extensions that could affect this enabled, so it's 99% TST fault). I'll report a specific issue about this. But that's not the point.

The point is - errors are bound to happen. Programming is never error-free. However, you can limit the number of affected users. And very easily - just use a devel/beta version branch, and a stable version branch. Currently, addons.mozilla.org is used as a devel branch - there's a new version every day or every other day. That means that a single error will affect almost everyone. I.e. you'll very likely annoy all your users just by doing a single mistake. Like in this case, when my trees get corrupted randomly several times per day.

addons.mozilla.org supports beta versions. Please use that. Upload the daily builds to beta channel. If people are interested in the latest greatest stuff, they can install from the beta channel. And use the default branch for stable versions (as they are intended) - i.e. once in some reasonable time (once, max twice per month?) promote a known-to-be-well-working build into stable. Direct people to stable branch by default.

Most people are not interested in "fresh from git" stuff. They want to do work in their browser, and they want it to work reliably. They might care about new features, but not every day, and not at the expense of instability.

Please consider this. Thank you.

**Comment by piroor** [comment]
I'm very sorry that my mistakes annoy you and more people. I agree that I lost carefulness in recent days. Especially, many many "reports" about how to hide the top tab bar and the sidebar header deranged me. I added a message in recent release to conduct people to existing knowledge, so I hope that it reduces such reports.

Because of my limited development resource and TST2 is not enough stable yet, I think it is not realistic to keep multiple branches by me for now. Instead, like in old days, I'll release a new version with more interval and there will be another development (unsigned) build from latest source hosted on my website.

(Anyway, luckily or unluckily I'll not able to use my private time to develop addons anymore until December.)

**Comment by irvinm** [comment]
@piroor please close this.
