### ISSUE TITLE
Icons for some websites not displaying in TST tabs when tracking protection is turned on.

### ISSUE THREAD

**Issue by the-borg** [piroor/treestyletab#1654]
## Short description
Icons for websites like Twitter, Facebook, eBay are not being displayed in the sidebar tabs when tracking protection is turned on in Firefox.  TST displays instead the generic gray globe icon. (When you add ublock to the mix it gets worse and will include sites like Amazon, Google, Bing, and Youtube.)
However, the icons are showing fine in the Firefox tabs at the top and on bookmarks. I can also browse to the actual favicon.ico of these sites and see it displayed in the browser.

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Turn on tracking protection in Firefox.
 4. Browse to Twitter, Facebook or eBay.

## Expected result
 Website's favicon to be displayed in TST tab.

## Actual result
Generic gray globe icon displayed in TST tab.

## Environment
 * Platform (OS): Win7 pro
 * Version of Firefox: 57.0.1
 * Version (or revision) of Tree Style Tab: 2.3.0

**Comment by piroor** [comment]
Due to restrictions of WebExtensions APIs, addon must fetch favicons with actual HTTP(S) request, but those requests are blocked by Firefox itself. The debug console says:

> The resource at “https://abs.twimg.com/favicons/favicon.ico” was blocked because tracking protection is enabled.

So this problem is not resolvable until any of bugs listed below is fixed:

[1404610 - Tracking protection should not apply on extension pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1404610 "1404610 - Tracking protection should not apply on extension pages")
[1315616 - Give extensions access to cached favicon URLs](https://bugzilla.mozilla.org/show_bug.cgi?id=1315616 "1315616 - Give extensions access to cached favicon URLs")

**Comment by the-borg** [comment]
I figured it was something like that.  Thank you for answering.

**Comment by the-borg** [comment]
Not sure about proper procedure here.  To close or not to close?

**Comment by piroor** [comment]
I think this issue should stay open for memorandum (TODO).

**Comment by gauravsharma013** [comment]
Yes, I'm facing same issue on couple of sites.

**Comment by piroor** [comment]
I close this because outdated. Now WebExtensions API returns data: URI and it won't be blocked.
