### ISSUE TITLE
Feature request: configurable keyboard shortcut

### ISSUE THREAD

**Issue by Adelscott** [piroor/treestyletab#1667]
Nice integration in FF57 !

Can you add a configurable keyboard shortcut so we can fast switch between bookmarks (CTRL-B) and Tree Style Tab (CTRL-something) ?

Thanks !

**Comment by piroor** [comment]
Due to WebExtensions's restrictions, we cannot define any keyboard shortcut dynamically to toggle sidebar. In other words, only static shortcut defined in the manifest file can toggle the sidebar. There are some bugs related to keyboard shortcut improvements:

https://bugzilla.mozilla.org/show_bug.cgi?id=1215061
https://bugzilla.mozilla.org/show_bug.cgi?id=1267145
https://bugzilla.mozilla.org/show_bug.cgi?id=1320332
https://bugzilla.mozilla.org/show_bug.cgi?id=1325692

**Comment by Adelscott** [comment]
Thanks for the reply, WebExtensions seems to be a big step back :(
