### ISSUE TITLE
Wrong selected tab after closing tab

### ISSUE THREAD

**Issue by toff** [piroor/treestyletab#1688]
## Short description
Wrong selected tab after closing tab.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open 3 tabs this way :
A
  \\-B
  \\-C (selected)
  I open a website, then I middle click on 2 links and finally I select tab C.
4. Close tab C. Selected tab is now B.
5. Select tab A and reopen tab C by middle clicking a link (like you did at step 3.) and select tab C again.
6. Close tab C.

## Expected result

Tab B is selected.

## Actual result

Tab A is selected.

## Environment

 * Platform (OS): Linux Ubuntu 16.04.3
 * Version of Firefox: 57.0.1
 * Version (or revision) of Tree Style Tab: 2.4.3

## Demo

![tst](https://user-images.githubusercontent.com/310113/34120370-b4ea688c-e425-11e7-813a-0e2affd9b236.gif)

**Comment by ivanatpr** [comment]
I've also noticed issues when closing tabs with lots of siblings where closing a tab causes focus to jump to the parent instead of the next sibling. Setting "browser.tabs.selectOwnerOnClose = false" in about:config seems to workaround the issue  but I imagine that might also cause other undesirable behaviors when closing tabs. 

I played around with the scenario Toff outlined above and found that when this happens it seems to infect any additional sibling tabs below tab C with the same unwanted behavior.

You can reproduce this behavior like so

1. Open 3 tabs this way :
A
\\-B
\\-C (selected)
2. Close tab C. Selected tab is now B.
3. Select tab A and reopen tab C by middle clicking a link (like you did at step 3.) and then also middle click on a third link to open tab D as a third child for A. You now have
A
\\-B
\\-C (reopened)
\\-D
4. select and close tab C. This should trigger the unwanted behavior of focusing on A instead of D
5. select and close tab D. This also causes tab A to be selected.

Note that if in step 5 you close tab B instead of D, the right behavior happens and tab D is selected. It only seems to break siblings in the tree below the double-closed tab.

I've also run into this enough times that I suspect it isn't limited to just cases where you close, reopen, and close the same tab, but I haven't been able to come up with a reproduceable test case for any other scenarios.

**Comment by ivanatpr** [comment]
Ok looks like there is more discussion about this problem in issue #1471 where the same workaround of setting selectOwnerOnClose  to false is suggested.

**Comment by piroor** [comment]
As you already commented, this is a feature of Firefox itself and not a bug. Even if you don't use TST, you'll see exact same result on Firefox's native tab bar.

**Comment by toff** [comment]
Closing this old bug.
TST has a correct tree behavior with browser.tabs.selectOwnerOnClose=false
