### ISSUE TITLE
Detach parent from tree

### ISSUE THREAD

**Issue by SicariusNoctis** [piroor/treestyletab#1711]
Typically, I find myself needing to swap a parent tab with a child, or moving it to a different location altogether. To accomplish this manually, I do:

 - Copy parent URL
 - Close parent tab (causes child to promote)
 - Open new tab
 - Paste URL and go

Of course, the problem with this is losing the parent's session/context.

It would be great to have some way of detaching parents without closing them.

**Comment by sumyungguy** [comment]
You could also select all the children and drag them to promote them, with Multiple Tab Handler installed. If you're still on Firefox 56, you could maybe make a keyboard shortcut for it, but I don't know what the code would be.

**Comment by piroor** [comment]
You can move a parent tab as an individual tab via drag and drop, on Firefox's native tab bar instead of the sidebar. Then you need to choose "Tree Behavior" => "When a parent tab is moved or closed by someone from outside of the tree sidebar" => "Treat as a parent always, when the tree sidebar is visible./..." (2nd item) or "Treat as a parent by operations inside the tree sidebar./..." (3rd item).

**Comment by piroor** [comment]
And, by recent commits now you can drag a parent tab as an individual tab by Shift-drag.
