### ISSUE TITLE
Firefox 59 introduced preliminary tab hiding

### ISSUE THREAD

**Issue by stanlane** [piroor/treestyletab#1722]
https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/ says
> Note that the original tab toolbar is still shown at the top of the window. Mozilla is working on this in Bug 1332447 (https://bugzilla.mozilla.org/show_bug.cgi?id=1332447).

Can you please also add this text to https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ ?

**Comment by piroor** [comment]
I think this new feature doesn't help TST users because active tab must be shown. Even if TST hides all tabs, they are automatically shown when a tab is focused on TST sidebar. Moreover, special tabs like `about:addons` are impossible to be hidden.

**Comment by piroor** [comment]
Sorry I misunderstood. The API can hide any tab except pinned tabs. So I'm planning to add a new option to hide inactive tabs.

**Comment by piroor** [comment]
Hmm, sadly the feature is need to be activated after Firefox 59 is released, because Firefox 58 and older versions cannot install TST with new permission `tabHide` neither in `permissions` nor `optional_permissions`. (You can try the feature on the branch https://github.com/piroor/treestyletab/tree/hide-inactive-tabs )

**Comment by piroor** [comment]
By changes at https://bugzilla.mozilla.org/show_bug.cgi?id=1350759 illegal value on optional permission should be ignored now. Hmm, is it correct? On Firefox 57 `about:debugging` I still see an "error" report, not "warning":

> Reading manifest: Error processing optional_permissions.2: Value "tabHide" must either: be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], must either [be one of ["<all_urls>"], match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], be one of ["bookmarks"], be one of ["find"], be one of ["history"], be one of ["activeTab", "tabs"], be one of ["browserSettings"], be one of ["cookies"], be one of ["topSites"], be one of ["webNavigation"], or be one of ["webRequest", "webRequestBlocking"]

**Comment by piroor** [comment]
The "error" actually doesn't block installation of TST, so I've merged the branch to the master.

However I've realized that the feature introduces another problem about tab focus. Because all other unpinned tabs are hidden, always the last pinned tab is focused after I close the active tab, even if there is other unpinned tab... (Firefox tries to focus to last visible tab and does fallback to hidden next tab.)

**Comment by piroor** [comment]
Hmm, the tab focus problem seems hard to be fixed on present design of TST. When the last pinned tab is focused after the active tab is closed, TST cannot detect the case is which one easily: the tab is focused as the last visible tab, or as the "owner" tab of the closed tab.

**Comment by tradewatcher** [comment]
a much easier way would be an option to activate "container links"  and display container names in the #sidebar-header menu than a single "Tree Style Tab" entry. 
A filter function to display only tabs from the selected container and start new tabs automatically in the selected container and all is fine... 

I dont know how much work this means. But this would be a really great solution.

Maybe some people will request to switch tabs between containers or open other containers per shortcut.

**Comment by piroor** [comment]
Please note that I'm still waiting the [bug 1332447: "API to hide the tabstrip"](https://bugzilla.mozilla.org/show_bug.cgi?id=1332447) become fixed. On the other hand, Firefox 59 only can hide individual tabs. I tried to hide inactive tabs to simulate "hide top tab bar" feature, but there are many problems:

 * When the current tab is closed, unexpected tab can be focused due to one of Firefox's spec: hidden tab should not be focused.
 * When you use another addon to provide "Tab Groups" feature with hiding individual tabs, TST completely ignores the "hidden" state of tabs. As the result you cannot use such another addon effectively with TST.

So, after something API to hide the tabstrip is land, I have to update TST to use the API to hide top tab bar and simply hide tabs from the sidebar if they are hidden by `browser.tabs.hide()` feature. Then TST will work together with another addon providing Tab Groups feature. TST won't need to implement such a feature by itself.

**Comment by piroor** [comment]
I close this because outdated.
