### ISSUE TITLE
feature request: Marker tab

### ISSUE THREAD

**Issue by yshui** [piroor/treestyletab#1728]
## Short description
Add support for creating a marker node in the tree, whose title can be edited by the user. This can be used, for example, to mark the purpose of subtrees.

**Comment by Lej77** [comment]
TST already has a special page for this purpose. How to create it and rename it was discussed in [Issue 1685](https://github.com/piroor/treestyletab/issues/1685).

**Comment by yshui** [comment]
@Lej77 OK, then I want to repurpose this issue to make this feature more visible and easier to use

**Comment by Lej77** [comment]
@yshui Since a lot of people seem to miss this feature that might be helpful. I think there has been people requesting marker tabs in TST extension reviews as well. But how should the feature become easier to find and use? Maybe a context menu item or it could be added in a similar way to how new container tabs are opened. It could be its own button beside the container tabs selector or its own item in the container tabs selection menu? It could also be added to [Multiple Tab Handler](https://addons.mozilla.org/firefox/addon/multiple-tab-handler/) so that when you selected multiple tabs you could choose to gather them under a group-tab.

**Comment by yshui** [comment]
@Lej77 I would suggest add it to the context menu. And Multiple Tab Handler support for this would be awesome.

**Comment by piroor** [comment]
OK, I've added [a new API to group given tabs](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#create-new-group-from-given-tabs) and ["Create New Group" command for selected tabs](https://github.com/piroor/multipletab/commit/3033540ba459ce8a46cc9366ca992a3a6338e8e6) for people who use both addons TST and MTH.

**Comment by yshui** [comment]
That is fast! Thanks.

**Comment by irvinm** [comment]
@piroor please close this.
