### ISSUE TITLE
Ability to group set of tabs under temporary group

### ISSUE THREAD

**Issue by madduck** [piroor/treestyletab#1747]
After having discovered that I can create dummy tabs using URLs such as `moz-extension://9614d91f-eb17-4958-b841-0b1746cff1f1/resources/group-tab.html?temporary=false&title=Read%20later` that are incredibly useful for grouping, I now wish there was a way to take a set of (top-level) tabs and assign them as children to such a tab.

I am unsure what the best UI for this would be, given that one cannot just select multiple tabs. Maybe upon opening a new TST group-tab, the body of the tab could display a list of open tabs in the current window, allowing me to "claim" tabs there, which then get moved to become children of this temporary tab?

**Comment by madduck** [comment]
If I select multiple tabs by mouse-drag, I cannot drag-drop them.

But if I select multiple tabs with multiple ctrl-clicks, then I can drag-drop them. Is there a reason for this?

**Comment by piroor** [comment]
Sorry, currently I have less motivation to add more features to manage group tabs. It was originally introduced originally to open bookmarks from a folder as a tree of tabs, with a metaphor of the bookmark folder itself. To keep TST simple as possible as I can, I believe that TST should not provide more features around the tab, instead only APIs should be provided.

**Comment by sumyungguy** [comment]
@madduck, as you now know, there's no need for the context menu items since it can be done with drag-and-drop, that's why Piro said "wontfix". But there does seem to be a bug about drag and drop of multiple tabs after selecting with long press and dragging. I opened piroor/multipletab#189 about the issue. Is this the problem you have?

As a work-around, instead of multiple control-clicks, you can also shift-click to select a range of tabs.

**Comment by madduck** [comment]
@sumyungguy This is exactly the problem and my latest conclusion.
Thanks for opening #189 about that.

**Comment by piroor** [comment]
Now TST has a built-in context menu command "Create New Group from tabs" for tabs multiselected via Ctrl/Shift-click.
