### ISSUE TITLE
used the code snippet to hide the top tabs and I would like to make the top bard dark to fit with the dark theme

### ISSUE THREAD

**Issue by ninja85a** [piroor/treestyletab#1753]
hey I've used this guide https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349 to hide the top bar but it makes it white which wouldnt be a big deal if I was using the standard theme but I'm using the dark theme currently using and I would like for the top bar to match it.
so how would I get that done?

**Comment by Lej77** [comment]
The top bar of the window should match the theme's colors if your not showing the title in the top bar. If you are then yes the top bar will be white. If you want to show the title in the top bar and have it match your theme's colors you could try using the CSS code I posted in [issue 1672](https://github.com/piroor/treestyletab/issues/1672#issuecomment-354185431). I'm using Windows 10 and if you have a different OS then it might not work correctly since it is quite complicated and probably easily broken, but it can't hurt to try.

**Comment by ninja85a** [comment]
gave that a shot but it doesnt seem to work I'm on win 10 as well so I'm not to sure what could be stopping it from working the only other thing I have in userchrome.css is 
`#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}`
which I only added after I added the code in #1672 that you posted and it didnt work before hand

**Comment by Lej77** [comment]
@ninja85a So you want to show the title in the top bar? If you don't show the title in the top bar is the top bar the correct color then? Also did you use my last comments code (i made 3 comments on that issue)?

**Comment by Lej77** [comment]
Also my third comment's code requires that you don't use Firefox's title alternative. That means you need to click the hamburger menu -> Customize, uncheck "Title Bar" at the bottom.

**Comment by irvinm** [comment]
@ninja85a can you close this or is it still an issue for you?

**Comment by irvinm** [comment]
@piroor can you close this item? No updates since Feb 2018.

**Comment by piroor** [comment]
OK, looks no progress, so I close this for now.
