### ISSUE TITLE
New tab on double click

### ISSUE THREAD

**Issue by bakaoniisan** [piroor/treestyletab#1765]
Could you add a (selection box) in settings to allow new tab with middle click or double right click?

In settings under - New Tabs Behaviour,  "New Tab" Button

"For (middle) click, open new blank tab as"
"For (double) click, open new blank tab as"

Thanks

**Comment by piroor** [comment]
Sorry I won't implement those behaviors because I think they are quite odd in general behavior of GUI widgets.

Generically double-click (and triple-click) action is effective only on cases when the target does just "invertible" reaction for single-click. For example:

 * Icons on your desktop (Windows, macOS, or Gnome on Linux) are not opened by single click, just focuses. And you need to double-click on an icon to "open" it.
 * Click on the title bar of a window just focuses to the window. Double-click on the title bar can be used for different special reactions: maximize the window, rollup/rolldown the window, and others.
 * Text in input field does nothing by single click, instead the cursor moves to the clicked position. In this case double-click on text can do some more special reaction: select a term, open the double-clicked URL text, and others.

On the other hand, UI widgets designed to react for single click does nothing for doube click. For example:

 * Click on a closebox ("x" button) of a window closes the window. It is not double-clickable, because the window is closed by the first click.
 * Click on a "OK" button in a confirmation dialog accepts the decisiton. It is not double-clickable, because the dialog is closed by the first click.
 * Click on a checkbox toggles its checked status. It does nothing for double-click, just toggled twice.

The "New Tab" button seems to be one of UI widgets of the secondary group, not in the first group. If I implement special reaction for double-click on the button, TST must not do something immediately by single click on it. TST needs wait for a while, and after guaranteed that it is not double-click action, it can open new tab. I think this is too slow and stressful.

And there is same problem for right-click. Single right-click generally opens the context menu. If I implement special reaction for double-right-click, TST won't open the context menu immediately by single right-click. More badly, on some environment (macOS and Linux) the context menu is opened by just pressing-down the mouse button, without releasing the button.

**Comment by bakaoniisan** [comment]
Sorry, I may have misunderstood the setting "For (middle) click, open new blank tab as" because I do not have middle click on Slimblade trackball or touchpad. I have never been able to use it.

> The "New Tab" button seems to be one of UI widgets of the secondary group
I was thinking middle click option in settings meant that middle clicking on any tab or focused tab would open a new tab. I was wrong 

I did not realise the "New Tab" button was used with "For (middle) click, open new blank tab as"

So I guess my 'wish' is for an option to double click a any tab (if possible) or focused tab to open a new tab
It would save a little mouse movement when looking through tabs and you want to open another.
As of now you have to select(focus) the tab, then move mouse to "New Tab" button, click and then you have the new tab focused. Which is fine when opening a tab from current page. No extra mouse movement.

**Comment by piroor** [comment]
Hmm, then the behavior can be implemented via API like https://addons.mozilla.org/ja/firefox/addon/tree-style-tab-mouse-wheel/ (it provides ability to reload tab by double click.)

**Comment by bakaoniisan** [comment]
If you think the effort is worth it to save some mouse movement.

I'd guess about 30% of the time I open a new tab it's by moving mouse directly down from focused tab tab to new tab button.

The other 70% is moving from page to new tab button which does not add any extra movement for most.

**Comment by piroor** [comment]
Sorry but I'm very conservative to adding new feature to TST, especially when the feature is not a built-in behavior of Firefox's tab bar and it is not related "tree of tabs". Please note that this is a design policy to keep TST feature-oriented. Otherwise, as I wrote at the [migration story](http://piro.sakura.ne.jp/latest/blosxom/mozilla/extension/treestyletab/2017-10-03_migration-we-en.htm), TST easily become too much, too heavy, and chaotic.

Thus, TST provides [APIs for other addons](https://github.com/piroor/treestyletab/wiki/API-for-other-addons) instead of adding built-in features for such cases. I hope that non-builtin features are implemented by people who want to use. And [there are some examples](https://github.com/piroor/treestyletab/blob/master/README.md#addons-extend-tst).

**Comment by irvinm** [comment]
@piroor please close this.
