### ISSUE TITLE
make new release of treestyletab have access to bookmarks as opt-in rather than mandatory. 

### ISSUE THREAD

**Issue by shirishag75** [piroor/treestyletab#1773]
Right now the new release of TST 2.4.14 asks access to bookmarks, make it opt-in sort of behavior rather than mandatory. 

## Environment

 * Platform (OS):  Debian Linux Buster (testing)
 * Version of Firefox: 58.0.1
 * Version (or revision) of Tree Style Tab: 2.4.14

**Comment by piroor** [comment]
`bookmarks` permission is still optional.
https://github.com/piroor/treestyletab/blob/master/webextensions/manifest.json#L20
If you update TST by installing new version from the website or a downloaded file, the confirmation dialog shows all permissions including already granted optional permissions. It is by design of Firefox itself.

**Comment by shirishag75** [comment]
umm... at my end it the box said it needs new permission for the add-on. There was nothing about that this is an opt-in thing.  I'll remove the add-on and install it again so that I can share a screenshot of the same.
