### ISSUE TITLE
[API Improvement] Remember registered extensions for next TST initialization

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1794]
## Short description
Currently if I have both MTH and TST installed and TST is updated then MTH's selection feature stops working until MTH is restarted. I though it should be possible to fix this by remembering the extensions that are registered for the next time TST starts up. Then TST can send the "ready" message to those extensions and they could re-register themselves.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install MTH
 4. Update TST. Same result as disabling and re-enabling TST.

## Expected result
MTH's selection feature should continue working after TST update.

## Actual result
MTH's selection feature stops working after TST update and requires that MTH is restarted (disabled and re-enabled) for it to start working again.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58.0.2
 * Version (or revision) of Tree Style Tab: 2.4.16

## Example Solution

Add the following code to a background script:
```JavaScript
async function saveExtensionId(id) {
    let data = await browser.storage.local.get({ extensions: [] });
    if (!Array.isArray(data.extensions)) {
        data.extensions = []
    }
    if (data.extensions.indexOf(id) < 0) {
        data.extensions.push(id);
        await browser.storage.local.set(data);
    }
}

async function messageExtensions(message) {
    let data = await browser.storage.local.get({ extensions: [] });
    if (!Array.isArray(data.extensions)) {
        data.extensions = []
    }

    let failedExtensions = [];
    for (let ext of data.extensions) {
        try {
            await browser.runtime.sendMessage(ext, message);
        } catch (error) {
            failedExtensions.push(ext);
        }
    }
    if (failedExtensions.length > 0) {
        data.extensions = data.extensions.filter((ext) => failedExtensions.indexOf(ext) < 0);
        await browser.storage.local.set(data);
    }
}

messageExtensions("ready");
```

Then use the `saveExtensionId` function for extensions that register themselves to TST via the `browser.runtime.onMessageExternal.addListener` listener.

**Comment by joshuacant** [comment]
I also see this behavior with all of my TST addons, though I've been trying to address the problem on my end, assuming my code was at fault. The TST API docs here: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#register-and-unregister make me think this should already be the working behavior. 

I'm still not 100% sure where the issue is, but I at least wanted to say that I've been seeing this same thing too. I've got an open issue on my tracker for it: https://github.com/joshuacant/tst-wheel_and_double/issues/6 as well as some discussion on a pull request here: https://github.com/joshuacant/tst-wheel_and_double/pull/10
