### ISSUE TITLE
[Enhancement] Move focus to popup window, when multiple tabs are closed

### ISSUE THREAD

**Issue by sanyarnd** [piroor/treestyletab#1795]
## Short description
When you close multiple tabs, popup window must have focus on raise. It is logical, and either way, you should cancel close, or accept it.
Also I suppose many Firefox users use shortcuts, so it'll be great enhancement to speedup workflow.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 58
 * Version (or revision) of Tree Style Tab: latest

**Comment by piroor** [comment]
Addon cannot grab focus due to restrictions of WebExtensions APIs. So, as a workaround, now TST shows the confirmation dialog in the content area if possible. It will handle keyboard operations after Ctrl-W shortcuts.

**Comment by irvinm** [comment]
@piroor not sure there is more to do with this one.  Can we close this one?

**Comment by piroor** [comment]
I've realized that the in-content confirmation dialog is now available on lately versions of Firefox, and it has been fixed with the commit 663f51609e6df8a19839087ae9ea984d1b1e2980.

Anyway, in-content confirmation is now available if `<all_urls>` permission is granted by the user and the active tab is not guarded (like addons.mozilla.org, about: pages, or others). I think it is the best way possible on WebExtensions API, so it looks enough to close this as "fixed".
