### ISSUE TITLE
Force to open links in new child Tab

### ISSUE THREAD

**Issue by IQnews** [piroor/treestyletab#1810]
For example: click on Google search results-links - and link opened in new child-tab.

**Comment by sumyungguy** [comment]
https://addons.mozilla.org/en-US/firefox/addon/tap-to-tab/
https://addons.mozilla.org/en-US/firefox/addon/dblclicker/
https://addons.mozilla.org/en-US/firefox/addon/open-link-with-new-tab/
Search for others...

**Comment by piroor** [comment]
Instead of "install only TST including its various features", basically "combination with other addons" is the recommended style of TST usage. I hope to make TST compatible with other addons, and keep it only with features related to "tree" or features impossible to be done by other addons. As you listed, the feature can be done by other addons developed for the purpose, and actually, https://addons.mozilla.org/en-US/firefox/addon/open-link-with-new-tab/ seems working well. If you get something compatibility problems, please report it.

**Comment by piroor** [comment]
I close this because outdated.
