### ISSUE TITLE
[feature request] Rename a tab

### ISSUE THREAD

**Issue by konradpapala** [piroor/treestyletab#1825]
Hello.

I would love to be able to rename a tab.

I know there already was a similar request, but it's old, and the solution is outdated (a different extension is proposed, which doesn't work anymore) - https://github.com/piroor/treestyletab/issues/794

I tried lots of existing extensions from this list:
https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=rename

Most of them just doesn't work with TST. I.e. no way to change a title. 
The ones which do work, have their serious issues. At least when working with TST

The most popular one: https://addons.mozilla.org/en-US/firefox/addon/rename-tab-title/ - **does** work almost perfectly. But it works **per url**. Not per tab. That means, that in any given site, like localhost/coo-project, whenever I rename the tab eg. to 'local / cool' it does "work" as soon as I click anywhere on the page, and by doing so I change the url.

What I really need to is rename a **tab**, so it is persistent, it won't change, whatever what, in that given tab. And I think (wild guessing here) the only way to accomplish that is to implement it directly in TST.

**Comment by piroor** [comment]
Because it is not related to "tree", I won't implement it as a built-in feature of TST.

**Comment by piroor** [comment]
The addon Simple Tab Renamer https://addons.mozilla.org/en-US/firefox/addon/simple-tab-renamer/ seems keep renamed title after navigation. So I think the addon should be updated to persist given name for each tab.

**Comment by konradpapala** [comment]
OK, I understand.

BTW, I also tested the "simple tab renamer" - I doesn't remember settings between browser restarts.

But OK, I understand why it won't be done. Thanks anyway.

**Comment by sidney-eliot** [comment]
> Because it is not related to "tree", I won't implement it as a built-in feature of TST.

I disagree, it totally has to do with treestyle and nothing else. Maybe not renaming tabs, but renaming grouped tabs should definitely be possible. A big reason why people use this addon is because every browser except for Firefox has a tab grouping feature, and to make Firefox usable we use this addon. I think renaming tab groups is important to quickly navigate around.

Please reconsider adding some sort of renaming for grouped tabs or maybe even add something new that can act a tab group container.

**Comment by piroor** [comment]
TST's group tab (try typing `ext+treestyletab:group` into the address bar) is already rename-able by clicking its title area.
![image](https://github.com/piroor/treestyletab/assets/70062/178d8d65-8903-4ae4-bee1-40c87858d9d2)

**Comment by sidney-eliot** [comment]
Oh, there's actually a way to group tabs into a folder. But is there an easier way of doing that than typing a command into the URL bar, maybe in a right click menu.

**Comment by piroor** [comment]
Please try to create a new bookmark into the bookmarks toolbar with the URL `ext+treestyletab:group`. It will be available like as a button to open a new group tab. (Sorry I have no plan to add any built-in menu command to open the tab to TST. Instead you can use a helper addon [TST More Tree Commands](https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/) for extra menu commands to operate such group tabs, if you seriously require them.)

**Comment by Baerbeisser** [comment]
Back do topic, renaming tabs seems to me a core feature. You do fetch the name from some API of Firefox, after resolving, right? I think adding a rename option similiar to Siedebery wouldn't add much complexity or bloat. Would be way more difficult to handle in an addon to tst.

**Comment by piroor** [comment]
There are some more addons providing the feature to rename tabs:

* [Tab Mix \- Rename Tab](https://addons.mozilla.org/en-US/firefox/addon/tab-mix-rename-tab/)
* [Tab ReTitle](https://addons.mozilla.org/en-US/firefox/addon/tab-retitle/)
* [Rename Tab Title](https://addons.mozilla.org/en-US/firefox/addon/rename-tab-title/)
* [Rename Tab](https://addons.mozilla.org/en-US/firefox/addon/rename-tab/)
* [Simple Tab Rename](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-rename/)
* [Tab rename](https://addons.mozilla.org/en-US/firefox/addon/context-menu-tab-rename/)

The feature looks really independent from tree. I can't believe it should be one of built-in features of TST, except if it need to be included to TST due to compatibility issues with those addons.
