### ISSUE TITLE
How to focus on previous child tab after closing current one?

### ISSUE THREAD

**Issue by giantoppai** [piroor/treestyletab#1827]
## Short description
Is there a way to focus on previous child tab after closing current child tab?

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Make three child tabs.
 4. Close the second child tab.

A - parent tab
-> A1 child tab (what I want focused)
-> A2 child tab (close this tab)
-> A3 child tab (what actually gets focused)

## Expected result
First child tab gets focused.

## Actual result
Third child tab gets focused.

## Environment

 * Platform (OS): 
 * Version of Firefox: 59.0
 * Version (or revision) of Tree Style Tab: 2.4.17

**Comment by piroor** [comment]
There is no option to do that, and it is also not the default behavior of Firefox itself. In other words, by the design policy, TST respects Firefox's default behavior for various cases. Because Firefox will focus to the tab A3 instead of A1 and it seems quite natural, TST does nothing for the case. (If another parent tab "B" exists next to the A3 and you close the active A3 tab, Firefox will focus to B but it is unnatural on TST and TST tries to redirect focus to A2. This is the only case TST controls focus of tabs for closing active tab.)

I think that the behavior "focus to left (previously positioned) tab after the current tab is closed" should be provided by another addon developed for the purpose, and TST should not provide the feature. If such an addon doesn't work with TST well, I'll make TST compatible to it or contribute to the addon to make it compatible with TST.

**Comment by giantoppai** [comment]
Thanks for the explanation, dev.

**Comment by giantoppai** [comment]
I started an add-on to fix my problem with very limited experience. It doesn't work perfectly and I don't know what to do. Can you take a look? (Please don't laugh)
https://github.com/giantoppai/TST-Focus-Preceding-Tab-On-Close

**Comment by Lej77** [comment]
@giantoppai I took a look at your code and made some improvements to fix a couple of issues. From my testing it should work pretty well now. The improvements are in a pull request on the GitHub page so you can see them there.

**Comment by giantoppai** [comment]
@Lej77 Wow, thanks so much for helping out! You improved it by a lot!

**Comment by giantoppai** [comment]
@neube3 I didn't before, but I think I should.

**Comment by giantoppai** [comment]
Add-on created.
https://addons.mozilla.org/en-US/firefox/addon/tst-focus-preceding-tab/

**Comment by giantoppai** [comment]
@Lej77 Would you like to be credited on the add-on page or be made as one of the authors? You did write nearly the whole thing.

**Comment by Lej77** [comment]
@giantoppai I doesn't really matter to me so you don't need to. But thanks for asking.

**Comment by piroor** [comment]
I close this because outdated.
