### ISSUE TITLE
Default favicon for tabs

### ISSUE THREAD

**Issue by chriscjs** [piroor/treestyletab#1828]
I don't like the new photon globe default favicon for tabs.  Is there any way to change it?

**Comment by piroor** [comment]
There is a user stylesheet to show old icon;
https://github.com/piroor/treestyletab/issues/1822#issuecomment-371339246

Anyway I won't make it an option, because the current "globe" icon is the default icon on Firefox 60 and later. To reduce costs of maintenance, TST respects appearance of the latest Firefox, this is a design policy.

**Comment by piroor** [comment]
I close this because outdated.
