### ISSUE TITLE
[feature request] Hide/show tabs when tab group is closed/open

### ISSUE THREAD

**Issue by gagarine** [piroor/treestyletab#1831]
I'm mostly using the TST group features:
![screen shot 2018-03-15 at 16 20 34](https://user-images.githubusercontent.com/164074/37472708-03ff42b8-286d-11e8-809a-8484f7db3f15.png)

I would like to hide/show tabs (on Firefox top bar) based on group that are open/close. Alternatively, that can be a context menu (hide/show this tree).

I know this is similar to https://addons.mozilla.org/en-US/firefox/addon/sync-tab-groups/ but sync tab groups UX is so bad, it's unusable. I'm also using the tree sometimes.

**Comment by gagarine** [comment]
Oh perhaps if https://addons.mozilla.org/en-US/firefox/addon/tab-groups/ group would be visible on TST (similary to TST group) that would be even better.

**Comment by piroor** [comment]
I'm negative to implement this feature, to avoid complex conflict with other addons. Tab Groups (and other similar addons) also uses the API to show/hide tabs. Tabs hidden by TST are hard to be controlled by Tab Groups, and the opposite is also. So I think that the most stable solution is the current implementation: hidden tabs are also hidden in the sidebar, and treated as "not exists".

**Comment by piroor** [comment]
Anyway, if there is an addon which provide context menu items for tabs, I'll contribute to the project to support TST's fake context menu, like: https://github.com/Morikko/sync-tab-groups/pull/96

**Comment by gagarine** [comment]
@piroor I switched to https://github.com/drive4ik/simple-tab-groups (very good add-on!) using the option "individual windows for each group". This should works pretty well with TST out of the box but didn't test it yet.

**Comment by Morikko** [comment]
[Maintainer of Sync Tab Groups]
> I'm mostly using the TST group features:

How to use it ? I have only tabs as parent, never folders.

> I would like to hide/show tabs (on Firefox top bar) based on group that are open/close. Alternatively, that can be a context menu (hide/show this tree).

It will land later (see [issue](https://github.com/Morikko/sync-tab-groups/issues/64)) but only between groups in Sync Tab Groups nothing related to TST. I have been delayed since I am focusing on stability and other features.

Also TST is probably not compatible with Sync Tab Groups any more. An [issue](https://github.com/Morikko/sync-tab-groups/issues/26) was opened. Since I have changed my code and probably broken it elsewhere. It is still on my plan to fix it.

-------
Some notes: 
 - Sync Tab Groups will try to restore Tree Style Tab when switching as much as possible when the issue will be fixed
 - Sync Tab Groups won't interfere with TST information (see My vision)
 - Sync Tab Groups won't use groups from TST. The other might be possible but depend on @piroor.

My vision:
 - TST: sub-groups with the tabs in each window
 - Sync Tab Groups: groups (bunch of tabs) where a group occupy a full window when used or is invisible (but in memory) if not.

**Comment by irvinm** [comment]
Can anyone on this thread confirm if this is still an issue or if there is anything more to discuss here?  @gagarine can you close this item if not?

**Comment by gagarine** [comment]
I'm not using TST anymore. I really can test it right now because I'm in the middle of a job and have +300 tabs open in various group and can afford to lose any of them :/.

**Comment by irvinm** [comment]
@gagarine I typically have 1000+ tabs in my sessions at any given time, so I understand.  I have found that using a session manager (like "Tab Session Manager") has provided me a nice safety blanket in case I lose my session and it is supports storing TSTs heirarchy if you enable it in the options.

If you don't want to test it now, may I suggest closing the issue until you are able\willing to try it again?

**Comment by gagarine** [comment]
@irvinm  Sure let close it. I will keep an eyes on this (I want to try TST again).
Thanks for Tab session manager, I reduce Firefox IO by changing session write delay and removing disk cache (see https://gist.github.com/gagarine/5cf8f861abe0dd035b7af19e4f691cd8 ) so this plugin can actually be the perfect addition to my setup.

**Comment by ctrueden** [comment]
I was looking for exactly this feature in TST—the ability to hide tabs (in the horizontal tab bar) of collapsed groups—and could find nothing discussing it in the README or in the list of TST extensions. Based on this and other linked issues here, I gather TST cannot and will not support this feature, and TST extensions cannot do so either without introducing unwanted side effects? But I discovered that the Sidebery extension can do it:

![Image](https://github.com/user-attachments/assets/ad11ff22-30d1-4665-a068-727d27dd2153)

Working great in my experience thus far, although I haven't tried it yet with hundreds of open tabs, and I have not tried combining it with other tab management extensions.
