### ISSUE TITLE
[feature request] Ability to include URL in sidebar tab tooltip

### ISSUE THREAD

**Issue by tobbez** [piroor/treestyletab#1832]
Because some sites use generic page titles, and you want to see what page is open in a tab without switching to it. Preferably it would appear on a second line in the tooltip (under the page title).

It doesn't seem possible to achieve using just custom CSS.

Doesn't seem possible using the 'API for other addons' either.

Existing addons that can change tab tooltips are not an option, because they do it by changing document.title inside pages, which means it won't work for all pages. That approach also causes issues for other addons that depend on or use the actual page titles.

**Comment by piroor** [comment]
Sorry I have no plan to add this feature, because TST respects behaviors of Firefox's native tabs doesn't do that.

Instead, I think this should be done by something addon developed for the purpose, because Firefox's native tabs also have same problem. If the addon overrides `document.title` of pages, updated title will be used by TST also.

**Comment by irvinm** [comment]
@piroor please close this.
