### ISSUE TITLE
Add a css class "new-tab" to new tabs.

### ISSUE THREAD

**Issue by AlanLynn** [piroor/treestyletab#1890]
There is no good way (that I'm aware of) to apply CSS styles to new tabs. Previously, I used the CSS below. But as of version 2.4.19 it no longer works, because tooltips are only shown for tabs that can't fit their full title.

```
/* Hide the favicon on new tabs. */
.tab[title="New Tab"] .favicon {
  visibility: hidden;
}
/* Gray text on new tabs. */
.tab[title="New Tab"] .label {
  color: #888;
}
```

The wiki contains a working (but inelegant) method for hiding new tab favicons. However this method does not appear to be able to alter the label color, or anything but the favicon. https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#pre-photon-no-favicon-tab-icon-1822 

For me, the best solution would be to add a css class "new-tab" to new tabs. This would make it trivial to apply any CSS style you want to new tabs.

* Related issue: #1822

**Comment by Lej77** [comment]
You can use one of the following selectors to select new tabs: 
* `.tab[data-current-uri="about:newtab"]`
* `.tab:-moz-any([data-current-uri="about:newtab"], [data-current-uri="about:home"])`
* `.tab[data-label="New Tab"]`

**Comment by AlanLynn** [comment]
The third one works great! Thanks, @Lej77.

```
/* Hide the favicon on new tabs. */
.tab[data-label="New Tab"] .favicon {
  visibility: hidden;
}
/* Gray text on new tabs. */
.tab[data-label="New Tab"] .label {
  color: #888;
}
```

Can we change the wiki to use this method? It's much nicer.

**Comment by Lej77** [comment]
@AlanLynn You mean for #1822? If so then probably not since it reacts to the default icon being set for a tab that actually has an icon. Using the new tab selector would only add another condition to the selector since the current conditions couldn't be removed.

If you mean that we should add your code to the wiki then we could do that.

You should note that the new code you suggested with the third option only works on english Firefox installations since it reacts to new tab's title. The other selectors i suggested (option 1 and 2) would be better to use in the wiki since they work for all locals.

**Comment by AlanLynn** [comment]
@Lej77 Yes. Thanks!

A "new-tab" css class would be more convenient, but I think this method should be good enough, so I'll close this issue.

**Comment by hub2git** [comment]
This doesn't seem to work. I'm on Firefox 69.0.1 on Linux Mint. After I added the code to the "Extra rules for Sidebar Contents" in TreeStyleTab's Advanced section, new tabs I Middle-Mouse-click still show the favicons to the left of the text of the webpage title.
