### ISSUE TITLE
TST context menu vanished

### ISSUE THREAD

**Issue by Vampire** [piroor/treestyletab#1975]
I just updated FF from 60.0.2 to 61.0.1 and now the TST context menu is not present any longer on the normal tab bar. :-(

**Comment by piroor** [comment]
I cannot reproduce this problem on my environment: TST 2.4.24 + Firefox 61.0.1 on  Windows 10. Could you try to reinstall TST?

**Comment by Vampire** [comment]
Sure, settings will be preserved, right? 
I can already say that disable, then enable did not help, as I tried that before reporting.

**Comment by piroor** [comment]
Reinstalling can clear the user data. Hmm, but disabling and re-enabling should work same as reinstalling, so you don't need to uninstall TST anymore. Context menu items provided by TST should be shown except all context menu items are disabled by TST's configurations.

Did you tried to restart Firefox itself? If you are running Firefox too long, addon information on the RAM can be broken and it can produce such an odd behavior.

And, does the problem appear with a clean profile? You can run Firefox with new clean profile with command line options: `C:\...\firefox.exe -profile=c:\path\to\blank\folder -no-remote`. If you cannot reproduce the problem on a clean environment, it can be caused by something in your regular profile: userChrome.css, other addons, cache, or others.

**Comment by Vampire** [comment]
Well, the context menu in the sidebar works as expected, just on the normal tab bar it vanished.

Firefox was restarted to do the upgrade of course. Didn't try to restart again though, will try when I'm at my box.

**Comment by Vampire** [comment]
What the ...?
Now that I'm back home, the context menu suddenly is present again, without further action. :-/
