### ISSUE TITLE
Please apply theme to group tabs

### ISSUE THREAD

**Issue by polyzen** [piroor/treestyletab#1986]

**Comment by piroor** [comment]
This is not easy due to some reasons. Basically TST loads and initializes theme information only when the sidebar is visible. In other words, theme management system is implemented as a part of the sidebar. On the other hand, group tab can be shown without sidebar. So we need to move codes for theme management from the sidebar module to the background module.

Sadly I have less motivation for this change, so I need pull requests to do that, from contributors who really want this feature.

**Comment by piroor** [comment]
I close this because outdated.
