### ISSUE TITLE
Should we use WebComponents for building a DOM element?

### ISSUE THREAD

**Issue by tetsuharuohzeki** [piroor/treestyletab#2000]
[From Firefox 63](https://groups.google.com/d/topic/mozilla.dev.platform/RcanREo7hU0/discussion), Gecko eventually [(will) ships](https://hg.mozilla.org/mozilla-central/rev/16daef3a89a2) Shadow DOM and Custom Element as known as [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components).

These features provides a way to create a custom DOM element and encapsulate it.
I think they would useful to building a view for this add-on.

**Comment by irvinm** [comment]
@piroor can you comment on this? (Sorry, I don't have a sense if this is still applicable today or not)

**Comment by piroor** [comment]
This was impossible on TST 2.x, but currently TST 3.x is designed very similar to this, so now it may be migratable to WebComponents. Especially if the migration improve performance or maintainability, I agree to do it.

**Comment by saneyuki** [comment]
To support TST's _theme_ completly, I suspect it's better to wait [CSS Shadow Parts](https://drafts.csswg.org/css-shadow-parts-1/) ([bug 1551113](https://bugzilla.mozilla.org/show_bug.cgi?id=1551113)).

But I think we can replace a simple element with custom element from now.

**Comment by saneyuki** [comment]
[CSS Shadow Parts](https://drafts.csswg.org/css-shadow-parts/) will [ships](https://groups.google.com/d/topic/mozilla.dev.platform/dWnXJtFKY0I/discussion) in Firefox v72.

By CSS Shadow Parts, I think we can provide a more reasonable way for style customization instead of depending on CSS variables. I suspect we can provide customizable style encapsulation.

**Comment by irvinm** [comment]
With FF72 out, is there more to look at now?

**Comment by piroor** [comment]
This looks should be progressed experimentally on a branch, until Firefox ESR68 becomes outdated. Maintaining multiple branches is hard for me, so I hope to concentrate to maintain and hope @saneyuki gives me experimental implementation examples...

**Comment by saneyuki** [comment]
I'm sorry. I don't have a concrete progress on https://github.com/piroor/treestyletab/pull/2427.

Because:

1. I'm busy recently....
2. I suspect we might need a bunch of refactoring to implement [the proposed plan](https://github.com/piroor/treestyletab/pull/2427#issuecomment-566461006).
3. By _reason 2_, I felt it might be better we should wait the end of life for ESR68 (Mozilla releases new ESR).

---------------

BTW, I think this issue has been almost done and this is still remains as a meta/umbrella issue. There are rests of pieces to continue Web Components-fication like CSS Shadow Parts and [Constructable Stylesheets](https://github.com/WICG/construct-stylesheets) ([BMO](https://bugzilla.mozilla.org/show_bug.cgi?id=1520690)). But I don't think they are not strong reason to keep this issue as open status.

Is it the time to close this?

**Comment by irvinm** [comment]
@piroor what do you think of @tetsuharuohzeki comments?  (Side note that ESR68 is almost end of life with ESR78 already out)

**Comment by piroor** [comment]
They looks to be quite different from the current paradigm, so I need a success model case to understand where TST should go to, like the first migration to WebComponents done by @tetsuharuohzeki.

When I tried to implement the [Extra Tab Contents API](https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API) I learned more about CSS Shadow Parts, but sadly my brain is still bound to old methods about styling of UI strongly and I cannot imagine CSS Shadow Parts based TST...

**Comment by irvinm** [comment]
@piroor \ @tetsuharuohzeki ... any thoughts if we should leave this open or not?

**Comment by piroor** [comment]
To be honest I still cannot understand what is the better future produced by completed migration to WebComponents. I think that the WebComponents technology is designed for modules shared across multiple projects, like confirmation dialogs ( https://github.com/piroor/webextensions-lib-rich-confirm ). It looks reasonable that style definitions in TST does not affect to such shared components accidentally, on the other hand, such isolation still looks overkill for me, to implement components available only in this project.

But I possibly misunderstand the power of WebComponents. If Firefox's native tabs are reconstructed with WebComponents, I'll learn effective usage of the technology to implement project specific components. I close this until the time.
