### ISSUE TITLE
Folders (and trees) are buggy

### ISSUE THREAD

**Issue by Ploppz** [piroor/treestyletab#2003]
I had one empty folder, and wanted to add a tab to it. I dragged it up and the result:

![ss](https://i.imgur.com/zGtX8Ka.png)

The second youtube tab there is actually in the `MUSIC` folder. There are a lot of such bugs. When I move folders around it gets worse. Its contents may become more scattered among the other tabs (while the folder is expanded - collapsing works fine)

In the following screenshot, the reddit tab is actually under the `TODO` folder.

![ss](https://i.imgur.com/RQg3Idd.png)

Another screenshot where all the tabs in the image is actually in the `MUSIC` folder:

![ss](https://i.imgur.com/NSpXFwC.png)

This happens when I drag a tab from _above_ the folder, and drop it on top of it.

Edit: I found that I have the same problem just using any arbitrary tab as a folder (or call it the root of a tree). Not always though, but most often.

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 61.0.1
 * Version (or revision) of Tree Style Tab: 2.5.1

**Comment by ssokolow** [comment]
I've encountered this problem too.

I haven't encountered it recently enough to be sure, but I suspect it will respond well to the same workaround I use for "tab refuses to be dragged". (Tap F1 twice to hide and show the TST sidebar so the document gets reloaded.)

**Comment by piroor** [comment]
I close this because outdated.

**Comment by ssokolow** [comment]
For the record, before I had to disable TST about a month ago because it seemed to be consistently contributing to Firefox being too sluggish, this problem was still an issue.

(I'm thinking that, when I have time, I'll investigate whether it's viable to write my own TST clone which treats the sidebar's DOM as the authoritative copy of the tree so it's impossible for it to get out of sync. I know, at minimum, I could ensure expand/collapse always works properly.)
