### ISSUE TITLE
disable container tabs

### ISSUE THREAD

**Issue by Tealk** [piroor/treestyletab#2032]
Hello,

is it possible to disable container tabs?

**Comment by piroor** [comment]
Sorry but I won't fix this "problem" by some reasons.

First, by TST's development policy, container tab features available on Firefox's plain tab bar need to be available on TST's vertical tab bar also. This is the main reason why container tab feature is integrated to TST by default.

Then, you may think that why the feature is not optional. There is the second reason. The permission `contextualIdentities` required to integrate container tab features is impossible to be granted optionally. See [the list of available values for `optional_permissions`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions) - it doesn't contain `contextualIdentities`. Thus I need to put `contextualIdentities` to the list of permanently required permissions. There is very less reason to make TST's container tab features optional, because I only can deactivate those features cosmetically but cannot remove the `contextualIdentities` permission oon the fly. Firefox still reports "TST requires container tab feature" even if there is no visible container tabs features, due to the fixed permission `contextualIdentities`.

**Comment by Tealk** [comment]
Thank you for the explanation. That's Great!
