### ISSUE TITLE
Cannot drag and drop a tab to the browser's bookmark toolbar anymore

### ISSUE THREAD

**Issue by C4rter** [piroor/treestyletab#2033]
## Short description
I'm unable to drag a tab from the TST to anywhere else in the browser. A black "not allowed" kind of sign blocks any interaction with the browser except inside the TST area.
Until recently, I could drag and drop a tab from TST to my bookmarks toolbar. That's not working anymore.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open website.
 4. Try dragging the tab onto the bookmark toolbar.
 5. A symbol shows and blocks dropping the tab on the bookmarks toolbar.

## Expected result
Dragging the tab to the toolbar and dropping it there should create a bookmark.

## Actual result
Unable to drop the tab over over the bookmark toolbar.

## Environment

 * Platform (OS):  Windows 7
 * Version of Firefox: 62.0
 * Version (or revision) of Tree Style Tab: 2.5.4

**Comment by C4rter** [comment]
Alright I found it in the Debug section in the settings:
Activating "AllowBookmarkCreationFromDraggedTree" fixed it.

I'm not sure why this is hidden inside the debug section but I'm glad it was somewhere.

**Comment by piroor** [comment]
> Why not keep the old behavior as default and add an option for switching to the new one?

Because the old behavior depended on a Gecko specific API [DataTransfer.mozSetDataAt](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/mozSetDataAt). [It is now deprecated and unavailable on Firefox 63 and later.](https://bugzilla.mozilla.org/show_bug.cgi?id=1453153) You still can use the API by a secret preference, but its availability is not guaranteed in future versions of Firefox.

**Comment by cameel** [comment]
OK. Thanks for the insight. It makes sense in that case.

Does this mean that creating bookmarks with drag an drop as a whole requires this deprecated API and that Shift + drop will stop working too when they remove the API?

**Comment by cameel** [comment]
I see. So with this new method you had a choice to either use `text/x-moz-url` as the default (which breaks tearing off when dropping on desktop) or to use `application/x-treestyletab-tree` as the default default (which breaks adding bookmarks).

At least now I know that it's just a necessary trade-off between two features rather than a random UI change. I'd personally have preferred to break tearing off but that's simply because I'm rarely ever using that feature. People who use it more would likely disagree. 

Thanks for taking your time to explain it. And for making this great extension :)

By the way, I see that the reason they're deprecating `mozSetDataAt()` is primarily because they think no one is using it:
- [Non-standard DataTransfer APIs have been deprecated](https://www.fxsitecompat.com/en-CA/docs/2018/non-standard-datatransfer-apis-have-been-deprecated/)
    > Given that Telemetry proves no public usage, these APIs will be completely removed in the near future.
- [Consider removing gecko-only DataTransfer APIs](https://bugzilla.mozilla.org/show_bug.cgi?id=1345192)
    > I was looking at these counters with Ehsan earlier today, and we saw basically no usage of the main problematic APIs (mozClearDataAt, mozSetDataAt, mozGetDataAt, mozTypesAt, and mozItemCount).

It's probably too late for them to back off from this change now but I wonder if they would have reconsidered if they knew that Tree Style Tab does rely on it.

> On the other hand, the current version transfers dragged tabs as two types "application/x-treestyletab-tree" and "text/x-moz-url". (Both these types allow to transfer multiple URLs with the "setData" method.)

I just tried it and with Shift pressed it adds only one bookmark. Is it a bug?

I can add multiple tabs as bookmarks only when I have `allowBookmarkCreationFromDraggedTree` enabled.

**Comment by piroor** [comment]
> So I need to redesign drag action to keep four different results: dragging one tab for a bookmark, dragging one tab for tearing off, dragging tree for bookmarks, and dragging tree for tearing off.

Now I'm planning to implement a new UI for these operations. The idea is:

 * A small "tab" will appear at the edge of the mouseover tab.
 * When the small "tab" get mouseover state, it will be expanded automatically and there are some separated aeas (with icons?) for different operations:
   - Area 1: dragging for tearing off the whole tree.
   - Area 2: dragging for bookmarking the whole tree.
   - Area 3: dragging for tearing off just one tab.
   - Area 4: dragging for bookmarking just one tab.

I think such an visual UI will help people who don't know such secret actions with modifier keys.

**Comment by piroor** [comment]
The tab drag handle is now available on the development build.
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

By pointing on edge of each tab, small palette will appear near the cursor.
![screenshot](https://user-images.githubusercontent.com/70062/46921275-6c616880-d034-11e8-9d13-cdfedbd35e2e.png)

**Comment by C4rter** [comment]
It stopped working for me in the official version and the debug option is gone.
Shift+Drag still works.

Will this new palette replace the old Drag+Drop feature in the release now or why was it removed?

**Comment by piroor** [comment]
On the latest release version, you can change configs at a new section "Drag and Drop" in the options page.

**Comment by piroor** [comment]
By default you need to shift-drag TST's tab to drop bookmarks. Did you try that?

**Comment by C4rter** [comment]
It started working again today, with and without shift. Don't know what that was yesterday. Sorry for the inconvenience.
