### ISSUE TITLE
Is it possible (via the extension api) to control the click behaviors on the native new tab button?

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2036]
I prefer to use the native new tab button placed on the navbar, this way it's always in the same place.

Currently the new tab button settings of TST (middle click, long click) do not affect it.  Is it possible to control the native button?  If not, is it possible to create an a different button that could be placed on the toolbar and behave the same as the TST new tab button?

**Comment by piroor** [comment]
TST (and any other WebExtensions-based addon) cannot control behavior of the native "New Tab" button.

And, TST cannot provide any extra toolbar button because WebExtensions allows to provide only one tolbar button for each addon. So you need to build a new addon pdoviding a custom "New Tab" toolbar button, collaborating with TST via [APIs](https://github.com/piroor/treestyletab/wiki/API-for-other-addons).

**Comment by bughit** [comment]
Would you consider adding an option to position your new tab button at top of the side-bar, so it does not move around?

**Comment by piroor** [comment]
You can do it with custom style rules via TST's configuration.
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#put-new-tab-button-at-the-top-of-the-tab-bar-1376

**Comment by bughit** [comment]
Thanks, that worked. Some of those tweaks are pretty useful, tab size and tab styling for different tab states. xul extensions like tab mix plus, classic theme restorer used to expose them in their ui. There would be value in them being proper settings especially if they could synced (don't know if webextensions can do that), otherwise you have to paste and maintain this tweaks buffer on multiple devices/vms/profiles
