### ISSUE TITLE
Show "recently closed tabs" in sidebar tab context menu

### ISSUE THREAD

**Issue by infinity0** [piroor/treestyletab#2038]
Hey, thanks for porting this very nice extension over to webextensions. I've been using it a lot over many years and it's made me infinitely more productive. I've been maintaining it in Debian too and recently updated to the latest webextensions version, it works well.

In previous versions of firefox (possibly in conjunction with the Tab Mix Plus extension) I remember being able to right-click in the TST sidebar and see a list of "recently closed tabs". This was a very convenient way to re-open a tab you just closed by mistake. Now new versions of firefox don't have this, and Tab Mix Plus is dead, I was wondering if TST can include this feature?

There are two related features already in firefox:
- Ctrl-Shift-T does a similar thing, but sometimes you close 5 tabs at once and only want to restore 2 of them.
- History -> Recently Closed Tabs is exactly the menu I'd like to see, but it's very far away from the TST sidebar especially if you opt to have it on the right side of the screen.

**Comment by piroor** [comment]
[Tree Style Tab Closed Tabs](https://addons.mozilla.org/ja/firefox/addon/tree-style-tab-closed-tabs/) provides the feature.

**Comment by piroor** [comment]
Because WebExtensions doesn't provide availability to show native context menu for tabs, TST reimplements all functionalities of the menu by self for the sidebar. Even if any other addon inserts extra commands to the menu, they won't appear in TST's custom menu. There is a bug about this topic, but it is still in progress: [1280347 - Add ability to provide custom HTML elements working as alias of existing Firefox UI items, especially tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1280347). Firefox Quantum also disallows to handle raw click events around the tab bar, and it is also impossible to put toolbar buttons into the sidebar panel.

So TST 2.x provides its API to insert menu items to its custom menu and/or handle raw events on the sidebar. There are some addons working together with TST: https://github.com/piroor/treestyletab/blob/master/README.md#addons-extend-tst

**Comment by infinity0** [comment]
Hi, thanks for the pointer. I installed that extension, however I notice that the "closed tabs" list show up only on the custom context menu for specific tabs. It would be better if they also showed up on the custom context menu for the tabbar. TST seems not to provide an API to do that currently, would you be able to provide it?

**Comment by piroor** [comment]
Sorry but I won't do that from TST's development policy. Basically I design TST as imitating Firefox's native tab bar except tree features. WebExtensions API's `browser.menus.create()` cannot add any extra commands to the menu on the blank area of Firefox's tab bar, so TST just respects that. In other words, if any future version of Firefox gets ability to do that, I'll do that on TST also.

By the way, [Firefox 64 provides ability to quote extra context menu commands added by other addons to the context menu on the sidebar.](https://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2018-10-14_override-context-on-fx64.htm#topic2018-10-14_override-context-on-fx64) I've updated TST to support that, but there is a same restriction: we cannot open the native context menu including those extra commands without specific tab. Firefox 64 just reports an error for API call with no tab ID like `browser.menus.overrideContext({ context:'tab', tabId: null })`.

**Comment by joshuacant** [comment]
I understand completely and that makes perfect sense given your long-standing development policy. Thanks for the answer.

**Comment by piroor** [comment]
I close this because outdated. Now TST's context menu is compatible to other addons which provide such context menu commands.
