### ISSUE TITLE
Auto-showhide-sidebar-by-mouseover-hover and Ctrl key press

### ISSUE THREAD

**Issue by marrak** [piroor/treestyletab#2052]
## Short description
Ability to show hidden sidebar with Ctrl key
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Configure auto show/hide sidebar as described here:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-showhide-sidebar-by-mouseover-hover
 4. Press Ctrl key

## Expected result
Sidebar is displayed

## Actual result
No action

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 62.0.3 (64-bit)
 * Version (or revision) of Tree Style Tab: 2.5.4

**Comment by piroor** [comment]
Due to limitations of WebExtensions APIs, it is impossible.

WebExtensions only allows to toggle visibility of the sidebar for [limited keyboard shortcuts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations) or the toolbar button.
Other arbitrary timing are disallowed, including `mouseover` and long-press of a key.

**Comment by piroor** [comment]
I close this because outdated.
