### ISSUE TITLE
Cannot drag tab to bookmark panel

### ISSUE THREAD

**Issue by 7OH** [piroor/treestyletab#2055]
## Short description

Cannot drop dragged tab to bookmark panel.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable in VIEW - PANELS - Show BookMakr Panel
 4. Open new tab with any site
 5. Drag tab to bookmark panel.

## Expected result

Tab (or tree) added to bookmark panel.

## Actual result

Drop pointer show disabled action and drop action cannot be done.
Maybe xpi need require permission to manage bookmarks

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Firefox 62 (x64)
 * Version (or revision) of Tree Style Tab: 2.6.1

**Comment by piroor** [comment]
It is a FAQ: https://github.com/piroor/treestyletab/blob/master/README.md#i-cannot-drop-tabs-to-the-bookmarks-toolbar-to-create-bookmarks

**Comment by 7OH** [comment]
So - can be changed pointer behavoir - not show drag process and show TIP instead of it - "DRAG with SHIFT" ?

**Comment by piroor** [comment]
Tooltip on tabs is already used to show full title of the tab, and the notification message popup breaks the drag session. So I've implemented a marquee-like notification message at bottom of the sidebar area (because such an message cannot be rendered in the content area when it is an about: page or addons.mozilla.org page.)
![image](https://user-images.githubusercontent.com/70062/47136891-0143ba80-d2f0-11e8-8bc9-0df10c27a272.png)

**Comment by 7OH** [comment]
Thanks. Nice. Will wait for release.
