### ISSUE TITLE
Strange behavior with Firefox 64.0b1

### ISSUE THREAD

**Issue by Zelman88** [piroor/treestyletab#2057]
I made a video that shows what's the problem since Firefox 64.0b1:
https://www.youtube.com/watch?v=ezUk1DFqe3M

As you could see sometimes the last tab disappears from tree style tab and I need to hide/show tree style tab to see it again. Sometimes the last tab doesn't respond for X button, I need to close it with right click menu.

**Comment by piroor** [comment]
This looks depending on a modified preference `browser.tabs.closeWindowWithLastTab`=`false`. It is `true` by default and the problem doesn't happen by default. Changing `browser.tabs.closeWindowWithLastTab` to `true` may become a workaround.

This doesn't happen on Firefox 63 beta, so something change on Nightly 64 may produce this problem.

**Comment by piroor** [comment]
This looks a  bug of Firefox itself. When the last tab is closed both "tabs.onRemoved" and "tabs.onCreated" should be notified to TST, but in this case only "tabs.onRemoved" is notified. Moreover, this happens only on new windows tracked after TST is initialized. After TST is reloaded, both "tabs.onRemoved" and "tabs.onCreated" are notified when the last tab is closed in a window, because the window is "already opened" on TST is loaded. Hmm...

**Comment by piroor** [comment]
I've filed a bug at bugzilla.mozilla.org: [1500180 - Listener for "tabs.onCreated" is not called for a tab opened after the last tab is closed with "browser.tabs.closeWindowWithLastTab" = "false"](https://bugzilla.mozilla.org/show_bug.cgi?id=1500180)

**Comment by piroor** [comment]
My patch has been marged and the bug will become fixed on Firefox 63 and later.

**Comment by Zelman88** [comment]
@piroor Firefox Dev edition updated today on my computer to 64.0b4 and now everything is back to normal with browser.tabs.closeWindowWithLastTab=false .
