### ISSUE TITLE
What's happened to the close tabs in context menu?

### ISSUE THREAD

**Issue by JamesM777** [piroor/treestyletab#2058]
The "Close other tabs" and "Close tabs to the right" have been moved to a sub-item in the context menu, under "Close Tab Options". Seeing as these are the functions I use most frequently, it is annoying to have them now requiring tow clicks instead of one. Can we please have the option of having them not under a sub-item in the context menu?

**Comment by piroor** [comment]
Because the current menu structure is restructured to become compatibe with Firefox 64's native context menu. It is not released yet but to reduce development cost I usually update TST to follow changes of Firefox Nightly. I know that TST should provide menu compatible to the running version itself (it may be Firefox 62 for now), but I cannot maintain them for multiple versions well.

**Comment by eclipseo** [comment]
The new menu in Nightly is great, thanks Piro!
