### ISSUE TITLE
TST API Fake Context Menus Stopped Working in 2.6.x

### ISSUE THREAD

**Issue by joshuacant** [piroor/treestyletab#2062]
## Short description
2.5.4 is the last version that works with addons that add menu items to TST's fake context menu. I can see all the addons register, and the addons that don't add context menu items work just fine.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install another addon that extends the fake context menu for TST.
 4. Right click a tab.

## Expected result
The addon's additional context menu items are shown.

## Actual result
The addon's additional context menus are not shown.

## Environment

 * Platform (OS): Windows 10 1809 x64
 * Version of Firefox: 64 beta
 * Version (or revision) of Tree Style Tab: 2.6.4 through 2.6.1 are affected.

2.5.4 works as expected.

**Comment by piroor** [comment]
In short: the addon need to be updated with genuine WebExtensions APIs.

On Firefox 64 and later, TST provides tree context menu as a native context menu of Firefox itself. Addons need to add extra commands to it via genuine WebExtensions API like `browser.menus.create()`, instead of [TST's fake APIs](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#extra-context-menu-items-on-tabs). There is [a blog post describing technical details](https://piro.sakura.ne.jp/latest/blosxom/mozilla/xul/2018-10-14_override-context-on-fx64.htm#topic2018-10-14_override-context-on-fx64).

**Comment by joshuacant** [comment]
Wow, a whole post with pictures and everything. Even I will be able to figure that out!

Thanks again, piroor. I'll get my extensions updated soon hopefully.
