### ISSUE TITLE
Blank page when clicking TST's new tab button with custom userscript homepage

### ISSUE THREAD

**Issue by metronidazole** [piroor/treestyletab#2065]
I realise this is not strictly a TST/Firefox issue as I am using a custom userscript, but I hope you can help as the issue only occurs when using a TST specific feature.

## Short description
When using a custom homepage that has been defined with a userscript (https://luke-baker.github.io/chrome/NewTab_custom-page.uc.js), I get a blank page instead of the homepage when using TST's button to open a new tab. 

Using the built in firefox hotkey or menu option to open a new tab works as expected.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Setup a custom homepage with this userscript https://luke-baker.github.io/chrome/NewTab_custom-page.uc.js  (see https://luke-baker.github.io/#introduction too)
 4. Click the new tab button at the bottom of the TST sidebar.

## Expected result
My custom homepage loads.

## Actual result
I see a blank (white) page (non-interactable).

Browser console:

```
NS_ERROR_DOM_BAD_URI: Component returned failure code: 0x805303f4 [nsIWebNavigation.loadURIWithOptions]
loadURI/<				resource://gre/actors/WebNavigationChild.jsm:111:14
_wrapURIChangeCall   	resource://gre/actors/WebNavigationChild.jsm:63:7
loadURI             	resource://gre/actors/WebNavigationChild.jsm:110:5
receiveMessage   		resource://gre/actors/WebNavigationChild.jsm:43:9
receiveMessage   		resource://gre/modules/ActorManagerChild.jsm:91:39

Sending message that cannot be cloned. Are you trying to send an XPCOM object? MessageChannel.jsm:968:8

uncaught exception: undefined
```

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 63
 * Version (or revision) of Tree Style Tab: 2.6.4

**Comment by piroor** [comment]
You should migrate to the [New Tab Override addon](https://addons.mozilla.org/firefox/addon/new-tab-override/) instead of a legacy user script. It completely works with TST for me.

**Comment by metronidazole** [comment]
@piroor That doesn't support local files (in the traditional sense).

**Comment by piroor** [comment]
Then it is a "problem" of the addon New Tab Override or WebExtensions API's restriction themselves, not an issue of Tree Style Tab. Anyway, after XUL is completely dead, such a hack based on legacy way won't work, so you need to find different way that effective on current and future versions of Firefox. There are some related information:

 * Currently "data:" URI is unavailable for new tab contents due to the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1317166 . When the bug become fixed, New Tab Override may provide a feature like: "upload" any local file to its storage and generate "data:" URI to open it as a new tab contents safely.
 * You can run any local HTTP server (apache, nginx, or others) to provide your local file via HTTP, and it is accessible from addons safely.

**Comment by metronidazole** [comment]
Unfortunately those alternatives come with downsides which were the reason I used a userscript in the first place.

In any case, it looks like this is a Firefox 63 regression (not TST) and it won't be fixed, so I'm closing this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1485778
