### ISSUE TITLE
Inconsistent tree when moving tab while loading

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#2071]
I open a new tab as a child with a middle click.
While the tab is loading, I move it to another tab.
When the tab finishes loading, the tab gets back to it's first parent.
The second parent still has the arrow sign.
I have to move the tab to an unrelated tab first and then I can move it again.

It doesn't happen always, there must be a timing issue.

**Comment by piroor** [comment]
Steps I've tried:

 1. Install TST.
 2. Install [New Tab Override](https://addons.mozilla.org/ja/firefox/addon/new-tab-override/?src=search)
 3. Set `http://localhost:8888/` as the new tab page.
 4. Run `netcat -l 8888` on WSL console (because I'm using Windows 10. Otherwise you can run that on Terminal.)
 5. Middle-click the "New Tab" button in the TST's sidebar.
    * Then a new loading tab is opened as a child of the current tab.
 6. Drag the new (loading) tab onto another tab.
    * The tab becomes a child of the drop target tab.
 7. Stop `netcat` in the console by Ctrl-C.
    * Then a "server not found" error is shown in the new tab.
    * The new tab does not moved automatically - it stays there.

I couldn't reproduce the problem by these steps. Hmm...

**Comment by Tragen** [comment]
Looks like the newest version fixed this as I cannot reproduce it anymore.
Thanks
