### ISSUE TITLE
3 out of 4 out-of-tab menu items do not perform as expected

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2096]
## Short description
The menu in question, activated by right-clicking in the sidebar but not on any (pinned) tabs:
![image](https://user-images.githubusercontent.com/771216/50317558-2b377a00-04f7-11e9-9fac-866c1685a0b5.png)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Activate the menu and perform those actions.

## Actual result
`Reload Selected Tabs`: reloads only the active tab despite multiple tabs are selected
`Bookmark Selected Tabs`: nothing happens. No confirmation dialogs. No error messages in Browser Console.
`Select All Tabs`: it does select all tabs, but the active tab always switches to the first tab (P.S. same issue for the item on on-tab menu too)
`Undo Closed Tab`: work as expected

## Note
All similar items on on-tab menu work as expected except `Select All Tabs`.

## Environment

 * Platform (OS): Windows 10 1809
 * Version of Firefox:  Nightly 2018-12-20 (20181220105637)
 * Version (or revision) of Tree Style Tab:  2.7.3

**Comment by piroor** [comment]
Thanks! The problem about `Bookmark Selected Tabs` was not handled unexpectedly until the commit c03898c. `Select All Tabs` problem is fixed by fd54b9f.

However, `Reload Selected Tabs` and `Bookmark Selected Tabs` will work for the active tab if you have no selection, because these commands are expected to be triggered with multiselected tabs. It is intentional and same to Firefox's native context menu commands. (So you'll see same result on the horizontal tab bar.)

**Comment by Fanolian** [comment]
> However, `Reload Selected Tabs` and `Bookmark Selected Tabs` will work for the active tab if you have no selection, because these commands are expected to be triggered with multiselected tabs.

I mean I have selected multiple tabs, but still `Reload Selected Tabs` only reloads the active tab instead of all selected ones. Sorry for the confusion.

**Comment by piroor** [comment]
Oops, I missed that. The commit 6e9b0db should fix the problem. Thanks again!

**Comment by Fanolian** [comment]
Fixed in 2.7.3.7940. Thanks again
