### ISSUE TITLE
Hide pinned tabs

### ISSUE THREAD

**Issue by DeaD3R** [piroor/treestyletab#2105]
I want to temporarily hide pinned tabs, but 
```
.tab.pinned {
display: none;
}
```
hides the icons but the space is still taken
![2018-12-26_154309](https://user-images.githubusercontent.com/16120515/50445014-32122280-0925-11e9-9c81-095676171e34.png)

**Comment by piroor** [comment]
Because TST lays out pinned tabs in different way from regular tabs. Pinned tabs are positioned with `position:fixed;top:***px;left:**px` and TST appends calculated top-margin to the tab bar to place positioned pinned tabs. `display:none` for pinned tabs only hides positioned tabs and it doesn't affect to calculated top-margin. Sadly the calculation algorithm is hardcoded and uncontrollable via custom CSS.

**Comment by DeaD3R** [comment]
All clear. Thank you very much.

**Comment by Lej77** [comment]
The following CSS code seems to work for me:
```css
.tab.pinned {
  display: none;
}
#tabbar {
  margin-top: unset !important;
}
```
