### ISSUE TITLE
[feature request] API call move-above, move-below

### ISSUE THREAD

**Issue by IGP** [piroor/treestyletab#2165]
## Short description
This is a feature request for two new API calls.

- move-above
- move-below

These API calls would have 2 required parameters and 2 optional parameter:

- tab (required, tab to be moved)
- target (required, tab to be moved above/below)
- followChildren (optional default false, same functionality as move-up/move-down)
- makeChild (optional default false, different behavior for above/below : if true and above then 'target' is made child of 'tab', if true and below then 'tab' is made child of 'target', if false then tab maintains indent)

## Use case
I am writing a small extension that allows you to sort children of a tab. After experimenting with browser.tabs.move() I have run into issues with maintaining the tree structure. This appears to be a two fold issue.

First is that TST does not seem to cope well with children being moved via browser.tabs.move() adjacent (just below?) of their siblings who also have children. As an example let's say you have 4 sibling tabs:
- a, b, c, d

Tab 'b' also has a child 'e'. Using browser.tabs.move() (or just dragging on the default tab bar) if you move tab 'd' above tab 'c' there is a good chance it will attach to tab 'e' and become a child of tab 'b'.

Second would be the async nature of TST. In my testing I did not have many issues when reordering a handful of tabs at a time (passing an array of tab IDs to browser.tabs.move()) but as I stepped up the amount of tabs the tree structure would break down.

**Comment by piroor** [comment]
I've added two more features: [`move-before` and `move-after`](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#move-tree-to-different-position). Naming of them and their parameters are based on DOM spec. (`insertBefore(tab, referenceTab)`) You can try them with the [development build](https://github.com/piroor/treestyletab/blob/master/README.md#development-builds).

Sad news: sorry but I didn't implemented the parameter `makeChild` you proposed, because it looks too much for me. I believe that this decision is similar to WE's API triage policy. Instead I think that addons should manipulate tree via elemental features [`attach` and `detach`](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#attach-existing-tab-to-another-as-a-child).

Otherwise, I think that something new more API to bulk-set tree relations to multiple tabs in a time may help you. Currently I have no idea what format is reasonable to specify a structure of tree. Internally TST uses a format like `[-1, 0, 0, 2, -1, 0]`. It means:

```
    [A]     => -1 (parent is not in this tree)
      [B]   => 0 (parent is 1st item in this tree)
      [C]   => 0 (parent is 1st item in this tree)
        [D] => 2 (parent is 2nd in this tree)
    [E]     => -1 (parent is not in this tree, and this creates another tree)
      [F]   => 0 (parent is 1st item in this another tree)
```

But I think it may be difficult for other developers. Do you have any idea?

**Comment by IGP** [comment]
Thanks for adding move-before and move-after!

Ive thought on the bulk-set idea for a while now and I can't think of a great way to do it that doesn't potentially step all over everything/not be extremely dirty. I think the way you have the tree setup internally is fairly easy to follow except for maybe that it appears that the order of sibling tabs is determined by their actual order in the list.

I think the attach and detatch could largely accomplish the same use case as a bulk set if they supported a parameter similar to followChildren like some other commands do.

**Comment by irvinm** [comment]
@IGP do you think your could close this issue?  (Or is there more to discuss at this point?)

**Comment by IGP** [comment]
The initial request has been addressed so closing this.
