### ISSUE TITLE
Context menu does not work with firefox 62

### ISSUE THREAD

**Issue by char101** [piroor/treestyletab#2173]
## Short description

I'm using firefox 62 and the context menu does not work with the latest version of treestyletab. In the error console there are these errors: 

```
TypeError: browser.tabs.highlight is not a function
```

Based on the [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/highlight), `browser.tabs.highlight` is supported since firefox 63. The addon [manifest](https://github.com/piroor/treestyletab/blob/master/webextensions/manifest.json#L196) still refers to firefox 60.

**Comment by piroor** [comment]
On my environment (Firefox ESR60) right-click on the sidebar does not open the context menu due to different error, and it has been fixed by the commit 7142978.

As you mentioned `browser.tabs.highlight()` is not supported on old Firefox, but the API is called from the context menu when you choose the command "Select All Tabs". Thus I changed the command hidden on old Firefox.

By the way, using Firefox 62 is not recommended because it is already became unsupported, and I think you should use ESR60 or latest released version (65)...

**Comment by perdolka** [comment]
Versions 2.8.0 and 2.8.1 doesn't work (for me at least) with 60.5.1esr and 60.5.2esr (x64)

**Comment by char101** [comment]
I have upgrade to firefox 66 beta due to this issue. I guess firefox 62 has some support but lack another support for the context menu, thus it works in firefox 60 by exclusion, but not in firefox 62.

**Comment by char101** [comment]
By the way I don't choose "Select All Tabs", the error appeared when I right click on a tab in the sidebar (thus no context menu at all - the context menu appeared when right clicking outside of the tabs), so I believe `browser.tabs.highlight` could be called not only when choosing "Select All Tabs".

**Comment by personalmountains** [comment]
Pretty sure your commit 714297894adab82c43314aa9f5394fd26421a80b broke the context menu on Firefox 65 when right-clicking on empty space on the sidebar (not on a tab). I'm getting `TypeError: options.tab is null` on `tab-context-menu.js:265`.

**Comment by piroor** [comment]
I close this because outdated.
