### ISSUE TITLE
incorrect restore of a tree created by "open all in tabs" (last tab is restored top level)

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2191]
## Short description

I could not repro it in a new profile, so I started matching TST settings but then different symptoms manifested (blank tree sidebar after restoration). So I guess we need to deal with that first.

Is there a way to dump out the settings without having to describe all the changes here? (#2190)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. change settings (will describe later if there's no way to dump them)
 4. add a bookmark folder with three urls
 5. restart
 6. open all in tabs
 7. restart
 8. restore previous session

## Expected result

proper restoration

## Actual result

![image](https://user-images.githubusercontent.com/895588/54553201-0e8cd000-4988-11e9-817d-717065597706.png)

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 66.0.0
 * Version (or revision) of Tree Style Tab: 2.8.6

**Comment by bughit** [comment]
the blank sidebar with a spinner is probably new in Fx 66. I was able to repro the original issue in Fx 65.0.2 with default settings, but more tabs.

1. create a bookmark folder with 6 (or more) booksmarks (http://example.org/?1, http://example.org/?2, ...)
2. restart
3. open all in tabs
4. restart
5. restore previous session
    ![image](https://user-images.githubusercontent.com/895588/54580664-92be7200-49df-11e9-90f7-c53c19f6f6cb.png)
   On my main profile, I've seen it more scrambled.

**Comment by flawless0714** [comment]
Similar issue here, but what I just encountered is my tree got mess up after auto update of the add-on. FYI, I had 170~ tabs at that moment :cry:.

Thanks for the add-on, keep going!

**Comment by piroor** [comment]
Possible related issue: #2201

By the way, restoration with the "Restore Previous Session" command is unfriendly with TST. Instead I'm using (and recommended is): Firefox Options => General => Startup => Restore Previous Session.

**Comment by flawless0714** [comment]
Oh, I see. My **Restore Previous Session** has enabled by default, and now I know that the "Restore Previous Session" command is unfriendly with TST, I'll take care of it, thanks for notification!

**Comment by bughit** [comment]
> By the way, restoration with the "Restore Previous Session" command is unfriendly with TST. 

Could you say more about that? Is it a Fx bug? Why is it different than startup restoration? Any possibility for you to get this working (I don't want startup restore, but occasionally need on demand restore)?

**Comment by piroor** [comment]
Firefox Options => General => Startup => Restore Previous Session case:

 1. Firefox is started.
 2. Firefox restores the previous session.
 3. TST is started, and wait until Firefox ends to open tabs (for the session restoration).
 4. Firefox finishes to opentabs for the session restoration.
 5. TST continues its initialization process. All tabs are already there, so TST successfully applies "the tree structure of all tabs" information to them.

The "Restore Previous Session" command in the application menu case:

 1. Firefox is started.
 2. TST is started, and wait until Firefox ends to open tabs (for the session restoration).
 3. TST continues its initialization process, but there are only some tabs, so TST gives up to restore tree.
 4. The "Restore Previous Session" command is invoked.
 5. TST waits until all tabs are opened/restored.
 6. TST tries to restore tree structure of them tabs based on relation information of tabs stored to each individual tab, instead of "the tree structure of all tabs" information.

This is the difference of two cases. The relation information of tabs stored to each individual tab is: "children", "ancestors", "previous" and "next" tabs. TST tries to find tabs based on those information, but it is sadly unstable and sometimes TST fails to detect those tabs.

**Comment by irvinm** [comment]
@bughit are you still experiencing a problem with the latest version given piroor's information?

**Comment by bughit** [comment]
this bug is till present in 3.0.10

**Comment by piroor** [comment]
I still cannot reproduce this on my environment, so there looks to be more unknown required conditions to reproduce it. For example:

* Secret options managed via `about:config`, under the namespace `browser.tabs.`
* Other addons especially related to tabs
* Some options of TST itself (*now they are exportable - TST options => Development => Debug => All Configs => Export)

Until conditions become clarified through researching on your environment, it is impossible to fix the problem by me.

**Comment by bughit** [comment]
The directions I provided are for a new profile, there are no other extensions and no pref changes. I just tried again with a new profile. The bookmark toolbar appears to be significant so if you follow these exactly, you should be able to repro (tested on win7 x64 and Ubuntu 14.04 x64).

1. start fx 66.0.3 x64 with a new profile `firefox -no-remote -profile c:\profile\path`
2. right click on the chrome and show the menu bar and the bookmark bar
3. create a "New Folder" on the bookmark bar
4. create three bookmarks in the folder (when I created only two it didn't prompt to group them when opening, bug?)
    1. name and location: http://example.org/?1
    2. name and location: http://example.org/?2
    3. name and location: http://example.org/?3
5. Install tst 3.0.10
6. close all but one homepage tab 
7. "Bookmark  bar" -> "New Folder" -> "Open all in tabs"
8. choose to group tabs when prompted by tst
9. you get this
    ![image](https://user-images.githubusercontent.com/895588/57110076-4b791000-6d05-11e9-9f29-83f8226e1770.png)
10. restart fx
11. "main menu" -> History -> "restore previous session"
12. you get this
    ![image](https://user-images.githubusercontent.com/895588/57110150-7e230880-6d05-11e9-9706-ed6b61c0ec32.png)

**Comment by bughit** [comment]
> when I created only two it didn't prompt to group them when opening, bug?

On subsequent "open all in tabs" it does not prompt even with three tabs. It's consistent, I can't get it to prompt at all and tabs open flat, that's definitely another bug. For the purpose of this bug you can disable confirm to group and then grouping works reliably.

**Comment by piroor** [comment]
Thanks! I've successfully reproduced the problem. The important point is: one of child tabs must be the active before Firefox restarts.

**Comment by piroor** [comment]
After investigation I've realized what's happen:

1. The first tab is initialized and a new unique id is issued for the tab. (Note: unique id is persistent across sessions.)
2. Firefox recycles the first tab as the restored old active tab. The old active tab had a unique id different from the one issued at the step 1, but it was not restored because the tab is recycled and it already has its own unique id.
3. The old parent tab is restored. TST tries to restore its children based on unique ids, but TST cannot find the old active child tab with the unique id.

**Comment by piroor** [comment]
I think the commit d9e89d8 should fix this. On my environment I don't see the problem anymore.

**Comment by irvinm** [comment]
@bughit it looks like this landed in 3.0.11.  Can you confirm if this solves your problem now?  If so, let's close out the issue.  Thanks.

**Comment by bughit** [comment]
fixed
