### ISSUE TITLE
Group tabs flash very fast and indefinitely after launching Firefox if "Optimize tree restoration with cache" is set On

### ISSUE THREAD

**Issue by Adelscott** [piroor/treestyletab#2198]
## Short description
Group tabs flash very fast and indefinitely after launching Firefox if "Optimize tree restoration with cache" is set On

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a group tab with tabs within
 4. Close Firefox
 5. Open Firefox (with "Optimize tree restoration with cache"  On)

## Expected result
No flashing

## Actual result
Flashing

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 66.0
 * Version (or revision) of Tree Style Tab: 2.8.7

**Comment by piroor** [comment]
Sadly I also see this problem sometimes, but it doesn't happen consistently. This problem is caused by codes to initialize a group tab: https://github.com/piroor/treestyletab/blob/fc98867201478122d8619374c78efbc17b467593/webextensions/background/handle-group-tabs.js#L210 but I still couldn't find it out: the trigger of infinitely running of the section.

**Comment by irvinm** [comment]
@Adelscott are you still seeing the same issue with the latest version 3.0.11?  If not, can you close out this issue?  If you are, please let us know.

**Comment by Adelscott** [comment]
@irvinm no in fact it disappeared ! I guess a solution has been found ! Thanks
