### ISSUE TITLE
bookmark folder "open all in tabs" do not open flat

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2229]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. create a bookmark folder with 3 urls https://example.org/?(1-3)
 4. restart
 5. open all in tabs
 6. the initial ungrouped state looks like this:
     ![image](https://user-images.githubusercontent.com/895588/56074132-3995f400-5d7b-11e9-9c04-ed5b9a6c2387.png)
 7. after grouping is chosen you get this:
    ![image](https://user-images.githubusercontent.com/895588/56074147-68ac6580-5d7b-11e9-9f51-c743f0908d15.png)

## Expected result

whether grouped or not, tabs should be at the same level

## Environment

 * Platform (OS): win7 x64 sp1
 * Version of Firefox: 66.0.3 x64
 * Version (or revision) of Tree Style Tab: 3.0.6

**Comment by piroor** [comment]
The result looks to be produced with the option: "New Tabs Behavior" => "When new tabs with a website same to the current tab is opened from the location bar (or othres)" => "Open as a child of the current tab". I've introduced some changes to ignore for the option when multiple tabs are opened in a time, so this should be fixed in the next release.

**Comment by irvinm** [comment]
@bughit can you confirm and close this item?
