### ISSUE TITLE
"open all in tabs" should have separate grouping pref

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2230]
Tabs from the safe folder are connected by more than temporal proximity, so one is likely to want them grouped even if temporal grouping is off.

Is it possible to detect an "open all in tabs" operation and group them?

**Comment by bughit** [comment]
On second thought, since the temporal grouping is only 100ms by default, can it apply to anything but "open all in tabs"? I guess I had other scenarios in mind, but perhaps there are none.

**Comment by piroor** [comment]
Sadly TST cannot apply a special behavior for tabs opened wit h"Open All in Tabs" command for a bookmark folder. This is one of WebExtensions restrictions. `webNavigation` API looks to provide ability to know which is the context the tab is loaded, and there is a value `auto_bookmark`, but it is not supported yet on Firefox.

**Comment by piroor** [comment]
See also: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/TransitionType

**Comment by irvinm** [comment]
@bughit or @piroor ... Is there any reason to leave this open?

**Comment by piroor** [comment]
TST 3.2.0 (released at 2019.10.28) and later has an extra context menu command "Open All as a Tree" (please try to give "Bookmarks" permission to TST and right-click on a bookmark folder.) It opens bookmarks under a grouping folder even if the auto-grouping option is disabled. It looks to be a workaround for this issue, you just need to mind to right-click on a folder instead of middle click or choosing the default "Open All in Tabs" command. So I close this for now.
