### ISSUE TITLE
reload this tree: top level item?

### ISSUE THREAD

**Issue by stapuft** [piroor/treestyletab#2240]
is there any way to add the "reload this tree", and "Reload Descendants" options as top level items in the context menu?

thanks for everything! you rule man!

**Comment by piroor** [comment]
Currently these options are not supported. Due to historical reasons, only some limited commands can be exposed to the top level of the context menu for now.

I was negative to add top level context menu items, because I thought that "tab context menu on the sidebar, provided by TST" is just a workaround until the original tab context menu on the native tab bar becomes available on the sidebar. If the native tab context menu became available and I migrated TST to use that, custom top-level menu items might became unavailable and many requests to add the missing feature might posted again and again, even if it is technically impossible. So, to avoid such a confusion, I decided that I never add extra top-level items to the context menu which are not available  in the native tab context menu.

However, now WebExtensions has the `menus.overrideContext()` method and it provides abilities only adding custom top-level context menu items, with no native context menu items. I think that the context menu on the sidebar don't need to restricted to a dead copy of the native tab context menu anymore.

**Comment by piroor** [comment]
The commit 7f0350e should implement this.

**Comment by stapuft** [comment]
Awesome! cant wait, thanks for the awesome addon!

**Comment by piroor** [comment]
I close this because outdated.
