### ISSUE TITLE
TST options are not readable when enabling browser.in-content.dark-mode

### ISSUE THREAD

**Issue by TRowbotham** [piroor/treestyletab#2243]
Using Firefox Nightly 68, dated 2019-04-26 on Windows 10. This feature is being introduced in https://bugzilla.mozilla.org/show_bug.cgi?id=1519547.

Steps to reproduce:
1) Type about:config in the address bar.
2) Search for the preference "browser.in-content.dark-mode".
3) Set the preference to true.
4) Restart the browser.
5) Go to about:addons.
6) Click the options button for TST.

Actual Results:
The text is not readable because TST is using dark text on a dark background.

Expected Results:
The text should be using a lighter color to make it readable.

**Comment by Fanolian** [comment]
This is [bug 1544212](https://bugzilla.mozilla.org/show_bug.cgi?id=1544212).

**Comment by p0358** [comment]
There are however extensions that display properly, for example Decentraleyes. Maybe solution is to not set text color manually and just keep it to default? Or set white background?

**Comment by Fanolian** [comment]
> Or set white background?

This is what bug 1544212 is about. It is a needed hack for now (but burns your eyes 😎) since all extensions expect a white background. I do not know why the patch is not approved yet.

Extensions can use [`prefers-color-scheme`](https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme) and define a separate set of CSS for dark mode. It is what [Decentraleyes does](https://git.synz.io/Synzvato/decentraleyes/commit/15c26a107330c9d274c93114da7dcfb0ae0638a0).

https://hacks.mozilla.org/2019/05/firefox-67-dark-mode-css-webrender/ 
https://phabricator.services.mozilla.com/D28369#830658

**Comment by TRowbotham** [comment]
This may be solved in the long run through the about:addons conversion to html, tracked in [bug 1505924](https://bugzilla.mozilla.org/show_bug.cgi?id=1505924), which should add support for native inline options

**Comment by Fanolian** [comment]
For the time being access the option in a separate tab by visiting:
`moz-extension://[Internal UUID]/options/options.html`
You can find the internal UUID in *about:debugging*.

**Comment by irvinm** [comment]
Is this still an issue for everyone?  I am using:

user_pref("browser.in-content.dark-mode", true);
user_pref("ui.systemUsesDarkTheme", 1);

... and my TST configuration is showing up the same as in moz-extension://[Internal UUID]/options/options.html

FF 69.0 (Win64), TST 3.1.8.

**Comment by TRowbotham** [comment]
No, this is no longer an issue since [1505924](https://bugzilla.mozilla.org/show_bug.cgi?id=1505924) introduced the new about:addons redesign. I'll go ahead an close this.
