### ISSUE TITLE
Add option to replace temporary group with last remaining child

### ISSUE THREAD

**Issue by SammysHP** [piroor/treestyletab#2253]
In the preferences you can select that a temporary group should be created if the parent tab of a branch gets closed. This group will stay open until all children are closed.

I propose to add another option (either in the preferences or in the tab group page) to replace the group with the last remaining tab if all direct children except one get closed.

**Comment by piroor** [comment]
Thanks, I think this is more natural than the current behavior on such a situation. TST is already designed to close a group tab automatically when there is only one child and it is another group tab, the special behavior was prepared for such cases. So, I've introduced changes to apply the new behavior as the fixed behavior for a group tab opened as a successor of a closed parent tab.

**Comment by irvinm** [comment]
@SammysHP can you review and close if this works?  Thanks.

**Comment by SammysHP** [comment]
I tested it for some days now and overall it works as expected. There might be a few special cases that cause problems, especially when re-opening closed tabs via ctrl-shift-t. I will check it in detail next weekend.

Not sure if this is related or a separate issue, but the group will be labeled as unread (which is highlighted in my config). IMHO groups should not get that class.

**Comment by SammysHP** [comment]
Works great except for one use-case (that might be not related to this feature):

- Open some children
- Close the parent, which creates a group
- Close the children until the last child replaces the group
- Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> to reopen the second to last child that was closed

Result: Only the group is recreated, but not the tab that was closed last.

@piroor Should I open new issues for the two open problems or are they already known and tracked somewhere?

**Comment by piroor** [comment]
Thank you for suggestions. I've introduced changes to keep group tabs "already read".

On the other hand, "restore last closed regular tab instead of group tab" looks hard to be implemented a little. Simply I can trigger "restore one more tab" automatically when a group tab is restored, but there are some problems:

* "Restore closed tab" operation is not limited to be executed for the recently closed tab. You can restore not recently closed tabs via the history menu or other UI.
* Cleaning up of needless group tabs may be done for multiple group tabs. For example:
  
  - [root, group tab] <= this will be closed automatically
    - [child, group tab] <= this will be closed automatically
      - [grand child, regular tab] <= this is closed manually
  
  On such cases, should all group tabs be restored?

I think it is hard to support all such edge cases, and the simple workaround "restore one more recently closed tab when a group tab is restored" will introduce various odd results on such cases.

**Comment by SammysHP** [comment]
I fully agree with you that it would be hard or impossible to guess which tabs should be restored. Thus I think this issue can be closed.

Thank you for the fast response and implementation!
