### ISSUE TITLE
Unable to download update

### ISSUE THREAD

**Issue by hhegedus** [piroor/treestyletab#2259]
## Steps to reproduce
Firefox disabled my Tree Style Tab extension with a message that it was not compliant and must be updated.  It presented me with two updates, but I was unable to download either one.  I then removed the extension all together, restarted Firefox and started to reinstall the extension, but it would not download either.  What is the problem?  Are your servers down temporarily?  

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): Mac 10.12.6
 * Version of Firefox:  66.0.3 (64bit)
 * Version (or revision) of Tree Style Tab:  don't know now because I deleted it and could not install the most current production version.

**Comment by Fanolian** [comment]
#2258 
You can also find the updates of this worldwide issue at https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by hhegedus** [comment]
2258 says the problem is fixed, but I still can't download.  Is there
anything else I should do?
Also, I had already deleted and tried to reinstall the extension before I
read the blog on the problem.  Will it be able to pick all the tabs that
are open now and put them at least in a flat tree or must I start
rebuilding my tree from scratch?  It may be ridiculous, but I have probably
have close to 100 tabs open.

**Comment by frougon** [comment]
The advice on [support.mozilla.org](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct) displayed in FF along with “this extension has been disabled because it is unsigned bla bla bla” said:

> If an unsigned add-on is disabled, you won't be able to use it and the Add-ons manager will show a message that the add-on could not be verified for use in Firefox and has been disabled. You can remove the add-on from Firefox and then reinstall a signed version from the Mozilla Add-ons site if one is available.

So, seing no other way to get TTS working again (it was disabled while FF was running, without my intervention!), I removed the add-on. And what does [blog.mozilla.org](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/) say?

> Our team has identified and rolled-out a fix (...) No active steps need to be taken to make add-ons work again. In particular, please do not delete and/or re-install any add-ons as an attempt to fix the issue. Deleting an add-on removes any data associated with it, where disabling and re-enabling does not.

Crap! I also have on the order of 100 tabs. :-((

(thanks for the add-on, though! :- )

**Comment by leftdisconnected** [comment]
Unfortunately, removing an extension deletes its data, so you may have lost your tab collection.  Removing extensions is generally to be avoided.  Disabling an extension is much safer as nothing is deleted.  I realize that this knowledge doesn't help if you've already removed and re-installed, but perhaps someone else will find this information helpful.  I do sympathize as I also have perhaps a hundred or more tabs and load or unload entire trees of them as needed.

Reinstalling Firefox is okay as doing so does not affect your profile(s), but DO NOT REMOVE add-ons unless you no longer need their data.

**Comment by frougon** [comment]
The problem is, **reinstalling the add-on doesn't work**: I am at

  https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

When clicking on _Add to Firefox_, it displays:

`Download failed. Please check your connection.`

on red background, but my connection is perfectly fine! This error has been there for several hours, for sure.

**Comment by piroor** [comment]
Duplicated of #2258.
