### ISSUE TITLE
How to disable all animation? It's not working?

### ISSUE THREAD

**Issue by IRainman** [piroor/treestyletab#2263]
I disable all animation in browser settings:

browser.download.animateNotifications = false
browser.stopReloadAnimation.enabled = false
toolkit.cosmeticAnimations.enabled = false

...and also disabled checkbox "Включить эффекты анимации" (in russian) in TST settings, but it's not working:

- when TST is loading
- when tab loading (reloading) animation
- when I trying to close group of tabs: some fade animation happened

all of this animation is still exist and I don't understand how to disable it.

TST version 3.0.11 on Firefox 66.0.3 32 bit  on Windows 10, 64 bit

**Comment by piroor** [comment]
The option respects what happens when `toolkit.cosmeticAnimations.enabled` is disabled. The option disables animation *effects* when tabs are opened and closed. TST also just disables effects on opening/closing/collapsing/expanding tabs. To deactivate throbber animations you need to do it with user-defined stylesheet on TST's options. For example:

```css
@keyframes throbber {}
@keyframes tab-burst-animation {}
@keyframes tab-burst-animation-light {}
@keyframes blink {}
```

**Comment by piroor** [comment]
I've added this to the code snippets: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#disable-all-animation

**Comment by irvinm** [comment]
@IRainman can you review?  Does this do what you need it to do?  If so, can you close this issue?

**Comment by IRainman** [comment]
Yep, tre crutch is work fine. Thank you
