### ISSUE TITLE
Note: dom.moduleScripts.enabled=true (aka default) is required for TST to work!

### ISSUE THREAD

**Issue by howaboutsynergy** [piroor/treestyletab#2287]
Heads up for `about:config` fiddlers:
`dom.moduleScripts.enabled` must be `true` for Tree Style Tab (aka TST) to work, else you see a bunch of `__MSG_*__` stuff(like `__MSG_config_appearance_caption__`) and no side-bar tabs:

![Screenshot_2019-05-24_13-29-31](https://user-images.githubusercontent.com/49106389/58324765-148bab00-7e28-11e9-9707-94035143d0ae.png)

Maybe this could be added somewhere in the wiki or to requirements somewhere ? Otherwise this "issue" can just be closed.

Note that the other addons that I used prior to installing TST, apparently worked fine with this setting to `false`: uBlock Origin, uMatrix, https everywhere.

**Comment by piroor** [comment]
I thought that disabling the native support of ES Modules on Firefox is not a popular customization. If my understanding is wrong and large number of people uses the config option, it may need to be announced before installation. Is there any evidence of the demand?

Basically Firefox has many secret preferences to toggle ON/OFF of web features (please look at `about:config` and find items with terms like `css` or `dom`), and WebExtensions addons may be affected. For example `dom.indexedDB.enabled`=`false` breaks many addons because it deactivates storage features of WebExtensions API itself. I think that listing up of all possible triggers of such problems is unrealistic and unnecessary.

**Comment by howaboutsynergy** [comment]
> Is there any evidence of the demand?

I know of no one else using this. 

> I think that listing up of all possible triggers of such problems is unrealistic and unnecessary.

I agree.

Closing, as I doubt anyone else was using this setting.
Thanks.
