### ISSUE TITLE
Please allow CSS change of contextual identity marker color

### ISSUE THREAD

**Issue by sbr61** [piroor/treestyletab#2296]
## Short description

I would like to add a CSS style snippet for the TST sidebar that changes the color of the contextual identity marker. The reason is that I use the Temporary Containers extension and so get lots of temporary container tabs, which should get a less prominent color. (I "sacificed" turquouise to become grey).

On the main Firefox UI, I can achieve this with

    .identity-color-turquoise {
      --identity-tab-color: #a0a0a0 !important; /* tab bar */
      --identity-icon-color: #a0a0a0 !important; /* address bar */
    }
in `userChrome.css` and with

    [data-identity-color="turquoise"] {
      --identity-icon-color: #a0a0a0 !important; /* multi-account containers menu */
    }
    
    .identity-color-turquoise {
      --identity-icon-color: #a0a0a0 !important; /* multi-account containers preferences */
    }
in `userContent.css`.

## Steps to reproduce

I debugged the TST sidebar and was able to change the color of the contextual identity marker of a certain tab in the following way:

    .tab.contextual-identity-firefox-container-107 .contextual-identity-marker {
      background-color: #a0a0a0 !important;
    }

However, there is no chance to do this in a CSS snippet on the TST preference page, as the tab numbers (here 107) vary. Would it be possible to pick up the background color from the `--identity-tab-color` attribute rather than assigning it to a generated class? Like so:

    .contextual-identity-marker {
      background-color: var(--identitiy-tab-color) !important;
    }

Then a snippet for the TST preference page would not even be necessary as the value would be taken from the modified `userChrome.css`.

## Environment

 * Platform (OS): Windows 10 Pro 1809
 * Version of Firefox: 67.0
 * Version (or revision) of Tree Style Tab: 3.0.15

**Comment by piroor** [comment]
The color of temporary containers looks changeable on the options page of the Temporary Containers itself:
![image](https://user-images.githubusercontent.com/70062/58776252-93d96580-8604-11e9-92f2-aedc822cd83d.png)

And, colors of already created Temporary Containers are also changeable via Firefox's options:
![image](https://user-images.githubusercontent.com/70062/58776354-3396f380-8605-11e9-8030-519d99fab17d.png)
The "Settings" button placed right of the "Enable Container Tabs" checkbox is that.

TST respects and applies updated colors of containers immediately. If preset choices of colors is not good for you, I think it must be fixed by the Temporary Containers addon side, also for people who don't use TST.

**Comment by sbr61** [comment]
I know these settings. The problem is not in TC, which just offers all available container colors. The limitation comes from the Mozilla multi-account container implementation, which only provides 8 fixed (and bright) colors. It is just because most of my tabs are in temporary containers why I would like to replace one of these colors by a more neutral one.

Seeing on the TST options page and the wiki that you support a lot of CSS snippets, I was just hoping that something could be added to customize the container colors in TST. The method I described above already works for all other elements of the UI (Firefox tab bar and address bar, multi-account containers addon preferences and menu), so it is just TST that does not allow to customize the container colors by CSS.

See Mozilla changeset [45e56d6e9dd](https://hg.mozilla.org/mozilla-central/rev/45e56d6e9dd) and [Mozilla contextual identity CSS file](https://searchfox.org/mozilla-central/rev/dbddac86aadf1d4871fb350bbe66db43728a9f81/browser/components/contextualidentity/content/usercontext.css).

**Comment by piroor** [comment]
OK, with the commit 2853e31 now you can remap colors of containers with a style definition like following:

```css
:root {
   --contextual-identity-color-blue: #37adff;
   --contextual-identity-color-orange: #ff9f00;
   --contextual-identity-color-green: #51cd00;
   --contextual-identity-color-pink: #ff4bda;
   --contextual-identity-color-purple: #af51f5;
}
```

But icons in the context menu are still shown with original colors, because they are embedded in the SVG icon file, as: https://github.com/piroor/treestyletab/blob/master/webextensions/resources/icons/contextual-identities/briefcase.svg?short_path=9568f3b#L13

**Comment by sbr61** [comment]
Thank you very much. This makes a big difference on my tree tab - now I have only bright colors where important.

I can live with the original colors on the context menu as it is not open all the time.

For people who use a huge number of generated temporary containers, the possibility to hide them on the menu would be helpful - if you like the idea. For instance, _Switch Container Plus_ (from the same author as _Temporary Containers_) has an Option _Hide Container Name RegEx_ that can be set to a regular expression for the names to hide on the menu, e.g. `tmp\d+` or `\d+`.

**Comment by piroor** [comment]
TST's context menu is mainly designed to emulate Firefox's native context menu on tabs, so such customizability looks out of purpose, sorry.

**Comment by irvinm** [comment]
@piroor I think we can close this one.

**Comment by piroor** [comment]
I close this for now because there is no further information.
