### ISSUE TITLE
Feature request: Subpins of pins

### ISSUE THREAD

**Issue by mazunki** [piroor/treestyletab#2297]
## Short description

I am a user who uses pinned tabs a lot, but I also love having subtabs for any given tab. 

Pinning tabs removes them from the tree system, which is an annoyance. There doesn't seem to be any middle ground for this. 

Having the option to place tabs under pinned tabs, and make them appear as pinned tabs do, possibly in another colour as these would be a great way to do this. 

If not, move children of current open pinned tab to the top of the list. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a webpage
 4. Create some children for this tab
 5. Pin the first tab.

```
A (to be pinned)
\- B (selected)
\- C
D (to be pinned) 
\- E
F
```

## Expected result
```
A (pinned) D (pinned)
\- B (selected) C
\- E (hidden or collapsed, as per settings)
F
```

## Actual result

```
A D (pinned tabs)
B (selected)
C
E
F
```

## Environment

 * Platform (OS): Ubuntu 18.04
 * Version of Firefox: 67.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.0.15

**Comment by piroor** [comment]
It is  hard due to some reasons. Backgrounds:

* TST basically respects Firefox's native tab behavior, including their order.
  * This is for compatibility with Firefox's native tab features and other tab related addons.
  * So, in your example, tabs B, C, and E need to be ordered as they displayed: [A (pinned), B, C, D (pinned), E, F].
* Firefox cannot place non-pinned tabs between pinned tabs.
  * Thus both A and D must be placed before B.
* Pinned tabs are treated specially on Firefox. They are restored on restart automatically, and loaded on the RAM.
  * To prevent placing of too many pinned tabs on the RAM, child tabs ("subpinned tabs" you told) should not be treated as pinned.

So there is only one way to implement the visual you suggested: showing tabs in the order different from Firefox's native tabs. For example, on the case you told, physical tabs are ordered as [A, D, B, C, E, F] but visible order need to be [A, B, C, D, E, F]. But such a hack will make things too complicated and restricted.

* TST may need to manage doubled information about index of tabs: physical index and visible index.
* Tabs operated by other addons or operated via Firefox's native tab bar will break the relation of doubled indexes. So TST may need to restrict operations produced outside of TST around tabs more aggressively.

On the other hand, my basic policy about TST is: keeping it simple as possible as I can. Implementation plan described above is quite opposite.

Thus I hope to put this plan unimplemented. Instead, as a workaround I've done a change with the commit 7d50a53. Currently TST tries to group tabs opened from a common pinned tab under a group tab (dummy tab). After the commit, TST automatically groups remaining children of to-be-pinned tabs like as "children opened from the pinned parent tab". I hope that this new behavior should help people who are suffered from unbound children of pinned parent tabs. How about that?

**Comment by mazunki** [comment]
I understand changing the order of the tabs is complicated. How about highlighting the group of tabs/the dummy tab while selected?

**Comment by piroor** [comment]
OK, I've introduced new "bundled-active" state for such tabs. TST treat a related tab like as the active tab visually. When the related  tab is out of screen, TST automatically scrolls the tab bar to the tab.

**Comment by irvinm** [comment]
@mazunki, is this sufficient?  Can you close this item if so?

**Comment by mazunki** [comment]
This is great. I have been busy for some time, being unable to answer/test the solution, but the provided method works very well. Thank you!
