### ISSUE TITLE
Open TST preferences from context menu

### ISSUE THREAD

**Issue by SammysHP** [piroor/treestyletab#2318]
Feature request: Add an entry to the context menu of the sidebar to open the TST preferences page. This would make customization easier accessible instead of menu, addons, search for TST.

**Comment by piroor** [comment]
Do you use the toolbar button of TST itself? You can go to TST's options page directly from the context menu on the button: ![image](https://user-images.githubusercontent.com/70062/59855385-d85c5380-93af-11e9-84b0-ded3dcff7b89.png) It is not a TST specific behavior, instead the menu is available on any toolbar button provided by addons.

And, as you saw in the screenshot, the menu provides limited version of options UI also (*this is TST specific.)

I'm negative to add a command item to go to the options page to the context menu on tabs, with some reasons:

* The command is fundamentally unrelated to the context: "what command do you want to invoke for the *tab*?"
* If you need to change TST's options too frequently on your daily use, something wrong. For example, a failure auto-detection of TST for your action's context. I believe that such a problem should be fixed on TST side, instead of providing easy way for workaround.

**Comment by SammysHP** [comment]
No, I don't use the toolbar button (but can add ero the overflow menu. Your reasons to not include it in the context menu are understandable.

Btw: I open the preferences often to test different features in different contexts to find the best solution for me. Also I improve my custom style regularly.

**Comment by piroor** [comment]
One more workaround, you can bookmark the options page with these steps:

1. Go to `about:debugging`.
2. Find the "Internal UUID" of Tree Style Tab. It should be an UUID like `XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`.
3. Create a new blank bookmark, and set its URL as `moz-extension://XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/options/options.html#!`. The UUID is TST's internal UUID.

Then you can open the options page in a tab.
