### ISSUE TITLE
[feature request] Configurable shortcut for closing current tab

### ISSUE THREAD

**Issue by iroedius** [piroor/treestyletab#2319]
Would it be possible to add a configurable shortcut for closing just the current tab?

**Comment by piroor** [comment]
Did you mean that an individual tab should be closed when the command is invoked on a parent tab and its descendants are collapsed? Then I'm negative to add the command, because:

* It looks unnatural behavior for me, when the tab is treated as a parent of other tabs. I don't do such an operation while the tree is collapsed. On the other hand, I sometimes want to close only the individual parent tab and actually do it, but on such situations always the tree is expanded on my cases.
* I agree that the current behavior of TST is unnatural when the sidebar is invisible. So, instead I implemented an option to treat tabs as solo tabs while the sidebar is invisible: TST's options => "Tree Behavior" => "When a parent tab is moved or closed...". Screenshot: ![image](https://user-images.githubusercontent.com/70062/59855069-2b81d680-93af-11e9-94ac-152ea9e4ffa3.png) The third option looks to introduce natural behavior on such cases. I think this should become a workaround for you.

**Comment by irvinm** [comment]
@piroor I think we can close this one.  @iroedius feel free to comment and\or reopen if you disagree.

**Comment by piroor** [comment]
I close this for now because there is no further information.
