### ISSUE TITLE
Erratic sidebar scrolling when moving tabs

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2321]
When I try to move a tab in the sidebar, the scrolling is erratic.  Nearly impossible to control, with the tendency to "jump" long distances very quickly.

Version of Firefox: 68.ob13
Version (or revision) of Tree Style Tab: 3.12
Windows 10 pro

**Comment by piroor** [comment]
I've introduced throttling for the auto-repeating of the auto-scroll behavior, with the commit. Could you try a new development build including the change?: https://github.com/piroor/treestyletab/blob/master/README.md#development-builds

**Comment by nollinvoyd** [comment]
That works, but now it is very slow and deliberate.  Could it be sped up just a bit?

**Comment by piroor** [comment]
It looks hard, because after the change TST simply ignores second or more "dragover" events in one event loop. As a workaround, please shake your mouse at the edge of the scrollable area. The "dragover" event is fired repeatedly even if you stay your cursor on the same position, but it is also be fired when the cursor is moved (shaken).

**Comment by irvinm** [comment]
@piroor are you inclined to make any more changes around this?

**Comment by piroor** [comment]
Sadly I have no more idea for this problem. Any pull requests for this topic is still welcome.
