### ISSUE TITLE
Extension "startup" tab opening every time

### ISSUE THREAD

**Issue by OsakaWebbie** [piroor/treestyletab#2324]
I use Firefox Portable, currently version 67.0.4, and recently installed TST version 3.1.2. Every time I open the browser, a tab with info about TST appears (moz-extension://cda85014-ef15-4385-8edd-462daac4067d/resources/startup.html). I assume such a startup tab is only supposed to appear once, not every time Firefox is opened. Since others are not complaining about this, perhaps it's unique to Firefox Portable, or perhaps just my installation. If there is an way to end this behavior, please let me know.

**Comment by piroor** [comment]
Looks similar to #2292. TST stores its own status with `browser.storage` WebExtensions API, and its backend was migrated from a JSON file to the IndexedDB on Firefox 66. If you disable the IndexedDB feature with `dom.indexedDB.enabled`=`false`, or if the database is corrupt, TST cannot update its own status as "the startup page was already shown". Could you check the preference with `about:config`? If the IndexedDB feature is enabled but you still see the problem, you may need to cleanup your Firefox profile to refresh the storage.

**Comment by OsakaWebbie** [comment]
Ah, I searched for my issue in English, but didn't try Japanese - haha! (Yes, I do read Japanese, as I've lived in Japan since 1996, but English will always be easier for me.) Piroorさんは日本人であるのを気づきませんでした。Piroorさんの英語は完璧です！

Unlike the user who wrote #2292, in my case `dom.indexedDB.enabled` is `true`.
How can I clean up my profile? If you can just point me to an applicable article or tutorial, I should be able to take it from there.

**Comment by piroor** [comment]
You can go to your profile directory from `about:support`. In the profile directory there is a folder named `storage`. It contains three subfolders `default`, `permanent`, and `temporary`. I've found a folder named like `moz-extension+++XXXX-XXXX-XXXX-XXX...` under the `default`, so deleting the folder containing the internal ID of TST on your environment in its name (maybe `moz-extension+++cda85014-ef15-4385-8edd-462daac4067d...`) possibly clear the broken DB. Otherwise, deleting `default` or `storage` will do that. But please be careful that deleting upper level directory may lose your local data stored by other addons and websites.

**Comment by OsakaWebbie** [comment]
Okay, that solved it - thanks. It's possible that deleting only the TST-specific folder would have been enough, but when I tested the result of that, I failed to realize that I needed to open Firefox twice, not just once, as it has to record that I've seen the page (dummy me!). But next I deleted the whole `default` folder and tested properly, and it behaved as it should. It was probably good to clean the whole `default` folder anyway - it contained 6,324 files totaling 201 MB!
