### ISSUE TITLE
[feature request] - Copy links of selected tabs

### ISSUE THREAD

**Issue by narzb** [piroor/treestyletab#2335]
I want to be able to copy URLs of selected tabs with context menu (right click)

Why :
to export easily all page i have opened without bookmark it

It would be a very useful feature to add to the context menu without degrade the interface (it will be hidden in context menu)

**Comment by irvinm** [comment]
I am not sure if you mean "selected tabs" (Using addon "Multiple Tab Handler") or if "all" tabs.  If you mean "all tabs", there is already an addon to do that:  https://addons.mozilla.org/en-US/firefox/addon/copy-all-tab-urls-we/

**Comment by piroor** [comment]
I personally use my another addon [Copy Selected Tabs to Clipboard](https://addons.mozilla.org/firefox/addon/copy-selected-tabs-to-clipboar/) with TST.

Sorry but I won't integrate this feature to TST because TST project focuses to "tree of tabs". Instead TST should be compatible with other addons like above, and if you see any compatibility issue with other addons please report that.
