### ISSUE TITLE
Sometimes closed tabs remain in the sidebar.

### ISSUE THREAD

**Issue by xzn** [piroor/treestyletab#2341]
## Short info

As titled, clicking on those entries doesn't do anything.

Closing and reopening the sidebar causes them to go away.

## Reproduction steps

Do normal web browsing. Sometimes a tab would stay in the sidebar after it's closed. Clicking on it has no effect. Closing the sidebar then reopen TST sidebar fixes it.

## Firefox version

68.0.1 Stable x64 on Windows 10

## TST version

AMO 2019 July 09

### Other addons

Move unloaded tabs for Tree Style Tab (AMO May 22)
UnloadTabs (AMO June 12)

I have a few dozons other addons installed. Though the only other one I know that may interfere with tabs is Tab Session Manager (AMO Feb 16)

**Comment by piroor** [comment]
Too less information. Please fill the issue template especially the steps to reproduce...

**Comment by xzn** [comment]
Apologies for too little information. Edited with slightly more info. Unfortunately I've no consistent way of reproducing it. Even after it happens, trying to do the same thing multiple times doesn't cause it to happen again. Then it happens some other time when I'm just doing normal web browsing.

Should I try the debug logs in the TST settings? What should be the files to enable debug log for? I've enabled `Log querying of tabs` and `Log internal messages` for now. Debug mode causes red outlines to be drawn on the sidebar which is quite distracting ..

**Comment by piroor** [comment]
TST reports too much debug logs, so it may not help debugging if you don't narrow down the conditions and situation to reproduce the problem enough yet.

Possible triggers for such a hard problem are:

* Tabs moved across windows.
* Operations for multiple selected tabs.
* Tabs immediately closed just after they are opened.
* Tabs immediately moved just after they are opened.
* (and more)

TST often expects that tabs are operated gently. Otherwise TST may process multiple asynchronous notifications in wrong order. Even if you see no odd behavior just after such operations, TST's internal information of tabs may be broken or unsynchronized to Firefox's native tabs. On such situation, any operation may bring the broken status to the surface. So, the operation you did when you saw the problem may not important and you may need to put focus onto operations you did before the time.

**Comment by xzn** [comment]
IIRC it happens usually when opening/reopening some tabs while immediately switching tabs.

Sometimes a tab is opened and then just disappears a few seconds later (the tab entry is never clickable or could be switched into) while sometimes a tab is opened/reopened but in the wrong order (when alt-tabbing)

**Comment by irvinm** [comment]
@xzn are you still seeing the issue?

**Comment by xzn** [comment]
Sorry though I closed this issue already. Thanks for the reminder.
