### ISSUE TITLE
Feature request: Option "Do not close child tabs anyway"

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2347]
Hi,
Currently, if the tree is collapsed, then closing the parent tab closes the entire tree. I would like to see an option "Do not close child tabs anyway".

Let everyone myself decide what behavior suits him best. At the moment such a choice is not provided.

Thank you for the wonderful addon.

**Comment by piroor** [comment]
Sorry but I won't implement the option because it looks unnatural for me. Instead a helper addon  https://addons.mozilla.org/en-US/firefox/addon/tst-change-close-tab-button-be/ may help you. It allows you to close just the parent tab by single left click on the close button of a parent tab, whether the tree is collapsed or expanded.

**Comment by wvxwxvw** [comment]
ОК. It's enough.
