### ISSUE TITLE
When we stop a slow web page TST stops working correctly

### ISSUE THREAD

**Issue by tbertels** [piroor/treestyletab#2356]
## Short description

If the message "A web page is slowing down your browser, what do you want to do" is shown and we stop the web page, TST stops working correctly.

## Steps to reproduce

 1. Open a web page that slows down Firefox (not just a script)
 2. Wait for the "A web page is slowing down your browser, what do you want to do" message
 3. Click on "Stop it"

## Expected result

TST continues working as usual.

## Actual result

We can't select or close the affected tab and if we close and reopen the TST sidebar, it cycles loading/showing a flat tab tree indefinitely. The only way to fix it is to restart Firefox or disable/enable TST.

## Environment

 * Platform (OS): WIndows 7 x64
 * Version of Firefox: 68.0.1
 * Version (or revision) of Tree Style Tab: 3.1.7

**Comment by piroor** [comment]
Is this TST specific problem and doesn't happen on other sidebar addons like Sidebar+, Sidebery, or others?

**Comment by tbertels** [comment]
I've installed Sidebery, I'll check it out the next time I reproduce it.

**Comment by stapuft** [comment]
> 
> ## Short description
> 
> If the message "A web page is slowing down your browser, what do you want to do" is shown and we stop the web page, TST stops working correctly.
> ## Steps to reproduce
> 
>     1. Open a web page that slows down Firefox (not just a script)
> 
>     2. Wait for the "A web page is slowing down your browser, what do you want to do" message
> 
>     3. Click on "Stop it"
> 
> 
> ## Expected result
> 
> TST continues working as usual.
> ## Actual result
> 
> We can't select or close the affected tab and if we close and reopen the TST sidebar, it cycles loading/showing a flat tab tree indefinitely. The only way to fix it is to restart Firefox or disable/enable TST.
> ## Environment
> 
>     * Platform (OS): WIndows 7 x64
> 
>     * Version of Firefox: 68.0.1
> 
>     * Version (or revision) of Tree Style Tab: 3.1.7

i have experienced this.

extension that caused the webpage to slow down was "Dark Reader" https://darkreader.org/ (likely due to its custom generated and inserted page styling to make the page dark, hangs up on infinite scrolling pages causing it to hang, and by proxy cause the web page itself to hang then the "stop" dialog appears [happens often on reddit.com and disqus.com both are infinite scrolling pages])

this has also happened to me occasionally before I got that extension, but using that extension (specifically on a low end computer like a netbook) is an almost surefire way to get that dialog to appear.





anyway, i can confirm that after clicking "stop" TST acts wonkey and might even crash and then get stuck on an infinite loading dialog that you must either disable and reanable TST to fix, or just restart firefox to fix.

**Comment by irvinm** [comment]
@tbertels can you give us an update?  If things are better, can you close this item?

**Comment by tbertels** [comment]
I haven't encountered a slow web page for a while, so I can't say if it's fixed or not.

**Comment by piroor** [comment]
I've tried with a page including an infinity loop:

```javascript
while (true) {
  Math.random() * 65500;
}
```

and it shows a info bar with a message: "A web page is slowing down your browser, what do you want to do?" But after I click the "Stop It" button TST still works correctly for me.

I think this is an environment specific problem. On my environment Firefox runs separate processes for addons and in-content web pages, thus even if I stop running scripts in a web page TST is not affected. On the other hand, if Firefox just separates processes for its UI and others (including addons and contents) stopping to run scripts in the "others" process may stop addons also.

Otherwise, if stopping of running script in a content affects to a process for an addon, it is clearly a bug of Firefox itself. They must be isolated, it is the most important concept of multi-processes on Firefox.

**Comment by tbertels** [comment]
I've tried too with that script, it works for me too.
