### ISSUE TITLE
Middle click next to tab

### ISSUE THREAD

**Issue by SammysHP** [piroor/treestyletab#2367]
You can left click on the background next to a tab to select it. But middle and right click behaves like clicks on the background.

Version 3.1.7

**Comment by piroor** [comment]
This is intentional decision. Left-click on the blank area regularly does nothing so it can be reassigned for tab activation on such cases. On the other hand, right-click on the blank area opens a context menu for operations about all tabs, and middle-click opens a blank tab. I think that overriding these functionalities may confuse people who use them.

**Comment by SammysHP** [comment]
OK, thanks for the explanation. Probably something that I can work around with a style that extends the area to the left (tried it once, but it required various changes because of overflow etc.).
