### ISSUE TITLE
Closing parent of collapsed tree fails repeatedly & without warning if TST is not visible

### ISSUE THREAD

**Issue by maxsu** [piroor/treestyletab#2382]
## Short description
Closing the parent tab of a collapsed tree causes that tab to repeatedly reappear if TST is not visible.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST sidebar
 4. Create a tree with child tab
 5. Collapse the tree

     Tree state:
     ```
     A
     \- B (collapsed)
     ```

 6. Close TST sidebar
 7. Attempt to close tab A

## Expected result

One of:

1. The tab closes as if it were the parent of an expanded tree

OR

2. TST displays a "You are about to close multiple tabs" warning

## Actual result

*Tab will close and reappear immediately*
     - This happens with no explanation, and can happen repeatedly
     - To stop the behavior one must select tab B or open TST

## Analysis

I believe this executes the codepath responsible for the, "You are about to close 2 tabs. Are you sure you want to continue" warning. This may default to the "Cancel" option because TST is not open to display the warning.

This behavior is very intermittent and was hard to localize/explain:
- There is no indicator that TST is the cause, when ordinarily the behavior would display an interactive warning
- It only happens when TST is not visible
- It only happens for a small subset of tabs

For me, the behavior only happened once a day or even less, as I had TST open nearly all the time. It was *very* perplexing, I nearly lost hope of explaining the behavior.

As the behavior is unexpected, difficult to explain, and difficult to link with TST, I believe it's less than ideal default behavior for a new or intermediate user.

## Workarounds

1. I have tested a few options in hope of disabling this behavior, but have not yet found one
2. Disabling the "You are about to close n tabs" warning allows us to close the parent without issue
  - This also closes children, which can be undesirable and is hard to predict if TST is not open

## Resolution
From the perspective of user explainability, expected behavior #1 is in my opinion the best solution, unless TST can:
1. Display a warning to explain the behavior
2. Provide an option to prevent the behavior

## Environment

I did test this with TST 3.1.8 it in a clean profile in firefox 68, 69, and 70.0b5 beta. I did not test the Development build. 

 * Platform (OS):  Windows 10
 * Version of Firefox: 70.0b5, 69.0, 68.0
 * Version (or revision) of Tree Style Tab: 3.1.8

**Comment by piroor** [comment]
Sorry I missed this report.

The problem appears only when TST doesn't have the `<all_urls>` permission. It is not granted by default and you need to give it to TST manually via the option "Don't expand collapsed tree and skip collapsed descendants, while switching focus of tabs via keyboard shortcuts". TST actually tries to show a confirmation dialog in the active tab but it is blocked by default and TST treats it as "the confirmation is canceled", yes your analysis is correct.

The root problem is: there is no available way to show a modal confirmation safely by addons. When the sidebar is displayed TST can show it in the sidebar, but otherwise we need to do it in the content area and it requires a special permission to execute arbitrary script. I think a notification may be useful for this purpose, but sadly Firefox doesn't support notifications with two or more buttons...

**Comment by piroor** [comment]
As a workaround I've implemented a notification when no confirmation is available. When you click the notification TST tries to cancel the last action - restores closed tabs.

**Comment by irvinm** [comment]
@maxsu is this sufficient from your end?  If so, can you close this item?

**Comment by irvinm** [comment]
@piroor I am guessing we can close this one.
