### ISSUE TITLE
Behavior when moving tabs

### ISSUE THREAD

**Issue by Dominiquini** [piroor/treestyletab#2403]
## Short description
I often try to move the current tab to the right of the tab I just started from a link I just clicked, but it seems to be impossible. The tabs return to their original order.

## Steps to reproduce

1. Open a link in a new tab
2. Try to move the current tab to the right of the new tab

## Expected result
Change the order of the tabs and change the new tab to become sibling of the current tab

## Actual result
Nothing changes in the tab bar

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 70.0
 * Version (or revision) of Tree Style Tab: 3.2.1

**Comment by piroor** [comment]
Did you mean that a operation in the horizontal tab bar natively provided by Firefox itself? Then it is by design of TST. TST doesn't accept any parent tab placed after its descendant - it is detected as a broken tree. On such case TST automatically "fixes" the order of tabs to keep their relations.

The order of tabs in the horizontal tab bar and the sidebar is synchronized by TST. If you really want to move a parent tab after its child, you need to drag the child tab and drop before the parent tab. Then the child will be detached from its parent and you'll move the tab there successfully.

**Comment by Dominiquini** [comment]
Thanks!

I'll close the issue.
