### ISSUE TITLE
[feature request] Provide a way to mark tabs as read

### ISSUE THREAD

**Issue by LordNacho** [piroor/treestyletab#2425]
## Short description
Currently if you reload the set of tabs after a crash or FF restart, all the tabs are marked as unread. There doesn't seem to be a way to unmark them, other than visiting all the tabs. This is inconvenient, especially as some tabs may be suspended and will require re-suspension. Only an issue if you are marking the unreads using CSS, but that's quite useful in normal operation.

A lot of apps use SHIFT + ESC to mark all as read, perhaps that's the way to go?

## Steps to reproduce
Just restart FF and load the previous session via the History menu.

## Environment
MacOS

**Comment by piroor** [comment]
A feature "mark tabs as read" looks not related to "tree of tabs" so I'm negative to add the feature, sorry.

Currently the "unread" state of TST tabs is provided to simulate the "titlechanged" state of Firefox's native tabs. The native "titlechanged" are updated with a trigger "DOMTitleChanged" but TST does it in different way based on regular WebExtensions API way, because listening of "DOMTitleChanged" requires the `<all_urls>` privilege. So, even if Firefox doesn't set "titlechanged" for restored tabs, TST may detect they as "unread" due to differences of those ways.

Just as a workaround, I've introduced some changes at a4b118a. Now TST doesn't set tabs unread when a background pinned tab is reloaded but the title of the tab is not changed. I hope this reduces the problem: tabs become "unread" after a session restoration.

**Comment by irvinm** [comment]
@piroor I think we can close this one.
