### ISSUE TITLE
[Feature Request] Tab Grouping 

### ISSUE THREAD

**Issue by KAmaia** [piroor/treestyletab#2428]
Feature request:

Tab groups, so that multiple tabs can be grouped together and viewed independently of one another.  Similar to the way tree tabs handles grouping of tabs.

**Comment by piroor** [comment]
You already can do that with:

* Multiselect tabs with ctrl-click or shift-click, right-click on tabs to open the context menu, choose "Tree Style Tab" => "Create New Group from tabs".
* Open `ext+treestyletab:group` from the location bar. It will opens a new dummy tab to group other tabs.
  * You should create a bookmark with the URI, if you hope to open such tabs only with mouse operations.

Sorry but I have no plan to add more features for grouping of tabs, because it looks not related to "tree of tabs". TST just provides the dummy tab for grouping as one of special cases on the tree management.

**Comment by irvinm** [comment]
@piroor I think we can close this one.
