### ISSUE TITLE
[Feature Request] Option to open all links in no container (w/exceptions)

### ISSUE THREAD

**Issue by kenyoni** [piroor/treestyletab#2429]
## Short description
Make a configuration option where a link on a page that is already in a named container is not opened in the  container *unless* it is in the same domain as the original page. In that case, open it in the same container. 

## Specifics 
Use case:  I have Google search results open in a container labeled "Google" . If I middle-click on a link, I want that link to open by default in a new child tab (which it does) but in no container.  If the link is in the same domain, (Google in this case) open it in  the same container as the parent.

Notes:
 * Yes, I realize that I can right click on the link, select "Open Link in a New Container Tab" and select "No Container". Kind of a PITA to remember to do for every link.
 * I am using the "Don't track me Google"  extension so links in Google search are sanitized.
 * This already works for the specific case: I have named containers for Amazon.com (and others) and after selecting in the dialog box the first time,  all Amazon.com links open in the Amazon container, including links in Google search results. (just a function of containers)  I would like this for the general case: If not in google.com,  amazon.com, or other special containered  domain, do not open in a container.
 * Confusingly, in TST options, there is already an option in "New Tabs Behavior->Non-blank new tabs", that says:
`New tab with the same website as the current tab from the location bar, bookmarks, histories, or other cases [this case?] Open as [a child of the current tab]`  

       - [X] Inherit the container of the current tab

    To me, this kind of implies that if the tab is **not** in the same website [domain?]  that this rule doesn't apply and so the new tab will be a child (default behavior) and  it **won't** inherit the container of the current tab. But it does, hence this request. :)

I'm surprised no one has requested this yet unless I am totally missing something about containers, how they work, and their purpose. 

I have read through most of the documentation and I *think* this falls in the scope of TST, We'll see. :)

## Environment

 * Linux spirit 5.3.15-1-MANJARO #1 SMP PREEMPT Thu Dec 5 11:01:29 UTC 2019 x86_64 GNU/Linux
 * Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
 * Tree Style Tab 3.2.5

**Comment by piroor** [comment]
The behavior you told is one of built-ins of Firefox itself, not of Tree Style Tab. TST doesn't control the container of tabs opened from links in a non-default container parent tab, instead Firefox itself opens a new tab with same container when tabs are opened from links.

The option "New tab with the same website as the current tab from the location bar, bookmarks, histories, or other cases" => "Inherit the container of the current tab" doesn't affect to the case. It is just for cases when TST failed to detect the context of newly opened tabs. (For more details of this context detection, please see also my comments on #2391)

Sorry but I'm negative to add this kind option to TST because it is not related to "tree of tabs". Instead I think you should use something another addon which is designed to control inheritance of containers on such cases. If you see any compatibility problem with the combination of TST and such an addon, please report it here again - then I'll try to improve compatibility of TST for the addon.

**Comment by irvinm** [comment]
@piroor I think we can close this one.
