### ISSUE TITLE
Has the TreeStyleTab menu been labeled "Tree of Tabs" for the holiday period?

### ISSUE THREAD

**Issue by vonHabsi** [piroor/treestyletab#2443]
Has the TreeStyleTab menu been labeled "Tree of Tabs" for the holiday period?

Right clicking a tab displays the TreeStyleTab menu as  **Tree of Tabs** and I wonder whether it is a temporary feature for the Christmas holiday period?

Happy Holidays :)

**Comment by piroor** [comment]
> Has the TreeStyleTab menu been labeled "Tree of Tabs" for the holiday period?

No, it's due to changing of localized name.

Recently I got a pull request to update Chinese locale and initially he translated the name of the addon to Chinese, but for better findability on addons.mozilla.org and the addons manager, finally I decided to untranslate the name of this addon itself and [I defined a translation policy.](https://github.com/piroor/treestyletab/blob/master/webextensions/_locales/README.md#policy-about-translation-see-also-2434)

On the other hand, histrically TST was named as "ツリー型タブ" in Japanese locale (it just means "Tree Style Tab".) This historical name violated the new translation policy. I thought to untranslate the name of the addon in Japanese locale, but English name looked not suitable in the context menu for me, and instead a feature-oriented menu label looked better. This is the reason why I changed the label of the menu to "Tree of Tabs".

In Japanese locale it is now translated to "タブのツリーの操作" (means "Operate Tree of Tabs"). In other words, I didn't include the term "operate" for the English locale, because:

* I thought that "Operate Tree of Tabs" looks too long for a menu label in the context menu.
* In English locale, a feature-oriented menu label is regularlly started with a verb, but a generic verb like "operate" is often omitted.

**Comment by vonHabsi** [comment]
The problem here is one of brand recognition. If not for the familiar TST icon users would not recognize it as the TST menu.

I think you should retain the familiar "Tree Style Tab" name on the menu for English users.

**Comment by vonHabsi** [comment]
This issue is really a matter of opinion and I'm leaving @piroor to close it if he is decided on the issue.

**Comment by piroor** [comment]
Hmm... I think that a survey should give an answer about this point, but it looks a too heavy task for me. If anyone do that it may change my decision.

**Comment by vonHabsi** [comment]
I am the only one who has mentioned it so far, and if other users don't add their opinion it is probably not that important. The icon is recognizable.

**Comment by irvinm** [comment]
@vonHabsi can you close this item then?  We can always revisit\reopen if needed.

**Comment by vonHabsi** [comment]
Closing. Under users who think the issue matters can reopen it with their own reasons
