### ISSUE TITLE
Keyboard shortcuts for common tasks

### ISSUE THREAD

**Issue by fctorial** [piroor/treestyletab#2473]
It would be nice to have keyboard/mouse shortcuts for common tasks like:

1. open new tab as child of current one.

2. Navigating tab tree

3. Moving subtree

4. Closing subtree

**Comment by piroor** [comment]
TST already have some of them:

* 1 => Open a new tab: Child Tab
* 3 => Move Current Tree Up / Move Current Tree Down
* 4 => Close this Tree / Close Descendants

And what the command "Navigating tab tree" means? Could you describe more details?

**Comment by fctorial** [comment]
@piroor Pressing `1`, `3` or `4` doesn't do anything on my installation. I'm using firefox 72 on linux.

By navigating tab tree, I mean moving up down in the list of tabs.

Where can I find the list of keybindings, if there is one?

**Comment by piroor** [comment]
What shortcut key did you actually pressed? If you really just pressed numeric `1`, `3` and `4` keys, please note that you need to set your custom shortcut (it must not conflict to Firefox's one) for each command manually via the "Keyboard Shortcut" section in the TST's options page, or `about:addons`.
![image](https://user-images.githubusercontent.com/70062/72948325-24e59280-3dc8-11ea-9bd5-3730f995140c.png)
![image](https://user-images.githubusercontent.com/70062/72948435-79890d80-3dc8-11ea-9712-883488538a4b.png)

**Comment by fctorial** [comment]
Great, that solves most of my issues. I've noticed that firefox default keybindings are preferred over the ones registered by an addon. Would it be possible to revert this behaviour?

**Comment by piroor** [comment]
It is an issue of Firefox itself and any addon cannot solve it for now. See also the bug:

1325692 - [commands] Explicit support for overriding built-in keyboard shortcuts by WebExtensions
https://bugzilla.mozilla.org/show_bug.cgi?id=1325692

**Comment by Kabouik** [comment]
I'm confused, was the keybindings section of TST moved somewhere else?

![ss-2020-03-16_125045](https://user-images.githubusercontent.com/7107523/76755828-797c0d00-677c-11ea-9b6b-8c41e72def60.png)

**Comment by piroor** [comment]
The section was removed, because Firefox already has better customization UI for keyboard shortcuts of addons. It is available at about:addons page:
![image](https://user-images.githubusercontent.com/70062/76765278-7ebb7500-67d9-11ea-9064-5a199bb969bc.png)

**Comment by Kabouik** [comment]
Awesome, thanks. Somehow I missed this menu even after looking where to edit shortcuts in Firefox for hours!

I still have an issue though: my keybinds to change tabs have no effect. Is it possible that they are conflicting with something else?

![ss-2020-03-16_153052](https://user-images.githubusercontent.com/7107523/76768522-07fb8900-6793-11ea-9839-e65937215ee2.png)

**Comment by piroor** [comment]
@Kabouik Alt-Shift-Up/Down for those commands work for me, at Nightly 76.0a1 on Windows 10. Is any other shortcut works for the command? Or, only these shortcuts (keybindings) don't work for any command?

**Comment by piroor** [comment]
@Kabouik If Alt-Shift-Up/Down don't work for any other command, it may be a problem of Firefox itself or a conflict with something utility running on your platform.

**Comment by Kabouik** [comment]
Thanks for testing @piroor. `Alt+Up/Down` does not work for anything (I tried other extensions), nor does `Ctrl+Up/Down`, and they don't seem to be assigned to other Firefox features because else there would be a warning. 

I am running Firefox 74.0 on Linux, and i3wm as my window manager (but `Alt+Up/Down` are not bound to anything).

**Comment by Kabouik** [comment]
`Alt+Up/Down` are properly recognized in Vivaldi, so the issue seems to be specific to Firefox and not to my environment.

**Comment by Kabouik** [comment]
Wait,I'm embarrassed to say I mixed things up and was trying to use the wrong TST function. I thought "Scroll tab up by line" was what I was after because I didn't see "Focus previous tab" before, probably because the former one was bound to a key by default and therefore draw my attention as one of the main functions. "Focus previous tab" further down the list is the feature I wanted, and assigning a keybind to that one does work as expected. I am really sorry for the noise @piroor. 

While I'm here, thanks a lot for this great add-on. It is a game changer for me, I would not use Firefox without it.
