### ISSUE TITLE
[Feature request] Close current tab by middle-click on empty space

### ISSUE THREAD

**Issue by emvaized** [piroor/treestyletab#2478]
Is it possible to configure action which is triggered on middle click on empty space in TreeStyleTab?
As for now, it is possible to open a new tab by this action (as well as by double-click). 

But I want to be able to close current tab by middle-click on empty space. It might be useful, because you won't need to aim for the exact open tab in the list to close it by middle-click, you can just use the empty space, and previous (or next) tab in the list will be focused automatically.

Is it possible somehow to implement this kind of behavior? Thanks in advance.

**Comment by piroor** [comment]
I won't implement this as a built-in behavior of TST because Firefox doesn't provide the option. Instead you need to create a helper addon to implement the behavior. [TST provides ability to listen click event on blank spaces](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-the-non-tab-area-is-clicked), and you can do any operation with the notification.

I think TST-MiddleClick https://github.com/AlexEndris/tst-middleclick may help your development. It restores the last closed tab by middle click on the sidebar, so you may simply change the result.

**Comment by emvaized** [comment]
> I won't implement this as a built-in behavior of TST because Firefox doesn't provide the option. Instead you need to create a helper addon to implement the behavior. [TST provides ability to listen click event on blank spaces](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-the-non-tab-area-is-clicked), and you can do any operation with the notification.
> 
> I think TST-MiddleClick https://github.com/AlexEndris/tst-middleclick may help your development. It restores the last closed tab by middle click on the sidebar, so you may simply change the result.

Yeah, that's exactly the way I went, and author of this add-on added optional functionality to close active tab, which can be enabled from add-on settings.
[https://github.com/AlexEndris/tst-middleclick/issues/5](https://github.com/AlexEndris/tst-middleclick/issues/5)

**Comment by piroor** [comment]
Oops, I missed that the feature has already been in the addon.
