### ISSUE TITLE
Shortcuts for closings tabs [feature request]

### ISSUE THREAD

**Issue by mazunki** [piroor/treestyletab#2505]
# Short description

Multiselecting tabs with Ctrl+LMB or Shift+LMB and then pressing the X closes all the selected tabs, and not the specific tab you pressed X on. This should be an option you could turn on or off (defaulted to on). 

Furthermore, closing an expanded (sub)tree and pressing Shift+LMB on the X should close all childs, regardless of the settings of what to do when a parent tab is closed or moved. Possibly add a settings for what do in the case of shift-clicking. 

As a last option, middle-clicking a selected tab or pressing the Del key on the keyboard while having selected multiple tabs should close all the selected tabs, following the same rules as LMB with regards to Shift-closing. 

# Steps to reproduce

- Install Waterfox.
- Install TST.
- Open some tabs with childs, select various as explained, and watch what happens. 
   
# Expected result

Tabs are closed as expected, according to currently non-existant settings. 

# Actual result

Tabs are not closed, or tabs are closed unexpectedly. This is a feature request. 

# Environment

   Platform (OS): Manjaro Linux
    Version of Waterfox: 2020.01.1
    Version (or revision) of Tree Style Tab: 3.4.1

**Comment by piroor** [comment]
> Multiselecting tabs with Ctrl+LMB or Shift+LMB and then pressing the X closes all the selected tabs, and not the specific tab you pressed X on. This should be an option you could turn on or off (defaulted to on).

This behavior simulates Firefox's native tab bar. I won't add any option to deactivate this for user experience compatibility until Firefox itself provides any option for it. (This is a design policy of TST, sorry.) If you seriously need the option now, you may need to create a helper addon to override the behavior around clicking on a closebox.

> Furthermore, closing an expanded (sub)tree and pressing Shift+LMB on the X should close all childs, regardless of the settings of what to do when a parent tab is closed or moved. Possibly add a settings for what do in the case of shift-clicking.

I didn't know but I've realized that Shift-Click on closeboxes in Firefox's native tabs don't close tabs - instead the action just changes multiselection state of tabs. For better compatibility on the user experience, I've decided to simulate this behavior on TST.

A new action "Shift-click on the closebox of a parent tab closes the tab and its descendants even if the tree is expanded" won't be added as a built-in feature, because it looks very special. As I wrote above Firefox's native tabs also does nothing special for the action.

Instead I think such a special action should be implemented by a helper addon. [There are many existing addons](https://github.com/piroor/treestyletab/blob/master/README.md#addons-that-extend-tst) which communicate with TST via [TST's API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons). Some of them may be a good template for you to implement the behavior you told. I recommend you to create it by your hand, because I will abandon maintaining of addons I don't use. Sadly there are many abandoned repositories under my account here...

> As a last option, middle-clicking a selected tab or pressing the Del key on the keyboard while having selected multiple tabs should close all the selected tabs, following the same rules as LMB with regards to Shift-closing.

Same to the previous suggestion. Moreover it looks useful for people who don't use Tree Style Tab addon also, so it looks a good motivation to create such an addon as an independent one, instead of adding new features to TST.

**Comment by mazunki** [comment]
So, in short, TST won't provide any option to have alternative shortcuts for configurable settings? I understand I can use the API to do it. I have to figure out how to make plugins myself, though. 

Thanks for the quick answer.

**Comment by piroor** [comment]
> So, in short, TST won't provide any option to have alternative shortcuts for configurable settings?

In short, the summary is right. TST aims to provide "Firefox compatible tab behavior with tree structure", and most other features are out of the scope of this project. Instead I hope make TST compatible with other tab related addons and helper addons via WebExtensions API and TST specific API - like Firefox and its addons do.
