### ISSUE TITLE
Clicking on tab title randomly opens it in new window

### ISSUE THREAD

**Issue by mr-brunes** [piroor/treestyletab#2519]
Sometimes when clicking on a tab title, it is opened in a new window. It's been like this for the past couple of months and it is *very* irritating.
This seems to occur randomly and I've no idea how to reproduce it. I'm sure I'm not doing anything weird like clicking and dragging.

It looks similar to https://github.com/piroor/treestyletab/issues/949 but the key difference is that it happens when I clicking on the tab title.

I'm on FF 74.0 and TST 3.4.6 on Win10 Pro/64 v1909.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
This looks same to #2185. It is due to Firefox's unsolved bugs:

* [1561522 - MouseEvent.screenX/screenY sometimes returns physical coordinates instead of CSS coordinates on dragend](https://bugzilla.mozilla.org/show_bug.cgi?id=1561522)
* [1561879 - Sometimes drag operation started in a sidebar contents provided by an addon is immediately canceled on macOS](https://bugzilla.mozilla.org/show_bug.cgi?id=1561879)

**Comment by piroor** [comment]
If you never want to detach tabs by drag and drop, there is an option to deactivate detaching of tabs from the window with such operations. It may suppress this annoying issue:
![image](https://user-images.githubusercontent.com/70062/76683235-e9d44280-6645-11ea-81ea-808c6a29e810.png)

**Comment by mr-brunes** [comment]
Useful info thanks. I have a 4k monitor and Logitech trackball, which might be relevant, but in any case I see that #2185 is closed now.
The trouble with disabling the drag'n'drop option is that I find dragging a tab to be very useful function, not least when a tab gets randomly opened in a new window! ;-) Alternatively an 'undo' style Ctrl-Z function would be very handy.

Any other suggestions to try?

**Comment by piroor** [comment]
> Alternatively an 'undo' style Ctrl-Z function would be very handy.

It looks useful for non TST users also. In old days I developed an extension named "Undo Tab Operations". It was outdated and didn't migrate to WebExtensions. But, today it looks to be able to be implemented better based on WebExtensions API. I hope someone implement such an addon, then I'll make TST compatible with it.

> Any other suggestions to try?

Sorry but I think there is nothing can be done for now... This problem is clearly depends on Firefox's bug, and due to the behavior of the problem, I cannot do any workaround on TST side - except disabling the detach-on-drop feature.

**Comment by irvinm** [comment]
@piroor I think we should close this for now.
