### ISSUE TITLE
Feature Request - keyboard shortcut for new tab

### ISSUE THREAD

**Issue by chaoscreater** [piroor/treestyletab#2543]
Hi,

Just wondering if it's possible to extend the app with keyboard shortcuts? If I do a CTRL+T to open a new tab using the default Firefox's tab handling, it opens a new tab as a child of the current tab.

But if I use the new tab button in Tree Style Tab, it opens as an independent tab (which is what I want).

How can I map this as a keyboard shortcut?

**Comment by piroor** [comment]
Have you ever configure Firefox to open new tabs always next to the current tab with some `about:config` option or another addon? Then could you try again with disabled it?

By the way you can set custom shortcuts for some "Open new tab as..." methods provided by TST. Go to the addons manager `about:addons` then click the "gear" button at the top-right of the addons list.

**Comment by chaoscreater** [comment]
Ahh yes, I did have this set to true - "browser.tabs.insertAfterCurrent". I set it to false and now my CTRL+T behaviour still opens next to the current tab, but as an individual tab now, which is what I want. Awesome!

By the way, is it possible for TST to remap the CTRL+T behaviour? This is considered as the built-in Firefox new tab function and so I couldn't map it in the shortcuts under about:addons. It probably doesn't matter, but just interested to know if this is possible.

**Comment by piroor** [comment]
It is a restriction of WebExtensions addons: now Firefox doesn't allow addons to override Firefox's builtin shortcuts. See also: [1325692 - [commands] Explicit support for overriding built-in keyboard shortcuts by WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1325692) So you need to use other similar shortcut like Ctrl-Alt-T.

**Comment by TobiaszCudnik** [comment]
What I'd like is to have a separate shortcut for opening a child tab, while keeping CTRL+T for a new tree root.

**Comment by irvinm** [comment]
@TobiaszCudnik or @piroor ... can we close this one for now until Firefox adds support for overriding standard shortcuts?

**Comment by TobiaszCudnik** [comment]
@irvinm My comment was regarding a non-standard shortcut for a TST specific feature (so not blocked by #1325692).

I'd like to bind eg `Ctrl-Alt-T` to `new child tab`. I checked the settings and nothing. Thx!

**Comment by piroor** [comment]
@TobiaszCudnik TST has a shortcut mappable command "Open a new tab: Child Tab". Have you tried that?

![image](https://user-images.githubusercontent.com/70062/81495382-f0500500-92ea-11ea-9934-1ed1d8e5036c.png)
![image](https://user-images.githubusercontent.com/70062/81495403-19709580-92eb-11ea-84f3-a18f25df470e.png)
![image](https://user-images.githubusercontent.com/70062/81495431-44f38000-92eb-11ea-859f-4004198608a4.png)

**Comment by TobiaszCudnik** [comment]
@piroor Thanks, that definitely solves my issue. I wasnt aware about a centralized shortcut management in FF.

**Comment by irvinm** [comment]
@TobiaszCudnik would you close this item?

**Comment by cstrahan** [comment]
To help others: I got the the behavior I expected after disabling [TST New Tabs First](https://addons.mozilla.org/en-US/firefox/addon/tst-new-tabs-first/). After that:

- opening new tabs from the context menu in TST no longer causes the new tab to be a new root
- Use of "Open a new tab: Child Tab" binding actually results in a child tab, instead of creating a new root

I consider my tabs to essentially be a stack -- I more often then not want to look through tabs in reverse chronological order. So having new child tabs open near their parent, and new roots to likewise be opened at the top of the tree, is pretty important to me.

I'll report the issue to the TST New Tabs First author. But if I may make a recommendation, it would be awesome if this could be an official option.

----

Discussion that led to TST New Tabs First: https://github.com/piroor/treestyletab/discussions/3009
