### ISSUE TITLE
Add option to enable fake context menu

### ISSUE THREAD

**Issue by techboyg5** [piroor/treestyletab#2578]
This should be added as an option, as it is easier to style with CSS.

**Comment by piroor** [comment]
The fake context menu is quite restricted and not compatible with other tab related addons. Instead I recommend you to use userChrome.css. See also: https://github.com/piroor/treestyletab/issues/2116#issuecomment-450730092

**Comment by techboyg5** [comment]
> The fake context menu is quite restricted and not compatible with other tab related addons. Instead I recommend you to use userChrome.css. See also: [#2116 (comment)](https://github.com/piroor/treestyletab/issues/2116#issuecomment-450730092)

But just in case the user really prefers this, it should be done.

**Comment by piroor** [comment]
I'm still negative to expose the fake context menu feature to further new-commers.

Currently the fake context menu is maintained just for a limited usecase: triggered by another addon [Multiple Tab Handler](https://addons.mozilla.org/firefox/addon/multiple-tab-handler/) after a drag-tab-selection action on the sidebar. It is not maintained as an "alternative choice usable instead of the regular native context menu". I strongly hope to remove it from TST if triggering the native context menu with arbitrary action become possible in the future (but I think it won't come true...)

Please remind that the fake context menu feature is just a legacy. It will be maintained while I still use it, but any new positive changes won't be done for it.

On the other hand, I'm positive to help you to customize the native tab context menu via userChrome.css like https://github.com/piroor/treestyletab/issues/2116#issuecomment-450730092 because such efforts may help people who use other tab management addons also.

**Comment by techboyg5** [comment]
> I'm still negative to expose the fake context menu feature to further new-commers.
> 
> Currently the fake context menu is maintained just for a limited usecase: triggered by another addon [Multiple Tab Handler](https://addons.mozilla.org/firefox/addon/multiple-tab-handler/) after a drag-tab-selection action on the sidebar. It is not maintained as an "alternative choice usable instead of the regular native context menu". I strongly hope to remove it from TST if triggering the native context menu with arbitrary action become possible in the future (but I think it won't come true...)
> 
> Please remind that the fake context menu feature is just a legacy. It will be maintained while I still use it, but any new positive changes won't be done for it.
> 
> On the other hand, I'm positive to help you to customize the native tab context menu via userChrome.css like [#2116 (comment)](https://github.com/piroor/treestyletab/issues/2116#issuecomment-450730092) because such efforts may help people who use other tab management addons also.

OK, thanks!
