### ISSUE TITLE
Feature request - move tab to another window

### ISSUE THREAD

**Issue by eliotb** [piroor/treestyletab#2583]
I'd like the tab context menu to include the ability to move the tab to another already open window.  I keep different categories of tabs in different windows, but sometimes end up with one in the "wrong" window.

I know it is possible to drag and drop a tab between windows, but this is awkward when windows are full-screen.

There is (I haven't tried) an extension to do only tab  moving https://addons.mozilla.org/en-US/firefox/addon/tab-mover/  but I think would be better integrated into tree-style tab

**Comment by piroor** [comment]
Sorry but I won't add the feature as a built-in, especially when it is already available via an existing addon, because I don't want to make TST a bloatware anymore. I was developed a bloatware addon "Tabbrowser Extensions" for old Firefox, and I made TST as a feature oriented spin-out of it because I gave up to maintain such a huge and complex product.
