### ISSUE TITLE
Folder icon

### ISSUE THREAD

**Issue by Vladi928** [piroor/treestyletab#2586]
Hi. I could not find how to change the folder icon to my icon. In addition, I did not find how to change the color of all tabs.

Version of Firefox: 76.0.1
Version of Tree Style Tab: 3.5.4

**Comment by irvinm** [comment]
@piroor should this one be labeled "fixed"?

**Comment by piroor** [comment]
I've found the way to use custom icon on the sidebar. Here is the code snippet:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-favicon-for-group-tabs-folder-icon

@irvinm I linked the change to this issue because it was motivated with this, but I didn't find out the way to override the favicon so I didn't set this as "fixed". Now I'm OK to mark this as "fixed".

**Comment by irvinm** [comment]
@piroor should we close this one?

**Comment by Vladi928** [comment]
Yes




суббота, 11 июля 2020 г., 21:25 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by irvinm** [comment]
@Vladi928 you can close it as well! :)
