### ISSUE TITLE
F1 stopped toggling the side panel with firefox 76.0.1

### ISSUE THREAD

**Issue by eriknelson** [piroor/treestyletab#2592]
## Short description
On Fedora 32 with Firefox 76.0.1, the F1 key has stopped toggling the side pane with all the tree style tabs.

## Steps to reproduce
Hit F1 and it doesn't work.

## Expected result
F1 key should toggle open and closed the side panel.

## Actual result
It doesn't work.

## Environment

 * Platform (OS): Fedora 32
 * Version of Firefox: 76.0.1
 * Version (or revision) of Tree Style Tab: 3.5.4

**Comment by SebiderSushi** [comment]
I observed this as well but notices that it did not appear in all of my profiles.
Also, the ["Refresh Firefox..."](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings?redirectlocale=en-US&redirectslug=reset-firefox-easily-fix-most-problems)  feature from about:support does resolve it.
I was not able to isolate it any further yet.

**Comment by eriknelson** [comment]
> I observed this as well but noticed that it did not appear in all of my profiles.
Also, the "Refresh Firefox..." feature from about:support does resolve it.
I was not able to isolate it any further yet.

This worked for me, although I did have to reconfigure my custom profile settings.

**Comment by DangerOnTheRanger** [comment]
Also a problem for me on Debian Bullseye with Firefox 76.0.1. I'd really rather not wipe my customizations if possible - does anyone know if downgrading Firefox solves the issue?

**Comment by irvinm** [comment]
Guys, just curious, but if you had something else in the sidebar does F1 still work?  (Bookmarks, history, etc.)

**Comment by piroor** [comment]
TST's shortcuts can be cleared accidentally sometimes. Please check the list of shortcuts at the add-ons manager (the gear button => Manage Extension Shortcuts) and set shortcuts manually if they are blank.
![(screenshot)](https://user-images.githubusercontent.com/70062/83340976-47109380-a319-11ea-9dd5-2cf606c99825.png)

I think this problem is caused from a hack for the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1475043 . Firefox 73 and olders disallow an addon to unset default shortcuts defined in the manifest.json, so TST doesn't define any default shortcut and initializes them as user-defined shortcuts on the initial startup time. But such user-defined shortcuts are sometimes lost accidentally on my environment, especially after trying uninstallation and installation again and again.

Currently Firefox ESR68 is still alive so I cannot remove the hack. After Firefox ESR78 is released I'll redefine default shortcuts statically, so such an accidental unassignment of default shortcuts will disappear.

**Comment by SebiderSushi** [comment]
Thank you for this wordy and in-depth insight!

**Comment by thomastoye** [comment]
I can close TST with `F1` but not open it again when it's closed. 78.0.1 (64-bit) on Ubuntu. The shortcut is still set. Opening history then pressing `F1` does not work. Setting the shortcut to something else does not work either.

![image](https://user-images.githubusercontent.com/3396772/87057176-d78a9f80-c206-11ea-824a-79441680265f.png)

**Comment by piroor** [comment]
Because Firefox ESR78 has been released, I've removed hacks around keyboard shortcuts with the commit 1207f34, so now default shortcuts are defined in the manifest.json statically. I hope it reduces unexpected clearing of default shortcuts...

@thomastoye TST toggles the sidebar based on the tracked status, so if the internal status is still "open" after you close the sidebar, the F1 key won't open the sidebar. This sometimes happens because TST sometimes fails to track current open state of the sidebar. On such situations reloading of TST (disabling and re-enabling) possibly fixes the problem. Could you try that?

**Comment by thomastoye** [comment]
@piroor Looks like that works, thanks!

**Comment by irvinm** [comment]
@eriknelson is there any reason to keep this open at this point?  If not, will you close it?
