### ISSUE TITLE
Consider preference for max number of tabs to confirm autogrouping

### ISSUE THREAD

**Issue by joshgold22** [piroor/treestyletab#2596]
I like the auto-grouping preference and having the confirmation to choose grouped or flat, but I never want it grouped when it's a very large number, such as when restoring a session.  Consider an additional preference to skip autogrouping (and the confirmation) when opening greater than a selected # tabs.  (This might be a very niche desire on my part.)

**Comment by piroor** [comment]
I agree the necessity of something mechanism to reduce unwanted auto-grouping, but I'm negative to add this option because it won't help people who frequently open large number of multiple tabs from both session restoration and other cases especially bookmarks.

Originally old XUL-based versions TST could group tabs from bookmark folders via middle click effectively, but I gave up to migrate the behavior to WebExtensions-based version because Firefox doesn't provide ability for addons to know a new tab is opened from a bookmark or not. Sadly [the "auto_bookmark" transition type is still not supported yet.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/transitionType) The timer-based current implementation (grouping of new tabs opened while 300 msec by default) was introduced just as a workaround for this case. 

When I decided to implement the workaround behavior, TST didn't have a custom context menu command "Open All as Tree" for bookmark folders. But now it is there, so now you can open a bookmark folder with a group tab with the command manually. If the original motivation of the auto-grouping is satisfied with the manual operation, it may be the time to deprecate the auto-grouping feature. How do you think about the idea?

**Comment by piroor** [comment]
> it may be the time to deprecate the auto-grouping feature.

Of course there is a choice that disabling the auto-grouping feature by default instead of removing.

**Comment by piroor** [comment]
I've done some experiments to detect tabs are opened from bookmarks or not, but finally I give up that. I've wrote why my experiments failed at comments in the commit 6de0625.

**Comment by piroor** [comment]
Second try: with the commit a0940cc I've introduced a new behavior.

* When multiple tabs are opened within 100 msec (by default) and 50% or more of them are successfully detected as "opened from bookmarks in the common parent folder", they are automatically grouped without confirmation.
* Otherwise tabs won't be grouped by default. (But you still can activate auto grouping for this case.)

I think this new behavior should reduce annoying unwanted auto-grouping (and confirmation) intelligently.

**Comment by piroor** [comment]
Renewed option
![image](https://user-images.githubusercontent.com/70062/83367380-36cae800-a3ef-11ea-81d0-bc2ca762b764.png)
Hover
![image](https://user-images.githubusercontent.com/70062/83367416-57933d80-a3ef-11ea-9da8-409d9a2a4bb3.png)
Unlocked expert options
![image](https://user-images.githubusercontent.com/70062/83367426-64179600-a3ef-11ea-9803-bc5fa059138d.png)

**Comment by irvinm** [comment]
@joshgold22 could you check with the new version if we can close this item or if there is more to discuss?

**Comment by joshgold22** [comment]
I haven't had a chance to test my own case yet — But am I right (reading above) that the change you made depends on checking bookmark folders, so it would not change the behavior for "restore session"?

I've learned more about why this is hard, and if this is simply "hard to fix" it might not be worth it for my case.

**Comment by piroor** [comment]
@joshgold22 Tabs opened by the "restore session" feature won't be grouped anymore by default, with the new behavior.

I thought that you were suffered from annoying auto-grouping for unnecessary cases including "restore session". The introduced change clearly aims to solve that. I agree that everything details of this behavior are quite different from your proposal, but I think it should help you, if my understanding about the root problem on your case is correct.

However, if my understanding is totally wrong and you really need to control the auto-grouping behavior based on the number of opened tabs, the change won't help you. To be honest I couldn't imagine the reason why you need such a control, except avoiding of unnecessary auto-grouping for new tabs opened from any sources not a bookmark folder.

**Comment by joshgold22** [comment]
I'm sorry, I was focused on the 2nd change and didn't see that you'd already excluded Restore Session from grouping.  If that's the case then no, I definitely would not need to have a fixed-number cutoff or any other help from preferences.

**Comment by joshgold22** [comment]
Dear Yuki,

It was just crossing my mind how much of a help TST is for me, really every day  I just wanted to send you my appreciation for all your work on it!

Thanks!
  -Josh G.

**Comment by joshgold22** [comment]
Is it possible to make Add To Pocket work with MTH, to add many pages to Pocket at once?

I believe this would depend on Firefox changing how Pocket works, rather than a change to MTH, so I didn't file it as an issue yet, but perhaps there's some way to ask for the needed change from Firefox.


 -Josh G.

**Comment by piroor** [comment]
I won't add the command as a built-in feature, instead I think it should be done by a separate addon for the purpose because it will be useful for all people who use mutiselected tabs whether they use MTH or not. 

Sorry but I don't know such an addon exists or not. If it exists and incompatible to MTH I'll fix the problem.
