### ISSUE TITLE
[Feature] Hidden Tabs on Top?

### ISSUE THREAD

**Issue by APerson4645** [piroor/treestyletab#2603]
I was wondering if we could get hidden tabs on the top bar when you close a folder? For example, [this extension](https://addons.mozilla.org/en-US/firefox/addon/hide-tab/?src=search) uses `extensions.webextensions.tabhide.enabled` to hide tabs, if we could get that feature to hide tabs when the folder they're associated with is closed in Tree Style Tab I feel it would be a nice little feature and allow for better apperance.

**Comment by piroor** [comment]
Sorry, I couldn't understand what is the point. Could you describe the expected behavior with the form "Steps to reproduce, Actual result, and Expected result" in the [issue template](https://github.com/piroor/treestyletab/blob/master/ISSUE_TEMPLATE.md)? If you have some screenshots they may help my understanding.

**Comment by APerson4645** [comment]
> 
> 
> Sorry, I couldn't understand what is the point. Could you describe the expected behavior with the form "Steps to reproduce, Actual result, and Expected result" in the [issue template](https://github.com/piroor/treestyletab/blob/master/ISSUE_TEMPLATE.md)? If you have some screenshots they may help my understanding.

I may have not correctly explained this. I was hoping that we could get a feature for this extension to work with tab hiding extensions such as the one linked above. Like, if you collapse a tree you can press a button in context menu such as one in the extension above to hide all the tabs in that tree.
