### ISSUE TITLE
Tree Style Tab in Separate Sidebar?

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2617]
I have several Add-ons that also use the Sidebar (e.g. RSS reader Sage-like; https://addons.mozilla.org/en-US/firefox/addon/sage-like/).
However, I still need to use TST with these Add-ons. Can TST use its own sidebar somehow?

**Comment by piroor** [comment]
It is currently impossible. Until [the bug 1328776 (Provide ability to show multiple sidebar contents parallelly)](https://bugzilla.mozilla.org/show_bug.cgi?id=1328776) become fixed TST cannot appear with other sidebar addons.

Some hints:

* [TST Bookmarks subpanel](https://addons.mozilla.org/firefox/addon/tst-bookmarks-subpanel/) based on [the Subpanel API of TST itself](https://github.com/piroor/treestyletab/wiki/SubPanel-API) is available to show small "Bookmarks" sidebar panel below TST's tabs.
* [Aggregate Tabs to Main Window](https://addons.mozilla.org/firefox/addon/aggregate-tabs-to-main-window/) helps you to use Firefox's multiple windows for each purpose: "an window for a sidebar panel" and "an window for browsing tabs".

**Comment by viking2** [comment]
Can the "TST Bookmarks subpanel" only show the Bookmarks as a subpanel? I now have the RSS in the Sidebar and would like that one as a subpanel instead. 

I will try "Aggregate Tabs to Main Window".

I also found this Add-on that creates a separate window for TST: 
https://addons.mozilla.org/en-US/firefox/addon/tst-in-separate-window/
That seems to work OK (it has very few reviews).
EDIT: tst-in-separate-window doesn't work properly. The Tabs are not updated :-(

**Comment by piroor** [comment]
> Can the "TST Bookmarks subpanel" only show the Bookmarks as a subpanel? I now have the RSS in the Sidebar and would like that one as a subpanel instead.

It just supports regular bookmarks (and only http/https URLs are loadable due to restrictions of WebExtensions API.) It contains no RSS support - it just opens the feed URL itself.

The addon was originally made as a demonstration of the Subpanel API. Currently there is no other subpanel addon I made because I personally don't have motivation to use other type sidebar panels together with TST. (Sometimes I use the "History" sidebar panel but it is rare case and I'm not stressed from switching between those sidebar panels.) If you seriously need something subpanel, I hope that you'll become an addon developer for yourself. In old days I originally started to develop addons just for myself, and I still believe that a private demand makes his/her product better and long live.

> tst-in-separate-window doesn't work properly

If you can narrow down the conditions to reproduce the problem with 100% probability, a detailed report will help the developer: https://github.com/Lej77/tree-style-tab-in-separate-window/issues

**Comment by viking2** [comment]
Maybe the tst-in-separate-window (TSTSW) issues are due to poor communication with TST. I post my issues here first. I created a new FF (v77) profile with only TST & TSTSW. 
1. When I click on the TSTSW I get a message that TST's ID cannot be determined:
![](https://i.gyazo.com/f46700d21db0e5ac3225ef500b09ed4d.png)
2. However, I have granted access in TST:
![](https://i.gyazo.com/cf6459ecff2aa5e770c3930155c60826.png)
3. I always have to force an update in TSTSW:
![](https://i.gyazo.com/8042c053dbcf08995ac3d4143cb4b8f7.png)
4. After this, I can open the TSTSW. However:
a. A separate tab is opened in TST (only) with the internal ID. Is that by design?
b. If I open new tabs in TST, they only show up in TSTSW (& FF top Tabs) but not in TST.  That is not what I had expected (I had expected the tabs to show in both TST & TSTSW):
![](https://i.gyazo.com/c41edb63d443250da546e74002fb39c2.png)

UPDATE 1: I forgot to mention that I am using WIN7(64-bit). 
I now also installed TST & TSTSW on a different WIN7(32-bit) PC, and I had the same issues. 
Firefox: v77.0.1
TST v3.5.5
tree-style-tab-in-separate-window v4.2

UPDATE 2: I now tried it on a 3rd PC running WIN10(64-bit) and had the same issues.

I have now also posted these issues (with more updates) at https://github.com/Lej77/tree-style-tab-in-separate-window/issues
I am beginning to believe that TSTSW is not able to synchronize the tabs between TST and TSTSW

**Comment by viking2** [comment]
I am closing this issue now, but see the follow up in a new issue here:
https://github.com/piroor/treestyletab/issues/2619

**Comment by Lej77** [comment]
My [`Tree Style Tab in Separate Window`](https://addons.mozilla.org/firefox/addon/tst-in-separate-window/) extension mostly provides a simple way to open Tree Style Tab's sidebar page (`moz-extension://some-unqiue-id/sidebar/sidebar.html`) in a new window. It also has some functionality (not very well tested since I don't use it much myself) for docking the opened window to the controlled window. 

When I first made the extension (at the end of 2018) I think that multiple sidebar pages could be open and all would be updated. However with the current Tree Style Tab version (and many previous ones) this no longer works and as soon as a new sidebar page is opened then all other such pages (including the one in Firefox's sidebar) that track the same window stops updating. I don't know if this is a use case that should be supported (it is really a hack and depends on implementation details of Tree Style Tab) but hopefully it is understandable why it currently doesn't work.
