### ISSUE TITLE
Firefox high CPU usage

### ISSUE THREAD

**Issue by ssc41** [piroor/treestyletab#2621]
## Short description
When I try and attach a file in Yahoo mail or login to my router, firefox locks up and a single thread maxes out. Both of these thing open a new window in the browser.

## Steps to reproduce

Using Firefox as normal and when I either try and attache a file in yahoo mail or login to my router, firfox locks up.

I know its something to do with this addon as I disabled everything but Tree Style tab and it still happened. The moment I disabled it it worked perfectly. I will try and get some screen shots.

## Expected result

Able to use the new windows that is opened

## Actual result

firefox locks up and a single thread maxes out

## Environment

 * Platform (OS): Windows 10 
 * Version of Firefox: 77.0.1 (54 bit)
 * Version (or revision) of Tree Style Tab: 3.5.5 (2020.6.6):

**Comment by Githubwoman** [comment]
Can you specify what kind of file do you want to attach (doc, txt, zip, etc.)?
Which CPU is in your PC?

I can't reproduce this issue but I can tell that on Intel Pentium N3450 (4 core atom), yahoo mail page is heavy burden.

Can you open about:performance tab before that grind and check what causes highest power usage?

Hint: I disabled cache in TST (option->advanced: optimize tree restoration with cache) because from my experience this can cause high memory usage and also on my low end CPU TST seems to be slower than without it.

**Comment by Githubwoman** [comment]
> Both of these thing open a new window in the browser.


That's rather interesting. I've encountered similar heavy load scenarios when I accidentally moved whole big tree (200+ tabs) to another window. You can do that by just dragging "parent" tab out of the side panel. I also "disabled" that feature in options-> drag and drop and switched drag to only move tree tabs inside one window.

**Comment by ssc41** [comment]
Got a Ryzen 2600x with 32Gb of memory so it should handle this with no problem. The reason I closed this was I closed a copule of tabs and it started working again, maybe related to the number of tabs open.

**Comment by piroor** [comment]
Is this mistakenly closed?
A performance profile can become a hint to detect the bottle neck.
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-collect-a-performance-profile

**Comment by ssc41** [comment]
I just thought it was a rogue tab, maybe there is an underlying performance issue.

**Comment by Githubwoman** [comment]
> A performance profile can become a hint to detect the bottle neck.

I'm almost sure that it isn't TST performance bottleneck. When I move tree tab between windows they seems to be reloaded. When you have something like 200 tabs that will take a tall from small CPU :).

That's why I was suggesting to ssc41 that maybe he accidentally moved such a tree of tabs (there were a mention about opening new browser window). Then I connected that to "fantom drag" which you mentioned on another thread more than half a year ago. In default configuration of TST dragging parent tab out of the sidebar will initiate that behavior. Which makes it easy to do so accidentally without even understanding why that happened.

**Comment by ssc41** [comment]
Attached a performance profile that I got while having the problem. Not a major hang but certainly took a time to get responsive again.

[profile.zip](https://github.com/piroor/treestyletab/files/4842217/profile.zip)

**Comment by irvinm** [comment]
@ssc41 just curious but are you seeing the same performance issues with 3.5.12?  Obviously there have been a fair number of changes since 3.5.5.

**Comment by ssc41** [comment]
> 
> 
> @ssc41 just curious but are you seeing the same performance issues with 3.5.12? Obviously there have been a fair number of changes since 3.5.5.

No it has been alot better recently. I will close this issue for now.
