### ISSUE TITLE
Pinned tabs don't have close button

### ISSUE THREAD

**Issue by mwoffenden** [piroor/treestyletab#2625]
## Short description

Any way to add the close button to pinned tabs?

## Environment

 * Platform (OS): MACOS 10.15.5
 * Version of Firefox: 77.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.5.5

**Comment by irvinm** [comment]
You can certainly use CSS to show the close button on pinned tabs, but you will also have to play with how the dimensions are done with pinned tabs in order to create some width for the buttons.  You will probably want to look over base.css and search for "pinned" as a starting point.

The two easiest ways without any changes, I know of, to close a pinned tab is to (1) right-click on the tab and select "Close Tab" or (2) unpin and close normally.

**Comment by mwoffenden** [comment]
Hoping to see this as a feature in a future release.  I do a lot of pinning and the (X) close button would be very nice.

**Comment by irvinm** [comment]
@mwoffenden of course ... I'll let @piroor comment if he wants to do that or not.  Thanks.

**Comment by piroor** [comment]
I won't add this feature natively because Firefox's native pinned tabs also doesn't provide such a feature, but you can reactivate the closebox for pinned tabs in TST's sidebar via a custom style rule like following:

```css
tab-item.pinned:hover tab-closebox {
  display: inline-block;
  margin: 0;
  padding: 0;
  position: absolute;
  right: 0;
  top: 0;
}
```

This example shows the closebox at the top-right edge of each pinned tab, only when the tab is hovered.

**Comment by piroor** [comment]
I've added it to the snippets: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-closebox-for-pinned-tabs-2625

**Comment by mwoffenden** [comment]
Works great!
