### ISSUE TITLE
Unread Tab in Legacy TST?

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2628]
The webextension version of TST has the option to add style rules.  For example, I use "Show title of unread tabs with red and italic font "

I  need to use the legacy version of TST with Waterfox. Is there any way to also "Show title of unread tabs with red and italic font " in this case?

I tried  the "Tab flip for Tree Style Tab " (https://addons.mozilla.org/en-US/firefox/addon/tab-flip-for-tree-style-tab/) with the legacy TST but it didn't work. I guess that this add-on only works webextension version of TST?

**Comment by piroor** [comment]
TST for legacy Firefox is not maintained by me anymore. There are some forks (for example https://github.com/Ulf3000/treestyletab ) and I guess Reddit or somewhere community of Waterfox users is better place to get support.

> I tried the "Tab flip for Tree Style Tab " (https://addons.mozilla.org/en-US/firefox/addon/tab-flip-for-tree-style-tab/) with the legacy TST but it didn't work. I guess that this add-on only works webextension version of TST?

It is not compatible to legacy TST, because the helper addon is made on the API initially implemented at WebExtensions TST.
