### ISSUE TITLE
Feature Request: Save/Open Extra Styles Rules in Separate Text File (& link to Separate Editor) 

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2641]
Can I post feature requests here?

The Extra Styles Rules Text field is small and difficult to navigate with many rules.

It would be helpful to be able to save and load the Extra Styles Rules from a separate text file.  
The file could then also be opened in a Separate Editor (e.g. Notepad++).  Editor path would be set in TST options.

**Comment by piroor** [comment]
It is quite out of purpose of this project. Sorry but I won't add this feature as a built-in of TST.

However I've been interested about possibility to do that via other addons, I've researched about two addons providing ability to edit textarea with external editors:

* [Browser's external editor](https://addons.mozilla.org/firefox/addon/external-editor/)
* [withExEditor](https://addons.mozilla.org/firefox/addon/withexeditor/)

After trying I realized that sadly both they don't work for options page of addons including TST's one, due to restrictions of WebExtensions API. I think that new WebExtensions API is required to do that, otherwise TST need to communicate those addons via their APIs - but currently they don't provide such ability.

**Comment by piroor** [comment]
After more studying I've realized that your original request can't be implemented but I decided to add import/export feature for CSS files.

First, we need to remind that there is a fatal restriction: an addon cannot call external text editor directly. We need to use a [native messaging host](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) to do that, it need to be installed as a native application and registered to the platform (e.g. Windows' registry). Due to security reasons, existing native messaging hosts are strongly bound to their owner addons, so TST can't recycle them. Instead we need to develop our custom native messaging host and distribute it for each platform - Windows, Linux and macOS. It costs too expensive for just an option of TST.

Proposal of API to open external text editor from TST for existing addons like Bee is the second option, but I don't have enough high motivation to request such an idea, because it will increase security risk on the provider addon.

The best option is adding new WebExtensions API to Firefox itself to allow such addons collaborate with TST without any special TST-specific codes. Currently external editor addons need to modify textarea in target documents via the API `menus.getTargetElement()`, but if there is any API like `menus.getTargetFieldValue()` and `menus.setTargetFieldValue()` such external editor addons will be available for any input fields including the one in TST's options page. But such a proposal will require more large number features to control input fields, especially rich text editor based on "contenteditable" HTML elements. Such a huge proposal will be rejected by Mozilla.

Import/export of CSS files can be implemented easily and it allows you to edit the file via your favorite text editor. Moreover I think it allows TST users to share their custom user styles with each other instantly.

**Comment by viking2** [comment]
Sounds good. I will wait for next version.

**Comment by irvinm** [comment]
@viking2 same with this item.  If ok, will you close this item?

**Comment by viking2** [comment]
This is a great new feature! The workflow could be:
1. Click "Save as File" to open with Note++ (for example).
2. Modify the treestyletab.css and save.
3. Open the modified file ("Load from File")
