### ISSUE TITLE
Adding dark mode for TST?

### ISSUE THREAD

**Issue by sblondon** [piroor/treestyletab#2654]
##  Short description

The colors used by TST do not change between light and dark modes. So there is a lighter block when TST is enabled on the dark mode (system and web pages).

I see two ways to implement it:
- included into TST: it would probably add a second style definition and use `prefers-color-scheme` CSS value to automatically select which mode has to be used.
  - pro: available to every users automatically
  - cons: could break add-ons relying on TST behaviour
- in another Firefox plugin: [tst-colored-tabs](https://addons.mozilla.org/fr/firefox/addon/tst-colored-tabs/) seems to be a good reference to implement the feature.
  - pro: no risks for other add-ons; lightly easier to implement
  - cons: probably less usage because users will ignore it exists

I'm interested to implement it. Which method do you prefer?

I already have a AMO account so I can upload it if you don't want to include it in TST.

## Environment

 * Platform (OS): Debian GNU/Linux 10 (buster)
 * Version of Firefox: 68.10.0esr
 * Version (or revision) of Tree Style Tab: 3.5.13 (2020.7.21)

**Comment by piroor** [comment]
TST already contains Dark mode support.
https://github.com/piroor/treestyletab/blob/trunk/webextensions/resources/ui-color.css#L191
It is disabled when TST respects the system color scheme, and the system color scheme config is active by default only on Linux, because "Dark mode" looks not major on Linux desktop environment. Instead TST respects colors defined in the theme when you switch GNOME themes. I think that Firefox has same policy - Firefox applies Photon color scheme on Windows and macOS but uses system colors for Linux.

You can disable this system color policy and apply "Dark mode" color on Linux. Please see TST options => Development => Color scheme => Photon.

**Comment by sblondon** [comment]
Thanks you for the detailed answer!

I use KDE with breeze dark theme. 
Firefox evaluates `prefers-color-scheme` as dark: opening this html code in Firefox shows a green background:
``` html
<html>
  <head>
    <style>
      @media (prefers-color-scheme: light) {
          body {
              background: orange;
          }
      }
      @media (prefers-color-scheme: dark) {
          body {
              background: green;
          }
      }
      @media (prefers-color-scheme: no-preference) {
          body {
              background: blue;
          }
      }
    </style>
  </head>
  <body></body>
<html>
```

In case it helps, the TST options panel has a dark background.

TST options => Development => Color scheme => system color is enabled.

The TST options shows that the Mixed theme is selected. (I never changed it previously.)

I guess dark mode should be enabled automatically.

When I change from Mixed theme to "Dark simple", TST change automatically to dark (and the reverse move works perfectly too).
When Mixed theme is enabled and Photon options are enabled, dark mode is displayed.

Did I miss something?
Could it be a mismatch between 'Photon' and 'system color' options?

**Comment by sblondon** [comment]
The [operating system detection](https://github.com/piroor/treestyletab/blob/ea6313945edfa053778c36fbe8f3f85514d9afa4/webextensions/common/common.js#L59) works properly. It returns `system-color`:

```javascript
/^Linux/i.test(navigator.platform) ? 'system-color' : 'photon'
```

**Comment by piroor** [comment]
I installed the package "kubuntu-desktop" to my Ubuntu VM and I've confirmed that Firefox doesn't respect KDE's theme colors.
![image](https://user-images.githubusercontent.com/70062/88194062-535e0080-cc79-11ea-82fb-e3259345c675.png)
In this screenshot I chose the "Breeze Dark" theme and Firefox's native UI doesn't respect the color scheme of the theme, because Firefox's GUI is basically rendered with GTK+.

And finally I've successfully activate the Dark color scheme on TST. Steps I did:

1. Open the KDE System Settings.
2. Choose the "Application Style".
3. Click the button "Configure GNOME/GTK Application Style".
4. Choose "Adwaita-dark", "Yaru-dark", or something Dark theme. (But the "Breeze-Dark" doesn't affect as expected.)
5. Start Firefox. Then you'll see dark colors on Firefox's native UI. TST's sidebar will be shown with light colors;
6. TST options => Development => Color scheme => Photon.

Then both Firefox's UI and TST's sidebar are rendered with Dark color schemes.
![image](https://user-images.githubusercontent.com/70062/88197429-712d6480-cc7d-11ea-8e64-28bd8cdcb12f.png)

**Comment by sblondon** [comment]
Adwaita is a Gnome theme and Breeze is a KDE theme. The KDE on GTK rendering is probably the root of the behaviour difference.

This is a screenshot of what I get with Breeze-dark, Mixed theme in TST and system color scheme in TST:
![dark_mode_tree_style_tab](https://user-images.githubusercontent.com/1708780/88292103-7a5c1700-ccf9-11ea-8412-5e21e72d16f1.png)

I think this issue can be closed and I will see in Firefox bugzilla if there is a known issue between KDE theme rendering in Firefox. I should try with Aurora too to see if the bug is reproducible with lastest version of the browser.

**Comment by piroor** [comment]
Thank you for researching! Hmm, in old days I researched about theme implementation of Firefox itself, and I realized that Firefox uses Photon colors on Windows and macOS but uses system colors only on Linux. But now I've research and realized again that most colors are dynamically calculated on all platforms:

https://searchfox.org/mozilla-central/search?q=path%3Athemes+prefers-color-scheme&path=&case=false&regexp=false
https://searchfox.org/mozilla-central/source/browser/modules/ThemeVariableMap.jsm#55
https://searchfox.org/mozilla-central/source/toolkit/modules/LightweightThemeConsumer.jsm#301

Those colors are also notified to addons, and TST uses it only when the color mode is "photon". Now it looks the time to change the default configuration on Linux...

**Comment by piroor** [comment]
With recent commits I've removed some options about theme. It was too chaotic from combinations of options - system color support ON/OFF and browser theme support ON/OFF. Now TST supports only the Photon color scheme and always applies the browser theme (on Mixed, Pain, and Vertigo).
