### ISSUE TITLE
Sidebar's tree randomly becomes blank. Need to restart firefox to fix the bug.

### ISSUE THREAD

**Issue by jarredou** [piroor/treestyletab#2660]
## Short description
Since few weeks, Tree Style Tab sidebar becomes blank even if tabs are opened. Sometimes it happens when opening a new tab, sometimes there's no apparent reason. Closing sidebar, or switching to "bookmarks" or "history" and opening back Tree style tab sidebar doesn't not fix the issue, I need to restart firefox.

## Steps to reproduce
Sometimes it happens when opening a new tab, sometimes there's no apparent reason

## Environment
Windows 7 64 bits / Firefox Developer 80.0b1 (64 bits)
TST version 3.5.13

**Comment by irvinm** [comment]
Maybe similar or a duplicate of https://github.com/piroor/treestyletab/issues/2272?

@jarredou do you have any means to reproduce this consistently?

**Comment by jarredou** [comment]
It doesn't seem to be a duplicate  of #2272 as TST's tree only disapears but doesn't load anything back. It just disapears and never come back while you don't restart Firefox. After restarting Firefox, the tree's structure is ok, even if some tree's subfolders/tab groups are shown as "expanded" but are collapsed. I need to click on "expand all tabs" then "collapse all tabs" options to get it right, but the structure itself is intact.

I'll need more time (I'm on holidays) to find a way to reproduce it consistently.

**Comment by piroor** [comment]
Could you try reloading of TST instead of restarting of Firefox? On the add-ons manager, disable TST and re-enable it again immediately, then TST is reloaded. If TST works again after the operation, the problem happened in TST and it should be fixed by me. On the other hand, if TST's sidebar is still blank after the operation, the process of Firefox for extensions has crashed and you really need to restart Firefox itself.

**Comment by jarredou** [comment]
Ok ! I'll try that next time the bug occurs.

**Comment by alistairpullen** [comment]
I have this problem several times daily and it has been happening for many many many months. Highly annoying.
Firefox 78.4.0esr (64-bit)

To recover, I used to close Firefox and re-open, then restore previous session.

However after finding this Issue here on Github; I tried reloading of TST via the add-ons manager instead of restarting of Firefox and TST is reloaded perfectly fine. Until next time it happens, rinse and repeat.

Interesting thing, while the issue is occurring, the TST toggle button at the top right of browser is non responsive.

Back to you piroor :)

**Comment by irvinm** [comment]
@jarredou any updates?

**Comment by jarredou** [comment]
Never happened again since my last message...

**Comment by irvinm** [comment]
@alistairpullen I know it has only been a few weeks, but is this still occurring for you?

**Comment by melleran** [comment]
I have this problem too since a week or two. Possibly since the last TST update. Reactivating the plugin via add-on manager helps.

**Comment by alistairpullen** [comment]
> 
> 
> @alistairpullen I know it has only been a few weeks, but is this still occurring for you?

I have been away for 2 weeks and returned today. It didnt happen today at least. I noticed other plugins are broken at the same time, so might not be TST.

**Comment by irvinm** [comment]
@piroor it seems for most people when they see this issue that simply restarting TST works for them.  What else would you need to possibly try to isolate what is happening?

**Comment by silverwings15** [comment]
i've never gotten this error, perhaps it could be an addon conflict?

**Comment by silverwings15** [comment]
hmm so it happened to me for the first time ever, although a quick F1 toggle got it working again

![image](https://user-images.githubusercontent.com/10742312/103144356-d587af00-475a-11eb-9847-6c2115126547.png)

**Comment by mYnDstrEAm** [comment]
Same or something similar here: it sometimes just suddenly stops displaying the tabs and becomes blank. This time it's flickering and starting to load for about 0.2 seconds just to become blank again and flicker. It could also be a separate problem. When closing the sidebar I can't open the sidebar again by pressing the TreeStyleTab addon icon (in the upper right) - I need to display bookmarks for example and then switch to TreeStyleTab. It didn't recently update. Maybe this is a separate issue - how can I get more info about what caused this? Edit: maybe it's related to the addon "NoScript" which also stopped working.

It wouldn't be a big problem to restart Firefox to fix this if TST was restoring the tree structures (created a separate issues for that) - but as of right now it doesn't so whenever this happens most tree structures are lost.

**Comment by piroor** [comment]
I've seen this problem while I'm researching the issue #2774. On my case, just closing and reopening the TST sidebar solves the invalidly blanked sidebar problem. It looks that TST's background process looks to track all changes around tabs successfully but the sidebar page looks to fail to synchronize its contents. (Reopening the sidebar panel is the most effective workaround for such cases.)

**Comment by piroor** [comment]
I think that something happens at [the receiver module in the sidebar page](https://github.com/piroor/treestyletab/blob/af4a46c08dbb9c3970a4b30cbb025aa30f09ff6b/webextensions/sidebar/sidebar-tabs.js#L452): it looks to drop some critical messages when there are very large number in-progress opening tabs.

However I've not narrowed down the condition successfully yet. When I tried with 267 tabs with real URLs for the Web the problem happend, but 267 tabs with an unaccessible URL `http://localhost/` (because there is no running HTTP server on my localhost) the problem didn't happen. There look to be more mixed triggers - for example `tabs.onUpdated` notifications around loading pages.

It means that debugging of this problem is very hard. Sadly I have very limited motivation about this topic, because ordinaly I don't open such very large number of tabs at a time on my usage, and there is an effective workaround: reopening the sidebar. So I won't fix this by myself, sorry. TST may need a patch written by someone who really suffered from this problem...

**Comment by mYnDstrEAm** [comment]
In my case reopening the TST sidebar doesn't solve the blanked sidebar problem - it will still flicker / be empty / don't complete loading. This is one of the cases where I have to restart firefox and upon doing so most tree structures are lost.
Nice to see you could find some problems! I probably wouldn't even have commented if there was a workaround. I can believe you that debugging this is hard - can't know that beforehand and it's probably much harder for people without in-depth knowledge of the code. But maybe I'll be able to dive deeper into this next time this occurs. Maybe it was a problem with an addon; I think I got similar problems whenever TST updated earlier but this doesn't occur during updates anymore.

**Comment by silverwings15** [comment]
this bug destroys your tree structure upon reset? that sounds really severe. even though reopening the TST bar doesn't fix the issue in OP's case, at least his tree structures are still intact

**Comment by piroor** [comment]
@mimecry The case I saw was a problem only on the sidebar module. The background module was still running and the sidebar content was reconstructed correctly after reopening the sidebar, for me. Moreover, even if the running background process becomes corrupted, the tree structure possibly can be restored after restarting, based on the information stored to the Firefox's built-in session data.

**Comment by irvinm** [comment]
Just checking in with everyone to see if people are still experiencing this situation and if there are any new observations.

**Comment by wsmwk** [comment]
I have seen this. But I do not have any data.  For me, does not require restarting Firefox

**Comment by grahamperrin** [comment]
Occasionally comparable symptoms when, for example, restoring a session of around 1,400 tabs with umpteen other extensions enabled whilst the computer is unusually busy with other things (consistently high disk/file system I/O for an extended period). 

Maybe comparable only in the blankness, which, if I recall correctly, occurs after disappearance of the side-to-side asynchronous progress indicator. For me: in most or all such cases, the blankness ends after a waiting period. 

I have a vaguer recollection of blankness occurring _rarely_ during a session (after a successful start). This probably occurs only when the computer is extraordinarily busy with other things. It's even rarer for the sidebar to not repopulate after a waiting period … maybe two or three times in the past six months. 

KDE Plasma, FreeBSD-CURRENT.

**Comment by irvinm** [comment]
@piroor is there anything you want to do with this one?

**Comment by irvinm** [comment]
@piroor just a friendly reminder on this one.

**Comment by piroor** [comment]
I can do nothing for now until more certain conditions are found...
