### ISSUE TITLE
When close current tab, treestyletab always switches back to its parent tab.

### ISSUE THREAD

**Issue by sudoyang** [piroor/treestyletab#2680]
Is it possible to ask treestyletab switches to its neighbour tab?

## Environment

 * Platform (OS):  Ubuntu 20.04
 * Version of Firefox: 79
 * Version (or revision) of Tree Style Tab: 3.5.19 (2020.8.4)

**Comment by piroor** [comment]
I think it is the effect of the option: TST Options => "Tree Behavior" => "When the current tab is closed as a last child" => "Move focus back to the opener tab if possible, when the current tab is closed". It aims to simulate Firefox's built-in behavior about the option `browser.tabs.selectOwnerOnClose`.

Currently I have no plan to add a confirmation dialog to choose the action on the fly, because it may happen too frequently and it may be annoying.

**Comment by sudoyang** [comment]
I am looking for the firefox default behaviour and this is just what I need. Thanks for the information.
