### ISSUE TITLE
"Save as File" treestyletab.css sets it as Read-Only

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2681]
I want to load the treestyletab.css in my editor (Notepad ++) and therefore select "Save as File" followed by "Open with Notapad++". 

The file is then saved at this path:
C:\Users\XXXX\AppData\Local\Temp\treestyletab.css
and it opens with Notepad++. 

However, the file is then set as Read-Only and I need deselect the Read-Only file attribute (using my file manager) to be able to edit the file.

Is the Read-Only attribute set by TST? How can it be avoided?

**Comment by piroor** [comment]
This doesn't happen on my Windows 10 + Firefox 79 + TST 3.5.20. TST just triggers a click on a link to download the generated file and never (and impossible) touches to the real file.

I've seen that the saved file is flagged as "downloaded from other computers" by Firefox. I think something security software on your system can flag it as read-only the file based on special rules.

**Comment by viking2** [comment]
If I instead save the file ("Save File") instead of "Open with Notepad++" (to the same path C:\Users\XXXX\AppData\Local\Temp\treestyletab.css in both cases), the Read-Only attribute is not set.
The  Read-Only attribute is only set when opening the file (with Notepad++ or just Notepad).

I am using WIN7 (64 bit), FF 78.0.2 (64 bit) and TST 3.5.19.

p.s. This didn't happen with an earlier version of TST (not sure which one, but the 1st version where the Save feature was implemented)

**Comment by piroor** [comment]
> If I instead save the file ("Save File") instead of "Open with Notepad++" (to the same path C:\Users\XXXX\AppData\Local\Temp\treestyletab.css in both cases), the Read-Only attribute is not set.


Oops, sorry I missed the point. It is clearly done by Firefox. Firefox disallows to overwrite the downloaded file while the helper application is running , because Firefox removes such a temporary file after the helper application exists and your saved change will be lost. This is a mechanism to avoid data loss.

You can deactivate this safe net: go to `about:config` and turn `browser.helperApps.deleteTempFileOnExit` to false. But you should pay attention that downloaded files won't be cleared automatically anymore and you need to cleanup the temporary directory periodically by yourself.

**Comment by viking2** [comment]
So it could not have been possible to "Open with Notepad++" w/o setting the Read-Only attribute in an earlier version of TST?
I assume that you meant "Firefox removes such a temporary file after the helper application _**exits**_". Is TST =helper application? When does it exit? When Firefox is closed?

Is there some way to have TST simultaneously save and open treestyletab.css in a different (user defined) location?

Otherwise, I guess that there is no way to change the Firefox configuration to turn browser.helperApps.deleteTempFileOnExit to false only for TST...?

**Comment by piroor** [comment]
>  I assume that you meant "Firefox removes such a temporary file after the helper application exits". Is TST =helper application? When does it exit? When Firefox is closed?

I meant Notepad++. Firefox waits until Nodepad++'s exit and removes the file after that.

> Otherwise, I guess that there is no way to change the Firefox configuration to turn browser.helperApps.deleteTempFileOnExit to false only for TST...?

WebExtensions API provides ability to override some Firefox options, but `browser.helperApps.deleteTempFileOnExit` is not allowed.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings

So the most easiest way to edit the file by an external editor is:

1. Export user styles as treestyletab.css to any location, instead of opening with the editor directly.
2. Open the file with the editor, edit it, and save changes.
3. Import treestyletab.css.

**Comment by viking2** [comment]
> 
> 
> So the most easiest way to edit the file by an external editor is:
> 
>     1. Export user styles as treestyletab.css to any location, instead of opening with the editor directly.
> 
>     2. Open the file with the editor, edit it, and save changes.
> 
>     3. Import treestyletab.css.

Actually, an easier/quicker way is:
1. Open treestyletab.css with the editor directly and save the file to a new location.
2. Edit the file and save changes.
3. Import treestyletab.css.
