### ISSUE TITLE
some bookmark folders open ungrouped

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2694]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. give it bookmark access, which enables grouping
    ![image](https://user-images.githubusercontent.com/895588/91516303-0fce6600-e8b9-11ea-99d7-faa5ea05ef16.png)
 4. show the bookmark bar
 5. create a new folder on it "New Folder"
 6. add two bookmarks to it
    1. https://support.mozilla.org/en-US/kb/get-started-firefox-overview-main-features
    2. https://www.mozilla.org/en-US/privacy/firefox/
 7. open all in tabs
 8. they open ungrouped
     ![image](https://user-images.githubusercontent.com/895588/91516000-71420500-e8b8-11ea-8bba-0b478c9626c7.png)

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 80.0.0 x64
 * Version (or revision) of Tree Style Tab: 3.5.23

**Comment by piroor** [comment]
Thanks, this should be fixed with the commit 5eda50ce9. TST tries to detect a tab opened from a bookmark based on the URL, and this method is based on a spec of Firefox's tab: a tab opened from a bookmark has the URL as its title. I knew the scheme part ("https://") is removed in the title but I didn't realized that the first "www." part of its hostname is also removed...

**Comment by piroor** [comment]
I close this because TST 3.5.31 is already available. (If you still see this problem, add comments please.)
