### ISSUE TITLE
[feature request] Ungrouping tabs

### ISSUE THREAD

**Issue by chronocide-commando** [piroor/treestyletab#2695]
Could you please add ungroup/unstack function, like in Opera 12 and Vivaldi? Currently there seems to be no way to ungroup grouped tabs other than dragging them out of group one by one.

This is useful for when you move a group to a separate window or simply have one last group remaining.

**Comment by piroor** [comment]
I've installed Vivaldi and tried to group/ungroup tabs but it looks not have a feature named "grouping of tabs". Did you talk about tab stacking instead? Does the term "ungrouping" mean canceling of tab stacking? If I misunderstood your idea please add comments...

**Comment by piroor** [comment]
I've added a command "Ungroup Tabs" experimentally with the commit 59b75c7. I hope it should work as you expected.

**Comment by chronocide-commando** [comment]
Specifically it's called "Unstack" in Opera 12 and "Ungroup tab stack" in Vivaldi, making all the tabs in a selected stack unstacked again.
"Ungroup tabs" in TST is greyed out for me for some reason, so it's probably for something else.

**Comment by piroor** [comment]
TST's command "Ungroup Tabs" is corresponding to another command "Group Tabs".  "Ungroup Tabs" is intentionally disabled for regular tree of tabs constructed from tabs opened with middle click on links, because they are not group of tabs constructed by the "Group Tabs" command.

Global "flatten tree" command is discussed at #2717, and I think it should be provided by a helper addon adding various commands to organize tree.

**Comment by irvinm** [comment]
@chronocide-commando this is now available with the helper addon.  Can you close this item?

**Comment by irvinm** [comment]
@piroor I think this can be closed.

**Comment by piroor** [comment]
Now a helper addon TST More Tree Commands containing both "ungroup" and "flatten tree" is available, and "ungroup" was removed from TST. I close this.
