### ISSUE TITLE
[Suggestion] Show/hide trees and tabs on tab bar

### ISSUE THREAD

**Issue by echeoquehaii** [piroor/treestyletab#2696]
Hello!

First of all thanks for this amazing addon, it has saved me a lot of times when having a lot of tabs open.
I have a suggestion though, I have checked all options and issues and I couldn't find an answer to this, sorry if I missed something and I am duplicating an issue.

I was looking for a way to kind of replicate the trees structure of TST on the tab bar at the top of the browser. What I mean is that I think it could be useful that if I hide a tree on TST the tabs in that tree would disappear from the tab bar, or would be hidden inside a single tab. In this way I could have a sort of different sessions to open whenever I need wihtout mixing the tabs on the tab bar. 
I don't know if I explained myslef clearly, and if this behaviour is already implemented in some way. If that's the case sorry!

**Comment by piroor** [comment]
There are some my past comments describing risks when TST hides tabs in Firefox's native tab bar:

https://github.com/piroor/treestyletab/issues/1831#issuecomment-373618534
https://github.com/piroor/treestyletab/issues/1371#issuecomment-491575613

In short: Tabs hidden when they are just collapsed will introduce compatibility issues with other tab addons and Firefox's native behavior (because hidden tabs are treated as unexisting by Firefox itself.) Thus I decided that I don't introduce this change.

**Comment by echeoquehaii** [comment]
> There are some my past comments describing risks when TST hides tabs in Firefox's native tab bar:
> 
> [#1831 (comment)](https://github.com/piroor/treestyletab/issues/1831#issuecomment-373618534)
> [#1371 (comment)](https://github.com/piroor/treestyletab/issues/1371#issuecomment-491575613)
> 
> In short: Tabs hidden when they are just collapsed will introduce compatibility issues with other tab addons and Firefox's native behavior (because hidden tabs are treated as unexisting by Firefox itself.) Thus I decided that I don't introduce this change.

Ok, I understand your point, even if I think it could be a nice addition. Thank you anyway for your reply!
