### ISSUE TITLE
Optional Default to Sidebar Hidden

### ISSUE THREAD

**Issue by robertII** [piroor/treestyletab#2706]
TST has a button in the top toolbar to open and close the tab tree panel.
I'd like to have the panel start out closed, so I can open it when I want it.

I use a mixture of windows and tabs: I'll open some web pages as tabs alongside related ones, and others in separate windows so I can see them alongside one another.
My problem with TST is that all my windows have a great big tab tree down the side.
Even the ones that have only a single document (tab).

So I'd really like TST to start out closed when I open a new window.
   Possibly by means of a preference/setting.
   Just possibly because I opened my new window from one where TST was closed,
   Or possibly as standard behaviour in a window with just one tab/document.

Robert.

P.S What I'd REALLY like is to have TST running in a "separate window" controlling visibility/selection of my tabs across all my windows.  But I'm guessing that will be a fair bit harder...

**Comment by piroor** [comment]
Firefox is designed to restore last sidebar state, so if you close the sidebar before you close the last browser window, he first browser window will have a closed sidebar at the next startup. If you see opened sidebar on every startup even if you closed the sidebar, I think something wrong...

You can show TST's tabbar in a separate window with a helper addon Tree Style Tab in Separate Window https://addons.mozilla.org/firefox/addon/tst-in-separate-window/

**Comment by robertII** [comment]
Thanks for the prompt and helpful response.
  
> Firefox is designed to restore last sidebar state, so if you close the sidebar before you close the last browser window, he first browser window will have a closed sidebar at the next startup. 

Oh yes!  You are right!   

Now I know that, I guess it gives me a way to mostly sort my problem.

It's not ideal, though:  It's very subtle -- I'll bet a lot of people (most people?) won't know that.  And if ever I get it wrong -- if the last window to close when I exit Firefox has its sidebar open -- I'll have to go round every window to close its sidebar, and then re-start Firefox again...  Oh, and if follow a link from a window with a sidebar, the new window opens with a side bar...  So I'll have to keep thinking about what is going on...

> 
> You can show TST's tabbar in a separate window with a helper addon Tree Style Tab in Separate Window 

Yes, I've actually got that.
But the tree that opens only shows/controls the tabs in the window from which it was launched.
I'd like one tree to find/control every tab in EVERY window...

Anyway, keep up the good work...

**Comment by piroor** [comment]
Anyway, the last state of the sidebar is out of control from addons like TST. I think you need to request a new option to Firefox, to keep the sidebar closed on the startup.

>  I'd like one tree to find/control every tab in EVERY window...

TST is strongly designed as "per-window tree", so it can't be done on TST natively.

Just a workaround, you can place tabbar window at any position with TST in Separate Window options => "Docked Window Settings" => "Open beside current window" => uncheck "Create the new window beside the current window". So you can layout multiple tabbar windows like panes. For example:
![image](https://user-images.githubusercontent.com/70062/92010761-24ad6c80-ed85-11ea-93f4-deabaaf7e7e9.png)
It is not a regular usage of the addon so if you like I recommend you to report a feature request to it.

Or, something similar addon instead of TST may help you. Here are some lists of similar addons I know: https://github.com/piroor/treestyletab#similar-projects

**Comment by irvinm** [comment]
@piroor sounds like there isn't anything more to do with this one.  Can we close?

**Comment by piroor** [comment]
OK, I close this.
