### ISSUE TITLE
[feature request] Add "Flatten tree" menu option

### ISSUE THREAD

**Issue by I60R** [piroor/treestyletab#2717]
Add "flatten tree" menu option with "flatten tree recursively" action on middle click. This will be more convenient than dealing with tab multiselect and Drag and Drop to achieve the same result, especially when long or deeply nested trees are involved. 

It would be useful when you want to merge two trees, and in any scenario when tab hierarchy no more matters.

**Comment by Joduai** [comment]
I'm both hands for a way to flatten trees on already opened tabs.

It would be also great to get 3rd(?) option.
I found out in other issues how to make tabs tree completely flat - but it applies only to new tabs.
I'd like to have an option to set a 1lvl deep tree. Now opening child tabs still nest them until the amount set in options and we still get the arrow to collapse/expand them.  I'd like to just open all child tabs nested only to 2nd lvl either opened from parent tab, or other child tabs.
I hope I explained my request understandable.

**Comment by piroor** [comment]
I think this should be implemented by a helper addon providing utility commands for TST, instead of TST itself.

TST already has too many menu commands. I think that TST itself should provide only some essential commands and some commands should be moved to the helper addon, judged based on the usecase style.

![image](https://user-images.githubusercontent.com/70062/93224170-c8e2da80-f7ab-11ea-9879-7f3d629f1331.png)
I ordinarily use TST with deeply nested tree like this screenshot. So I hope to put commands for this usecase to TST itself. On the other hand, I don't flatten tree-ed tabs on my regular usage. I just use tree structure constructed by TST automatically, and it is rare case that I organize tree structure manually. Thus I hope to extract commands for grouping and tree organizing to the helper addon:

* Group selected tabs
* Ungroup tabs
* Flatten tree (the command proposed at this issue)

**Comment by piroor** [comment]
And some keyboard shortcut commands are also need to be extracted:

* Create new group from selected tabs
* Ungroup tabs
* Indent current tab
* Outdent current tab

**Comment by piroor** [comment]
I think this plan is reasonable and will be a good news for people who use TST with the grouping-based style. I rejected requests about grouping-based style commands for a long time, but the new helper addon will contain those commands.

The only one concern is: the helper addon won't be maintained by me aggressively. As I told above the grouping based usecase is quite different from my daily life, so I have less motivation to maintain the addon by me. After I successfully extract grouping features to the helper addon, I hope to delegate or concede administration permission of the addon to someone who seriously need it.

**Comment by piroor** [comment]
I've started to implement a helper addon I planned at here: TST More Tree Commands.
https://github.com/piroor/tst-more-tree-commands

**Comment by piroor** [comment]
Corresponding branch of TST: https://github.com/piroor/treestyletab/tree/separate-more-tree-commands

**Comment by piroor** [comment]
I've released the helper addon TST More Tree Commands.
https://addons.mozilla.org/firefox/addon/tst-more-tree-commands/

I'm finding the successor owner of the project. If you are interested, please contact me to take the ownership.
https://github.com/piroor/tst-more-tree-commands#authors-comment-from-piroor

**Comment by irvinm** [comment]
@I60R can you close this item as the new addon is now available?

**Comment by piroor** [comment]
Sorry my unclear indecisiveness. I close this by myself because this command never become a part of TST itself.
