### ISSUE TITLE
Opening Temporary Container Tabs from a Link Puts it at the Top of the Tree (Instead of at the Bottom)

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2720]
I have set TST to append new child tabs at the bottom of the tree. That works as expected. 
However, when I open a new Tab using the Temporary Container extension, it puts it at the top of the tree instead. I see no option in the Temporary Container extension to control the Tab position. Can this be controlled by TST?  

## Environment
 * Platform (OS): WIN7 (64 bit)
 * Version of Firefox: 80.0.1 (64 bit)
 * Version (or revision) of Tree Style Tab: 3.5.27
* Temporary Containers: https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/ (v.1.9.1)

**Comment by piroor** [comment]
I couldn't reproduce the problem. Steps I did:

1. Start Firefox 81.0 with clean profile.
2. Open any website in a tab. I used `https://piro.sakura.ne.jp/latest/`.
3. Install Tree Style Tab 3.5.27.
4. Install Temporary Containers 1.9.1.
5. Go to the options page of Temporary Containers, and turn on the checkbox "Automatic Mode".
6. Go to the tab opened at the step 2, and middle-click on some links to open new tabs with no container.
7. New tabs are opened at the bottom of the tree with no container, but reopened with temporary container automatically.

At the step 7, opened tabs are opened as last child of the active tab for me. Any difference about configurations of TST itself and Temporary Containers?

**Comment by viking2** [comment]
I reproduced what you wrote above except when I middle-click (on my mouse) a new temporary container opens. Why is that? 

The difference with our setups is otherwise that I don't use Automatic mode (it is unchecked)!
In this case, regular (non-container) tabs opens as children at the bottom of the tree, while container tabs open at the top of the tree (I select to open the Tab in a temporary container by right-clicking).

**Comment by piroor** [comment]
Ah, I got it. I didn't know how to open tabs in temporary containers without the automatic mode, and I finally understood that there is a context menu command "Open link in new Temporary Container tab". After I disabled the automatic mode and opened links from the command, I've successfully reproduced this problem.

**Comment by piroor** [comment]
I've looked the debug log. What happens when a new temporary container tab is opened from the context menu command is:

1. A new tab is opened with a container at the end of the tab bar without any opener information, by Temporary Containers.
2. The tab is moved next to the active tab by someone (maybe Temporary Containers).
3. TST detects the moved tab, and attach the tab to the existing tree based on the inserted position.
4. TST detects the newly opened tab but doesn't try to attach it to the active tab as its last child, because it was opened without any opener information.

On the other hand, if you middle-click on a link:

1. A new tab is opened at the next of the active tab with an opener information, by Firefox itself.
2. TST detects the newly opened tab and try to attach it to the active tab as its last child based on the opener information. (And the tab will appear as the last child of the tree.)

So I think Temporary Containers needs to specify the opener information for a new tab.

**Comment by piroor** [comment]
I've created a pull request to do that on Temporary Containers side.

**Comment by piroor** [comment]
The PR has been merged, so this issue will be fixed with the next release of Temporary Containers.

**Comment by viking2** [comment]
Great. Thanks!
I will close this after testing the new version of Temporary Containers.

**Comment by irvinm** [comment]
@viking2 has the new version been released?  Can you close this item if resolved?

**Comment by viking2** [comment]
@irvinm,
No, a new version has been released yet :-(.

**Comment by irvinm** [comment]
@stoically this pull request has been merged into Temporary Containers since October 9th.  Any chance you could produce a point release to verify this has been fixed?

**Comment by irvinm** [comment]
@viking2 may I suggest closing this item for now?  There isn't anything more that can be done on the TST side now and if the pull request doesn't fix the issue long term you can always reopen this issue.

**Comment by stoically** [comment]
@piroor  @irvinm Sorry for the delay, released TC 1.9.2, thanks for the PR!

**Comment by viking2** [comment]
Works now. Thanks!
