### ISSUE TITLE
disable auto pinning

### ISSUE THREAD

**Issue by petebrag** [piroor/treestyletab#2721]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Too less information. Please describe what is the problem you saw.

**Comment by petebrag** [comment]
Hi, is there a video or videos explaining all the functions and keyboard shortcuts for TST?  

Thanks,

Pete

**Comment by irvinm** [comment]
@petebrag there is a lot of information in the [wiki](https://github.com/piroor/treestyletab/wiki) and if you do a search for issues with the term you are looking for.  Else, if you have a more specific question,  people can try to help out.  There are not videos of all of the functions and keyboard shortcuts.  [Unless @piroor has found a new love of making videos that I do not know about. 😄]

**Comment by piroor** [comment]
Sorry but I have no plan about creating high quality videos describing usage of TST for now. About documents about keyboard shortcuts also. This is just because due to my poor resource.

Here are some short video clips I tweeted with descriptions of TST features:
https://twitter.com/piro_or/status/1250806769900638208
https://twitter.com/piro_or/status/1250806027114606592
https://twitter.com/piro_or/status/1250804410617225217
https://twitter.com/piro_or/status/1250803308387696641
https://twitter.com/piro_or/status/1250800580957581312

**Comment by petebrag** [comment]
First off, TST is awesome. I love it and use it everyday.  I have a question: is there a way to disable the collapsing of tabs? Like when I open one within the other, they nest and I find myself expanding  them all the time.  I just don't use or like tabs collapsed one within the other. Thanks.

**Comment by piroor** [comment]
There is a FAQ: please see the topic "I don't need automatically organized tree, instead I just want to organize tree by myself" in https://github.com/piroor/treestyletab#feature-requests 

Thank you for loving TST, however please remind that this is an issue tracker, not a user forum. Each issue aims to track a bug or a feature request. If you have something question about usage of TST, I recommend you to post it to somewhere forum like the Reddit.

I close this because this is not a valid "issue".
