### ISSUE TITLE
group-tab auto-closing prefs do not stick

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2737]
## Short description

In my main profile "Close this tab when there are no more children" and "Close this tab when there is one or less child" are unchecked and checking either doesn't stick, the next "open all in tabs" they are unchecked again.

In a new profile "Close this tab when there are no more children" defaults to checked but changes also don't stick.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. enable bookmark folder grouping
 3. show the bookmarks bar 
 4. create a folder on it
 5. add two bookmarks to it (https://example.org twice)
 6. open all it tabs
 7. in the group-tab check the unchecked "Close this tab when there is one or less child"
 8. close the group tree
 9. open all it tabs
 10. the "close this tab ..." checks are back to defaults

## Environment

 * Platform (OS): win7 sp1 x64
 * Version of Firefox: 81.0.1 x64
 * Version (or revision) of Tree Style Tab: 3.5.32

**Comment by piroor** [comment]
It is a designed behavior. Those checkboxes just controls only the particular tab itself containing checkboxes but won't affect to further group tabs.

I've implemented new (secret) options to control default checkbox state for group tabs. Thereare four new options at TST options => Development => All Configs:

* `groupTabTemporaryStateForNewTabsFromBookmarks`
* `groupTabTemporaryStateForNewTabsFromOthers`
* `groupTabTemporaryStateForChildrenOfPinned`
* `groupTabTemporaryStateForOrphanedTabs`

`1` means `Close this tab when there are no more children`.
`2` means `Close this tab when there is one or less child`.
You'll need to set `groupTabTemporaryStateForNewTabsFromBookmarks` to `2` to get the expected result.

**Comment by bughit** [comment]
controlling just the current tab is rather useless, it's quicker to manually close it than to fiddle with these checks, so it would make sense for them to change the defaults

**Comment by piroor** [comment]
I hope that people remind the nominative of those checkbox labels is "this tab" isntead of "this type tabs". As described at this section https://github.com/piroor/treestyletab/commit/cf31e60b58e438d5bffac9294c666281514e2141#diff-895c7889a4ca984d671ca3a96b548828bdfbf1ee7e0368ed5ad96cc7b4591b06R178 TST switches default checkbox state for each context. This is because there are multiple purposes why TST bundle tabs as a group. Moreover the context of a group tab may be changed after it is opened - indeed I sometimes want a particular group tab to become permanent but keep further new group tabs temporary. Applying checkbox state for all further group tabs will break not only TST's per-context group tab behaviors but such manual context changes also. Switching checkboxes back to their previous state on every "next time" after I changed checkbox state for a particular tab looks too stressful for me.

Currently these new four options have no regular option UI. I'm planning to list them as expert options.

**Comment by piroor** [comment]
Options UI is now exposed with the commit b191aae.

**Comment by irvinm** [comment]
@bughit does this solution work for you?  If so, can you close this item?

**Comment by irvinm** [comment]
@piroor you could probably close this one.
