### ISSUE TITLE
New tab option behave weired

### ISSUE THREAD

**Issue by Galliver7** [piroor/treestyletab#2739]
## Short description
以下のオプションの挙動がおかしい（と感じます）
![screenshot_538](https://user-images.githubusercontent.com/8030470/96252923-ae3f9380-0fed-11eb-9a58-7b8e37db3f80.png)

ロケーションバーの検索より新しいタブを開いた際、「独立したタブとして開く」として挙動する場合と「現在のタブと同階層で隣に開く」として挙動する場合があります

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 該当の設定に変更します
 4. アドレスバーから検索を行い新しいタブを開くと、意図しない挙動が発生する場合があります。
* browser.urlbar.openintab = true にしています

### 同階層タブからアドレスバーで検索し新しいタブを開いた → 意図しない動作❎
独立したタブとして開く
![screenshot_539](https://user-images.githubusercontent.com/8030470/96253933-69b4f780-0fef-11eb-99d1-1fab3648b5fa.png)

### 同階層タブからアドレスバーで検索し新しいタブを開いた → 意図した動作✔
現在のタブと同階層で隣に開く
![screenshot_540](https://user-images.githubusercontent.com/8030470/96254038-979a3c00-0fef-11eb-80bd-d5377b3a3cf2.png)

### 同階層タブを別のサイトに遷移し、小タブからアドレスバーで検索し新しいタブを開いた → 意図しない動作❎
独立したタブとして開く
![screenshot_541](https://user-images.githubusercontent.com/8030470/96254166-cf08e880-0fef-11eb-8959-90ce41801f77.png)

## Expected result
アドレスバーから検索して開いたすべての新しいタブは「現在のタブと同階層で隣に開く」として動作する

## Actual result
同階層タブを別のページに遷移すると、アドレスバーから検索して開いたタブの挙動が「独立したタブとして開く」になる
（現在再現できている方法がこの方法です、これ以外にもあるような気がします）

## Environment

 * Platform (OS): win10 64bit
 * Version of Firefox: firefox 81.0.2
 * Version (or revision) of Tree Style Tab: 3.5.32

**Comment by piroor** [comment]
3つの場合（意図に反した結果、意図通りの結果、意図に反した結果）が列挙されていますが、3番目については機能的に意図通りの動作ではないかと思います。
当該設定は「新たに開かれたタブのURLが現在のタブのURLと同じドメインだった場合の制御」なので、

* Googleの検索結果のページを開いている状態でアドレスバーから検索を実行→当該設定が反映される
* Googleの検索結果でないページを開いている状態でアドレスバーから検索を実行→当該設定は反映されない

というのが設計上意図された結果となります。

1番目の場合では現在のタブの内容は何でしょうか？　もしGoogleの検索結果のページでなかったのであれば、上記の説明が当てはまると思います。そうでない場合、こちらで現象を再現できていないので、詳しい再現手順を特定頂く必要があります。

（なお、なぜこの機能の適用対象が「同じドメインの場合だけ」なのかというと、この条件を外してしまうと、ブックマークや履歴から開いたタブなどまでが片っ端から設定の影響を受けてしまい、影響が大きすぎるからです。「アドレスバーから開かれたタブ」を確実に検出する方法があれば「アドレスバーから開いたタブは常に何々として開く」という設定項目を設けられるんですが、APIの制限のため検出不可能なので、現状ではこのようになっています。）

**Comment by irvinm** [comment]
@Galliver7 any thoughts on piroor's comments?  Is there anything more to do with this issue?  If not, can you close this item?

**Comment by irvinm** [comment]
@piroor what are your thoughts on this one?  (I am not sure I got everything via Google translate)

**Comment by piroor** [comment]
機能としては設計意図通りなので、このissue自体はクローズすることにします。
（アドレスバーからの入力だけを選択的に制御する機能が必要だ、という要望については、それ自体でissueとして扱う価値はあると認識しています。ただ、後述の技術的な理由により実現は困難と踏んでいます。）

@irvinm Thank you for reminding, I close this for now because the report is about designed behaviors. I agree it is little hard to understand and less-intuitive, but sadly we cannot solve it due to restrictions of WebExtensions API.


----

> 「アドレスバーから開かれたタブ」を確実に検出する方法があれば「アドレスバーから開いたタブは常に何々として開く」という設定項目を設けられるんですが、APIの制限のため検出不可能なので、現状ではこのようになっています。

この点について技術的なメモを残しておきます（主に自分用）

* [webRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest)：リクエストの契機がアドレスバーからの入力や選択だったかどうかを知る情報が渡されない。
* [webNavigation.onCommitted](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCommitted)：ページ遷移の契機が何だったかを知るヒントはあるが、[その種別](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/transitionType)について、Firefoxは「アドレスバーからの入力が契機だった」という事を示す種別に未対応。
* [omnibox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/omnibox)：アドレスバーに何らかの入力が行われたことを検知できるAPIに見えるが、実際にはアドオン固有のprefixを入力したときにしかイベントが通知されない。そのため、通常のURL入力が行われたかどうかを知る術がない。
