### ISSUE TITLE
OneTab support

### ISSUE THREAD

**Issue by xmass** [piroor/treestyletab#2741]
Please add support of adding Tree tab to OneTab plugin or have similar feature to save tree of tabs from right click to a 'bookmark like' page. 
The goal is to save selected sub tree with hiearchy as list of links. Please see the OneTab addon.

**Comment by piroor** [comment]
TST has ability to create bookmarks within a folder from tree of tabs: see the right click menu on a tree. And, you also can restore tree of tabs with the action: right-click on the saved folder and choose "Open All as a Tree". Did you try that?

**Comment by xmass** [comment]
Ah nice. I haven't seen this feature. Thank you for pointing it out!

**Comment by rajeshmanivan** [comment]
Hi, I checked the "bookmark this tree" option in the righ-click(context) menu. But I still prefer an onetab integration, because I find firefox bookmarks to be clunky to use.

Edit: Ignore this comment. Onetab addon has a keyboard-shortcut to send the current tab to onetab. that function works for me. The shortcut have to set in the firefox addon keyboard-shortcuts menu, before starting to use it.
