### ISSUE TITLE
Beta 84 bookmarks bar

### ISSUE THREAD

**Issue by XakepSDK** [piroor/treestyletab#2764]
### Short description
Firefox beta 84 adds bookmarks bar on top of a blank page. Does anybody know how can i disable it or make it shorter, so tabs don't move down a bit when i open blank page?

### Environment
Firefox 84.0b2

**Comment by piroor** [comment]
I've not tested Firefox 84 beta but Nightly 85 has an option to control the behavior. Right click on the bookmarks toolbar, and choose "Bookmarks Toolbar" => "Always" or "Never", then the bar is stably shown or hidden.

I'm trying to suppress the visual gap due to dynamically shown/hidden toolbar with recent commits, but I still cannot find out any good solution. There is no hint to detect what happens on Firefox: is the bookmarks toolbar shown/hidden temporary or permanently? If it is just a temporary change TST can apply visual offset to cancel the gap, but it make topmost tab (or pinned tabs) inaccessible. If the change is permanently, the topmost tab (or pinned tabs) never been accessible...

**Comment by XakepSDK** [comment]
Thanks! Beta 84 has same feature. I like bookmarks tab feature, so it would be cool if it was possible to shrink it so it won't move TST sidebar down.

**Comment by piroor** [comment]
I've implemented some workaround. Now TST tries to detect visual gap triggered by the bookmark toolbar on a about:newtab tab and offsets the contents of the tab bar. When you want to see tabs invisible due to the offset, you'll see them by hovering on the top edge of the sidebar.

You can try the development build:
https://github.com/piroor/treestyletab#development-builds

**Comment by irvinm** [comment]
@XakepSDK any feedback?

**Comment by XakepSDK** [comment]
I haven't tried developer builds, just hiding bookmarks toolbar is enough for me
