### ISSUE TITLE
TST: add example on how to filter tabs on title/data-label

### ISSUE THREAD

**Issue by mafjmafj** [piroor/treestyletab#2771]
I wanted to colorize tabs based on title:
I assume data-label means title and came up with this snippet
```
tab-item[data-label^="Create Issue"] .label {
  background-color: hsl(1, 30%, 80%);
}
```
Without the `[data-label^="Create Issue"]` part I can see color change taking effect.
With `[data-content-uri^="http://jira"]` the color change is applied to relevant tabs.
With `[data-label^="Create Issue"]` the change does NOT get applied to tabs with clearly visible matching title
(`[data-label^=""]` also has NO effect.)

I did not see any example of  how to do it.

The usecase is to clearly differentiate tabs I am actively editing content with, such as:
 * `Create Issue` for jira

**Comment by irvinm** [comment]
![image](https://user-images.githubusercontent.com/979729/100380598-25047f00-2fe5-11eb-9939-3bb7d69f8460.png)

**Comment by mafjmafj** [comment]
Thanks. Is there a reference somewhere on the available fields, attribute filtering etc... All the googling seem to point simply to tree style tab.

**Comment by irvinm** [comment]
@mafjmafj honestly the best place is really still the wiki.  If it isn't in the wiki, the next best place (how I did this one) was to simply inspect the CSS live (via TST debugging - [How to inspect tree of tabs](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs)) where I found that the label was stored in the variable "title" and the rest was pretty easy to piece together.

**Comment by piroor** [comment]
@mafjmafj  As @irvinm told, sadly there is no stable document for TST customization via CSS. Element names, class names, attributes, and DOM structure may be changed from various reasons, and I don't write any "reference document" of them because I don't have enough resource to maintain it. Frequently used customization examples are filed to [code snippets](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules), but they sometimes become broken due to changes on TST I did and they need to be updated by their users through [investigation with the debugger](https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar).

**Comment by piroor** [comment]
I've added a FAQ topic: 710f3a551

**Comment by irvinm** [comment]
@piroor I think we can close this.
