### ISSUE TITLE
Both the hotkey and the TST button breaks sporadically

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2772]
## Short description
For some reason both become non-functional sometimes. I see no errors int the console, but I can't open TST with either. Only by the sidebar dropdown menu.

## Steps to reproduce

So far I didn't notice what initiates this.

## Environment

 * Platform (OS): Win 10
 * Version of Firefox: 83.0b10 Dev edition.
 * Version (or revision) of Tree Style Tab: 3.6.2

**Comment by txtsd** [comment]
Same for me.

 ## Environment
* Platform (OS): Arch Linux
* Version of Firefox: 83.0 stable
 * Version (or revision) of Tree Style Tab: 3.6.2

**Comment by piroor** [comment]
This looks to be a duplicated of #2671.

**Comment by piroor** [comment]
If you thought it is a problem that F1/toolbar button doesn't close the sidebar immediately while the sidebar is loading, it is by design for now. Currently TST uses `sidebarAction.open()` and `sidebarAction.close()` to toggle the sidebar. When there is any living connection between the sidebar and the background page, it means the sidebar is shown, and TST calls `sidebarAction.close()`. Otherwise the sidebar is hidden and TST calls `sidebarAction.open()`. This means that the state "the sidebar is opened but not initialized yet" is detected as "sidebar is hidden" despite the sidebar is actually visible, and you'll see unworking F1/toolbar button for a while.

The commit ee69298 introduces a change to call [`sidebarAction.toggle()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction/toggle) if it is available (on  Firefox 73 and later.) It will improve the response for F1/toolbar button - it hides the sidebar even if it is still in loading.

**Comment by txtsd** [comment]
idk about OP but #2671 is what's happening to me

**Comment by irvinm** [comment]
@piroor any reason to leave this open as a duplicate?

**Comment by piroor** [comment]
@mzso Does the problem still happen with TST 3.6.3? If it looks to be suppressed please close this.

**Comment by mzso** [comment]
@piroor 
Not sure yet. Only used it a little since yesterday.

**Comment by txtsd** [comment]
Hasn't happened yet for me.

**Comment by silverwings15** [comment]
been working fine for me as well

**Comment by mzso** [comment]
So far so good here as well.

**Comment by irvinm** [comment]
@mzso do you want to close this item for now?  If it is still an issue, you can re-open as needed.

**Comment by mzso** [comment]
[**@irvinm**](https://github.com/irvinm) commented on [2020. dec. 8. 13:50 CET](https://github.com/piroor/treestyletab/issues/2772#issuecomment-740600172 "2020-12-08T12:50:13Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) do you want to close this item for now? If it is still an issue, you can re-open as needed.

I guess.
