### ISSUE TITLE
[Feature Request] Option to make alt-enter new tab from location bar a sibling tab

### ISSUE THREAD

**Issue by IAmNotAJerk** [piroor/treestyletab#2787]
## Short description
Requesting an option to make "alt-enter new tab from location bar" a sibling tab to current tab.

Currently there is an option for "new tab with the same website as the current tab from location bar, bookmarks, histories, or other cases". I did try that but that does not apply to my case. 

(extra note, if you want to know why I want this feature:
This could be very useful when making related research on related topics during browsing.)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. new tabs behaivor of "new tab with the same website as the current tab from location bar, bookmarks, histories, or other cases" changed to "open as the next sibling of the current tab"
 4. At certain tab page, enter search terms or url links at location bar, then hit alt + enter

## Expected result
Open that location bar new tab as a next sibling tab of current tab.
A
\- B (selected)
\- D <-- (create a new tab here from location bar by hitting alt-enter)
C

## Actual result
New tab is opened, no problem. But it as at the very end of all tab trees. 

A
\- B (selected)
C
D <-- (alt-enter from location bar created new tab here instead)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 84.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.6.3

## A FANBOY's NOTE
First time posting, but have been using your addon for years and I always have secretly admiring your humble and straight-to-the-point personality. Hope my description is clear enough for you and plz let me know if I should clearify anything.

**Comment by piroor** [comment]
Sadly this couldn't implemented, because addons cannot detect Alt-Enter action in the address bar for now. Instead all new tabs from the location bar can be attached to the current tab, but it become an overkill behavior - it means that tabs opened by various cases (from bookmarks, history, drag-and-drop, and other addons) become children of the current tab by default.  Please see my comment at an old issue for more background: https://github.com/piroor/treestyletab/issues/2391#issuecomment-542302281

**Comment by irvinm** [comment]
@IAmNotAJerk will you close out this item since it can not be done?

**Comment by IAmNotAJerk** [comment]
Sure. 👍
