### ISSUE TITLE
Significant Time Difference Between 2 Methods To Send Tabs

### ISSUE THREAD

**Issue by PantherX** [piroor/treestyletab#2792]
# Short description

When attempting to use the [Send Tab from Firefox](https://support.mozilla.org/en-US/kb/send-tab-firefox-desktop-other-devices) feature, TST has a significant delay while the "native" option works instantly.

I think my issue is different to the one reported here #2419 but I am not 100% sure so am creating this issue just in case they are different. Moreover, it might be a Firefox Sync issue too but again, am not 100% sure.

# Steps to reproduce

 1. Start Firefox with clean profile
 2. Log into Firefox Account
 3. Wait for clean profile to load settings
 4. Rename current system to something unique in TST > Options > Context Menu > Send Tabs to Other Devices with the contest menu via Firefox Sync
 5. Restart Firefox
 6. Right click on the Tab and send to System A:
 ![image](https://user-images.githubusercontent.com/5349122/103432482-602d4a00-4c44-11eb-932e-43480b998d31.png)

# Expected result

I would expect that it would take few seconds for it to appear in System A.

# Actual result

It takes few minutes (up to 15 minutes) for the sent tab to appear on System A. What is baffling is that when I sent the tab via the Address Bar, it instantly showed up (within 2 seconds):
![image](https://user-images.githubusercontent.com/5349122/103432513-d631b100-4c44-11eb-894f-fb9352415301.png)

Using two different methods to send a tab should take the same time.

# Environment

 * Platform (OS): Windows 20 10H2; System A fresh install, System B in-place upgrade from previous Windows 10 versions
 * Version of Firefox: 84.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.6.4

**Comment by piroor** [comment]
Sadly it can't be fixed by TST. There is no available API to send tabs via Firefox Sync by an addon. There is a related bug: [1417183 - Provide a web extensions API-based way to send pages between devices](https://bugzilla.mozilla.org/show_bug.cgi?id=1417183).

Thus TST implements a "fake" send pages feature based on the [storage.sync API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync). Assume that there are two devices A and B:

* When you tried to send a tab from A to B with TST's menu, TST writes sent tabs information to the sync storage at the device A.
* The data written to the sync storage at the device A is uploaded to the sync server by Firefox implicitly. Sadly there is no chance to control the uploading process from an addon at any arbitrary timing. (But you can trigger a synchronization manually with the app menu at A.)
* The updated data on the sync server is downloaded to the device B implicitly. Sadly there is also no chance to kick the process from an addon at any arbitrary timing. (You can trigger a synchronization manually with the app menu at B.)
* When Firefox on the device B has downloaded the updated data successfully, Firefox notifies it to listeners of `storage.sync.onChanged`. TST "receives" sent tabs data with the listener, and opens them as new tabs.

The sync storage is a multi-purpose data store, and too frequent synchronization will increase network traffic, so it looks reasonable that Firefox restricts synchronization of the sync storage.

On the other hand, Firefox uploads tab information and it is downloaded on the destination device immediately, for the native "send tab to device" command. This means that Firefox applies different frequency rules for each sync data.

Something method to kick the synchronization will help addon authors, but I think there is little hope of a future such an API become available, due to the proposal policy about WebExtensions API: any proposal of an API looks to be rejected if it will increase the amount of resource usage...

**Comment by PantherX** [comment]
Hiya @piroor 

Thanks for the detailed explanation! I was manually syncing on Device A but it never occurred to me to sync on Device B. Considering that I now know how the system works, I can see that this isn't a TST issue but a Firefox limitation. Thus, I will close this issue now. Thanks once again for your response 😄
