### ISSUE TITLE
TST for Safari?

### ISSUE THREAD

**Issue by BrianGilbert** [piroor/treestyletab#2801]
## Short description
Now that Safari supports webextensions, is it possible, and is there any intent to make a TST release for Safari?

https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by Lej77** [comment]
I think this is unlikely since there isn't even a version of Tree Style Tab for Chrome or any other browser except Firefox, see the [FAQ / frequently rejected requests/proposals](https://github.com/piroor/treestyletab#other-browsers-support) in the TST readme. 

I can also imagine some issues with porting the addon since some important functionality isn't provided by most browsers ([APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs), [Manifest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json)). For example the [`sidebar_action`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action#browser_compatibility) manifest key that allows an extension to define a custom sidebar page is only supported in Firefox and Opera. You could work around this issue by opening the sidebar page in a new window and manually or automatically moving it beside the main window, like the [`Tree Style Tab in Separate Window`](https://github.com/Lej77/tree-style-tab-in-separate-window) addon does for TST.

Another important API would be the [`getTabValue` and `getWindowValue`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions#browser_compatibility) API. Without those methods it is really hard to store tab specific data. I can imagine workarounds like storing a list of tabs (with urls and titles) for all windows in the extension's storage and trying to match that list with the opened windows when the browser is restarted or the addon is reloaded (for example after an update). Or simply forgetting all tree structure on browser restarts which might work well for people that rarely restore sessions, though it would probably still lose info for closed tabs that are reopened.

TST also have other Firefox specific behavior that would need to be disabled or worked around for other browsers. For example to synchronize the animations for loading "throbbers" (icons) it uses the [`-moz-element`](https://github.com/piroor/treestyletab/blob/90b6d2232b68efbd4bcd692f4d6f9292c97af070/webextensions/sidebar/styles/throbber.css#L103) css property to mirror the appearance of a hidden element, until the animation has completed one iteration [after which the normal animation](https://github.com/piroor/treestyletab/blob/90b6d2232b68efbd4bcd692f4d6f9292c97af070/webextensions/sidebar/sidebar-tabs.js#L87-L100) is used for performance. This could probably be disabled quite easily but the question is how much Firefox specific behavior TST actually depends on.

Still the extension could be useful even with all these limitations but It would probably require a bit of effort to port it.

**Comment by irvinm** [comment]
@piroor any desire and\or evaluation if this is even possible?  (I'm with @Lej77 that this probably isn't possible yet)

**Comment by piroor** [comment]
As @Lej77 explained (thank you @Lej77 !) TST cannot be ported to non-Gecko browsers for now, due to API limitations.

And currently I have no plan to re-implement TST-like extension for other browsers by my hand, except when the time to exodus from Firefox come and there be no suitable alternative extension for me.
