### ISSUE TITLE
Can't Turn Off New "Force TST Behaviour on Tab Strip-triggered Actions" Behaviour

### ISSUE THREAD

**Issue by ssokolow** [piroor/treestyletab#2837]
## Short description

Since a week or two ago, Tree Style Tab has started trying to close child tabs when I close the parent using the browser's tab bar if the parent tab is collapsed in the TST sidebar.

Given that there are no structural cues in the browser's tab strip, this brings me no benefit (I have to look at the sidebar anyway if I want to act on the tree structure) and means that, often, I forget to check the TST sidebar to make sure the current tab is expanded if it's a parent and wind up having to cancel an unwanted "close entire group" operation.

I've had to mitigate this misfeature by turning off as much automatic collapsing as possible and doing everything else I can find to ensure that tabs stay expanded all the time.

## Steps to reproduce

1. Start Firefox with clean profile.
2. Install TST.
3. Open some tabs, including one with children.
4. Navigate to a tab outside the group in a manner which triggers auto-collapse of the group.
5. Middle-click the group parent in the browser's built-in tab strip.
6. Watch as TST closes a bunch of tabs I wanted to keep and displays the "Are You Sure?" dialog.
7. Curse and click "Cancel" on the "Are you Sure?" dialog to get my tabs back.
8. Click the parent's icon in the sidebar to expand it.
9. Middle-click the parent *in the sidebar* to achieve the effect I wanted in the first place.

This behaviour is present in a fresh Firefox profile with default Tree Style Tab settings and I couldn't find a way to disable it in my normal profile.

## Expected result

The tab I wanted to close should close and nothing else.

I want TST, but I want it *in addition to* how how I interact with the browser's built-in tab strip, not instead of. (Partly because, whenever the browser gets bogged down, extension-provided UIs like TST become unusable while the built-in tab strip remains usable.)

I set my TST configuration with that goal in mind, sacrificing whatever TST features I need to in order to achieve it.

## Actual result

Because I'm not looking at TST's sidebar when I close a tab in the tab strip, I get surprised by TST unexpectedly closing tabs I *didn't* intend to close and I have to go through four extra steps to get them back and then close just what I intended.

This kept happening again and again before I resorted to making sure all parent tabs remained open at all times, because it's just too counter-intuitive.

## Environment

 * Platform (OS): Ubuntu 16.04.7 LTS
 * Version of Firefox: 86.0 (64-bit) ("Mozilla Firefox for Ubuntu, canonical - 1.0" build by canonical from the Ubuntu repositories)
 * Version (or revision) of Tree Style Tab: 3.7.3

**Comment by irvinm** [comment]
Have you tried looking at these options to get your desired behavior?

![image](https://user-images.githubusercontent.com/979729/111870671-6fc35180-895c-11eb-99e3-b175bb7e18e2.png)

**Comment by ssokolow** [comment]
I completely missed that I hadn't checked "Unlock Expert Options", so that checkbox was missing from that section.

Looks like the real bug is one of the following two things:

1. New defaults get added which change the behaviour visible to people with expert option hidden and can't be reverted without enabling the expert options. (This is the more direct bug because it effectively makes checking "Unlock Expert Options" mandatory to maintain a consistent appearance across automatic upgrades.)
2. The preferences need to be redesigned to make it easier to find settings. (Maybe a search box that includes a clickable "plus X expert settings which are currently hidden".)

**Comment by ssokolow** [comment]
Actually, no. On second thought, that says "when the sidebar is invisible" and opening a new TST sidebar takes so long (5-10 seconds) when it has my current 550 tabs open that I never make it invisible and just sometimes ignore its presence.

If it's conditional on me hitting F1 to hide the sidebar, it's irrelevant and useless to me, because I can't afford to burn 5-10 seconds waiting on TST's throbber every time I want to switch between using the tab strip and using TST.

(Plus, I'm not sure about now but, historically, TST has also bogged down the browser when its throbber was running... possibly because I'm on an Athlon II X2 270, which only has two cores but probably not because, from what I remember, it seemed to more be that the Chrome process was blocking on IPC with the extension process somehow, leaving stuff in content processes (like playing YouTube videos) and applications completely independent of the browser unaffected... unless it lasted for something like 30 seconds or more in which case the YouTube videos would freeze.)

**Comment by piroor** [comment]
Sorry for this confusion. The option was introduced for #2506.

When a new option is introduced, there are generally two possible choices for an application: enable it for all users or only new comers. Firefox itself choose both strategies for each options, indeed `browser.ctrlTab.recentlyUsedOrder` is enabled only for new comers but `browser.urlbar.trimURLs` is enabled for all users. But I think such a mixed policies make people more confused. So TST has a constant policy: keep the old behavior only if a new option is newly introduced but corresponding old option was intentionally changed by the user. Otherwise activate new option by default generally.

To reduce confusion from changed behaviors, I sometimes notify some serious changes with the desktop notification on TST's startup, but it is rare case for now. On future versions I show the notification on every update, except cases the update has no behavior change. I hope it should help people who like old behaviors.

I agree that there are too many options and they are complecated. I continuously try to simplify them with some trials - sometimes I unify multiple options to one high-context option, sometimes I extract an optional behavior to a separate helper addon, but TST still have too many choices. A search box looks a good workaround. Sorry, but I'm busy generally and it may be implemented in a far future by me. If you seriously need it now, could you try to implement and send me a pull request?

**Comment by ssokolow** [comment]
> Sorry for this confusion. The option was introduced for #2506.

That's still talking about "when TST is hidden". I want to turn off "Middle-clicking a tab in the tab strip may close other tabs *when TST is shown*".

> Sorry, but I'm busy generally and it may be implemented in a far future by me. If you seriously need it now, could you try to implement and send me a pull request?

Unfortunately, at the moment, I've got problems in my life, so I can't even properly give my own projects the maintenance they need.

I've more or less grown used to making sure subtrees of tabs always stay fully expanded as a workaround, even if it means I use TST more as a vertical tab strip than a tree. (Something I'd already been leaning toward anyway after one too many encounters with bugs that corrupted the three structure.)

**Comment by piroor** [comment]
> That's still talking about "when TST is hidden". I want to turn off "Middle-clicking a tab in the tab strip may close other tabs when TST is shown".

Ah, OK I've understood what you meant, and I've added a new option like as you told. However please note that it may not work as you expected on some cases due to  API restrictions.

Basically TST cannot detect the detailed trigger of a tab closing, TST just can know: the operation is triggered in the sidebar (via mouse operations or the context menu) or outside of the sidebar (keyboard shortcuts, mouse operations in the native tab bar, or operations in other addons). Thus, even if you put your eyes on a collapsed tree in the sidebar, Ctrl-W will close only the parent tab because it is handled by Firefox itself - it is outside of TST.

**Comment by ssokolow** [comment]
That's fine. After tripping over so many tree-corruption bugs over the years, I've developed a preference for that behaviour.

(Leaving TST more as a way to visualize things, with multiple-tab closing handled through Firefox's built in multi-select for tabs.)

**Comment by irvinm** [comment]
@ssokolow can you close this item or is there more to discuss?

**Comment by ssokolow** [comment]
The updated version is present in my Firefox and it appears to work as desired, so I'll close it.
