### ISSUE TITLE
Failed to detect duplicated tabs on Firefox 89

### ISSUE THREAD

**Issue by piroor** [piroor/treestyletab#2845]
After logging on Nightly 89.0a1 I've realized that TST cannot detect duplicated tabs anymore. The detection method still works on Firefox 87.0, so something change triggers this problem. Hmm...

**Comment by piroor** [comment]
On Nightly 89.0a1, `browser.sessions.getTabValue` for a newly opened tab sometimes fails. It looks required to wait until its initialization is finished - on my case 100ms is enough safe but it may be different on some environments.

**Comment by piroor** [comment]
https://hg.mozilla.org/mozilla-central/rev/018c3b3935934a697d422ba551b60894e773c202
https://hg.mozilla.org/mozilla-central/rev/26082a39ec6371d911af53e971fb736434a20667
https://hg.mozilla.org/mozilla-central/rev/0a97bfe2a11241da32e2bbc402e8090f5cf07c33

There are some changes for the "Fission" project (multi-processes), they can trigger this problem.

**Comment by piroor** [comment]
On my case 400msec delay is required for 100% successful detection. 350msec delay just successes with 80% probability. This delay is painfully large...

**Comment by piroor** [comment]
1701900 - sessions.getTabValue() requires too large delay to get expected value for a duplicated tab
https://bugzilla.mozilla.org/show_bug.cgi?id=1701900

**Comment by irvinm** [comment]
@piroor do you want to add the label "bug of Firefox itself" for tracking purposes?

**Comment by piroor** [comment]
Not only around duplicated tabs, this change of Firefox looks to break tree restoration on the startup.

**Comment by piroor** [comment]
I've introduced a change 1f22694 to reduce the side effect I commented at https://github.com/piroor/treestyletab/issues/2845#issuecomment-831220611

**Comment by grahamperrin** [comment]
@piroor @rNeomy and all, please, can we collectively identify the **meanings of the various non-loaded states** in the Firefox 95.0.2 screenshot below? 

From the top, I see: 

* dimmed (_Can't compile anything : freebsd_)
* planet/globe icon **plus** power symbol (_ZFS Caching_)
* planet/globe icon (_grahamperrin comments on No Latest repository for aar…_)
* dimmed **plus** grey dot **plus** power symbol (_x3270 compile error | The FreeBSD Forums_)

![2021-12-24 12 25 42 inactive states](https://user-images.githubusercontent.com/192271/147354839-409af86c-d293-4e57-8532-ee7ab237fabd.png)

I'm almost certain that in my case, the power symbol is always associated with Auto Tab Discard. 

I'm uncertain about other aspects. 

Thank you

**Comment by irvinm** [comment]
@grahamperrin, what does this have to do with this issue?  It is a reasonable question, but probably better discussed in "Discussions".  Auto Tab Discard is likely part of it ... and the "dimmed" tab is likely a "discarded" tab (depends on TST CSS) but many addons implement that feature.  The planet\globe just says that the favico isn't available or hasn't been loaded yet.

**Comment by grahamperrin** [comment]
Thanks for asking. 

I'm getting **duplication of tabs** in recent days, difficult to diagnose, but I'm slowly gaining the impression that it occurs: 

* only if the tab is without a favicon when clicked for the first time (after the Firefox startup routine finishes opening previous windows and tabs).

I have been unable to refine the bug to any particular extension, or combination of extensions. 

I began wondering whether the issue is with Firefox, then found my April 2021 issue 2880 involving duplication (closed, not a TST issue), then found this duplication-related issue #2845 with the **Firefox-issue** label. 

----

### Postscripts

Cross-reference FreeBSD bug [260901 – www/firefox dom.ipc.processCount 8 but maybe more than eight such processes](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260901)

2022-03-17: since things seem to progressing around `https://github.com/Drive4ik/simple-tab-groups/issues/891#issuecomment-1071013557` I'll hide this comment, and my previous comment, with an assumption that they're off-topic.
