### ISSUE TITLE
Hiding tab bar isn't smooth from ui perspective

### ISSUE THREAD

**Issue by asafarevich** [piroor/treestyletab#2847]
## Short description

Using F1 key to hide tab bar creates a small black artifact before webpage takes up full screen for half a sec, but kinda jarring. Only happens if tab bar is on left side.

   1. Start Firefox with clean profile.
   2. Install TST.
   3. Press F1
  

## Actual result
![image](https://user-images.githubusercontent.com/30283914/113019967-fcc59200-9136-11eb-95e1-311c8fc463f5.png)

## Environment

    Platform (OS): ubuntu 18.04
    Version of Firefox: 87.0 (64-bit)
    Version (or revision) of Tree Style Tab: 3.7.3

**Comment by piroor** [comment]
Did you told about hiding the sidebar instead of showing? Hmm, I cannot see the blank area on my environment - the sidebar looks to be hidden and the webpage area is expanded immediately.

Does the problem happen with other sidebar panels, for example hitting Ctrl-H to show/hide the history sidebar panel? Then it is a problem of Firefox itself, not TST side.

**Comment by asafarevich** [comment]
I just realized I should have specified this was if the side bar was moved to the right instead of the left through the settings.
Ctrl-H does not have this issue as it appears from the left side.

**Comment by piroor** [comment]
I've tested Ubuntu 20.04LTS on VirtualBox and confirmed that white blank area appears when I press the F1 key to collapse the sidebar while the system is very slow. The difference of the color looks to be caused from the system color.

It looks to happen on Ctrl-H also for me. I don't know why Ctrl-H on your environment doesn't cause the problem, but I'm guessing that Ctrl-H may be faster than F1, because the Histories sidebar panel is running in Firefox's main process itself but TST is running on a different process.

**Comment by asafarevich** [comment]
Im not having this issue when the bar is on the left side. It's exclusive to the right side.  Also my machine on the higher end of performance. So not seeing how this would be because of slowness.

**Comment by piroor** [comment]
Hmm, anyway I can't imagine how to "solve" this problem by TST side. I really want a help by someone expert of Gecko renderings...

**Comment by sakkamade** [comment]
~~Works fine for me. (Equally with TST on right and left sides.)~~

~~Arch Linux, KDE; Firefox 88.0.1 (64-bit).~~

**Comment by sakkamade** [comment]
<details><summary>Video content</summary>


https://user-images.githubusercontent.com/62730422/124531964-18f46180-ddff-11eb-9d72-38c5eb4fdb3a.mp4

https://user-images.githubusercontent.com/62730422/124531972-1bef5200-ddff-11eb-8507-a4f9162c1042.mp4


</details>

**Comment by sakkamade** [comment]
Never mind, with dark website and white UI theme, or conversely, I can see it as well.

EDIT: However, at my side, the behaviour is the same with History (Ctrl+H) and Bookmarks (Ctrl+B), and is reproducible only if the sidebar on the **left** side.
