### ISSUE TITLE
"Don't expand collapsed tree and skip collapsed descendants, while switching focus" broken on Firefox 87

### ISSUE THREAD

**Issue by haoadoreorange** [piroor/treestyletab#2859]
## Short description
The option `Don't expand collapsed tree and skip collapsed descendants, while switching focus` doesn't take effect anymore.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Check option `Don't expand collapsed tree and skip collapsed descendants, while switching focus` on Welcome page

```
A
\- B (collapsed)
C 
\- D (collapsed)
E (selected)
```
--> Ctrl Pageup

## Expected result
E -> C

## Actual result
E -> D

## Environment

 * Platform (OS): Ubuntu 20.04
 * Version of Firefox: 87.0
 * Version (or revision) of Tree Style Tab: 3.7.4

**Comment by piroor** [comment]
Due to restrictions of the WebExtensions API, the feature is available only when you started the operation with a regular page and it is focused.

* When the tab "E" is Firefox's built-in page or addons.mozilla.org page, TST cannot inject a script to detect pressing down of the Ctrl key.
* When something Firefox UI is focused (ex. the address bar) TST cannot detect the pressing down of the Ctrl key.

Is your case one of these situations? Otherwise please tell the URL of the tab E. I'll research what blocks TST's keydown detection.

**Comment by haoadoreorange** [comment]
Hi, I ended up just using directly the shortcuts to switch and don't expand, I will close the issue here.
