### ISSUE TITLE
Solo tab drag behaviour does not apply correctly when dragged via the Firefox tab bar

### ISSUE THREAD

**Issue by BobVul** [piroor/treestyletab#2860]
## Short description
The tag drab behaviour "move solo tab" does not work in the Firefox tab bar (outside TST)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set drag behaviour any of the "move solo tab" options
 4. Open three tabs, with the second tab a child of the first:

    ![image](https://user-images.githubusercontent.com/1674237/114786607-bec89f00-9dc1-11eb-95b5-37e7f368ec16.png)

    ![image](https://user-images.githubusercontent.com/1674237/114786723-f8010f00-9dc1-11eb-9fa6-5b73a9c1a0a3.png)

 5. Drag the parent tab to be the last tab via the TST sidebar

    Result:
    
    ![image](https://user-images.githubusercontent.com/1674237/114786860-30085200-9dc2-11eb-8b37-dc00f8dcbe9f.png)

    ![image](https://user-images.githubusercontent.com/1674237/114786870-34346f80-9dc2-11eb-9f11-29d03fa723a7.png)

6. Revert back to the step 4 layout
7. Drag the parent tab to be the last tab via the Firefox tab bar

    Result:

    ![image](https://user-images.githubusercontent.com/1674237/114787032-71006680-9dc2-11eb-960d-9972cf69b035.png)

    ![image](https://user-images.githubusercontent.com/1674237/114787042-75c51a80-9dc2-11eb-9637-8b02117e92a7.png)

## Expected result

Expected layout after dragging parent to be after child:

![image](https://user-images.githubusercontent.com/1674237/114786860-30085200-9dc2-11eb-8b37-dc00f8dcbe9f.png)

![image](https://user-images.githubusercontent.com/1674237/114786870-34346f80-9dc2-11eb-9f11-29d03fa723a7.png)

This works correctly if the drag action is executed on the TST sidebar.

## Actual result

When the drag action is executed on the main Firefox tab bar, the entire tree is moved despite the drag action being set to "move solo tab".

![image](https://user-images.githubusercontent.com/1674237/114787032-71006680-9dc2-11eb-960d-9972cf69b035.png)

![image](https://user-images.githubusercontent.com/1674237/114787042-75c51a80-9dc2-11eb-9637-8b02117e92a7.png)

## Environment

 * Platform (OS): Windows
 * Version of Firefox: 89.0a1 (2021-04-14)
 * Version (or revision) of Tree Style Tab: 3.6.5.11204

**Comment by BobVul** [comment]
Also, as an additional/related feature request, would it be possible to have a separate set of options for the Firefox tab bar?

Ideally I would like a setup where:

* When dragged via TST, move the entire tree
* When dragged via Firefox tab bar, move solo tab

**Comment by piroor** [comment]
Hmm, it looks the time to restructure those options again.

All possible behaviors for closed parent tab are:

* T1: Close descendants too
* T2: Replace closed parent with a dummy tab and keep the tree
* T3: Promote the first child as the new parent always
* T4: Promote all children as the level of the closed parent always
* T5: Promote the first child when a root tab was closed, otherwise promote all children
* T6: Liberate child tabs from the tree

All possible behaviors for moved parent tab are:

* U1: Move descendants too
* U2: Replace moved parent with a dummy tab and keep the tree
* U3: Promote the first child as the new parent always
* U4: Promote all children as the level of the moved parent always
* U5: Promote the first child when a root tab was moved, otherwise promote all children
* U6: Liberate child tabs from the tree

All possible operation cases are:

* A: Operations in the sidebar
  * A1: for collapsed tree
    * consistently T1
    * consistently U1
  * A2: for expanded tree 
    * configurable with T1-6
    * consistently U1
* B: Operations out of the sidebar (native tab bar, keyboard shortcut, or other addons), with invisible sidebar
  * B1: for collapsed tree
    * configurable with T1-6
    * configurable with U1-6
  * B2: for expanded tree
    * configurable with T1-6
    * configurable with U1-6
* C: Operations out of the sidebar (native tab bar, keyboard shortcut, or other addons), with visible sidebar
  * C1: for collapsed tree
    * configurable with T1-6
    * configurable with U1-6
  * C2: for expanded tree
    * configurable with T1-6
    * configurable with U1-6


Possible modes (recommended configuration set) are:

* D: Consistent mode: apply TST behaviors around tabs same to the one in the sidebar always.
  * A1 consistently T1 and U1
  * A2 consistently U1, **configurable with T2-5**
  * B1 and C1 consistently same to A1
  * B2 and C2 consistently same to A2
* E: Parallel mode: apply TST behaviors only for specific cases, otherwise operate the tab as a solo tab.
  * A1 consistently T1 and U1
  * A2 consistently U1, **configurable with T2-5**
  * B1 consistently same to B2
  * B2 **configurable with T2-5 and U1-5**
  * C1 consistently same to B2
  * C2 consistently same to B2
* F: Custom: full configurable
  * A1 consistently T1 and U1
  * A2 consistently U1, **configurable with T1-6**
  * B1 **configurable with T1-6 and U1-6**
  * B2 **configurable with T1-6 and U1-6**
  * C1 **configurable with T1-6 and U1-6**
  * C2 **configurable with T1-6 and U1-6**

**Comment by piroor** [comment]
Screenshots:

"when a parent tab is closed or moved":
![image](https://user-images.githubusercontent.com/70062/115103253-81b00880-9f8b-11eb-977b-90af82fbeb90.png)
![image](https://user-images.githubusercontent.com/70062/115103264-91c7e800-9f8b-11eb-897a-cacda690f844.png)
![image](https://user-images.githubusercontent.com/70062/115103272-98565f80-9f8b-11eb-8c3d-62e9b0f1648e.png)

"drag and drop":
![image](https://user-images.githubusercontent.com/70062/115079332-fc513780-9f3b-11eb-8782-b8cda23efa31.png)

**Comment by piroor** [comment]
On the new version you can configure behaviors around tabs moved via Firefox's tab bar. However please note that the option affects to other cases also: keyboard shortcuts or other addons. This is due to restrictions of the WebExtensions API framework.

**Comment by BobVul** [comment]
Thank you! The new version (from CI artifacts) works perfectly as desired :)

![image](https://user-images.githubusercontent.com/1674237/115145672-1bfc7300-a096-11eb-99d2-4c1194da8740.png)

**Comment by irvinm** [comment]
@BobVul 3.8.0 has been released.  Can you verify if this has been fixed and close this item?

**Comment by BobVul** [comment]
Yup, all works as expected on release version.

Thanks again!
