### ISSUE TITLE
Add Share menu to Tab Context menus

### ISSUE THREAD

**Issue by kristofferR** [piroor/treestyletab#2867]
[Firefox recently added the Share Menu to the native Tab Context](https://bugzilla.mozilla.org/show_bug.cgi?id=1690569) menus since Proton removed it from the tree dot menu in the address bar.

Please add it to the TST tab context menu too. Right now, with the native tabs hidden and only TST tabs visible, the Share functionality is completely inaccessible.

**Comment by piroor** [comment]
Sadly it is impossible for now because there is no WebExtensions API to call the "share" feature. I've filed a bug about this topic: [1706675 - Add an API to call the "Share" command of Firefox itself (on Windows 10 and macOS)](https://bugzilla.mozilla.org/show_bug.cgi?id=1706675)

Until Firefox provides an API for the feature, we need to use a native messaging host. It needs to do things same to Firefox does. FYI:

* [the implementation on Windows: WindowsUIUtils.cpp](https://searchfox.org/mozilla-central/rev/d280cc26237b62096b89317e4ed6dea8b2bdf822/widget/windows/WindowsUIUtils.cpp#338)
* [the implementation on Windows: nsMacSharingService.mm](https://searchfox.org/mozilla-central/rev/d280cc26237b62096b89317e4ed6dea8b2bdf822/widget/cocoa/nsMacSharingService.mm#164)

I can develop a native messaging host for Windows, but macOS is out of my hands...

**Comment by kristofferR** [comment]
@piroor I just noticed that they requested your input over in the Bugzilla thread. ;)

**Comment by piroor** [comment]
It looks too late but I've commented to the bug...

**Comment by irvinm** [comment]
Now being tracked at:  [Add Share Menu to File Menu on macOS](https://bugzilla.mozilla.org/show_bug.cgi?id=1512851)
