### ISSUE TITLE
Add the recently closed tabs to TST tab context menu

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2873]
Hi!

I was wondering if that can be done with some code. And someone on reddit already had a [script](https://github.com/aminomancer/uc.css.js/blob/master/script/undoListInTabContextMenu.uc.js) for that. But won't work for TST tabs. Quote:

> sure, I have a script for it. instructions here.
> 
> edit: oh, btw it seems it doesn't work for tree style tabs. that extension makes its own context menu within the sidebar browser, which fully unloads every time the sidebar is closed, making it extremely difficult to add a menu item to it. the only way I can think of is to make an extension and hook the menu creation to use runtime.sendMessage to make a menu item when the extension makes its menu items.
> 
> but I don't think that's going to work, since this script won't work as an extension, it requires privileged modules to generate the document fragment for the recently closed tabs/windows lists and the localized menu labels. which won't be instantiated in an extension sandbox. I did a bit of research and it looks like I might be able to use the "ExtensionTestUtils" to create an invisible system extension, which would have access to the runtime API I'd need, but I'm not sure that would have access to any global objects either. and it seems like a lot of work too, I'd be basically building an entire extension file system sandwiched inside a script lol. it sounds kinda silly but oddly enough, it appears in the firefox source code several times, I guess it's used frequently for testing extensions.
> 
> if anyone has any ideas or info for making this work, I'd be happy for any feedback, I'd definitely prefer if the script worked for TST too

So @piroor (or anyone really) do you think there's a better way to do it?

**Comment by piroor** [comment]
There are some existing addons providing "recently closed tabs" menu to the tab context menu working with TST completely:

* [Undo Close Tab](https://addons.mozilla.org/firefox/addon/undoclosetabbutton/)
* [Undo Closed Tabs Menu](https://addons.mozilla.org/firefox/addon/undo-closed-tab-menu/)

I've looked the userChrome.js script and I thought that the functionalities can be implemented via WebExtensions API. The method [sessions.getRecentlyClosed()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/getRecentlyClosed) returns both closed tabs and windows. Thus you can provide a "recently closed windows" menu, with a filtered results of the method.

I cannot recommend you to do like that with the userChrome.js way - it requires very deep knowledge and continuous struggling around inner codes of Firefox itself. The answer is buried there: https://searchfox.org/mozilla-central/ Of course I can investigate that by myself (yes it is one of my job) but I have no private motivation about such a futureless thing... Instead I recommend you file feature requests to bugzilla.mozilla.org to add genuine WebExtensions APIs to do something currently impossible.

**Comment by piroor** [comment]
Oops I forgot to answer to the subject of this issue. Sorry but I have no plan to add such an menu command as a built in feature, because Firefox's tab context menu does not have that and it beyonds the project scope of TST.

**Comment by aminomancer** [comment]
> 
> 
> There are some existing addons providing "recently closed tabs" menu to the tab context menu working with TST completely:
> 
>     * [Undo Close Tab](https://addons.mozilla.org/firefox/addon/undoclosetabbutton/)
> 
>     * [Undo Closed Tabs Menu](https://addons.mozilla.org/firefox/addon/undo-closed-tab-menu/)
> 
> 
> I've looked the userChrome.js script and I thought that the functionalities can be implemented via WebExtensions API. The method [sessions.getRecentlyClosed()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/getRecentlyClosed) returns both closed tabs and windows. Thus you can provide a "recently closed windows" menu, with a filtered results of the method.
> 
> I cannot recommend you to do like that with the userChrome.js way - it requires very deep knowledge and continuous struggling around inner codes of Firefox itself. The answer is buried there: [searchfox.org/mozilla-central](https://searchfox.org/mozilla-central/) Of course I can investigate that by myself (yes it is one of my job) but I have no private motivation about such a futureless thing... Instead I recommend you file feature requests to bugzilla.mozilla.org to add genuine WebExtensions APIs to do something currently impossible.

In case you were curious, I did eventually manage to [make it work](https://github.com/aminomancer/uc.css.js/blob/master/script/undoListInTabContextMenu.uc.js) without the extensions API. Though you're right, this one really was a constant struggle lol.

Btw, while I'm here, I noticed that the TST icon on the sidebar switcher target supports `-moz-context-properties` now, which is great. But the same icon appears in the "Tree of tabs" menuitem in the context menu, which doesn't have any fill or -moz-context-properties defined. So for me it's a black icon on a dark blue background. I fixed it for my own purposes but I was wondering if this is because it's impossible for you to set the style of the menuitems with an extension.

I don't know if there are any variables exposed to extensions that reflect global attributes like `lwtheme-textcolor="bright"` but I've seen other extensions that actually swap PNG images based on the theme, so they couldn't be relying on `-moz-context-properties` to do that. I suppose you could run a media query for `prefers-color-scheme`, it's not a perfect reflection of the UI theme but it's probably better than nothing. Then instead of setting the fill you could just swap between an icon with hardcoded black and an icon with hardcoded white fill. Anyway that's just a minor issue, just thought I'd send some feedback while it's on my mind.

**Comment by piroor** [comment]
@aminomancer I've tried dynamically generated SVG icon and it looks to work as expected, thus I've introduced a change 702376c to apply the icon color or the text color defined by the active theme without `context="fill"`. Thanks!

**Comment by aminomancer** [comment]
Awesome, looks like a great change

**Comment by irvinm** [comment]
@mzso can you close this item given there are workarounds and there is no planned work?

**Comment by irvinm** [comment]
@piroor I think this can be closed.

**Comment by mzso** [comment]
[**@aminomancer**](https://github.com/aminomancer) commented on [Apr 28, 2021, 6:38 AM GMT+2](https://github.com/piroor/treestyletab/issues/2873#issuecomment-828137625 "2021-04-28T04:38:29Z - Replied by Github Reply Comments"):
> In case you were curious, I did eventually manage to [make it work](https://github.com/aminomancer/uc.css.js/blob/master/script/undoListInTabContextMenu.uc.js) without the extensions API. Though you're right, this one really was a constant struggle lol.
> 

I've been using it ever since. However it unfortunately broke when I upgraded to dev edition 116 from 109. The menu items don't appear in TST's only the default tab context menu. But even there the one for the closed tabs is broken and doesn't show any items.

I tried recentlyClosedTabsContextMenu.uc.js as well, which I guess is newer. However with this nothing appeared in either of the context menus.

**Comment by aminomancer** [comment]
> I tried recentlyClosedTabsContextMenu.uc.js as well, which I guess is newer. However with this nothing appeared in either of the context menus.

[The script](https://github.com/aminomancer/uc.css.js/blob/master/JS/recentlyClosedTabsContextMenu.uc.js) is updated pretty routinely to account for changes in the Firefox source code that would otherwise break the script. So in order to keep it working in Firefox Nightly, I often have to update the script in ways that make it stop working in older versions of Firefox. The dev edition is basically beta with some different default preferences. And there will often be times when my scripts don't work in beta, because beta is effectively 1 to 24 days behind nightly. And beta 116 is 2 versions behind 118 anyway, which is what nightly is on currently.

So if you want these scripts to work reliably you'll have to use the Nightly release channel. Then if you notice something stopped working, try updating Firefox and the scripts. If it's still not working, you can wait a couple days to see if I upload a new version, or you can [file a bug report](https://github.com/aminomancer/uc.css.js/issues/new/choose) on my repo. I made a [script manager](https://github.com/aminomancer/uc.css.js/tree/master#aboutuserchrome) to help with that process, but unfortunately it seems to suffer from a memory leak of some kind, so I don't recommend using it right now unless you fully quit/restart Firefox a lot. If you leave Firefox open when you put your OS to sleep, don't use the script manager.

**Comment by mzso** [comment]
@aminomancer Hm. Going in the other direction, I can dig up older versions, right?
FF117 broke way too many things for the time being. I guess 116 should be around mid June, right?

**Comment by aminomancer** [comment]
Yes, you can use older versions, but that alone won't necessarily fix your problem. Try rolling back to 116 and then, from there, try [older versions](https://github.com/aminomancer/uc.css.js/commits/master/JS/recentlyClosedTabsContextMenu.uc.js) of the script until it works. When you change scripts you have to clear the startup cache btw.

**Comment by mzso** [comment]
@aminomancer Okay. Thanks!

**Comment by mzso** [comment]
[**@aminomancer**](https://github.com/aminomancer) commented on [Aug 23, 2023, 8:36 PM GMT+2](https://github.com/piroor/treestyletab/issues/2873#issuecomment-1690449413 "2023-08-23T18:36:13Z - Replied by Github Reply Comments"):
> Yes, you can use older versions, but that alone won't necessarily fix your problem. Try rolling back to 116 and then, from there, try [older versions](https://github.com/aminomancer/uc.css.js/commits/master/JS/recentlyClosedTabsContextMenu.uc.js) of the script until it works. When you change scripts you have to clear the startup cache btw.

Well, I tried going back all the way to 2.0.5 form june 2022, but none of the versions display any of the menus everywhere.
To be fair only the latest was released after [FF116 went to nightly](https://wiki.mozilla.org/index.php?title=Release_Management/Calendar&redirect=no) on 2023-06-05.
But none did even what the ancient version from 2021 does, showing the broken closed tabs menu and the working closed windows menu on the tab bar context menu.

Maybe FF116 was never made compatible? Which is sad for me and also because it was the stable up till a few days ago.
