### ISSUE TITLE
[Linux] Vague landing borders upon tab dragging

### ISSUE THREAD

**Issue by sakkamade** [piroor/treestyletab#2901]
Good day.

## Short description
The landing lines visible only for a few moments, what makes tab's dragging quite undetermined.  

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create some tabs
 4. Drag some tabs

## Expected result
I would like to see persistent borders to exactly understand where the tab will land.

## Actual result
The landing borders are visible only for a moment.

https://user-images.githubusercontent.com/62730422/118780652-cb865a00-b87b-11eb-9bc7-62cdfa37bb50.mp4

## Environment

 * Platform (OS): Arch Linux, KDE
 * Version of Firefox: 88.0.1 (64-bit) 
 * Version (or revision) of Tree Style Tab: 3.8.1

**Comment by irvinm** [comment]
I primarily use Windows and have no problems, but I fired up Ubuntu (TST 3.8.1 \ FF 88) and see the exact same thing.  @piroor it looks like both the landing line and the landing box get displayed initially, but then disappear even if you don't move the mouse.

**Comment by piroor** [comment]
Thanks! The behavior was introduced as a failsafe for cases when a drag operation is accidentally canceled without clearing the drop position marker. On other platforms the clearing does not happen while dragging, because "dragover" event is fired repeatedly while the cursor is hovering on a tab. I forgot that "dragover" is not repeated on Linux. With the commit 6ed6ce6 TST doesn't clear the position marker with delay on Linux.

**Comment by sakkamade** [comment]
Let's consider it is fixed then.

I will test when I have a time.

**Comment by sakkamade** [comment]
Yes, may confirm that it works great now.
