### ISSUE TITLE
Feature request: control focus after tab closing

### ISSUE THREAD

**Issue by franckspike** [piroor/treestyletab#2910]
I would like TST to give focus to the parent tab when closing its last child.
And to focus on the next child if any.

But this should be fully configurable!

Thank you

**Comment by travisterrell** [comment]
This is the way it would naturally work to me as well, but I understand why they chose not to override the default browser behavior. Also, in my opinion this behavior should only occur when the TST pane is visible.

I'm not a dev on this particular project, but maybe you could explain what you meant by _fully configurable?_ I can't think of m(any) other possibilities. It would seem a simple on/off would probably be sufficient (and certainly less work, ha.)

**Comment by irvinm** [comment]
@franckspike I might suggest looking into https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/.  This pretty much tries to accomplish what you are looking for.

**Comment by franckspike** [comment]
@travisterrell I'm not really sure if another configuration would be useful in real life other than "FF's default" or "go to left sibling else parent"… maybe "go to parent always" ?  or "go previous tab always" ?  or maybe "last sibling else parent" ?  or maybe "go to first child, else left sibling, else parent" ?  

I'm seeing a pattern here:

A sequence of combo boxes ordered by preference each having these options:
 - FF's default
 - first child
 - last child
 - next sibling
 - previous sibling
 - parent
 - previous (displayed tab)

My setting would be
 1- first child
 2- next sibling
 3- parent
 4- previous (displayed tab)
 5- FF's default

Plus, this new configuration section would cover other configurations elsewhere, so we could replace them with this new section maybe

**Comment by franckspike** [comment]
@irvinm well… I am just realizing the addon is not only similar be exactly what I was proposing loll

**Comment by piroor** [comment]
Sorry I won't increase number of options about this point, so this issue is "won't fix" on this TST project

However it looks to be done with a helper addon for the purpose, newly developed by someone (or you). There are some hints:

* Firefox provides "successor tab API". For more details, please see [my article about the API](https://qiita.com/piroor/items/ea7e727735631c45a366). 
* TST provides [an API to get tree information of a tab](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#get-tree-information-for-specific-single-tab).
* There is an existing helper addon controlling successor tabs: [TST Focus Preceding Tab On Close](https://addons.mozilla.org/firefox/addon/tst-focus-preceding-tab/) ([repository](https://github.com/giantoppai/TST-Focus-Preceding-Tab-On-Close)).

**Comment by irvinm** [comment]
@franckspike would you mind closing this item?

**Comment by franckspike** [comment]
alright then, I'll try the above addons or just fork from one and create a new one if I can't find what I'm looking for

I'm not sure if there's a place where to list new TST addons !?

Thank you!

**Comment by piroor** [comment]
Pull requests to update the list https://github.com/piroor/treestyletab/blob/trunk/README.md#addons-that-extend-tst are welcome!
