### ISSUE TITLE
why is there no information in the documentation about the location of userChrome.css?

### ISSUE THREAD

**Issue by jt3k** [piroor/treestyletab#2916]
I have a question and suggestion.

# [1/2] Suggestion
provide simple instructions to 100% hide the horizontal tab bar.

instead of imperative instructions in your article, add simple declarative commands that are necessary to achieve the goal.

Your article on hiding native tabs is just a nightmare for a reader who wants to solve a problem and not feel humiliated.

I read your article earlier, and on my work computer I managed to hide the tabs. It seems that I succeeded by finding the answer to the question in Google, and not in your github.

And now I cannot get results.

# [2/2] Question

I want to hide the horizontal tab bar.

1. I found a mention on the Internet that userChrome.css may be there. "~/Library/Application\ Support/Firefox/Profiles/"
I have here two directories with profiles and I chose the one with the latest modification date (today).
2. There was no userChrome.css file in the directory, and I created it.
3. Inside I placed the lines indicated in [your article](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-userchromecss) for hiding tabs.
4.also i set in about:config `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`

after restarting firefox, I still see a horizontal tabbar strip

what am I doing wrong?

intel mac
macos bigsur
firefox 89

**Comment by irvinm** [comment]
@jt3k as for your suggestion, there are several ways to hide the horizontal tab bar and that has also changed over time due to changes in Firefox.  I looked at what I was using and it is completely different than what is documented on the wiki.  In general, people can contribute to the wiki and help keep that information up to date.  A good source of information like this is on reddit at [r/FirefoxCSS](https://www.reddit.com/r/firefox/).  However, I do believe what is posted on the wiki should work.  (It is possible you are in the wrong directory or maybe you have userChrome.css.txt if you have extensions hidden ... or something like that)

As for your question, to get a definitive answer to where your profile folder is located:  Go to about:profiles in the URL bar, find the profile that says "This is the profile in use and it cannot be deleted" and look at the folder next to "root folder".

**Comment by piroor** [comment]
Please remind that basically I don't recommend hiding the native tab bar. TST's sidebar does not support full features of the native tab bar due to restrictions of WebExtensions API, and I don't believe TST is enough stable to replace Firefox's tab bar completely. I usually use TST together with horizontal tab bar, and never hide the horizontal tab bar for safety.

If I hid the tab bar on my environment in my daily use, I might maintain userChrome.css hack codes, but actually I don't do that. So guidance to hide the tab bar need to be maintained by people who really use. I think it is a nightmare for regular people who don't know how to research and find out solutions with debugger. I intentionally don't describe details how to hide the horizontal tab bar, to save people from critical troubles.

I say again, I don't recommend you to hide the horizontal tab bar if you cannot write any suitable userChrome.css hack by yourself. I have no motivation to investigate how to hide the horizontal tab bar, because I'll never do that and it may lead people to troubles.

**Comment by irvinm** [comment]
@jt3k will you close this item?  There is nothing to do on the TST side.  If you still wanted to continue this as a new "discussions" section, I think that would be ok.
