### ISSUE TITLE
Issues/questions regarding Export/Import and sync devices

### ISSUE THREAD

**Issue by Gitoffthelawn** [piroor/treestyletab#2935]
I'm not sure if any of the following indicates one or more underlying issues, or if everything is "by design".

All testing performed with TST v3.8.2 on Firefox 89 in Windows.

If I perform a TST `Reset All` and then immediately perform an `Export`, this is the result:

```
{
  "optionsExpandedSections": [
    "section-appearance",
    "section-debug"
  ],
  "syncDeviceInfo": {
    "id": "device-[epoch time #1]-[5 digit integer #1]",
    "name": "Firefox on Windows",
    "icon": "device-desktop"
  },
  "syncDevices": {
    "device-[epoch time #2]-[5 digit integer #2]": {
      "id": "device-[epoch time #2]-[5 digit integer #2]",
      "name": "Firefox on Windows",
      "icon": "device-desktop"
    }
  },
  "syncDevicesLocalCache": {
    "device-[epoch time #2]-[5 digit integer #2]": {
      "id": "device-[epoch time #2]-[5 digit integer #2]",
      "name": "Firefox on Windows",
      "icon": "device-desktop"
    }
  },
  "userStyleRulesFieldHeight": "130px"
}
```

If I then close Firefox and restart Firefox, 2 notification boxes appear.  If I close both those notification boxes without performing any actions, and then perform a TST `Export` the exported data changes significantly.  It is now:

```
{
  "chunkedUserStyleRules0": "...long string...",
  "configsVersion": 24,
  "notifiedFeaturesVersion": 8,
  "optionsExpandedSections": [
    "section-appearance",
    "section-debug"
  ],
  "syncAvailableNotified": true,
  "syncDeviceInfo": {
    "id": "device-[epoch time #1]-[5 digit integer #1]",
    "name": "Firefox on Windows",
    "icon": "device-desktop",
    "timestamp": [epoch time #4]
  },
  "syncDevices": {
    "device-[epoch time #2]-[5 digit integer #2]": {
      "id": "device-[epoch time #2]-[5 digit integer #2]",
      "name": "Firefox on Windows",
      "icon": "device-desktop"
    },
    "device-[epoch time #3]-[5 digit integer #3]": {
      "id": "device-[epoch time #3]-[5 digit integer #3",
      "name": "Firefox on Windows",
      "icon": "device-desktop",
      "timestamp": [epoch time #4]
    }
  },
  "syncDevicesLocalCache": {
    "device-[epoch time #2]-[5 digit integer #2]": {
      "id": "[epoch time #2]-[5 digit integer #2]",
      "name": "Firefox on Windows",
      "icon": "device-desktop"
    },
    "device-[epoch time #3]-[5 digit integer #3]": {
      "id": "[epoch time #3]-[5 digit integer #3]",
      "name": "Firefox on Windows",
      "icon": "device-desktop",
      "timestamp": [epoch time #4]
    }
  },
  "syncOtherDevicesDetected": true,
  "userStyleRules": "",
  "userStyleRulesFieldHeight": "130px"
}
```

Observations/questions:

1. The Firefox profile has no syncing and no account.  Should any of these sync devices be created by TST?
1. What is the meaning of the contents of "syncDeviceInfo", "syncDevice", and "syncDevicesLocalCache" sections?
1. What are the 5 digit integers after the epoch times?
1. There appears to be a bug in which new devices are created after closing Firefox and restarting it.
1. "configsVersion" is included in the second export, but not the first.  Likely a small bug.
1. "chunkedUserStyleRules0", "userStyleRules", and "userStyleRulesFieldHeight" items are created for the second export even though they have not been modified.  In contrast, all the other unmodified settings are not exported.
1. Is an `Import` action the same as `Reset All and then Import` or `Import and only change settings contained in the import file`.  Deciding on this will likely impact whether or not it is best to include the settings listed in the previous item when they are unchanged.

Thanks for all your hard work on this fabulous extension!  I hope this testing and all the details are helpful to you.

**Comment by piroor** [comment]
> 1. The Firefox profile has no syncing and no account. Should any of these sync devices be created by TST?

Yes, it is not related to the device name of Firefox Sync. Firefox doesn't provide any WebExtensions API to get information about Firefox Sync, so TST manages synchronized devices by itself.

> 2. What is the meaning of the contents of "syncDeviceInfo", "syncDevice", and "syncDevicesLocalCache" sections?

`syncDeviceInfo` is the identifier information of the current device. `syncDevice` will have a list of `syncDeviceInfo` synchronized from all your sync devices. `syncDevicesLocalCache` is a copy of `syncDeviceInfo`, the only one difference between them is: `syncDevicesLocalCache` won't be synchronized across devices. When Firefox Sync synchronizes  `syncDeviceInfo` from your another device, TST detects new other devices not listed in `syncDevicesLocalCache`.

> 3. What are the 5 digit integers after the epoch times?

It is a random number added for safety. Even if TST instances on different devices generates their `syncDeviceInfo` at just same time, the added rundom number should make them unique.

> 4. There appears to be a bug in which new devices are created after closing Firefox and restarting it.

Thanks, this is a bug and the commit 405dfdc should fix it.

> 5. "configsVersion" is included in the second export, but not the first. Likely a small bug.

Thanks, this is a bug also. The commit 1c702f4 should fix it.

> 6. "chunkedUserStyleRules0", "userStyleRules", and "userStyleRulesFieldHeight" items are created for the second export even though they have not been modified. In contrast, all the other unmodified settings are not exported.

`chunkedUserStyleRules0` and `userStyleRules` are initialized on the migration process. After the commit 1c702f4 they are initialized just after you reset all configs, so you'll see stable result between second and third exporting.

On the other hand `userStyleRulesFieldHeight` is updated after the options page is loaded. (The updating process is triggered by the initialization of the rich text editor, and it won't be processed on reset.) It is `10em` by default, and when the options page is loaded it will be instantiated to `120px` or any corresponding pixel value.

> 7. Is an Import action the same as Reset All and then Import or Import and only change settings contained in the import file .

The expected behavior is "reset and import", and initial migration should not affect to this operation. Recent changes and one more b6de1f1 should do that, thank you for mentioning.

**Comment by Gitoffthelawn** [comment]
Thank you for all the answers, confirming the bugs I found, and issuing patches!  Wow!

I need to spend a little more time reading everything you wrote a couple more times and then I may have some more feedback.

Thank you for thanking me for finding and reporting the bugs.  It's nice to feel appreciated, and I certainly appreciate all your efforts as well!

**Comment by irvinm** [comment]
@Gitoffthelawn make sure to close this when things are resolved.  Thanks.

**Comment by irvinm** [comment]
@Gitoffthelawn just a friendly reminder.

**Comment by irvinm** [comment]
@piroor I think this can be closed.
