### ISSUE TITLE
Export/Import of "migratedBookmarkUrls"

### ISSUE THREAD

**Issue by Gitoffthelawn** [piroor/treestyletab#2937]
I noticed that the export files may contain a section called "migratedBookmarkUrls" that contain the temporary GUID of the installed copy of TST.

I only partially understand the function of that section, and why it is included in the exports (please feel free to explain in more detail!), but I wanted to make sure you considered the following cases that aren't obvious:

1. Install TST in a new Firefox profile.
2. Perform the necessary steps to have the "migratedBookmarkUrls" section included in the export file.
3. Export TST data.
4. Uninstall TST.
5. Close Firefox.
6. Open Firefox in the same profile.
7. Install TST.
8. Import the exported TST data file.
9. Since the GUID of TST has now changed, will the now-erroneous data in "migratedBookmarkUrls" cause any issues?  Does anything need to be done to handle this case?
10. Create a new Firefox profile.
11. Repeat steps 7-9.

**Comment by piroor** [comment]
The purpose is described here: https://github.com/piroor/treestyletab/blob/b6de1f171a639d14c40e202bd481fdd739842218/webextensions/background/migration.js#L295-L301

It is exported and imported because I designed the configs library lazily to import/export all config keys without any exception. However I think it is not dangerous. `migratedBookmarkUrls` just stores URLs no need to be migrated anymore, for better startup performance. Even if it is overridden with blank value or any imported value containing GUID not matching to the running TST instance's GUID, it just means that the startup migration will be done again, so it won't be processed two or more times. (On the other hand, bookmarks created, updated, or synchronized while TST is running will be updated dynamically unrelatedly to `migratedBookmarkUrls`.)

**Comment by piroor** [comment]
I think it is impossible to cleanup needless `migratedBookmarkUrls` values, because TST cannot detect which case was happeed about an updated `migratedBookmarkUrls`:  "synced from other devices" or "imported from a file".

**Comment by irvinm** [comment]
Given that this really can't be resolved, can we close this item?  (@Gitoffthelawn \ @piroor)

**Comment by Gitoffthelawn** [comment]
@piroor Sorry I've been so busy lately.  When importing TST settings into a new Firefox profile, what sections of the export file do you recommend deleting before performing the import, if any?

**Comment by irvinm** [comment]
@Gitoffthelawn based on piroor's response ("Even if it is overridden with blank value or any imported value containing GUID not matching to the running TST instance's GUID, it just means that the startup migration will be done again, so it won't be processed two or more times."), it sounds like you don't need to delete anything before performing an import.

It also sounds like if you did delete anything (or even everything) in that section, it would just do the startup migration again as that GUID wouldn't be found.

**Comment by piroor** [comment]
@Gitoffthelawn Here is a list of locak config keys they won't be synchronized between devices via Firefox Sync: https://github.com/piroor/treestyletab/blob/1b63e60c2fe193937471d0222255c4461f8f72ba/webextensions/common/common.js#L13-L68 They are used to store temporary data or platform specific status.

* I recommend you to delete them before importing if you hope to transfer it across devices.
* You don't need to delete them if you plan to use the exported data just as a backup and import it on the same device.

**Comment by Gitoffthelawn** [comment]
@piroor Thank you for that list.  Do you also recommend deleting `migratedBookmarkUrls` and/or anything else (when transferring across devices)?

**Comment by piroor** [comment]
With the commit 64f1396 I've introduced a change to sanitize imported and exported data. `migratedBookmarkUrls` won't be imported and exported anymore.

**Comment by Gitoffthelawn** [comment]
Wonderful! Thank you!  I look forward to it.
