### ISSUE TITLE
[Proposal] A better Drag'n'Drop concept

### ISSUE THREAD

**Issue by I60R** [piroor/treestyletab#2949]
I hate how current Drag'n'Drop works: it's so frustrating and irritating for me to sort tabs with it, especially in how time-consuming and error-prone this simple task could become. However, I do have a large number of tabs, did made tabs smaller with custom CSS, and use some trees as a sort of bookmarks folders, so excuse me if this sound so harsh while it might be mostly my fault that it doesn't work as I expect.

Anyway, I come up with D'n'D concept that seems to work for everyone:

- You long press on a tab or selection or start dragging something, which hence activates D'n'D
- If you release the button — nothing happens, draggable item(s) are still under the cursor
- In this mode you're still able to:
  - Click on other tabs to activate them, expand/collapse trees, etc.
  - Ctrl/Shift + click on other tabs to add them to selection
  - Middle click on them to close or activate any other action set in preferences
  - Right-click to activate menu & use it
  - Scroll
  - Do whatever other action you able in regular mode
- Then hover on a target tab and long press on:
  - Left button -> to drop item(s) below it
  - Middle button -> to drop item(s) above it
  - Right button -> to drop item(s) underneath it
- Otherwise hitting Esc cancels the dragging mode

Despite unfamiliar, this seems to be much more efficient at least because it wouldn't require an effort to hold left button during the whole drag time and wouldn't depend on such timing and precision required currently to choose the place where to drop items(s). You would also have a full control over the tree thus reaching deeply nested or long-distanced targets would be much easier. 

Although, the current D'n'D is certainly better for reordering nearby tabs, that still in my case isn't a common usage and it seems to be much more efficient with move-upward/move-downward shortcuts instead.

Ultimately, the new behavior might be easily explained in tab drag notification.

---

So, is something like that doable? With plugin? Or maybe I miss something and it has no sense at all?

**Comment by piroor** [comment]
Sorry but I won't implement such complex actions as a built-in feature, because it looks to be not compatible to any other existing application. Currently TST respects generic behavior of tree operations in other well-known applications - Firefox's folder tree, Windows Explorer's folder tree, Adobe Illustrator's layer tree, and so on. Basically I want to keep TST as "no need to study how to use it specially".

Instead I recommend you to implement those proposed behaviors to a separate helper extension. Your extension may control Firefox's tabs and TST's tree structure via its API https://github.com/piroor/treestyletab/wiki/API-for-other-addons and general WebExtensions API.

**Comment by irvinm** [comment]
@piroor I think this can be closed.

**Comment by I60R** [comment]
Today I moved one tab from the top of my tree to the bottom while a very large tree was expanded in the middle. Since the scrolling wheel is unavailable during drag and TST scrolls veeery slowly when an object is placed on an edge of sidebar it took nearly 30 seconds to finish. This is certainly incomplete and hostile UI for a large number of tabs.

@piroor could be there at least "Drop selected tab(s) here" menu item, so we can just select tabs then hover on target and select this without dragging anything? For me that would be a huge usability improvement.

When speaking about consistency with other applications: I will never do the same movement with Drag'n'Drop but with Cut'n'Paste instead which TST unfortunately lacks. What I propose might be a sufficient enough substitution which other users may appreciate as well.

**Comment by piroor** [comment]
Sadly the unavailable wheel problem can't be solved by addon side because Firefox doesn't notify wheel events while in a drag session.

I agree that it is reasonable to imitate cut-and-paste for tabs. But it still be beyond TST's project scope. I think it is the best way that a new extension named like "Cut and Paste Tabs" is published (it sounds good to be published as an independent extension, for people who use horizontal tab bar or other vertical tab bar extensions) and TST becomes compatible.
