### ISSUE TITLE
Tabs jump back and forth due to built in theme change

### ISSUE THREAD

**Issue by sparkitus** [piroor/treestyletab#2952]
## Short description
Commit 561776d breaks TST for me. I get all the tabs jumping to the right when vertically shrinking a window past the point when they all fit on the screen, and they jump to the left when going back again. Backing out the code change or completely removing the workaround code fixes it for me. Related to #2852 
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select Photon, Proton or High Contrast Themes
 4. Shrink (or enlarge) a window vertically with lots of tabs
 5. Tabs jump to the right (or left)

## Expected result
Tabs stay still.

## Actual result
Tabs jump about

## Environment

 * Platform (OS): OSX
 * Version of Firefox: 89
 * Version (or revision) of Tree Style Tab: 3.8.3

**Comment by piroor** [comment]
Do you mean about "jumping" of tab elements repeatedly? I couldn't reproduce the problem on my MacBook. It looks need  more conditions like custom user styles.

Otherwise, it is by design and expected. On macOS Firefox shows scrollbar over contents on scrollable element, and it covers "twisty" of tabs (button to collapse/expand tree). To keep accesibility to twisty in tabs, TST is designed to shift elements in tabs when the sidebar is scrollable.

**Comment by sparkitus** [comment]
Thank you for making such a great extension! 
Sorry for not explaining well enough.  Here are some images of what I am talking about (left bad, right good):
![mac](https://user-images.githubusercontent.com/86236418/124387775-55c13b00-dccf-11eb-9e7d-f21ba199904f.gif) ![lin](https://user-images.githubusercontent.com/86236418/124388005-3d055500-dcd0-11eb-9551-57b68a8e14b2.gif)
There are two related things here. The first is when using Preferences>Advanced>Extra style rules to set #tabbar.overflow to something, such as #tabbar.overflow { scrollbar-width: none; }. The commit 561776d breaks the use of this as it added #tabbar.overflow to several style themes:
:root.platform-mac.left #tabbar.overflow tab-item:not(.pinned) {
There is no need to move the tab elements when this is set. The two images above are default profiles running Photon with #tabbar.overflow { scrollbar-width: none; }: the one on the left is on OSX, the right Linux. 
The second is if the code is removed (the mac workaround code from the commit) by adding the the whole default Photon profile set to TST prefs and commenting the workaround out (no additional prefs, no tabbar.overflow). When this is done the tab elements still move to the right when the scrollbar appears (this matches the default Linux system behavior), so the code appears redundant maybe? .
A temporary workaround is to set 
:root.platform-mac.left tab-item:not(.pinned) { ...
in advanced prefs.

**Comment by piroor** [comment]
Thanks, I got what happened.

Sorry but custom user styles sometimes become broken due to changes of TST itself, this is one of unavoidable risk of the custom user styles feature. I try to keep compatibility as possible as I can for known custom user styles, but I sometimes introduce breaking changes intentionally like b8e919b85cafd4507b79adad7620072aa1f3e9a1, then you may need to update your user styles manually.
