### ISSUE TITLE
post 3.8.4 regression: no bottom border on the top of the tab bar photon styled new tab button

### ISSUE THREAD

**Issue by bughit** [piroor/treestyletab#2961]
## Short description

no bottom border on the top of the tab bar photon styled new tab button

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Switch to TST photon style
 4. [put the new tab button at the top](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#put-new-tab-button-at-the-top-of-the-tab-bar-1376)

## Expected result
3.8.4: new tab bottom border
![image](https://user-images.githubusercontent.com/895588/124694260-e30eb600-deae-11eb-9e14-e088dd998103.png)

## Actual result
3.8.6: no new-tab bottom border
![image](https://user-images.githubusercontent.com/895588/124694439-40a30280-deaf-11eb-916b-65445f0af81f.png)

## Environment

 * Platform (OS): win10 21h1 x64
 * Version of Firefox: 89.0.2 x64
 * Version (or revision) of Tree Style Tab: 3.8.6

**Comment by piroor** [comment]
I've updated the snippet.
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#put-new-tab-button-at-the-top-of-the-tab-bar-1376

This kind incompatibility won't be "fixed" by TST, instead user styles should be updated.

**Comment by bughit** [comment]
There are some styles like this one that deserve to be incorporated into the settings. If you're changing the color or the size of something, there's an huge spectrum of subjective choices, so that can be a user style. But a binary choice between top and bottom new button placement is more significant/important/valuable. There's a more objective reason for the choice (top placement), it fixes the position of a frequently used button making it easier/quicker to get to.

**Comment by piroor** [comment]
I agree that it will be useful for some people, but I need to decide accepting or rejecting feature requests, sorry. I've updated the FAQ topic "Add more minor/trivial options" under the section ["feature requests"](https://github.com/piroor/treestyletab#feature-requests). Here is a cited list of policies about decisions:

* If Firefox has the option, TST also should provide similar option to emulate it. (ex. `browser.tabs.closeTabByDblclick` emulation, `browser.tabs.seleectOwnerOnClose` emulation, warnings for closing multiple tabs, style switch for leftside/rightside sidebar)
* If TST imitates Firefox's UI and Firefox doesn't provide any options to control them, TST basically don't provide options for them. (ex. visibility options for imitated context menu commands)
* If it is essential for accessibility, TST should provide the option. (ex. text direction option, animation effects, "High Contrast" theme, color switch for the toolbar button icon)
* If it is impossible to be done via simple CSS tricks, TST should provide the option. (ex. unfaviconizing of pinned tabs, positioning options for new tabs, drag-and-drop behavior)
* If it is already available during combination with another extension, TST don't provide options for them. (ex. coloring of tabs, suspending of tabs, detailed control of tab focus)

Please remind that some existing options may violate these policies due to historical reasons.
