### ISSUE TITLE
About the access to translation

### ISSUE THREAD

**Issue by NightSharp** [piroor/treestyletab#2990]
I want to update one of the message.json
but the web-ext-translators seems not be able to do this as before.
I input the URL but the website do nothing.
And items on GitLocalize are incomplete.
several items are not be contained in it.

**Comment by piroor** [comment]
Thanks! For a long time the task was stuck because I couldn't synchronize latest locale resources to GitLocalize. After some struggling I finally realized that a project on GitLocalize is bound to a specific branch and it must be recreated if the target branch need to be changed. Thus I've recreated treestyletab project on GitLocalize: https://gitlocalize.com/repo/6376 Could you try with it?

**Comment by piroor** [comment]
One more:  the description for web-ext-translator was wrong: the URL must contain the branch name. I've updated that: https://github.com/piroor/treestyletab/blob/trunk/webextensions/_locales/README.md#translation-on-a-web-service

**Comment by NightSharp** [comment]
> 
> 
> Thanks! For a long time the task was stuck because I couldn't synchronize latest locale resources to GitLocalize. After some struggling I finally realized that a project on GitLocalize is bound to a specific branch and it must be recreated if the target branch need to be changed. Thus I've recreated treestyletab project on GitLocalize: https://gitlocalize.com/repo/6376 Could you try with it?

OK, Thanks
