### ISSUE TITLE
Can't reorder Tabs anymore.

### ISSUE THREAD

**Issue by robert-synofzik** [piroor/treestyletab#2997]
Hi, 

I can't rearrange Tabs anymore on FF 91.0.2 on  MacOS 11.5.2

I have no idea how to reproduce it.

Any ideas?

**Comment by irvinm** [comment]
@robert-synofzik are you still having this issue?  I haven't seen anyone else (Mac or not) have any issues with reordering tabs recently.  If you create a new profile (to test), does that work for you?

**Comment by irvinm** [comment]
@piroor #WorksForMe, #HelpWanted, #Stale

**Comment by piroor** [comment]
@robert-synofzik  I couldn't reproduce this problem. Could you try following workarounds if you see this problem again?:

* Switch the sidebar to Bookmarks (or others) and try dragging of bookmark items. Is that available? Then switch the sidebar back to TST again and try moving tabs please.
* Go to `about:addons` (the add-ons manager), disable TST, and re-enable TST. After that try moving tabs please.

**Comment by baszoetekouw** [comment]
I am also experiencing this issue on MacOS 12.1. I'm pretty sure dragging and reordering tabs has worked before, but now I can't reorder tabs nor drag them to another windows.

Regarding @piroor 's workarounds:
 - Dragging bookmarks in the Bookmarks sidebar also doesn't work.  Does that mean this is an issue with Firefox rather than with this extension, perhaps?
 - Disabling/reenabling the addon doesn't make any difference.

On futher inspection, it seems drag and drop is totally broken.  For example, the html drag&drop example from https://www.w3schools.com/html/html5_draganddrop.asp also doesn't work , nor does dragging a file from the finder to Firefox.
