### ISSUE TITLE
Clicking X next to last tab on bottom of the list sometimes doesn't close the tab

### ISSUE THREAD

**Issue by rieje** [piroor/treestyletab#3024]
Clicking X to close the last tab on bottom of the list sometimes doesn't close the tab. It may also be the last few tabs at the bottom of the list, but I am sure I have never experienced this problem with closing tabs the same way when they are in the middle or the top of the list. As a I result, I need spam click briefly to close it. Ctrl+W to close the tab always works fine, so I'm thinking thinking this may be a TreeStyleTab issue. I use the addon for many years and it was only until I switched to Wayland (Linux, using Sway compositor) from X that this problem occurs. I've experienced this since ~4 months ago after the switch to Wayland.

I'm not able to reproduce the problem, it happens seemingly random and frequently enough on both my desktop/laptop machines for this to be mildly annoying. 

**EDIT**: Does not necessarily apply to last tab--applies to at least the last 2 tabs and includes clicking the tab itself, which means not just closing the tab but focusing it.

 * Platform (OS): Wayland (Sway)
 * Version of Firefox: 92.0
 * Version (or revision) of Tree Style Tab: 3.8.12

**Comment by piroor** [comment]
When the problem happens, could you try following steps?:

1. Switch the sidebar to Bookmarks.
2. Click bookmark items at bottom of the sidebar to confirm it is clickable or not.
3. Switch back the sidebar to TST.
4. Click "x" button in the bottom tab again to confirm it is available or not.

If both Bookmarks and TST sidebars don't respond to click events at bottom area, it looks to be a bug of Firefox or the environment.

Otherwise, something invisible element covers bottom tabs on such situations. Could you try inspecting the unclickable area when the problem happens?:

1. Go to `about:debugging`.
2. Switch to "Extensions".
3. Click "Inspect" of TST item.
4. Choose "sidebar.html" from the lsit of the window chooser (the button 2nd from the top-right edge of the debugger).
5. Choose "Inspector" tab of the debugger.
6. Click the "Pick an element" button (the button leftside of the "Inspector" tab).
7. Click the "x" button of the bottom tab in the sidebar.
8. Take a screenshot of the inspector and paste it here.

If the inspector doesn't choose anything, you may need to do same inspection with the browser debugger (for Firefox itself.)

1. Hit the F12 key to open the web tools.
2. Hit the F1 key to open the settings tab of the web tools.
3. Scroll down the settings tab and turn checkboxes "Enable browser chrome and add-on debugging toolboxes" and "Enable remote debugging" on.
4. Hit a keyboard shortcut Ctrl-Alt-Shift-I to open the browser toolbox. If it asks you to allow remote debugging, you need to grant it.
5. Choose "Inspector" tab of the browser toolbox.
6. Click the "Pick an element" button (the button leftside of the "Inspector" tab).
7. Click the "x" button of the bottom tab in the sidebar.
8. Take a screenshot of the inspector and paste it here.

**Comment by rieje** [comment]
On paying closer attention, I think this might be a Firefox-related issue. Besides the side tab bar, the bottom may also be occurring at the bottom portion of any part of the Firefox window (e.g. buttons at the bottom part of a webpage), though it seems less frequent.

Closing for now.
