### ISSUE TITLE
Send tab to device:  Different results if browser is open or not on receiving end

### ISSUE THREAD

**Issue by irvinm** [piroor/treestyletab#3034]
## Short description
Sending tabs between Firefox instances has different results depending if the receiving Firefox is running before the event or not.

## Steps to reproduce

1. Start with a clean profile \ Install TST
2. Enable browser.tabs.insertAfterCurrent = true
3. Create a tree of tabs
3. Close Firefox
4. From remote Firefox instance, send tab(s) to closed Firefox
5. Start Firefox and see that newly created tabs are inserted at the root, not as the child of the current tab
6. From remote Firefox instance, send tab(s) to open Firefox
7. See that tabs are inserted properly

## Expected result
Tabs should be properly inserted into a tree regardless if Firefox was running or not.  (Up until the number of tabs runs into this Firefox problem:  https://github.com/piroor/treestyletab/issues/2419)  This is the behavior if Firefox is already running.

![image](https://user-images.githubusercontent.com/979729/140336367-bd1b8d71-aeb5-45de-8123-2db8b908b265.png)

## Actual result
Sending tabs to a broswer that is closed will result in tabs being created at the root.

![image](https://user-images.githubusercontent.com/979729/140336505-6b26749f-4097-4feb-aa3c-9837b26557ef.png)

## Environment

 * Platform (OS): Windows 10 (21H1)
 * Version of Firefox: FF 94.0
 * Version (or revision) of Tree Style Tab: 3.8.15

**Comment by irvinm** [comment]
I had to send another tab today from my phone to my PC and saw something additionally strange and wanted to document it.

Starting with:

![image](https://user-images.githubusercontent.com/979729/140388662-a901abe4-6ca3-4273-a643-e566202de076.png)

I pushed a tab and it got created under the active tab as a child. (Good)

![image](https://user-images.githubusercontent.com/979729/140388839-b6d2ca41-3898-4d3d-bce7-100fb1720f48.png)

I went back to the original tree, made the first child the active tab and sent another tab.  This time, the new tab was created as a sibling to the active tab vs. a child. (Different ... I thought it too might be a child)

![image](https://user-images.githubusercontent.com/979729/140388963-c3705c8d-2f22-4708-8631-191550c83a65.png)

Finally, I went back to the original tree, made the last tab the active tab and send another tab.  This time, the new tab was created at the end of the tree as a root tab not related to that tree. (This doesn't seem right)

![image](https://user-images.githubusercontent.com/979729/140389375-911ad7f2-793e-40bc-9d99-af194d1ed36a.png)

**Comment by irvinm** [comment]
@piroor I just wanted to make sure you saw I created a separate issue for this topic.

**Comment by piroor** [comment]
Sorry for my silence. I've researched what happens at this situation.

On my case:

1. Firefox opens the received tab.
2. TST is loaded. TST tries to restore tree based on the last session data associated to whole tabs.
3. The total number of tabs is changed from the last session data, so TST gives up to restore tree.
4. TST starts to build tree structure based on the information saved to each tab (preceding, following, ancestors and children).
5. The received tab has no relation information, so TST doesn't touch to that.
6. Other tabs have relation information, so TST construct tree keeping their position.
7. As the result, the received tab is left inside constructed tree unexpectedly.

So, I think TST should scan all tabs after tree construction, and fixup tree structure based on the position of received tabs like they are drag-and-dropped inside existing tree.

**Comment by piroor** [comment]
The commit b73c911 should fix this.

**Comment by irvinm** [comment]
Thanks @piroor, I will test it out in the next release.

Can you also take a look at the last scenario in https://github.com/piroor/treestyletab/issues/3034#issuecomment-961262364?

Basically, if you are running Firefox and send a tab while the last tab of a tree is selected, the new tab is created below that tree as a root tab vs. a sibling to the last tab.  If you want me to move that into a separate issue, I can do that as well.

**Comment by piroor** [comment]
@irvinm Sorry I forgot to respond about it.

In short: currently it looks impossible to take care this case.

* Firefox doesn't provide any effective information to detect "tabs sent from other devices" via WebExtensions API, so those tabs are always detected same as "regular tabs opened with URL". Thus TST cannot provide specific option for this case.
* Those tabs are placed next to the active tab always: it is the effect of `browser.tabs.insertAfterCurrent`.
* As the result, tabs unmanaged yet by TST appear somewhere in existing managed tabs. They can break tree structure of managed tabs. Tab operations on the native horizontal tab bar also produces this kind situations.
* For safety TST detects such unmanaged tabs and attach to existing tree with guessed relation based on their position.
  * A tab between "parent" and "first child" becomes "new first child".
  * A tab between same level children becomes a new child with same level.
  * A tab after a child tab and before a root level tab of different tree: this is special. It may be a new child tab of the parent of the child tab preceding to the tab, or may be a new root level tab: because both cases don't break the tree. TST treats such a case as "a new root level tab" if there is no hint to guess it is which side.

**Comment by irvinm** [comment]
Thank you @piroor, that makes sense.  I appreciate the explanation.

It isn't that big of a deal as I can just move\attach the tab as appropriate to fix the situation.
