### ISSUE TITLE
[Feature Request] Embed chosen bookmarks (maybe even bookmark toolbar itself) on top of the tree

### ISSUE THREAD

**Issue by nulledone** [piroor/treestyletab#3043]
![1](https://user-images.githubusercontent.com/29547468/143675522-bd1b1f77-8e16-404f-a327-d21023702308.png)

**Comment by piroor** [comment]
![image](https://user-images.githubusercontent.com/70062/143686418-26e43c7c-1bd3-48de-83fe-15a0a4cd8168.png)
This checkbox controls the behavior.

**Comment by nulledone** [comment]
I was talking about creating a new line for chosen bookmarks rather than setting bookmark toolbar. Pictures above is what it currently is, and what I would like it to be.

**Comment by nulledone** [comment]
@piroor

**Comment by piroor** [comment]
OK, I misunderstood what those screenshots described about. I'm happy if you put such a detailed description at first on the next time.

Anyway I won't implement the feature because it is out of the project scope. Instead there are some possible alternative solutions:

* Use pinned tabs for the purpose. In TST's sidebar pinned tabs are listed horizontally as favicons at the first line of the sidebar. And see also the support topic to keep pinned tabs suspended on the startup: https://support.mozilla.org/en-US/questions/1271043
* Implement a helper addon providing a subpanel behaves like the bar. TST Tab Search https://github.com/NiklasGollenstede/tst-search looks a good example implementation.
* Fork TST and extend it with the feature.
