### ISSUE TITLE
Firefox 95: problem with High Contrast theme

### ISSUE THREAD

**Issue by actionless** [piroor/treestyletab#3054]
## Short description
After upgrading Firefox to 95 this happened.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select High Contrast theme
 4. Open Children Tab

## Expected result
Background is different color from the tab itself.

## Actual result
![2021-12-09--1639079706_330x187_scrot](https://user-images.githubusercontent.com/1655669/145466837-e61d9ff2-e341-45e5-8065-00c093feb4fc.png)

## Environment

 * Platform (OS): Arch Linux x64
 * Version of Firefox: 95.0
 * Version (or revision) of Tree Style Tab: 3.8.16

**Comment by piroor** [comment]
Could you paste a screenshot of the expected result? I don't know how it is rendered on old versions on your environment.

**Comment by piroor** [comment]
And I need more information about the GTK+ theme you are using. It looks different from the default "Adapta". I'm not familiar to Arch Linux so I need descriptions how to install the theme.

**Comment by actionless** [comment]
> I don't know how it is rendered on old versions on your environment.

it should be either darker or lighter (depending on theme), just not the same color

> And I need more information about the GTK+ theme you are using. It looks different from the default "Adapta". I'm not familiar to Arch Linux so I need descriptions how to install the theme.

it's oomox-gtk-theme, do you mean it is displayed normally on Adapta?

**Comment by piroor** [comment]
OK, I've confirmed what's happen.
The background color is based on CSS's system color `CaptionText`.
Here is a screenshot of Firefox ESR91 vs Firefox 95 (left=ESR91, right=95).
![image](https://user-images.githubusercontent.com/70062/145559497-ac572f80-d125-48f7-b196-7b474ad2edb6.png)
In this screenshot, both Firefox loads the page http://www.iangraham.org/books/xhtml1/appd/update-23feb2000.html : it contains a demo of CSS system colors.
TST's background color is based on 35%-`CaptionText` and 75%-`AppWorkspace` on the "High Contrast" theme. Because the `CaptionText` became quite light, the final color on Firefox 95 became lighter also.

**Comment by piroor** [comment]
I cannot see this difference on Windows 10. It looks Linux specific - Firefox 95 may contain something changes around applying GTK+ theme colors.

**Comment by actionless** [comment]
The default TST theme still have normally displayed background, would solution from default theme work here?

**Comment by actionless** [comment]
but i recommend using GrayText, because in both dark and light themes it should be contrast enough from background of the tab

**Comment by piroor** [comment]
Thanks, I've applied your idea with the commit cd6e242.

**Comment by actionless** [comment]
just tested - it works for me :+1: 

thanks for supporting your extension - been fan for many years :)
