### ISSUE TITLE
Request: Save tree/window/tab into html file

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#3065]
## Short description

Hi!
I think it would be useful. There's a send tree to device feature, and a bookmark tree feature. But sometimes it would be neat if you could just export a tree or the whole tree in a html file that I could take with myself on a pendrive for example.

**Comment by piroor** [comment]
It looks to be beyond the project scope. Instead it should be done by a helper extension developed just for the purpose.

Sorry but it won't be developed by me because currently I have no motivation to use it. Thus it need to be developed by someone who seriously want it. There are some hints:

* [TST provides ability to collect tree information via its API.](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#get-tree-information-for-all-tabs-in-a-specific-window)
* [You can request to Firefox downloading arbitrary data as a file](https://dev.to/nombrekeff/download-file-from-blob-21ho). TST also uses the method to [export configs as a JSON file](https://github.com/piroor/webextensions-lib-options/blob/3e0df1dd04e31ae681690d523b76c106f49a3d4a/Options.js#L377-L406).
* [The official tutorial for new add on developers](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions)
