### ISSUE TITLE
[feature request] Firefox-like, multiletter prefix folder search when bookmarking

### ISSUE THREAD

**Issue by eavesjump** [piroor/treestyletab#3077]
## Short description

When bookmarking through TST, the UI lets you search bookmark folders by first letter to choose the destination, but not second letters or beyond. For example, I want to be able to type "cabinet" to jump to the first bookmark folder prefixed with "cabinet". Firefox's native bookmarking UI behaves the latter way. I much prefer it because I have so many bookmark folders that it takes a long time to find the right folder even when I know its exact name. (Repeatedly typing the first letter gets there eventually, but it's very slow.)

 * Platform (OS): macOS
 * Version of Firefox: 96.0.1
 * Version (or revision) of Tree Style Tab: 3.8.19 (2022.1.13)

**Comment by piroor** [comment]
This is due to restrictions and spec of the menu-ui library ( https://github.com/piroor/webextensions-lib-menu-ui ). The list of existing bookmark folders is implemented based on the library, and it simulates behaviors of regular menus (the menu bar, the context menu, etc.) of Firefox itself.

On menus of Firefox, a letter in each menu item may be decorated with underline. It means the accesskey of the menu item, it works as a shortcut to the item. The library was originally designed to simulate these behaviors, and finally I extended it for menu items with no specified accesskeys: use their first letter as their implicit access key. This is the reason why the first letter is only effective for your input.

I think that multiple-letters support can be beyond the scope of the library, but I agree such a behavior is useful for some languages, so I've opened an issue about the enhancement: https://github.com/piroor/webextensions-lib-menu-ui/issues/1

**Comment by irvinm** [comment]
@piroor can you label this item?  It has been a while.

**Comment by piroor** [comment]
Sorry for my long silence. Done by 4dd3d4a.

**Comment by ngirard** [comment]
I just saw this in the changelog and hoped it would make bookmarking less painful, but I can't see where this feature has been implemented. Could someone please tell me how to leverage this new feature ?

**Comment by eavesjump** [comment]
Confirmed it works for me. When you bookmark tabs through the TST interface (for example, right click a tab and click "Bookmark Tab"), then click the button to select a bookmark folder, eventually you may find yourself with a long list of bookmark folders to scroll. That's where you can now just type the prefix of the folder name you want to use (instead of having to scroll through all the names).

**Comment by ngirard** [comment]
Aha, got it. Thanks very much @eavesjump, and kudos to @piroor  !
