### ISSUE TITLE
Close Tabs window disappears when trying to use from other displays

### ISSUE THREAD

**Issue by Malvalar** [piroor/treestyletab#3104]
## Short description
Close tab confirmation window disappearing if the Firefox window is not on display 1.

## Steps to reproduce

- Multiple displays, multiple Firefox windows
- Have a vertical tab configuration in a Firefox window that is not on display 1
- Collapse tabs
- Close collapsed tabs using the TST tab close button.
- Window flashes briefly on display 1 and then disappears. It shows in the thumbnail previews of windows from the taskbar, but it cannot be brought forward or located anywhere.
- If the same window is moved to display 1, and then the same actions repeated, the confirmation window appears as expected on display 1.
- Move back to another display, behavior returns.

 1. Started Firefox with clean profile.
 2. Installed TST.
 3. Same behavior as described above.

![Screenshot 2022-04-14 221130](https://user-images.githubusercontent.com/5958333/163512297-b813c682-4aef-454c-bff1-14a7c8154ac0.jpg)

## Expected result
Window with a list of tabs to be closed, confirm or deny.

## Actual result
Window flashes briefly on the main window and then disappears. It shows in the thumbnail previews of windows from the taskbar, but it cannot be brought forward or located anywhere.

## Environment

 * Platform (OS): Windows 10, 21H2, 64 bit
 * Version of Firefox: 99.0.1, 64-bit
 * Version (or revision) of Tree Style Tab: 3.8.21

**Comment by piroor** [comment]
* How your displays are placed?
* Does the problem appear with different combinations of display positions? (display1=top,display2=bottom / display1=left,display2=right / display1=bottom,display2=top / display1=right,display2=left )
* Hover on the Firefox item on the taskbar => hover on a dialog window item => right-click on it => choose "move", then you can move the dialog window with cursor keys of your keyboard. Where is your dialog window placed at (left outside, top outside, right outside, or bottom outside)? 

Something figure like this will help me to understand what happens on your environment:
![image](https://user-images.githubusercontent.com/70062/163515258-bdf354d8-64d2-4b47-99be-667d4d05344f.png)

**Comment by Malvalar** [comment]
![Screenshot 2022-04-14 225206](https://user-images.githubusercontent.com/5958333/163515565-7b622666-4bd8-4b8a-bc2d-09db56c25644.jpg)
This is my current configuration. Generally I keep 3 Firefox windows, one each, maximized on each display.

Tried swapping the displays to a vertical configuration instead of horizontal, no change in behavior.

If I to try to do the Move for a Firefox window on Display 2, it place the cursor into the lower left of whichever display I enter the tab preview on. The dialog will not appear, just the arrow cursor and trying to move with arrow keys doesn't cause anything to happen.
On Display 1 it works as expected, but if I try to Move the visible dialog from the preview on a different display it places the cursor on the far left and far right middle of Display 1, depending on which display I do it from.
Display 3 is the opposite of 2--cursor always appears in the bottom right of the display of where I select the Move option.

If it helps, if I open multiple dialogs, even from different tab sets, if I close one from the tab preview it will close all of the dialogs.

I would also note that it was working fine a few days to a week ago and I can't remember making any updates to my machine in that time.

**Comment by piroor** [comment]
Thanks! One more question, any your display use hi-dpi setting? TST may place dialog windows at unexpected place due to difference of CSS pixels and physical display pixels.

**Comment by Malvalar** [comment]
Maybe? I'm not entirely sure. The smaller monitors are both 1920 x 1080, while the larger is a native 3840 x 2160 so it has a relatively high DPI. Scaling on it is set to 200%

**Comment by piroor** [comment]
OK, I might got what's happen. This problem looks to happen due to multiple device pixel ratios of monitors.

The API to move window position (`windows.update()`) treats specified coordinates as CSS pixels. When the dialog is placed at a scaled display, the coordinates are converted to device pixel values based on the devicePixelRatio of the scaled display.
![image](https://user-images.githubusercontent.com/70062/163792471-25eb9b19-09a0-4a27-a816-56c72ba451dc.png)

But when the dialog is placed at a non-scaled display, the coordinates are converted to device pixels based on the devicePixelRatio of the non-scaled display. As the result, finally calculated physical coordinates are different from the previous one despite we specify same CSS pixels.
![image](https://user-images.githubusercontent.com/70062/163792504-bc00d8a1-9db7-4968-9407-4b88b40a7d9c.png)

More worse, the devicePixelRatio looks treated as same to the value of the primary display if we get it from the background page (TST uses it to run manager modules.) So, when TST calculate coordinates of a dialog based on a window placed at the display 2 or 3 on your environment, the final coordinates will become far from expected one.

Sorry I cannot imagine how to fix such a complex problem caused by limited functionalities of WebExtensions APIs... The easiest way is respecting the default behavior of WebExtensions API: a new window opened via the API is always placed at the middle of the primary window.

**Comment by piroor** [comment]
Recently I introduced some changes around dialog positioning and it may affect to this problem. Could you try the latest development build?
https://github.com/piroor/treestyletab#development-builds

**Comment by Malvalar** [comment]
Seems to work.
It flickers briefly on the main window and then appears on the correct display.
