### ISSUE TITLE
[Feature Request] Bottom Bar Tree tab

### ISSUE THREAD

**Issue by ghost** [piroor/treestyletab#3115]
Is it possible to move the sidebar to the bottom of the web browser? e.g Firefox
Similar to bottom bar of Intellij IDEs

**Comment by irvinm** [comment]
Just a couple of thoughts here, but TST uses the sidebar and that can only be configured to be on the right or the left of the browser.  In addition, Firefox no longer has a means to anchor anything to the bottom of the browser like the old "status bar". (https://helpdeskgeek.com/wp-content/pictures/2011/05/01_status_bar_in_firefox_3_thumb.png)

Bottom line is that I do not think this is possible due to Firefox limitations.
