### ISSUE TITLE
Sizes Confirmation window while simultaneous opening of tabs

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#3136]
@piroor 
Confirmation window while simultaneous opening of tabs it stretches to a width larger than the screen if there are many characters in any address (data: or simply encrypted unicode). Can you fix it, or do the code for userChrome.css? I myself can't figure out how to limit the size of this window.

**Comment by wvxwxvw** [comment]
I get it, it's not a bug, it's a feature.  :)
I picked up the code.
```
.rich-confirm-dialog {
    max-width: 1000px !important;
}
```

**Comment by piroor** [comment]
Hmm, it sounds odd. The confirmation dialog width is limited to 75% of the parent window.　On my case a dialog containing 10000 letters labeled tab doesn't expand the dialog size larger than the parent window:

![image](https://user-images.githubusercontent.com/70062/171136378-dc39d1e4-b706-4469-af00-dbb1cb77abfc.png)

One possibility, if you use different size screens and one of them is smaller than others, the shrunken size dialog may become larger than the small screen.

**Comment by wvxwxvw** [comment]
No, the screen is always the same. The problem was confirmed by another user. And I was talking about the confirmation window for opening tabs at the same time, and not closing them, as you have in the screenshot.
Maybe it's the Screen API protection, but it seems that only the minimum is spoofed there. I.e. this should not happen. It's just a thought.

**Comment by piroor** [comment]
Ah, sorry I missed the term "opening". I've confirmed that the problem happens with running following code via the Browser Console:

```javascript
{
const title = (() => { let s = ''; for (let i = 0, maxi = 10000; i < maxi; i++) { s += 'A'; } return s; })();
for(let i = 0; i < 30; i++) { openURL('about:blank?' + title + i); }
}
```

The dialog for grouping is not shrunken automatically for now. I need to update it based on logic around the dialog for closing tabs.

**Comment by wvxwxvw** [comment]
主なことは、あなたが今知っているということです。

**Comment by piroor** [comment]
The commit db88d8b should fix this.

**Comment by piroor** [comment]
By the way, this looks to be an example case indicating why the three parts "steps to reproduce", "expected result" and "actual result" in the issue template are important.

* Text descriptions can be misread like this case - mainly due to my poor English reading. I sometimes easily give up to read whole descriptions, instead I read descriptions partially.
* Even if I misread the context of descriptions, 100% reproducible "steps to reproduce" will lead me to see what you saw, and the gap between "expected result" and "actual result" will help me to get understanding what needs to be fixed.
* Non-verbal descriptions like code snippets (like above mine), screenshots, or screencasts will help our inter-language communication.

So, I hope future issues to be opened with filled template by your cooperation. Thanks!
