### ISSUE TITLE
Tab opens as child on middle-click regardless of settings

### ISSUE THREAD

**Issue by manyfew** [piroor/treestyletab#3139]
## Brief description

Tabs that should open as siblings of the current tab upon middle clicking a link or the reload button still open as children of the current tab regardless of user preferences.

## Steps to reproduce

1. Configure as follows:

![Non-blank new tabs](https://user-images.githubusercontent.com/11704566/171611518-df42f924-6536-40ad-b4bf-a4f5181dfcc8.png)

2. Open a website containing links
3. Middle-click any link

**Expected result:** Link opens as the next sibling of the current tab.
**Observed result:** Link opens as child of current tab.

4. Using the previous tab, middle-click the Reload button

**Expected result:** Link opens as the next sibling of the current tab.
**Observed result:** Link opens as child of current tab.

## Remarks

The same behaviour is observed when a link is left-clicked on a website that forces links to open in new tabs

## Environment

 * Platform (OS): **Windows 11**, version: **21H2 (OS Build 22000.675)**
 * Version of Firefox: **100.0.2 (64-bit)**
 * Version (or revision) of Tree Style Tab: **3.8.23**

—Thank you

**Comment by piroor** [comment]
It is the expected behavior, not a bug. The term "new tab " in all these options means "new tabs opened without any context information ([`tabs.Tab.openerTabId`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab#openertabid))". They won't affect to tabs from links because such tabs have the ID of the current tab as their `openerTabId`.

I'll update label text of these options more descriptive about this spec.

**Comment by piroor** [comment]
TST actually has a hidden option to do your expectation: TST options => "Development" => "All Configs" => "autoAttachOnOpeneddWithOwner". Setting it to `2` will open new tabs from links as sibling tabs, `3` will open tabs as just next sibling tabs.

Currently it is not exposed to guard users from accidental change, because I think values except `1` (open tabs as children) are unnatural and not user friendly.

**Comment by manyfew** [comment]
Hi, thank you for replying and, sorry, I think I deleted the email notifications unintentionally. I hadn't even noticed the All Configs section, really great stuff! Where can I learn more about these configs?

**Comment by manyfew** [comment]
Setting autoAttachOnOpeneddWithOwner = 3 works good for me, thank you!

**Comment by piroor** [comment]
I've restructure options around new tabs behavior. I hope this restructuring reduce confusion of people.

And I've exposed an UI for `autoAttachOnOpeneddWithOwner`. I'm afraid this may introduce more confusion...

**Comment by manyfew** [comment]
> I've restructure options around new tabs behavior. I hope this restructuring reduce confusion of people.
> 
> And I've exposed an UI for `autoAttachOnOpeneddWithOwner`. I'm afraid this may introduce more confusion...

Thank you
