### ISSUE TITLE
[Bug] When restoring a tree, tabs in "reader" mode return as Undefined.

### ISSUE THREAD

**Issue by CaioCMartinelli** [piroor/treestyletab#3157]
Hello, first I would like to congratulate you for being able to develop an incredibly useful extension like this.

 ‎
Regarding the bug I found, in short it happens when you have a tab in Firefox's native "reader" mode, this tab may or may not be in the middle of others and you decide to save the entire tree using (or not) TST ways in your bookmarks. 
 ‎

Firefox saves the bookmark link as `"about:reader?url=%url%"`. When you then decide to restore that tree (using TST to restore the structure too) the TST restores it as `"about:blank?about:reader?url=%url%"` which produces a "Undefined" and blank page.
 ‎
 ‎
**Procedures:**

**1 -** Save any page or group of pages with native Reader mode activated in any of them in your bookmarks in one folder (using Firefox native or TST way).

**2 -** Click on that folder and select the option to open it with the TST "Open all as a Tree"

 ‎
**Result:**

Pages saved in reader mode is presented as Undefined with a blank screen.
 ‎
 ‎
**Environment:**

Windows 10 Pro - Version 2004
Firefox 102.0.1
Tree Style Tab 3.8.26

**Comment by irvinm** [comment]
I think this is going to end up being a limitation of the addon API.  Addons are not allowed to created "privileged" tabs like about:reader, about:config, etc. ([reference](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create))  I tried bookmarking about:config and restored it and it show the same behavior.  about:blank is not considered "privileged", so I think the current behavior provides a compromise in functionality due to restrictions from the API.

I think the choices here are:

1. Continue to use TST to "Open all as a Tree" ... and then for any of these instances, you just have to remove "about:blank?" from the URL and you should get what you want ... OR:
2. Use the Firefox "Open all bookmarks" which should open the bookmarks properly, but you will lose the tree hierarchy.

@piroor may have some other suggestions\ideas as well.

**Comment by piroor** [comment]
This is due to limitations of WebExtensions API as @irvinm described. However I've realized that an `about:reader` URL has its original URL completely as its URL parameter. With the commit 6ec9c64, now TST fallback such URLs to their original versions - it looks better than just blank page.

**Comment by CaioCMartinelli** [comment]
Great. Given the current limitations of the API, I think it's the best approach.
