### ISSUE TITLE
[Bug] visual regression in a form of unnecessary indent for root level tabs near the scrollbar

### ISSUE THREAD

**Issue by ssergiienko** [piroor/treestyletab#3195]
## Abstract

Latest update 3.9.0 (2022.9.13) bring a visual regression in a form of unnecessary indent for root level tabs near the scrollbar.
It shows itself only when scroll-bar is present.

## Steps to reproduce

Reproduced both with the clean profile and in the new window from existing profile.
Just open tabs till scrollbar appear and see unneeded indent (see screenshots)

## Expected result
![Screenshot_20220823_150917](https://user-images.githubusercontent.com/9850672/189858649-58093ff5-e4ac-467f-aea3-6401d34e8323.png)

## Actual result
![Screenshot_20220913_104424](https://user-images.githubusercontent.com/9850672/189858549-c131b361-f93f-4a7e-bfba-430115c96c41.png)

## Environment

 * Platform (OS): Archlinux
 * Version of Firefox: 104.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.0 (2022.9.13)

**Comment by piroor** [comment]
TST looks failed to detect "autohide" state of the scrollbar. I've introduced a change a960cbc to detect the state more certainly. Could you try the development build with the change?: https://github.com/piroor/treestyletab/actions/runs/3044417660

**Comment by piroor** [comment]
Note: you need to load it as a temporary extension via `about:debugging`.

**Comment by ssergiienko** [comment]
Looks like it didn't help
Version of plugin: 3.9.0.1

![image](https://user-images.githubusercontent.com/9850672/189889133-fd1e738c-dff5-423a-957b-0ce7c66fc0f0.png)

Do I need any extra steps after Temporary plugin installation? e.g. restart FF?

**Comment by piroor** [comment]
OK I got it, it is the result of an intentional change at TST 3.9.0.

On some platforms the scroll bar of the tab bar is hidden by default and shown on hover. As the result the auto-shown scroll bar can block clicking of TST's "twisty" UI (the button to collapse/expand tree). Thus TST shifts tab UIs a little to avoid such a blocking, when the tab bar is scrollable on such environments. On TST 3.8.x the shifting was produced with "padding" (inner space) in tab elements. On the other hand, TST 3.9.0 shifts tabs with "margin" (outer space) of tabs themselves. The shifted distance is "1em" by default, it means "the height of the character M (capital m)".

You can change the distance with a secret option: TST Options => Development => All Configs => ~~autoHiddenScrollbarPlaceholderSize~~ `shiftTabsForScrollbarDistance` (on TST 3.9.2). Changing it to ~~"0"~~"0px" and reopening the sidebar takes the old appearance back. I think "0.35em" or smaller value looks better for your case due to the reason I told above.

**Comment by piroor** [comment]
Sadly the width of such an auto-hidden scroll bar cannot be calculated by an addon. You need to customize the shifting distance by yourself.

**Comment by ssergiienko** [comment]
Thanks for the detailed explanation and workaround!

> On some platforms the scroll bar of the tab bar is hidden by default and shown on hover. As the result the auto-shown scroll bar can block clicking of TST's "twisty" UI (the button to collapse/expand tree)

Looks like this is exactly about my platform - I see small scrollbar only on hover, but I never experience any issues with blocking TST ui with it :thinking: 
With "0em" now it looks absolutely usable without any issues, but maybe it's subjective :man_shrugging:

**Comment by JeroU** [comment]
> With "0em" now it looks absolutely usable without any issues, but maybe it's subjective 🤷‍♂️

So do i. It's probably dependant on the scrollbar size which is quite smalll by me.
thanks

**Comment by piroor** [comment]
I've decrease the default value from 1em to 0.5em and introduced more changes to make the option configurable via regular options UI.

**Comment by julienbaley** [comment]
Glad I've found this page, it took me a really long time to identify it was scroll bar related (I always have too many times); should have checked here first :-)

**Comment by julienbaley** [comment]
Coming back to it, I think this is causing another issue: now, the nested tabs also stick to the left of the screen, instead of being indented. Is this what [74d0aa9](https://github.com/piroor/treestyletab/commit/74d0aa9031792df07330163816b2df5b9bb37249) is addressing? :)

**Comment by piroor** [comment]
@julienbaley I couldn't see such a problem on Firefox 104.0.2 on Windows 11 + TST 3.9.1. If you use any user styles, could you paste it here?

**Comment by julienbaley** [comment]
I'm not aware of any particular configuration (aside from setting autoHiddenScrollbarPlaceholderSize to 0), where can I check about it? (sorry, not very familiar with the configs of TST, I've been a happy basic user for many years!)

(Firefox 104.0 on Ubuntu 20.04, if ever that matters)

**Comment by julienbaley** [comment]
(Firefox 104.0 on Ubuntu 20.04, if ever that matters)

**Comment by Phidica** [comment]
@julienbaley Do you set it to "0" or to "0em"? I see the same problem as you when I set it to "0" but if I use "0em" then it is fixed.

**Comment by SuperTux88** [comment]
Yes, I also had the problem that everything sticked to the left when setting it to `0`, but then I set it to `0em` and that fixed it.

**Comment by julienbaley** [comment]
Thanks @Phidica , that solved it!

**Comment by piroor** [comment]
Sorry I forgot that the `calc()` function of CSS requires something length unit for `0`.

**Comment by piroor** [comment]
TST 3.9.2: The option was internally renamed to `shiftTabsForScrollbarDistance` and exposed here.
![image](https://user-images.githubusercontent.com/70062/190444900-e15d372b-4f98-4b74-80e3-1b7ad0372ddd.png)

**Comment by BensonBear** [comment]
> TST 3.9.2: The option was internally renamed to `shiftTabsForScrollbarDistance` and exposed here.

Oh thank God!  When something awful happened to TST recently, I spent an hour fiddling with various options before I finally came to issues at github and found this issue and the fix (interally) and then that it had been added already to the exposed options.  
 
But the problem is much much worse on my system (FF 104.2 on Linux) than just a little "unnecessary indent".   In fact I would have posted a new issue had I not made sure the other recent issues were unrelated.  

So as well as the indent (I noticed but it doesn't bother me) when the mouse is moved close to the left side of the sidebar, the tabs inside are scrolled to the left or the right a little bit depending on which direction the mouse is moving.   Very very disturbing! 
 
I did see it was related to the scrollbar being visible, and investigated for a while turning the scrollbar off or hiding it, which didn't help.   I wonder if maybe a setting of 0.0em for this variable is more desirable as a default, or if there is someway to detect whether 0.5em (or any positive value) cause this problem and setting the default accordingly?

Anyway what a relief, thanks!
