### ISSUE TITLE
Opening the history tab using the shortcut closes the entire tab

### ISSUE THREAD

**Issue by zenightman** [piroor/treestyletab#3201]
Pretty self explanatory. Once you open the history tab, everything in the tab section is gone.

**Comment by piroor** [comment]
What is the "history tab"? I don't know that on Firefox and TST. Please describe how to reproduce the problem through the issue template.

**Comment by zenightman** [comment]
My bad.
![image](https://user-images.githubusercontent.com/113671730/190594169-1df1625e-769d-4817-93e4-052fc2b59666.png)

Regular tabs in a session disappear once you hit Ctrl+H to open your navigation history.

No way of going back, closing that history tab will close everything but the page you're on without the ability to recover the previous session.

![image](https://user-images.githubusercontent.com/113671730/190594537-64f6d9a8-f793-4ab4-951c-e7a0de9ee860.png)

**Comment by zenightman** [comment]
Never mind I was being an idiot. You can click on the dropdown and select the TreeStyle Tab from. Apologies for wasting your time.

**Comment by piroor** [comment]
In short: they cannot be shown together due to restrictions of Firefox. TST is just a sidebar panel and there is no way to show multiple sidebar panels together on Firefox.

Related topics:

* [1328776 - Provide ability to show multiple sidebar contents parallelly](https://bugzilla.mozilla.org/show_bug.cgi?id=1328776)
* #3185
