### ISSUE TITLE
[Bug] Tabs position change with delay on native tabbar

### ISSUE THREAD

**Issue by DreamC** [piroor/treestyletab#3202]
## Abstract
Opening tabs as child tabs show incorrect position on native tab bar for some time, introducing "jumping" behavior. TST sidebar shows this correctly.
This behavior is relevant only for native Firefox controls like New Tab ("+") or Duplicate Tab (middle button on refresh).
Depending on your settings for child tab position this may behave a little bit differently.

## Steps to reproduce
Open a child empty tab and switch back to the parent tab.
```
A (focused)
\- Empty
```
Now open any link in a child tab. Native tab bar will first spawn this tab next to the parent and then after a delay jump it to right after the blank tab.
```
A (focused)
\- B (for a split second)
\- Empty
```
```
A (focused)
\- Empty
\- B
```

## Expected result
Should not show any jumpiness in tab position.

## Actual result
Noticeable jump in tab positions.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 105.0
 * Version (or revision) of Tree Style Tab: 3.9.2

**Comment by piroor** [comment]
It is impossible to "fix" by an addon, because Firefox doesn't allow control of new child tab position before it is opened and we always need to move the tab after it is completely opened.

**Comment by DreamC** [comment]
I guessed as much, but there is still a big difference in behavior when you open links after blank tabs.
https://youtu.be/QvChqk_Q1jg
If you open links "normally", then there is either no delay or it is negligible. This is the thing you are talking about, right?
However, if you open a blank tab, then opened links, first of all will be placed in wrong position (in my case they have to be placed right after the current tab, but they are moved after the blank tab) and the delay is way longer.

**Comment by piroor** [comment]
In the sidebar panel I totally mimic native tab UI of Firefox itself with WebExtensions API, so we can interrupt processes to open new tabs with control as we like, whereas new tabs opened via Firefox's native UI are just notified after they are opened.

**Comment by piroor** [comment]
Firefox's `tabs.onCreated()` API gives TST very limited information, so TST has to do various things including requesting and waiting extra information for new tabs to detect the context of the new tab. If TST could detect the context without such an extra requests, TST can control new tabs without delay.

**Comment by DreamC** [comment]
The issue appears when you open a new tab with immediate switch to it from native controls (when you Ctrl+LMB "+" button or when you Ctrl+Shift+LMB any link)
Here on the video you can see that if you open tabs without immediately switching to them, then native tab bar shows no delay and correct position. However if you immediately switch to them, then the position is broken and there is a noticeable delay.
https://youtu.be/On1el_dS9lY

**Comment by piroor** [comment]
Because Firefox has its own tab control features: `browser.tabs.insertRelatedAfterCurrent` and `browser.tabs.selectOwnerOnClose`. Firefox controls new tab position partially without complete tree management. If the controlled result is same to the one TST expected, TST does nothing (and new tabs are opened at the position immediately.) If the result is different from TST expected, TST moves the opened tab with unavoidable delay.

**Comment by piroor** [comment]
When you open tabs sequentially without moving tab focus, they are controlled by Firefox as "related tabs". When click any tab in the tab bar, Firefox forgets the "related tabs" information, so next new tabs will be opened next to the parent tab - between the parent and old "related tabs".

On the other hand, TST tracks "child tabs" information after you move focus. Even if you click any tab and back to the parent tab, TST can treat more new tabs as new children and can place them after existing children.

While tabs are opened same as TST's expecting child tab position, TST does nothing extra control. After Firefox forgets the "related tabs" information, the position of new tabs opened from links are different from TST's expected position, so TST starts to control their position.

**Comment by DreamC** [comment]
Even for TST it is not an expected position - immediately switched tabs are not marked as "viewed", thus FF tries to open a new tab next to current (as the other one is viewed), but TST moves it to behind the previous one (as TST counts it as not viewed).
At least for setting emulating the FF behavior.

With the rest I do agree, you are right and thanks for the explanation.

**Comment by DreamC** [comment]
I'd still say that this is an inconsistent behavior between Firefox emulation and vanilla Firefox.

In vanilla, if you open a blank tab by middle click (open blank tab and switch to it), then it is considered as viewed, i.e. next new tabs position will be reset.
Like this:
```
A (Current)
```
Open blank tab:
```
A
Blank (Current)
```
Switch back to parent:
```
A (Current)
Blank
```
Open any link in background by middle clicking:
```
A (Current)
B1
B2
Blank
```

In emulation, this blank tab is not marked as viewed, thus TST force moves next new tabs to after the blank tab.
The current behavior forces this:
```
A (Current)
```
Open blank tab:
```
A
Blank (Current)
```
Switch back to parent:
```
A (Current)
Blank
```
Open any link in background by middle clicking - they are opened as in vanilla, but then forced to the back:
```
A (Current)
Blank
B1 - moved
B2 - moved
```

**Comment by piroor** [comment]
It was an intentional behavior of TST. Currently TST has no option to simulate Firefox's behavior around tabs from existing tab, you described at https://github.com/piroor/treestyletab/issues/3202#issuecomment-1261222123. The option does not affect to tabs opened from unpinned tabs: TST Options => "Tabs opened from Existing Tabs" => "Insertion position of new child tabs (will appear at root tabs) from *pinned tabs*" => "Next to the recently opened child, or near the opener (simulates Firefox's default behavior)".


Originally I didn't have the plan to simulate Firefox's default behavior for tabs opened from existing tabs because:

* It requires managing "last related tab" information and I didn't implement that on early versions of TST.
* I thought that the "last related tab" behavior of FIrefox is just made as a workaround to provide TST-like tab control avoiding to implement complete tree management like TST, for the horizontal tab bar (it is not good place to show nested tree). On the other hand TST already had its complete tree management, so I though that the Firefox compatible behavior is a lesser version of TST's behavior and needless.
* Too much options make things complex. I hoped to reduce exposed options of TST in its options page.

Now TST has its own "last related tab" management as a by-product from simulation of successor tab behavior, and I changed the policy to expose detailed options just for experts. So I've implemented a new choice to simulate Firefox's behavior for tabs opened from an existing tab with the commit 105380b.
