### ISSUE TITLE
[Enhancement] Containers as tree roots

### ISSUE THREAD

**Issue by mjmacleod** [piroor/treestyletab#3234]
It would be incredibly useful to have an option to be able to have containers appear as the "root" of the tree (e.g. like how https://github.com/maciekmm/container-tabs-sidebar handles containers, except with TST behaviour inside each of the containers) and the actual tab trees and their children to then appear underneath the container to which they belong and otherwise operate the same as TST behaves.

so instead of:
```
A | private
  \- B | private (collapsed)
C | work
  \- D | work
E | banking (selected)
```

you would have:
```
private (collapsed)
  \- A
    \- B (collapsed)
work (collapsed)
  \- C
    \- D
banking (expanded)
  \- E (selected)
```

**Comment by piroor** [comment]
I won't add this feature as a built-in of TST, because it is beyond the project scope. Instead I'm positive to improve TST's compatibility with other addons which automatically rearrange tabs based on their container like [Container Tab Groups](https://addons.mozilla.org/firefox/addon/container-tab-groups/). See also: #3214
