### ISSUE TITLE
[Enhancement] add a "group by container"

### ISSUE THREAD

**Issue by Pomax** [piroor/treestyletab#3239]
## Abstract

With multi-account containers for Firefox, it would be super useful if the tree style tab could be told to always group "containered" tabs with a master heading that has the collapse/expand function so that if you create a new containered tab, it doesn't just end up in between other tabs in the tree, but clearly nested under that container's master node.

This would greatly improve working with containers combined with tree style tab.

**Comment by Pomax** [comment]
(I currently do this by creating a "new tab" for a container I'm using, and then setting `document.title` for that new tab to the container name, so I can nest everything appropriately. While that works, it's also something that would be far nicer if it could be done _without_ having empty tabs hanging around, or having to hack up tab titles =)

**Comment by piroor** [comment]
I have no plan to implement this as a built-in feature of TST because it is beyond the project scope. Instead I'm positive to improve TST's compatibility with other addons which automatically rearrange tabs based on their container like [Container Tab Groups](https://addons.mozilla.org/firefox/addon/container-tab-groups/). See also: #3214
