### ISSUE TITLE
[Enhancement] new tab button replaced by row of new-tab-container buttons

### ISSUE THREAD

**Issue by colemickens** [piroor/treestyletab#3244]
## Steps to see the situation

Hi, I am using MAC / containers more extensively because adtech is awful.

I would be a bit more functional with them if I could easily open a new tab directly instead of long-pressing the new tab button.

Presumably this would be an optional feature the user would likely opt-into.

## Expected result

before
```
[              +               ]
```

after:
```
[ x ][ y ][ z ]    [    +     ][v]
```

where `x`, `y`, `z`, are the icons for my various containers (`v` is the current dropdown).

**Comment by colemickens** [comment]
Alternatively, if I could make it so that it ALWAYS drops-down the container list on signle click, that would likely be sufficient.

**Comment by piroor** [comment]
Did you try the checkbox?: TST Options => "New Tabs not from Existing Tabs" => "Special actions on the "New Tab" button => "Show Container selector button on the "New Tab" button, when the button is pointed"
![image](https://user-images.githubusercontent.com/70062/199589094-6dd1198f-f6f9-48f6-9c5b-a5816202d4e3.png)

**Comment by cletusw** [comment]
@piroor That just puts a tiny caret icon at the far side of the new tab button, which @colemickens noted in their report as "(v is the current dropdown)". I believe the ask is for a) larger, direct-to-specific-container buttons to the left of the + button (i.e.g not in the dropdown menu), and/or b) an option for making the + button itself (from the left edge to the right edge of the pane) *always* show the dropdown for selecting a container instead of defaulting to "default".

For motivation, I use a vertical mouse to reduce hand strain, and it is quite tricky to click exactly on the tiny dropdown arrow to select a container. Also, if I were not using Tree Style Tab, I could just click the large + button in the top tab bar, which has exactly this behavior (always shows the select a container dropdown).

**Comment by irvinm** [comment]
@piroor are you considering anything for this enhancement?  If not, we should just close it.

**Comment by piroor** [comment]
I think it is possible by something helper addon using TST's API to insert arbitrary contents on the new tab button.
https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API#how-to-insert-extra-contents

Due to the project policy, I won't add useful features not related to tree management and not implemented in Firefox's native tab bar, especially it can be implemented via API. If you encounter something blocker while implementing the feature with API, please comment here again.
