### ISSUE TITLE
[Enhancement] Search among tabs

### ISSUE THREAD

**Issue by mboman** [piroor/treestyletab#3251]
## Abstract

It would be really useful when you have a bunch of tabs open, many of them nested, to be able to search for the correct tab by URL or page title. After a while the number of tabs that are open are quite high, and I find myself open a new tab because I can't locate the tab I already have.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a bunch of tabs
 4. Have a search function in TST that allows searching by URL or webpage title
 5. Highlight or filter out those tabs that matches the search criteria.

## Expected result

Visually highlight or filter to only show the tabs that match the search criteria.

## Actual (present) result

No search function present from what I find.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 105.0.5
 * Version (or revision) of Tree Style Tab: 3.9.10

**Comment by piroor** [comment]
TST Tab Search https://addons.mozilla.org/firefox/addon/tst-search/ provides the feature. Did you try that?

Sorry I have no plan to add the feature as a built-in of TST because it is beyond the project scope. Instead of making TST a swiss army knife, I hope TST should work together with other feature-oriented addons.

**Comment by mboman** [comment]
Yes, it was what I was looking for. Thanks for your help.

**Comment by TFWol** [comment]
Might want to reopen this; **TST Tab Search** seems to have [stopped working](https://github.com/NiklasGollenstede/tst-search/issues/37).

Dev also hasn't made commits to any repo in past few months.

**Comment by irvinm** [comment]
@miltuss why would we reopen this issue here?  The basic working principal for TST has changed recently and @piroor has been clear this was to improve performance, but that certain working things would break because of this.  (TST-Search and the TST CSS to count tabs are just 2 examples)  Each of these "solutions" will need to revisit how to make things work again on their end.

**Comment by piroor** [comment]
@TFWol Did you look at #3531 ?

**Comment by TFWol** [comment]
> @TFWol Did you look at #3531 ?

Sorry, I completely overlooked that. Guess I shouldn't browse repos while exhausted 😅
