### ISSUE TITLE
[Enhancement] Selection in Close Tabs window

### ISSUE THREAD

**Issue by dstd** [piroor/treestyletab#3259]
It would be useful to be able to skip some tabs in bulk closing operation. It could be implemented by checkboxes in "Close Tabs?" confirmation window.

Like if I'm closing a tree of tabs but would like to keep several of them – I'd just deselect them before confirming.

Thanks!

**Comment by piroor** [comment]
I have less motivation to implement this feature by myself because TST mainly aims to simulate Firefox's native behavior and Firefox's confirmation dialog does not provide such a feature. But I also agree that the list of tabs in the confirmation dialog is a unique feature of TST and it looks reasonable to add checkboxes. Thus I'll merge a PR to implement the idea if you do that. You'll need to modify codes around these lines:

https://github.com/piroor/treestyletab/blob/898858044bedf81bebf82d86e31670698ff1a8c5/webextensions/background/background.js#L552

https://github.com/piroor/treestyletab/blob/898858044bedf81bebf82d86e31670698ff1a8c5/webextensions/common/dialog.js#L106

**Comment by irvinm** [comment]
@dstd, you can also do this manually.  If you select the first tab, then shift+click the last tab ... that selects that group of tabs.  You can then ctrl+click on any of the tabs you do not want to close to unselect them.  

Maybe not the perfect solution, but you can do that now.

**Comment by dstd** [comment]
Oh, thanks! I missed that option (cmd+click on mac). Well, at least it will help in such cases, even if it is not so convenient 👍
