### ISSUE TITLE
[Enhancement] Easier collapse / expand folder tabs

### ISSUE THREAD

**Issue by dsl101** [piroor/treestyletab#3287]
## Abstract
Change functionality of folder tabs to simply collapse / expand, not activate, when clicked.

## Detailed Description
Apologies if this is already in there somewhere—I read the options, and only saw this in relation to double-click, but that doesn't work for me (see below †).

I have many many tabs organised into multiple nested folders, and it's extremely useful to help navigate. I'm also regularly collapsing / expanding folders, and find the very tiny drop arrow a hard target to hit. I also almost _never_ want to see the actual folder tab, with it's list in the main window. So I'd like a way to configure the tab with a single click to collapse / expand, just as if the drop arrow had been clicked.

Note, when I say 'folders', I mean tabs with this kind of URL: `moz-extension://9b563068-d3b7-4d91-8d34-26d99b7af13b/resources/group-tab.html?title=Networking`. So that is a 'folder' of stuff to do with networking for example. The tab itself, when active, just shows the list of its contents, which I'm happy not to see.

Thinking about how to make this work, I was wondering if the 'click' target for the collapse / expand icon could simply be extended to cover the tab name, but I'm not sure if that's really doable just with CSS, or would need changes to TST itself?

† I did see the 'Double click tab to collapse / expand', but I also have the Tab Flip plugin, which means single clicking a tab switches back and forth between the clicked tab and the last active tab. So double-click expands the tree, but also briefly activates the folder, and then switches back to the previous tab, causing visual jank, and often the folder I just opened scrolls out of view.

## Environment

 * Platform (OS): Windows 10 / 11
 * Version of Firefox: 109.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.12

**Comment by irvinm** [comment]
@dsl101 just 2 thoughts on this ...

1. You could use CSS to change the format the drop arrow to make it easier to use ... I know this probably isn't your first choice.  (Bigger, different spacing, etc.)
2. You might want to see my thoughts (https://github.com/piroor/treestyletab/discussions/3281) as it is very similar.  At the end of the day, I don't think it is currently possible with TST directly but could be implemented if Piroor wanted to or as an helper addon.

**Comment by SHHSSH** [comment]
This can be done with the helper addon Lock as collapsed. 
TST Settings - When a tab gets focus, expand its tree and collapse others automatically (Check box)

Lock as collapsed Settings - Don't expand tree automatically when (a Parent Tab gets focused) (Uncheck box) 

***** Secondary Comments *****
It takes some optimising of your settings to find what be suits you, though in the end it's really efficient once you're able to macro the set Collapse/Expand keys to a multi macro mouse or any convenient key on your keyboard.

https://addons.mozilla.org/en-US/firefox/addon/tst-lock-tree-collapsed/

The Collapse/Expand hotkeys are located in your about:addons, then the gear icon to the top right. -These are under TST, not Lock as collapsed, though Lock as collapsed will help you I think in this regard too

One of the best things I noticed over time with lock as collapsed, was its ability for me to SKIP over locked groups/folders, with Ctrl+Tab/Ctrl+Shift+Tab, when they are collapsed. In previous TST versions prior to Lock as collapsed helper add on, it would automatically expand the grouped folders whenever I'd want to simply skip past that group/folder.

In recent times I've optimised my TST/Lock as collapsed to rectify this issue and now Ctrl+Tab etc. skips over the whole group/folder and only selects the folder once, then onto the next group/tab.

Although I added other remarks regarding hotkeying of it all, the first comments do allow you to singularly click the parent tab and it will expand the group/folder for you, if you need any screenshots or exported settings, just let me know.

**Comment by dsl101** [comment]
Thanks both for the detailed comments—I will certainly take a look at the helper you linked and see if I can get close to what I'm after. If not, I've built a really small add-on for colouring tabs before, so might take a stab at something specifically for this purpose and post here on progress.

**Comment by SHHSSH** [comment]
Really appreciate that reference @dsl101, I had been having memory issues for the past while, sporadically but couldn't isolate it and I was constantly refreshing profiles etc.

I'm actually using the Lock as collapsed right now though but if the freezing happens again, I've taken note now of that as a potential cause.

**Comment by dsl101** [comment]
No problem! Also, I have a v0.1 version of _my_ add on that just does single click to open / close 'folder' tabs. I suspect there are some rough edges around moving tabs, discarding, etc. But once it's approved, I'll post a link and take feedback :).

**Comment by SHHSSH** [comment]
> No problem! Also, I have a v0.1 version of _my_ add on that just does single click to open / close 'folder' tabs. I suspect there are some rough edges around moving tabs, discarding, etc. But once it's approved, I'll post a link and take feedback :).

I've started using this person's scroll wheel for going through tabs, along with their setting of "Double click" refreshes the tab - https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab-mouse-wheel/, otherwise yeah, double click in Lock as collapsed was good enough for me whilst using that. 

Though all in all, there is a setting in TST under "Tree Behavior" that offers you to expand the tree when the parent tab is selected, albeit, I believe it also collapses all other trees automatically. Do you use that setting? I don't. I have macros hotkeyed on my mouse atm, for Expand/Collapse all (With manually pressing shift) otherwise the macro is set as expand/collapse current tree.

**Comment by dsl101** [comment]
I don't have that setting, no. I have various different trees open at the same time, which is useful, and I really don't want the 'folder' tabs to activate at all—I don't find them useful, and some of mine are _huge_ and lag quite a bit on load. But I just filed [this bug](https://github.com/piroor/treestyletab/issues/3299), as the documentation seems out of step with the behaviour I see regarding not activating the tab. Hope it's something trivial, otherwise the solution will be a lot more involved...

**Comment by dsl101** [comment]
OK, the bug went away :). My simple add-on is now here: https://addons.mozilla.org/en-GB/firefox/addon/tst-folder-expand-collapse/

**Comment by SHHSSH** [comment]
> OK, the bug went away :). My simple add-on is now here: https://addons.mozilla.org/en-GB/firefox/addon/tst-folder-expand-collapse/

@dsl101 Is there about a 333ms or 111ms delay in its initiation? I got it working after thinking it wasn't, then I checked for some potential TST settings conflicts, in the end, I believe it was - https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab-mouse-wheel/, which is a pretty important addon for me as it prevents me from having to use my G-Shift+Right Scroll wheel as those internal buttons on that segment of the mouse seem to deteriorate some of the easiest.

So I got your addon to work without that addon, which I am very unhappy about to behonest, your add on would be awesome without its (seemingly) delay too.

I've deferred from LAC for a while to isolate my freezing issues and I'm not certain if it was the cause yet, though it's been running fine, I have fears it's something else though.

I always tried to do what you do with TST by utilising it as a easily optimisable hierarchical bookmark toolbar, however, over years I really begun to notice sluggish things about opting for that route.

I believe I will try it again though, as bookmarks get pretty darn messy and I'd much prefer they were merely long-term storage and not currently relevant research.

It would be amazing if you could figure out why your addon doesn't work with this scrolling tab addon :|, I'd definitely continue using it, it saves the risk of ruining the commonly used Left/Right scroll buttons on my mouse.

Be well mate.

***EDIT*** I spoke to soon, it still doesn't work, lol... even without that scroll addon enabled, maybe it's some TST setting damnit :|

 
***EDIT EDIT*** Got it working again after a restart, even with the other scroll addon :) perfect, I was getting tired of having to double-click, it's another reason I had expand current tree hotkey on mouse. Cheers mate, definitely using, still a delay though? Confirm if so please.

***EDIT EDIT EDIT*** Nah, it's totally temperamental, only works when it wants to, now it's just not at all again. 

***EDIT EDIT EDIT EDIT*** I can't believe if you're reading this, though even with your addon disabled, it's working functionally as if it was enabled, so maybe it wasn't working all along and I was just perceiving it as working with another TST setting that is likely just expanding the tree from having the parent tab clicked and active for a few hundred milliseconds.

So that's where we're at, haha, will leave it like this for a while, is functional and I am still able to use the scroll tab addon.

**Comment by SHHSSH** [comment]
Nah it wasn't your addon being enabled or disabled, whatever, total wackjobbery, it does work as it should, it must be conflicting in some manner with other addons. I am thankful for you addon immensely though, as it's able to help me expand with ease AND it even ignores LockedasCollapsed trees! Awesome.

If you care at all, my adons - 
https://ibb.co/k2XP4B6
https://ibb.co/sJW7Zhp

and my TST settings - https://mega.nz/file/IH42RbID#35qTWSj9wZYFa97qs0INSGg6XEZcHkF6mCzz0vkq_mE

**Comment by dsl101** [comment]
Well, that was a bit of a rollercoaster :). The add-on system for TST is great in one respect (being able to create things like this), but a nightmare in another respect—conflict of settings, needing 2 add-ons to achieve the desired results, etc. In some circumstances, the order in which the add-ons receive the messages from TST would be important, and I've no idea how TST / FF decides—it could even be different for each user based on the extension id, if that isn't global.

The delay you describe can often be down to something waiting to see if there's going to be a double click, before proceeding with a single click action. My add-on only responds to the `tab-clicked` message, but if I double-click on a 'folder' tab, I do see some glitching where the tree expands, collapses, then _sometimes_ is activated. I'll have to dig into why, but this is exactly the kind of thing that's hard to manage when the functionality is split across lots of different devs, rather than being handled by the main TST dev who's got a good overall picture of how everything hangs together.
