### ISSUE TITLE
[Bug] New tabs opened from pinned tabs are put at the end of the list

### ISSUE THREAD

**Issue by valenting** [piroor/treestyletab#3296]
## Abstract

Instead of being opened at the top of the list, new blank tabs are opened at the end of the list of tabs.

## Steps to reproduce

Configure TST to:
- open new tabs as a child of the current tab. 
- open new blank tabs as a child of current tab
- Insert position of new child tabs: The top of the tree

## Expected result

When opening a new tab with Ctrl-T the new tab should open at the top of the list.
From a pinned tab, the new blank tab should be the first in the list.

## Actual result

The new blank tab is put at the end of the list of tabs.

## Environment

 * Platform (OS): Ubuntu 22.04
 * Version of Firefox: 112.0a1 (2023-02-23)
 * Version (or revision) of Tree Style Tab: 3.9.12

(I apologize if there is an option to achieve this behaviour already - I couldn't find it)

**Comment by irvinm** [comment]
Although there might be a bug here (open new blank tabs as a child of current tab should give you what you want) have you considered using:

`user_pref("browser.tabs.insertAfterCurrent", true);`

Not sure if that breaks any other behaviors you wanted.  This basically forces any new tabs to be inserted after the current one.  In the case of pinned tabs, the new tab will be created at the top of the non-pinned tabs.

**Comment by SHHSSH** [comment]
I came to Github to post this, I've been trying to fix it with settings for MONTHS, I never want to break the settings I have because I am able to skip past grouped/foldered tabs with Ctrl+Tab with these settings when they are Lock as collapsed, in the past it would open the group and scroll through it.

Anyway, @irvinm that worked, didn't know it was in about:config and tried in userchrome.css and TST's CSS settings first :)

See if that breaks anything in the future, appreciate it.

**Comment by piroor** [comment]
@valenting I've realized that TST need to treat the case specially. The commit d14a6b6 should fix this.

@SHHSSH Does this fix affect your topic?

**Comment by SHHSSH** [comment]
> @SHHSSH Does this fix affect your topic?

It has, yes. Totally functional now and prioritises new tab as child tab even with native Firefox origins via bookmark toolbar opening. In years past it would only open as a child on certain conditional origins.
