### ISSUE TITLE
[Enhancement] (Can I make the pinned tabs collapsible like a tree of normal tabs)

### ISSUE THREAD

**Issue by c02y** [piroor/treestyletab#3312]
## Abstract
I always have multiple pinned tabs opened in my Firefox, but I don't always need the full list of them in that place, so is it possible to make the list of the pinned tabs collapsible like a tree of normal tabs, when I need to use one of the pinned tab, I can click and expand the tree?

BTW: I know I can make it to only display the icons of the pinned tabs to save some place, but this is not what I mean, I still need to see the titles of the pinned tabs when they are expanded.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: firefox 111.0-1
 * Version (or revision) of Tree Style Tab:  3.9.14

**Comment by piroor** [comment]
I'm negative to implement this feature. There are some reasons:

* Firefox does not open a pinned new tab from a pinned tab when you middle-click a link in a pinned tab. In other words, Firefox always opens new tabs from links in a pinned tab as regular tabs, even if you set `browser.tabs.insertAfterCurrent` to `true`. I think this means that Firefox developers treat pinned tabs as very special. I'm afraid that breaking the basic strategy may introduce more problems.
* I won't use the feature because I'm using large number of pinned tabs with faviconized appearance and horizontal collupsion/expansion of such faviconized tabs looks hard to understand what's happen. Features I won't use will be abandoned easily - I have very less motivation to maintain codes for features I never use.

Instead of adding built-in behavior, it looks possible to implement as a helper extension with [TST's API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons). If you develop such an addon I'm welcome to add a link to it to the list of known helper addons.

**Comment by c02y** [comment]
Thanks.
