### ISSUE TITLE
[Enhancement] prevent any scrolling (particularly while user is closing tabs)

### ISSUE THREAD

**Issue by colemickens** [piroor/treestyletab#3318]
## Abstract

I'm not sure if this is even possible, or feasible, but it's really my only tiny usability issue with Tree Style Tabs.

TST is of course amazing and allows me to just open far too many tabs during a day. Often time I'll be cleaning up tabs:

I position my mouse over a tab and close it, and then the next one rolls up, I close it, etc.

But eventually, I run out of tabs at the *bottom* of the list, and the list SHIFTS underneath me. So all of the sudden, I'm closing a tab group high up in my tabs, instead of the next one in line.

Particularly, I believe Firefox has a feature for tabs that tries to minimize this behavior. If the tabs become shrunk, and you start closing them, they remain shrunk until the mouse cursor leaves the tab area.

It would be ideal if TST could emulate this, by only shifting the tab list whenever the mouse cursor leaves the TST area. (I don't know if this behavior is something that TST does, or just how it works out with the DOM/browser).

If it would help, I can provide a video showing this, if I haven't described it well.

**Comment by piroor** [comment]
TST is designed to lock the scroll position until the cursor is out from tabs, but the logic sometimes fails while you move the cursor while tabs are removed, due to "mousemove" event fired on the blank area of the tab bar. Thus I've introduced some more safeguard with the commit 71f9937 for such an unexpected mousemove events. It should help you.
