### ISSUE TITLE
Question on tab cycling shortcut when using vertical tabs 

### ISSUE THREAD

**Issue by Zabooby** [piroor/treestyletab#3319]
I am finally trying out vertical tabs but there is one issue that is bugging me.

When using normal horizontal tabs pressing Ctrl + Tab will cycle between your most recent tabs.

For example if you have 4 tabs open and are currently on the 4th tab and have just switched from the third the shortcut will cycle these two tabs first.

But with TST and also Sidebery the shortcut cycles chronologically, going from the 4th to the 1st.

Is there a way to get the original functionality back?

**Comment by piroor** [comment]
Did you check the checkbox?: Firefox options => "General" => "Tabs" => "Ctrl+Tab cycles through tabs in recently used order"
It was checked by default at older versions of Firefox, but unchecked by default on Firefox 89 and later.
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1692303

**Comment by Zabooby** [comment]
Damn I've been using Firefox for over two years and never knew that was a setting, thanks for pointing it out!

Also I've been comparing TST and Sidebery and had a few questions:
1. In Sidebery, it detects the theme I'm using and matches it automatically can TST do the same? 
2. Sidebery has the panels feature does TST have anything similar?
3. From the few reddit posts I've seen would it be accurate to say TST is more for power users while Sidebery is better for beginners to vertical tabs?

**Comment by piroor** [comment]
>     1. In Sidebery, it detects the theme I'm using and matches it automatically can TST do the same?

TST automatically applies the color scheme of the browser's active theme.

>     2. Sidebery has the panels feature does TST have anything similar?

TST does not provide popup panel for the toolbar button. TST is designed to be used with permanently shown sidebar.

>     3. From the few reddit posts I've seen would it be accurate to say TST is more for power users while Sidebery is better for beginners to vertical tabs?

It is difficult to say what is "better for beginners".

TST is designed to simulate Firefox's native tab behaviors (ex. tab context menu) and isolated from features not contained in Firefox except tree management, to minimize confusion from difference between Firefox's native tabs UI and TST's sidebar UI. It should mean that TST's default behavior (vanilla settings with no customization) may be friendly for general Firefox users including beginners. I think Sidebery may be an addon for power users if its behavior is quite different from Firefox's one and it has various custom features .

On the other hand, someone may think that TST has very limited features so it is designed for power users. They may think that Sidebery is for beginners because it has rich features and options UI.

So I decided to stay myself away from any fray from the topic. Currently I have no idea to compete aggressively with other projects.

**Comment by Zabooby** [comment]
Thanks for the insightful response, after spending more time with both I can definitely see that although they are made for the same core purpose the approaches they take are very different. But I am glad they both exist! :)
