### ISSUE TITLE
[Bug] RootFolder missing when restoring a TabsTree from Bookmarks

### ISSUE THREAD

**Issue by morco** [piroor/treestyletab#3321]
## Abstract

I'm recently stumbled about this addon and immediately took a liking. Playing around with it to find the best way for me to use it I came across a behavior which seems buggy to me. Using the built-in save to bookmark and then trying to recreate the tree from bookmark feature "eats up" the root folder (special manual named "group-tab" meta folder).

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install TST More Tree Commands.
 4. Install TST Open Bookmarks as Partial Tree (only for comparison).
 5. Create 1 or 2 level hierarchical tab tree, with all parent levels being `group-tab` meta tabs from TST More Tree Commands addon.
 6. Bookmark the tree by selecting "bookmark this tree" from context menu on root folder.
 7. Try to re-create the same tree from bookmarks by selecting "Open all as Tree" or "Open all as Tree including subdirs".

Let's take an Example Structure like this:

```
root (group-tab metatab)
  subfolder (group-tab metatab)
    normal-tab-1
    normal-tab-2
```

## Expected result

After restore from bookmark the following tree structure is expected:
```
root (group-tab metatab)
  subfolder (group-tab metatab)
    normal-tab-1
    normal-tab-2
```

## Actual result

```
subfolder (group-tab metatab)
  normal-tab-1
  normal-tab-2
```

## Environment

 * Platform (OS): Linux (Ubuntu) 
 * Version of Firefox: 111.0.1
 * Version (or revision) of Tree Style Tab: 3.9.15
 * Version (or revision) of TST More Tree Commands: 1.5

## Additional Notes

As this issue involves more than one extension and I'm not sure where is the best place to put this. It might be possible that this is better addressed in "TST More Tree Commands" repo.

**Comment by morco** [comment]
After comparing what the plugin does when using "standard" tabs tree without manual group-tab meta nodes I think I can see where the deciding difference is.
For the standard case an extra root dir is automatically created inside the bookmark folder to house the tree tab. In that case it is undoubtedly correct to skip this automatically created top-level directory.
But for a tree starting with a manual group-tab meta-node this auto toplvl dir creation does not happen and the tree structure is put directly into the bookmark folder.

So would it be possible to always create this top-lvl auto dir which should fix it I would assume?
Alternatively it might be fixable on the restore side applying some detect and handle differently magic?

A third variant I would also be fine with is to allow the "Open Tree partially" feature also on top-lvl bookmark nodes as it doesn't seem to have this "skip the the 1st folder" behavior but I don't know if this really fits in the concept.

**Comment by piroor** [comment]
Did you talk about bookmarks created by TST with this structure?:

* `root` (bookmark folder)
  * `subfolder` (regular bookmark, url is `ext+treestyletab:group?title=subfolder&...`)
  * `> normal-tab-1` (regular bookmark)
  * `> normal-tab-2` (regular bookmark)

Then this is intentional and currently there is no option to save/restore complete tree on this case.

* TST's behavior on opening tabs from a bookmark folder:
  * TST opens a "group tab" corresponding to the bookmark folder, to organize tabs from bookmark items as a tree. I initially designed this behavior for bookmak items with no tree information. In other words, the "group tab" was introduced to avoid multiple root level unorganized tabs made by the action "open bookmarks from a folder".
  * But there is an exception. TST does not open a "group tab" corresponding to the bookmark folder ("root" on your case), if there is only one top level tab from bookmark items ("subfolder on your case). This is because tabs from bookmarks are already organized as a tree and we need to do nothing to avoid multiple root level unorganized tabs.
* TST's behavior on bookmarks creation:
  * On regular cases TST creates a bookmark folder to save the whole tree, and creates all bookmark items corresponding to all tabs in the target tree under the bookmark folder.
  * But there is an exception. When the target tree is organized under a "group tab" ("root" on your case), TST does not create a regular bookmark corresponding to the "root", instead TST creates a bookmark folder corresponding to the "root", and creates bookmark items from descendants ("subfolder" and two regular items) under the bookmark folder. I initially designed this behavior for cases with a root level group tab and flat children.

Your case is on these both exceptions and the combination produces the unexpected result you saw.

**Comment by piroor** [comment]
The commit 1d9db2c adds a new option to deactivate the exception: 'TST does not open a "group tab" corresponding to the bookmark folder ("root" on your case), if there is only one top level tab from bookmark items ("subfolder on your case).'
