### ISSUE TITLE
[Enhancement] Recommend TabSessionManager so people don't lose their tab trees and sessions

### ISSUE THREAD

**Issue by mYnDstrEAm** [piroor/treestyletab#3334]
## Abstract
I think TabSessionManager should be recommended by the addon in a way that the user reads that because otherwise people can lose all their tabs, which happened many tabs looking through the repo's issues.

It should be a high priority that people to make absolutely sure people don't lose their sessions and depending on how it's implemented this could be a very small change, especially if there already is an intro window getting displayed after the addon is installed.

## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open many tabs and sort them in tab trees
 4. Experience a crash or anything else that causes you to lose your session, making it not recoverable with Firefox' History->Restore previous session

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
It looks out of the project scope for me. TST and Tab Session Manager are designed for quite different purposes.

I agree the combination is effective on some use cases, but your suggestion looks like a recommendation to combine Adobe Illustrator (high-power vector graphics editor tool) and Microsoft PowerPoint (presentation tool) for all PowerPoint users - I use AI and PP together but I don't think to recommend that for people because overkill for most PP users.

**Comment by mYnDstrEAm** [comment]
Yes but TSM can (help users) ensure that they don't lose their tab tree structures, this is how it's relevant despite of the different purpose. One option would be to only recommend it once the number of tabs first grows above a certain number (or a small info popup whenever it does).

If it's really out of scope the issue could be closed. I proposed **ways for users to discover, learn about and find helpful TST extensions like TSM** in a separate issue and discussion could continue there:  #3339.
