### ISSUE TITLE
[Enhancement] Support Chrome

### ISSUE THREAD

**Issue by tbodt** [piroor/treestyletab#3354]
Chrome 114, available since last month, supports a [side panel api](https://developer.chrome.com/docs/extensions/reference/sidePanel/). The API is different from firefox, though.

**Comment by piroor** [comment]
TST depends on session store API also - it is required to track tabs over sessions. Chrome does not provide it for extensions so TST on Chrome may lose tree structure more frequently after you restart Chrome.

And more, currently TST is based on the Manifest V2 but Chrome supports only Manifest V3 extensions. Manifest V3 does not allow extensions to run any permanent process, but TST is designed to work with a permanent process which track all changes of tabs in the background. It became more hard to port TST to Chrome due to the death of Manifest V2 on Chrome.

**Comment by piroor** [comment]
Anyway I have no plan to port TST to Chrome by my hand because I have no plan to switch the main browser from Firefox to Chrome and I'm developing TST mainly for myself. I won't try port TST to Chrome until Firefox completely dies.
