### ISSUE TITLE
[Enhancement] Add context menu items for opening a new tab as child/sibling/independent of the current tab

### ISSUE THREAD

**Issue by saltiniroberto** [piroor/treestyletab#3393]
Via the new tab button at the bottom, it is currently possible to open a new tab and select its relationship to the current tab.
However, this is not very handy when many tabs are open as the new tab button is then located to the bottom.
It would be far easier to have such an action available via the context menu.

**Comment by piroor** [comment]
I have no plan to add the feature because Firefox doesn't provide context menu commands like "open new tab here". 
There is an addon which provides the feature for Firefox's native tabbar: https://addons.mozilla.org/firefox/addon/new-tab-here/
So I think there are two possible choices:

* Requesting a feature to open a new "child" tab (opening a new tab with an `openerTabId` parameter) to the addon: it will be useful for other tree tab addons.
* Creating a new helper addon for TST with a context menu command like "open new child tab".
