### ISSUE TITLE
[Bug] Buttons sometimes work on the wrong tab, requires an addon restart

### ISSUE THREAD

**Issue by lengau** [piroor/treestyletab#3403]
## Abstract

Occasionally, the UI will activate the wrong tabs on click. This has happened across multiple Firefox profiles on multiple machines, including with the latest TST.

The right-click menu etc. also refers to the wrong tab and the UI still updates. The issue seems to be limited to the fact that the UI thinks I'm interacting with a different object.

## Steps to reproduce

Unfortunately I haven't over several months been able to create a clear set of reproduction steps. However, this appears to occur the most with:

* 5 or more windows on different desktops
* Multiple displays
* Firefox set to have native Wayland mode on Linux (though it does also occur under X11)
* Pinned tabs

## Expected result

Click a tab in tree-style tabs, get that tab

## Actual result

Get the wrong tab, but consistently the same incorrect tabs. The UI highlights the correct tab, so it's just the input that's wrong.

## Workaround

Disabling and re-enabling Tree Style Tab in `about:addons` always fixes it.

## Environment

 * Platform (OS): Ubuntu Linux (multiple versions, currently using Kubuntu 23.10)
 * Version of Firefox:  Multiple versions dating back to 112. Currently: 118.0.1 (64-bit) using the snap install (this appears to be irrelevant though as it also occurred when using a deb package).
 * Version (or revision) of Tree Style Tab:  Current: 3.9.17 (This has been going on since at least July

**Comment by piroor** [comment]
This sometimes happens on Windows environment also, so it looks a platform independent issue.

1. Something happens which breaks synchronized state and order of tabs between Firefox and TST.
2. Due to the broken synchronization, clicking on a TST tab activates different Firefox tab.

Sadly we cannot investigate what causes the broken state at the stage 2. We need to know what operation triggers the broken state at the stage 1.

From my personal experience, situations this kind of problems often happens are:

* Multiple tabs are opened in a browser window and they are moved to another browser window imediately (by another addon).
* A child tab is opened from an existing tab, a new more tab is opened automatically as a "reopened" tab (by another addon), and the initially opened child tab is immediately closed.

Firefox addons including TST needs to access Firefox's tabs via asynchronous APIs. Tracked state of tabs may be confused when multiple operations are happens at a time, but it is quite inconsistent - sometimes happens and sometimes doesn't, maybe due to system performance or other reasons. So I still need more help to narrow down stable steps to reproduce...
