### ISSUE TITLE
[Bug] Can't drag tabs out the window into a new window

### ISSUE THREAD

**Issue by YousufSSyed** [piroor/treestyletab#3411]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open two tabs
 4. Drag one out of the current window.

## Expected result
The tab is removed from the current window and a new window is created with and for it. 

## Actual result
The tab doesn't move at all despite seeing the banner message on the bottom that it would do so.

## Environment

 * Platform (OS): macOS 14
 * Version of Firefox: 119.0.1
 * Version (or revision) of Tree Style Tab: 3.9.18

**Comment by piroor** [comment]
Could you try shake your mouse cursor over other tabs before you release the button at outside of the sidebar area? Sometimes TST fails to detect your releasing of the button at outside of the sidebar, due to DOM event un-firing when you move your cursor across the sidebar immediately. Moving cursor across multiple DOM elements fires DOM event more certainly.

**Comment by YousufSSyed** [comment]
@piroor Here's a video
https://github.com/piroor/treestyletab/assets/42646062/52846fbb-39aa-4b08-828c-66f9f4b619ea

**Comment by piroor** [comment]
Thanks! Hmm, more debugging on macOS looks required...

**Comment by YousufSSyed** [comment]
@piroor Would you want me to do some debugging?

**Comment by simcye** [comment]
I get this occasionally, when it happens tabs go greyed out and I can't move them using either tree tab interface or the normal firefox interface, also when it happens at the bottom of the tree tab interface it starts scrolling this help text: "Dropping ot outside of sidebar will detach tabs from window [...]"

only way to fix it is restart firefox

**Comment by piroor** [comment]
After some investigation, I've realized that the problem is triggered due to delayed notification of changes to the local storage.
When you try to detach a tab from the window:

1. [dragenter event is dispatched, and internal config `lastDragOverSidebarOwnerWindowId` is updated with a specific window id.](https://github.com/piroor/treestyletab/blob/1d97b0906cba49c119bbb4d368b1a4051c12e793/webextensions/sidebar/drag-and-drop.js#L1134)
2. [dragleave event is dispatched, and internal config `lastDragOverSidebarOwnerWindowId` is cleared.](https://github.com/piroor/treestyletab/blob/1d97b0906cba49c119bbb4d368b1a4051c12e793/webextensions/sidebar/drag-and-drop.js#L1244)
3. `storage.local.onChanged` listener is called with `lastDragOverSidebarOwnerWindowId=id` (it was triggered by dragenter) and internal value of `lastDragOverSidebarOwnerWindowId` is unexpectedly overwritten with a specific window id.
4. [dragend event is dispatched when you release the mouse button. `lastDragOverSidebarOwnerWindowId` has a window id, so TST treats the dragend event as "happens at inside the sidebar area", because `lastDragOverSidebarOwnerWindowId` should be cleared by dragleave.](https://github.com/piroor/treestyletab/blob/1d97b0906cba49c119bbb4d368b1a4051c12e793/webextensions/sidebar/drag-and-drop.js#L1419) As the result TST does not detach the tab from the window.

I've introduced [a change to avoid such a timing issue](https://github.com/piroor/webextensions-lib-configs/commit/246038c6051fdcae3f26248a3fed7bf83e38128e). A new development build is available at https://github.com/piroor/treestyletab/actions/runs/7193861829 so could you try it? @YousufSSyed

**Comment by YousufSSyed** [comment]
@piroor I installed Firefox Dev Edition and sideloaded it on the about:debugging page. It works very inconsistently, I thought it wasn't working at all until I did it like 5 times.

**Comment by piroor** [comment]
TST intentionally ignores tabs dropped near to the sidebar within (tab-height / 2) pixels for safety. For example, tabs dropped within 10 pixels from the sidebar area won't be detached if your tabs are shown with 20px height. Is your case described with this behavior?

Otherwise, some old workarounds may cause mis-detection of coordinates. Could you collect debug logs with a new development build? Steps are:

1. Download XPI from https://github.com/piroor/treestyletab/actions/runs/7203396156 and install it.
2. Go to TST's options page.
3. Under the "Development" section, set as:
   * "Debug mode" => checked
   * "Log with timestamp" => checked
   * "sidebar/drag-and-drop" => checked
   * All other checkboxes under "Detailed logging" => unchecked 
4. Go to about:debugging
5. "This Firefox" => "Temporary Extensions" or "Extensions" => "Tree Style Tab" => click the "Inspect" button.
6. A remote debugger window is opened for TST. Ensure that "always on top" is activated.
7. Click "Console" in the debugger window.
8. Click the trash box button to clear contents.
9. Try to detach an individual tab with drag and drop.
10. You'll see logs like this: ![image](https://github.com/piroor/treestyletab/assets/70062/495b6575-f329-4f0a-b02f-f3870781cfc2)
    All logs below the message "onDragStart: start" are from your drag session. This is an example when a tab is successfully detached - please note there is a message "trying to detach tab from window". 
11. Look at logs below the message "onDragEnd,". Some detailed parameters are collapsed with ellipses like "Object { a:0, b:1, ... }", for example "dragend at:" in the screenshot. It means some parameters are not disclosed, so click their triangle to expand them. You don't need to expand parameters recursively - only the top level needs to become visible, like as: ![image](https://github.com/piroor/treestyletab/assets/70062/a758b668-28d4-4be7-9b5a-f7553245fcd4)
12. Copy logs below the message "onDragStart: start" and paste it here.
