### ISSUE TITLE
[Enhancement] hide collapsed tabs and introduce a key shortcut to collapse/expand

### ISSUE THREAD

**Issue by polysquirrel** [piroor/treestyletab#3421]
## Steps to see the situation
This is an alternative (or complementing) proposal to #3324 
```
A (focused)
 \- B (collapsed)
 |- C (collapsed)
D 
 \- E
 |- F
```

## Expected result
Let's define the toggle as `ctrl+space` for 'collapse/expand all' and `ctrl+shift+space` for 'collapse/expand recursively'.

Pressing either `ctrl+space` or `ctrl+shift+space` should create the following tree:
```
A (focused)
D
 \- E
 |- F
```
Additionally, tabs `E` and `F` are *hidden from the top tab bar*.
In this configuration, `ctrl+pgdown` brings focus to `D`, and following `ctrl+pgup` brings focus back to `A`.

**Comment by piroor** [comment]
There are some my past comments describing risks when TST hides tabs in Firefox's native tab bar:

https://github.com/piroor/treestyletab/issues/1831#issuecomment-373618534
https://github.com/piroor/treestyletab/issues/1371#issuecomment-491575613

In short: Tabs hidden when they are just collapsed will introduce compatibility issues with other tab addons and Firefox's native behavior (because hidden tabs are treated as unexisting by Firefox itself.) Thus I decided that I don't introduce this change.
