### ISSUE TITLE
[Enhancement] Ability to move to the top of the screen

### ISSUE THREAD

**Issue by Slyceth** [piroor/treestyletab#3432]
I would like to see the feature of being able to use this add-on to completely supplant the old firefox tab system. I already removed the regular tabs with css, but the fact I'm stuck with the sidebar really restricts watching ultrawide (cinema) video content, just to name one problem, it also crowds the screen from 2 directions unnecessarily.
I see no reason not to try to move it to the top, the tab groups that are open can collapse either down, overlaying the screen, or sideways, overlaying the other tabs. 
You can even have 2 or even 3 or more rows of tabs and tab groups! And maybe the option to autohide some of them until you hover.

**Comment by piroor** [comment]
Sadly it is impossible for now because Firefox does not allow such behaviors for WebExtensions API-based addons. 
Using [Tree Style Tab in Separate Window](https://addons.mozilla.org/firefox/addon/tst-in-separate-window/) and something native utility application to put arbitrary window on the top may be a workaround.
