### ISSUE TITLE
[Enhancement] skip close confirmation when holding shift

### ISSUE THREAD

**Issue by Vosjedev** [piroor/treestyletab#3448]
## Steps to see the situation

 1. Start Firefox with clean profile.
 2. Install TST.
 3. open a tree of tabs.
 4. try and close the top tab with shift to skip `are you sure you want to close x tabs?` prompt and close the whole tree.

## Expected result
The confirmation about closing tabs is not shows because shift is pressed.

## Actual (present) result
It just shows the confirmation

## Environment

 * Platform (OS):  linux
 * Version of Firefox: Firefox develop edition 123.0b6 
 * Version (or revision) of Tree Style Tab: 3.9.22

-----

Because of how this template is structured, I need to add some things (not a problem).
This is not currently an existing feature, but I would like to request a feature. That is: closing the parent of a tree while holding shift (or any other modifier you like for this) should close the tree without confirming closing the tree. If you like to add a setting to enable/disable this, please do so. Some people could not like this, but choose for yourself if you have the time to add a toggle for it (I don't need it).

Thanks, TST improved my workflow a lot.

**Comment by SHHSSH** [comment]
This would be really useful as I do have to have an additional Enter key press because it's wiser to keep the warning prompt it feels.

Although I find the potential for it to conflict with other(maybe native FF tab behaviour) multi-select functionality of the tree, whereas; all sub-tabs are selected(even when clicking on X).

If this potential conflict is able to be worked around, this would be a great, optional enhancement.

PS
If you're thinking Shift is still an additional key press also for the user, for some it doesn't feel as much so because it's often a key that's utilised on the mouse.

**Comment by piroor** [comment]
I've tried to multiselect large number tabs and shift-click on the close box of the active tab or shift-middle-click on a mutiselected tab at Firefox's native tab bar, and Firefox still shows a confirmation dialog. Thus the behavior you described here looks incompatible to Firefox and beyond the scope, due to the base policy of this project :behaving as Firefox compatible behavior as possible.

This feature looks to be able to be done by a new helper addon using TST's API. I hope you develop and publish it.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#when-a-tab-is-clicked

**Comment by Vosjedev** [comment]
Then it'll end here as I am not planning on learning extention development anytime soon. I guess this can be closed then.
