### ISSUE TITLE
[Bug] Tab numbering is incorrect (remains static) above a certain tab count

### ISSUE THREAD

**Issue by Decohero** [piroor/treestyletab#3486]
## Abstract

This bug affects the tab numbers displayed on the tabs when the CSS contains a tab counter as shown in the documentation example, which has worked for many years without modification.

When there are more than a certain number of tabs (in my case, 133 on one system and 113 an another), scrolling the tab list beyond the point where that tab number is at the bottom will cause TST to redraw the tab numbers such that the bottom tab always has that same number (e.g. 133), and the rest of the tabs above it descend sequentially.

So for example, if you have 1000 tabs, scrolling to the bottom of the list should show tabs 950-1000, numbered 950-1000, but they are instead shown numbered 64-113.  The correct numbers appear while scrolling, but are quickly redrawn with the incorrect numbers.

## Steps to reproduce

If needed, add the tab numbering CSS to the tab display field in the config panel:

	#tabbar {
	  counter-reset: vtabs atabs tabs;
	  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
	}
	.tab:not(.collapsed):not(.discarded) {
	  counter-increment: vtabs atabs tabs;
	}
	.tab:not(.collapsed) {
	  counter-increment: vtabs tabs;
	}
	.tab:not(.discarded) {
	  counter-increment: atabs tabs;
	}
	.tab {
	  counter-increment: tabs;
	}

	.tab::after {
	  background: black;
	  color: Orange;
	  opacity: .7;
	  content: counter(tabs);
	  font-size: xx-small;
	  right: .1em;
	  padding: 0.1em;
	  pointer-events: none;
	  position: absolute;
	  bottom: 0.1em;
	  z-index: 200;
	}

	.tab .active-marker::before {
	  background: Highlight;
	  color: HighlightText;
	  content: counter(vtabs);
	  font-size: x-small;
	  right: 0.2em;
	  padding: 0.2em;
	  pointer-events none;
	  position: absolute;
	  bottom: 0.2em;
	}

Then create enough tabs to observe the bug.  It would seem that the number of tabs needed to show the bug is dependent on how many tabs are visible on your screen (i.e. tab height).  150 tabs should be plenty.

Then scroll the tab list to see if the tab numbers stop incrementing after a point.

## Expected result

Properly-numbered tabs.

## Actual result

Improperly-numbered tabs (which stop incrementing after a point).

## Environment

I suspect that this behavior appeared with a recent Firefox update.  Both affected systems are running the current TST: 4.0.3 (2024.3.13) and the current Firefox (115.8.0esr).  One system is Mac OS 12.6.2 (Monterey), and the other is Windows 10 22H2 (19045.3448).  The previous version of TST was also affected.

**Comment by piroor** [comment]
In short: CSS counter hack is not available anymore and we need to use a helper addon. See also the discussion: #3472

**Comment by Decohero** [comment]
I had been expecting a tab counter extension based on the TST API to appear, but I never saw one.  The absence of an accurate tab count has been so disruptive to my workflow that I tried creating one myself.  It's not perfect, but for those few who may require this feature, it seems to work well enough:

Plugin here:
https://addons.mozilla.org/en-US/firefox/addon/tst-tabcount/

Code here:
https://github.com/Decohero/tst-tabcount

**Comment by roman-orekhov** [comment]
@Decohero 
Thank you!
The tab count hides folded tabs count, close button and muted tab signs however (which all appear on the far right of the tab). Is there an easy fix one can make in `background_script.js` to overcome this?

**Comment by JZersche** [comment]
> I had been expecting a tab counter extension based on the TST API to appear, but I never saw one. The absence of an accurate tab count has been so disruptive to my workflow that I tried creating one myself. It's not perfect, but for those few who may require this feature, it seems to work well enough:
> 
> Plugin here: https://addons.mozilla.org/en-US/firefox/addon/tst-tabcount/
> 
> Code here: https://github.com/Decohero/tst-tabcount

![Image](https://github.com/user-attachments/assets/61e16156-7e59-46c7-8c9e-00a63ef59d7f)

>>> tab-item .extra-items-container.behind

Modified:
```
function insertContents(tabId, content = tabId) {
    var formattedContents = '<small id="tab-counter" part="tab-counter">' + content + '</small>';
    browser.runtime.sendMessage(TST_ID, {
        type:     'set-extra-contents',
        place:    'tab-behind',
        part:     'tab-counter',
        tab:      tabId,
        contents: formattedContents
    });
}
```
```
            style: `
            ::part(%EXTRA_CONTENTS_PART% tab-counter) {
                background: black;
                color: white;
                font-size: xx-small;
                left: 0.1em;
                padding: 0.1em;
                pointer-events: none;
                position: absolute;
                bottom: 0.1em;
                z-index: 200;
            }
          `,
```


So the fix is simply adjusting the styling to however the user wants it and inserting it in the appropriate selector I listed above. This extension could be improved to add a settings option to choose where the tab counter is inserted, if anyone thinks it worth the effort. 

I modified the code to automatically reorder the tab numbers whenever tabs are sorted or moved. Previously, the numbers remained static after drag-and-drop operations or tab rearrangements, leading to disordered numbers. With this simple correction, tab numbers now update instantly in response to both Tree Style Tab events and native browser tab movement, ensuring they always reflect the correct order in real time.

You can deprecate and remove these items from your listeningTypes: [:
`'tree-attached', 'tree-detached',`

Additionally, remove these cases from your switch statement.
`case 'tree-attached': case 'tree-detached':`

<https://pastebin.com/kex7Hkqg>


All that's needed is this. I just tested it, and it works perfect. 

```
registerToTST();
refreshTabNumbers();
// Add this:
+browser.tabs.onMoved.addListener(() => refreshTabNumbers());
+browser.tabs.onAttached.addListener(() => refreshTabNumbers());
+browser.tabs.onDetached.addListener(() => refreshTabNumbers());
+browser.tabs.onRemoved.addListener(() => refreshTabNumbers());
+browser.tabs.onCreated.addListener(() => refreshTabNumbers());
```



As for why the CSS counter loses count, I believe it's due to Firefox's use of DOM virtualization for performance optimization. Instead of rendering all tab elements in the DOM at once, Firefox only keeps the currently visible tabs — and a few adjacent ones — in the active DOM tree. Since CSS counters rely on the physical presence and order of elements in the DOM, tabs that are not currently rendered are excluded from the count, leading to static or incorrect numbering.

**Comment by roman-orekhov** [comment]
> As for why the CSS counter loses count

Thanks for your explanation! I guess I'm out of luck then

**Comment by JZersche** [comment]
> > As for why the CSS counter loses count
> 
> Thanks for your explanation! I guess I'm out of luck then

The fix I posted above will address your issue —>

> the tab count hides folded tabs count, close button and muted tab signs however (which all appear on the far right of the tab). Is there an easy fix one can make in `background_script.js` to overcome this?

**Comment by roman-orekhov** [comment]
I hope original author would merge the fix so that I can use a signed version of the addon. Updating the file in the xpi stopped the addon as unsigned. And I won't be disabling `xpinstall.signatures.required` (even if I were to move to an ESR/Nightly/Developer editions) as it would allow for all unsigned addons not just this one.

**Comment by JZersche** [comment]
> I hope original author would merge the fix so that I can use a signed version of the addon. Updating the file in the xpi stopped the addon as unsigned. And I won't be disabling `xpinstall.signatures.required` (even if I were to move to an ESR/Nightly/Developer editions) as it would allow for all unsigned addons not just this one.

I'll have it signed later on if it isn't merged. Check back here in a week.

Edit: Should be signed within the next 24 hours.

**Comment by roman-orekhov** [comment]
> +browser.tabs.onDetached.addListener(() => refreshTabNumbers());
+browser.tabs.onRemoved.addListener(() => refreshTabNumbers());
+browser.tabs.onCreated.addListener(() => refreshTabNumbers());

BTW, your paste doesn't contain these

**Comment by JZersche** [comment]
> > +browser.tabs.onDetached.addListener(() => refreshTabNumbers());
> > +browser.tabs.onRemoved.addListener(() => refreshTabNumbers());
> > +browser.tabs.onCreated.addListener(() => refreshTabNumbers());
> 
> BTW, your paste doesn't contain these

Yeah I'm aware, I never added them to the code either. It's really only needed if you're moving a tab out of the window. But after the upload is signed, I'll patch that in. It works just fine for now, assuming you're not dragging tabs out of the window and back in, and even if you are, an extension like SortTabs will sort it. But it'll all work once Mozilla signs it. I will also release my Tree-Style Tab theme on my GitHub.. right now.

https://github.com/JZersche/Tree-Style-Tab-zDark-Theme/tree/main

![Image](https://github.com/user-attachments/assets/2c8e5c04-8f1e-4daa-a11e-08f0093dfcc8)

**Comment by JZersche** [comment]
https://addons.mozilla.org/en-US/firefox/addon/treestyle-tab-count

Signed

**Comment by roman-orekhov** [comment]
Thanks!

It's almost invisible on default (light) theme, but it shows correct tab count on the left of the tab unlike the `counter(tabs)` code for the 'new tab' button! Is it possible to have data exported from this extension into TST so that the 'new tab' button would receive correct tab count? (Edit: nvm, there is another addon with correct tabcount on the new tab button already)

Also closing inner tabs doesn't update the numbers

**Comment by JZersche** [comment]
> Thanks!
> 
> It's almost invisible on default (light) theme, but it shows correct tab count on the left of the tab unlike the `counter(tabs)` code for the 'new tab' button! Is it possible to have data exported from this extension into TST so that the 'new tab' button would receive correct tab count? (Edit: nvm, there is another addon with correct tabcount on the new tab button already)
> 
> Also closing inner tabs doesn't update the numbers

I haven't yet patched in the fix for that yet. Just for now, use 
>>> addons.mozilla.org/en-US/firefox/addon/sorttabs

Then sort your tabs with it, and it'll sort the numbers out also until I get around to patching in the next update.

```
+browser.tabs.onDetached.addListener(() => refreshTabNumbers());
+browser.tabs.onRemoved.addListener(() => refreshTabNumbers());
+browser.tabs.onCreated.addListener(() => refreshTabNumbers());
```

Edit: 7.21.2025 — All Issues are fixed. Simply update.

Support for light theme, with the ability to change the coloring will come later on when I become more experienced with developing addons. I rushed this release, so just for now you can use dark theme. (which is also better for your eyes anyway)
