### ISSUE TITLE
[Bug] Startup time is very long (5-10 min) with many tabs loaded

### ISSUE THREAD

**Issue by valadaptive** [piroor/treestyletab#3512]
## Abstract

With many tabs loaded (~5000), TST takes 5-10 minutes to start up. It looks like the culprit is either custom element lifecycle callbacks or updateVisualMaxTreeLevel.

[Here's a profile showing custom element lifecycle callbacks](https://profiler.firefox.com/public/k93negdcrg9pdda62s8ee2r9ehk3t114bnrz26r/stack-chart/?globalTrackOrder=01&implementation=js&thread=2&v=10), and [here's one showing updateVisualMaxTreeLevel](https://profiler.firefox.com/public/wes9212qqhrc1qnqvtyat6nf0js7q4sep0b6prg/stack-chart/?globalTrackOrder=01&implementation=js&thread=2&v=10).

This is very likely to be an "accidentally quadratic" bug--updateVisualMaxTreeLevel is almost certainly querying every tab every time it is called, and a lifecycle callback may also be doing something that involves iterating over every tab.

It also seems like each tab element is triggering a forced reflow when it's created, which is also a huge slowdown.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set Firefox to restore previous session
 4. Open thousands of tabs
 5. Restart Firefox

## Expected result

Firefox opens in a minute or two

## Actual result

It takes 5-10 minutes for TST to load, during which time the sidebar is frozen and no tabs can be loaded.

## Environment

 * Platform (OS): Fedora Linux 39
 * Version of Firefox: 124.0.1
 * Version (or revision) of Tree Style Tab: 4.0.10

**Comment by piroor** [comment]
Thanks, I've realized that too many function call happens on the no-animation mode. With recent changes it is now throttled.

**Comment by manyfew** [comment]
Is it normal that Firefox uses several GB of ram when hundreds of tabs are open, even if they are not loaded? Before I start Firefox RAM usage on my computer is less than 4 GB, after starting FF it's > 14 GB, but I'm only a handful of tabs (20 or so). Also loading times are very long, usually minutes. This has been like this for as long as I can remember.

**Comment by piroor** [comment]
How did you measure RAM usage? Some measurement method can report too large number because Firefox has its owne RAM allocation system. The allocation system takes large RAM area at first for better performance but most of part may not used actually.

On my case, Firefox 124.0.1 on Windows 11 with 500+ tabs, `about:memory` reports:

* Main Process
  * Explicit Allocations: 936MB
* GPU
  * Explicit Allocations: 375.63MB
* extension
  * Explicit Allocations: 402.59MB

Could you compare explicit allocations size of these three processes when TST is loaded and TST is unloaded?
(There are more content processes but we can ignore them because those processes will eat RAM even if TST is not installed. We should concentrate to think about RAM usage of TST related processes, the three.)

**Comment by manyfew** [comment]
Hi, thanks for replying. I used the process manager (Process Hacker in my case) to check total RAM usage while Firefox is running. Then I close Firefox and RAM usage drops to 3 or 4 GB. I had always assumed TST was the resource hog. Let me disable TST and restart Firefox to see if it opens more quickly and also what happens to RAM usage. I will report back in a minute. Meanwhile, I just checked _about:memory_ and here are the numbers:

Main process → Explicit allocations: 1,328.76 MB
GPU → Explicit allocations: 673.97 MB
extension → Explicit allocations: 634.84 MB

It doesn't look too different from yours.
