### ISSUE TITLE
[Bug] No longer able to prevent automatic tree expand / collapse?

### ISSUE THREAD

**Issue by jjlee** [piroor/treestyletab#3513]
I guess I'll report this from my user perspective as a bug even though it may be an intentional change (also :heart:  TST, I've been using it since... is it 2008??  The ongoing care with maintenance has made it very valuable).  If this is an intentional change, it would be great to know the reasons (e.g. perhaps changes to the firefox extensions API or performance characteristics, or simplified code?).

Problem: Previously it was possible to set "Tree behavior" preferences such that TST never automatically expanded or collapsed tabs (by "automatically" I mean without an explicit user click on the ">" / "v" widget to the left side of each non-leaf tab).  Now I can't figure out how to achieve that behaviour by setting TST preferences.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create a top-level tab with children tabs: Drag all the open tabs under the "Welcome to Firefox" tab so that they are direct children of that tab.
 4. Open a "New Tab" tab by clicking the "+" button at the bottom of the vertical tab bar ("New Tab" is now selected and is a top-level tab, a sibling of "Welcome to Firefox")
 5. Open a new tab as a child of "New Tab".  To do that I middle clicked the first of the default new tab page story links

## Actual result

- The "Welcome to Firefox" tab collapses.
- Clicking on "Welcome to Firefox" expands that tab and collapses "New Tab".
- It seems to be not possible to configure TST so that it never automatically expands or collapses tabs in this way.

## Expected result

- It's possible to configure TST such that at this point the expanded/collapsed state of "Welcome to Firefox" is unchanged.  I used to do this by toggling "When a new tree appears, collapse others automatically", and "When a tab gets focus, expand its tree and collapse others automatically" under "Tree behavior" in preferences.

## Environment

 * Platform (OS): Arch Linux
 * 124.0.1
 * Version (or revision) of Tree Style Tab: 4.0.10

**Comment by ugurbolat** [comment]
experiencing the same behavior

- firefox 124.0.1 
- tree tabs 4.0.8
- ubuntu

**Comment by jf** [comment]
experience the same thing here. This used to be a thing that I would set up for **each and every single install of TST**; I even have a screenshot of all the settings I want to have so that I can reproduce it on every install, so I know it's a thing.

Now I can't find it, and I *hate* this default. The following is a screenshot of what I used to be able to set (I uncheck the first 2 options: `When a new tree appears, collapse others automatically`, and `When a tab gets focus, expand its tree and collapse others automatically`)

(For the record I've also tried unchecking what looks like it could work - except it doesn't: `Don't expand collapsed tree and skip collapsed descendants, while switching focus of tabs via keyboard shortcuts. (*You need to allow executing scripts on webpages.)`)

<img width="674" alt="Tree_behaviour:_REJECT_stupid_auto-collapsing;_ADD_SMART_double-click_default!!!" src="https://github.com/piroor/treestyletab/assets/7270/722f9060-95d4-45f6-9a56-fd7e5e27887a">

**Comment by jjlee** [comment]
@jf Thank you, toggling on those two gave me the behaviour I want (before the recent changes removing them), I've updated my report with those preference labels.

**Comment by jjlee** [comment]
Ah, they're still in there, just hidden!

To get the behaviour I wanted:

- Navigate to tree style tab preferences
  - Menu bar -> Tools -> Addons and Themes
  - Select "Extensions" section (left hand side of screen)
  - Select Tree Style Tab
  - Select "Preferences"
- Check "Unlock Expert Options"
- Under "Tree behavior", unselect "When a new tree appears, collapse others automatically", and "When a tab gets focus, expand its tree and collapse others automatically"

**Comment by ugurbolat** [comment]
@jjlee thanks for the instructions. I found these defaults also disturbing.

**Comment by czert** [comment]
@jjlee thank you! Thought I was going crazy. Didn't notice the "expert options" check box.
