### ISSUE TITLE
New version 4.0.12 changed some of the styling

### ISSUE THREAD

**Issue by sgjohnson1981** [piroor/treestyletab#3526]
The new update 4.0.12 somehow changed some of the styling. As far as I can tell the borders are different. I don't know enough about CSS to mess around with this. Please change it back.

4.0.11
![old_version](https://github.com/piroor/treestyletab/assets/49596637/e9dbf4b2-e589-41ec-b340-c8eab696b3bc)

4.0.12
![new_version](https://github.com/piroor/treestyletab/assets/49596637/861c29ba-bc3b-4c15-b482-b323446cfb0f)

**Comment by sgjohnson1981** [comment]
Note: this is the High Contrast theme.

**Comment by piroor** [comment]
Hmm, could you try setting a user style sheet as following?:

```css
:root {
  --tab-border: GrayText;
}
```

Basically the "High Contrast" theme aims to provide enough contrast for handicappers about their visibility, so it prefers visibility than elegantism. In previous version the border color is defined as "ButtonShadow" but it is now same to "ButtonFace" which is used for tab faces, on recent version Firefox (I don't know it is an intentional change or a unintentional bug). "ButtonBorder" also looks too thin, so I chose "ButtonText" for the border color - which definitely have enough contrast. 

But I agree that too high contrast is also not a best choice. I think that "GrayText" - it is for text color of disabled UIs - should be between "ButtonText" and "ButtonFace" and the better choice for this case. How do you think?

**Comment by sgjohnson1981** [comment]
I have no idea what you're referring to. GrayText is similar enough to what it was. I tried playing around with the instructions for inspecting the add-on but I couldn't figure it out.

**Comment by piroor** [comment]
Sorry for less description. Here is detailed instructions:

1. Start Firefox.
2. Install TST.
3. Go to TST Options.
4. Appearance => Choose "High Contrast"
5. Advanced => User Style Sheet => add a style declaration `:root { --tab-border: GrayText; }`

**Comment by sgjohnson1981** [comment]
Sorry, I wasn't clear either. I meant the second part about the different property tags. If you just enter "GrayText" I don't understand what all the other things have to do with it. Though I am curious what other colors are available.

When I said "GrayText is similar enough" I meant I was able to change it with the CSS you included and it seems similar enough to what was in 4.0.11.

**Comment by piroor** [comment]
System colors are defined at https://www.w3.org/TR/css-color-4/#typedef-system-color but please note that chose colors may be rendered differently on other environments, for example "ButtonFace" will be a light gray and "ButtonText" will be black on environments with "Light" color scheme but "ButtonFace" will be dark gray and "ButtonText" will be white on environments with "Dark" color scheme. We addon developer need to choose better combination which is effective on various environments as possible as we can.

**Comment by SteveFromAccounting** [comment]
This worked, thanks! This changed with the recent update in both macOS Ventura as well as Windows, but changing it back to `GrayText` using the HighContrast theme still made it look black for me, so I just set it to `rgb(210, 210, 214)` manually for myself.

**Comment by ssergiienko** [comment]
_jFYI for someone who it might be useful. I got best results with `--tab-border: ButtonBorder;` which is good both in regular mode and at dark incognito._
