### ISSUE TITLE
[Enhancement] Option to re-open browser with all tabs Collapsed

### ISSUE THREAD

**Issue by fung00** [piroor/treestyletab#3545]
**Description:** an option to have the tab tree default to fully collapsed whenever the browser is re-opened after being shut down.

**Rationale:** if you're re-opening a lot of sub-trees, what you want right away is to see just the top headings so you can quickly navigate to whatever you want first.

**Note:** An option to fully re-create the previous tree state, with sections expanded or collapsed as when the browser was closed, would be nice too, but much less important (and probably much more work).

**BTW:** **_Love_** Tree Style Tab, could NOT use Firefox (or Waterfox) without it. Brilliant work, many thanks!

**Comment by piroor** [comment]
I'm negative to add this options as a built-in, because I think it is natural to restore trees' collapsed/expanded state. Instead this looks possible to implement as a helper addon. I hope it is published by someone really need it, not by me.

TST has an API to collapse tree from other addons.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#collapse-expanded-tree
The key of the feature is: you'll need to call this API only once per a window, when a browser window is opened and all tabs are completely restored. For example, listening "tabs.onCreated" and treating a window as completely restored when 500msec past from last "tabs.onCreated" event for a window.
