### ISSUE TITLE
[Enhancement] “Focus to Parent Tab” and “Collapse this Tree” in one keyboard shortcut

### ISSUE THREAD

**Issue by knoajp** [piroor/treestyletab#3570]
## Abstract
When you use Windows Explorer, you can use the same [Left] key twice to “Focus to Parent Folder” and “Collapse this Tree”.
But current Firefox doesn't allow the assignment of the same key on different functions.
(I believe I could manipulate it with the same [⌘Left] keys on TST until Firefox 56...)

## Steps to see the situation

1. Go to "about:addons".
2. Manage Keyboard Shortcuts.
3. Assign [Something] to the “Collapse this Tree”.
4. Assign [Something the same] to the “Focus to Parent Tab”.
5. You get the "Already used" error. (I don't know the exact error message in English)

For my preference, I want to assign [^Left] or [⌘Left].
(Although [⌘Left] is already assigned for the native "Back" navigation...)

## Expected result

(I suppose it is hard to have the same key assignment for multiple functions on Firefox itself, so...)

TST to have a combined function of:
“Focus to Parent Tab, or Collapse this Tree (when it has expanded children)”

```
A
 \- B
 |- C (focused)
```
↓ [^Left] keys
```
A (focused)
 \- B
 |- C
```
↓ [^Left] keys
```
A (focused & collapsed)
```

**Comment by piroor** [comment]
I've implement new keyboard shortcut slots:

* Collapse Tree or Focus to Parent Tab
* Expand Tree or Focus to First Child Tab

And, after some dogfooding, I've realized that Up/Down/Left/Right keys should move focus spatially for faviconized pinned tabs. Thus I've added more keyboard shortcut slots and assign key combinations by default as following:

* Simulate Up Key on Tree (default: Alt-Shift-Up)
  * It moves focus to the above faviconized tab, if possible.
  * Otherwise it moves focus to the previous tab without expanding its tree.
* Simulate Down Key on Tree (default: Alt-Shift-Down)
  * It moves focus to the below faviconized tab, if possible.
  * Otherwise it moves focus to the next tab without expanding its tree.
* Simulate Left Key on Tree (default: Alt-Shift-Left)
  * It moves focus to the left faviconized tab, if possible.
  * Otherwise:
    * It collapses tree if possible, otherwise moves focus to the parent, if you use sidebar with leftside appearance.
    * It expands tree if possible, otherwise moves focus to the first child, if you use sidebar with rightside appearance.
* Simulate Right Key on Tree (default: Alt-Shift-Right)
  * It moves focus to the right faviconized tab, if possible.
  * Otherwise:
    * It expands tree if possible, otherwise moves focus to the first child, if you use sidebar with leftside appearance.
    * It collapses tree if possible, otherwise moves focus to the parent, if you use sidebar with rightside appearance.

**Comment by knoajp** [comment]
I've been quite satisfied with this feature since then, but today I noticed the keys could also be triggered on texareas.
I suppose it'll be better if the keys aren't triggered on input/textareas of websites. 😉
