### ISSUE TITLE
[Enhancement] Moving multiple tabs (if selected) up or down with the default keybind for tab movement.

### ISSUE THREAD

**Issue by matru** [piroor/treestyletab#3599]
There's already a keybind implementation for moving the current tab up or down, but there isn't any to move selected (multiple ones) all at once. If I have multiple ones selected, and I use the assigned keybind, it just moves the tab that I am currently on.

I believe that the default behavior of the current keybind should track if I have multiple selection and work accordingly, not only initiate the bind to the tab I am viewing.

**Comment by piroor** [comment]
I won't add the feature to TST. It should be a separate addon for the purpose, instead of just an option of TST. It will help more Firefox users including using horizontal tab bar also.

**Comment by matru** [comment]
So is your lack of interest in implementing this in TST because such functionality can become useful to users outside TST? I do understand you approach TST addons the unix way.

If that's right, I do agree that this should become an universal function (browser agnostic too), since if someone wants to move a tab up or down, left or right, they will not have multiple tabs already selected while doing this command. Many other commands already are applied to the selected tabs, one would not expect to only close the tab he's viewing by pressing ctrl-W, while also having multiple tabs selected. 

Since I am not an addon developer myself, how much effort would something like this take for you and how's your backlog on this kind of things?

**Comment by piroor** [comment]
Yes, my policy about Firefox addons is based on the Unix way. It is from my regret about my old addon - too grown with various useful features and I unfortunately gave up to maintain it for new versions of Firefox.

Same as other native operations, I agree that multiselected tabs should be moved together when it is done by keyboard shortcuts, like they are moved by drag-and-drop. I think it should be tracked as a "bug" of Firefox and should be fixed by Firefox side, so I recommend you to report it to bugzilla.mozilla.org.

An addon for a workaround will do:

1. Track multiselected tabs and memorize their order, when the highlighted state of tabs are changed. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onHighlighted
2. Handle moved tabs. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onMoved You may need to defer further operations until multiple "tabs.onMoved" events are completely handled in a period.
3. After all "tabs.onMoved" events are handled, check positions of multiselected tabs with `tabs.query({ highlighted: true })`.
4. If only one tab was moved and the order of highlighted tabs are changed, now we need to move rest tabs also. Move rest tabs to suitable position with "tabs.move()".

**Comment by piroor** [comment]
A workaround addon or "fixed" Firefox behavior may be incompatible to TST, thus I'll need to update TST to make compatible better.

**Comment by SHHSSH** [comment]
@matru I too thought this feature would be useful but I understand piroor's lack of interest in implementing it, I believe the move tree up/down is pretty decent and I've utilised that for a long while now along with "Flatten tree" through TST More Tree Commands to allow for a quick hotkey of a flattening the tree if I'd like to merely move the individual tab with the same Tree Up/Down hotkey.

Some things in TST take a lot of interconnectivity to allow for seamless productivity, hope this helps.

**Comment by matru** [comment]
@SHHSSH I do utilize the flatten tree keybind from More Tree Commands too! The problem with moving a tab (or a tree) with a keybind is that I can't utilize the same behavior as I would do with mouse clicks, that's the following. Say I have hundreds of tabs, so scrolling is needed to navigate, and even messier to re-order in some cases, so I would like to drag say 5 tabs from somewhere and place them somewhere else (close to other relevant tabs, or maybe choose a parent for all of them, but the parent is placed far away in the tab list). There are few ways one could do this:

1.) You would select those tabs that you want to reposition and drag them through the vertical TST sidebar (or the firefox default tab bar) and finally drop them where you would like to after arriving to the new parent tab (or just any other tab) you sought.

2.) Use the default firefox Move Tab > Move tab to Start (or end), then do 1.) - in the case if the tabs you drag are way to far down on the opposite ends, this will shorten your drag and scroll distance to the parent/relevant tab.

3.) Select the tabs you want to reposition, scroll down but without dragging them, select that tab you want them to be next to, and drag them all to that place. The difference being, in this last case, the drag movement can be as little as a pixel instead of a long drag and scroll as before, but it's not as consistent as a keybind, though more consistent than drag scrolling through all your tabs.

Number three is the reason why I would like to have the keybind to move selected tabs up or down. So my question was really a proxy to resolve that issue, but then again I definitely believe it's only intuitive for the behavior of tab movement to apply to the selected tabs, not only to the one you're viewing.

**Comment by SHHSSH** [comment]
I think I understand what you mean.
Now, if I am understanding correctly, the way I work with such a situation is this;
Either, I select ONLY THE PARENT TAB of the tree which has the tabs I'd like to move in it(otherwise i'd flatten it like we discussed before and move only it) and that allows for me to hotkey on my mouse the move tree up/down.

However, I think maybe you're talking about if the tabs are mixed up throughout your TST sidebar, therefore in such cases for this I have to manually select them and within the context menu I press "V"(the access key) for "Move Tabs" and I then simply press S for Start or E for End... this is about the only real productivity macro I have found for such situations.

Additionally, though this is not totally relevant but it allows for me to access the current tab's context menu without needing to manually click on the TST sidebar, I have a python script running with image recognition of the border of my current tab
![capture_001_07082024_135036](https://github.com/user-attachments/assets/04076ff5-f5fd-4441-b07b-bb2377501f9c) it then right clicks on the corner of that via a hotkey I have set on my mouse to allow for ease of access to the tab's context menu.

Sorry if this is not what you meant, maybe I didn't fully understand... as I too would like for the native move tree up/down to be able to recognise if multiple selected tabs aren't actually in a tree and it would just move them all individually instead of the primary one of the multiple selection.

**Comment by SHHSSH** [comment]
@matru 

I should have read more clearly but was at work, since you did already mention the Move Tab native Firefox functionality.
But I did a quick Addon search and found this add-on that actually does work as you'd like - 

https://addons.mozilla.org/en-US/firefox/addon/move-tab-hotkeys/

It does act a little odd for me, but it's not surprising that it does indent the selected tabs into other trees, since obviously it wouldn't be able to acknowledge that and of course it'd be amazing if we could somehow have this work seamlessly with our current Tree Up/Down hotkey, but I think this is decent for ya.

**Comment by piroor** [comment]
The commit 2271bc9 should improve compatibility with the addon Move Tab Hotkeys.

**Comment by SHHSSH** [comment]
> The commit [2271bc9](https://github.com/piroor/treestyletab/commit/2271bc9ef6581cc790c7d9c7d5d9d570da88994d) should improve compatibility with the addon Move Tab Hotkeys.

How so may I ask? In the sense that perhaps we could use TST's hotkeys in conjunction/interoperably with the "Move Tab Hotkeys". I.e; they would work together with the same hotkey?

As I know Firefox throws a conflict message when two addons share the same hotkey, but I wonder if perhaps since it does allow you to input the same hotkey in hotkeys' options, that we could set the same hotkey for both and perhaps it would work for both? 

I dunno really what will be the interaction and will wait for the update, thanks for everything you do @piroor

**Comment by piroor** [comment]
Sorry for less information. Before the commit 2271bc9 TST failed to fixup tree structure around moved tabs when you move multi-selected tabs by something action outside of TST (e.g. drag-and-drop in the horizontal tab bar, hotkeys provided by other addons) so you would see broken tree. Now TST fixups tree structure correctly on such cases. You still need to assign different shortcuts manually for Move Tab Hotkeys and TST.

**Comment by matru** [comment]
@SHHSSH 

> I should have read more clearly but was at work, since you did already mention the Move Tab native Firefox functionality.
But I did a quick Addon search and found this add-on that actually does work as you'd like -

> https://addons.mozilla.org/en-US/firefox/addon/move-tab-hotkeys/

Perfect, this fixes the issue I had with my workflow! Thank you! And thanks @piroor for the small optimization!
