### ISSUE TITLE
[Enhancement] Tree expansion without the click

### ISSUE THREAD

**Issue by bobf32** [piroor/treestyletab#3606]
I use the feature Tree Behaviour / When a tab gets focus, expand it's tree and collapse others automatically. 

I think it would be really nice if this feature could be made, optionally, to work without having to click, but by simply hovering the mouse over the top of the tab tree. See Vivaldi tab stacks for an idea how this works. Essentially without having to click to expand / collapse each tree the navigation is far more fluid, especally with no delay between the hover and the expand. I probably save dozens of clicks a day by using using tab stack navigation. Would be a great addition to TST I think.

**Comment by piroor** [comment]
Sorry I'm negative to implement this behavior as a built-in because:

* TST's tree behavior mainly refers Windows Explorer, Adobe Illustrator, and other similar applications containing tree-like UI. On most cases I know, expanding tree with hovering looks not implemented, except while drag-and-drop. (And expanding tree by hover while drag-and-drop is already available on TST.)
* I won't use the feature personally to avoid unexpected expanding of trees. Features I never use will easily be forgotten and abandoned as unmaintained.
* The feature looks possible to be implemented with a helper extension using [TST's API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons). I hope that people seriously need the feature makes addon for that, like [other examples](https://github.com/piroor/treestyletab/wiki/Helper-addons-extending-functionality-of-TST).

**Comment by piroor** [comment]
[TST Hoverswitch](https://addons.mozilla.org/firefox/addon/tst-hoverswitch/) and [TST Folder Expand Collapse](https://addons.mozilla.org/firefox/addon/tst-folder-expand-collapse/) may be a reference to implement the feature.
