### ISSUE TITLE
[Enhancement] Save group tab in bookmarks as folder

### ISSUE THREAD

**Issue by Baerbeisser** [piroor/treestyletab#3621]
## Abstract
Bookmarks folder context option "open as tree", the folder gets opened as "group tab" (moz-extension://cf11975d-b81f-4f2a-9d07-1ea684096456/resources/group-tab.html?title=<folder>) if not disabled in settings.

If you save the tree again as bookmarks, the group tab gets saved as a bookmark, not as a folder. I think it would be more practical to save group tab as folder again, especially if you have multiple such "folders".

![Bildschirmfoto_2024-08-26_17-21-26](https://github.com/user-attachments/assets/58f825a3-08c7-405e-b346-705dc3be674c)
![Bildschirmfoto_2024-08-26_17-24-22](https://github.com/user-attachments/assets/4db8bc97-c459-43c4-83a3-729504da146d)

should be

![Bildschirmfoto_2024-08-26_17-28-03](https://github.com/user-attachments/assets/8f8e2ea3-38da-4c96-bc40-299f7cb64fe2)

**Comment by piroor** [comment]
TST is designed to skip bookmarking of the parent "group tab" when you create bookmarks from a tree. Could you present detailed steps to reproduce with the [template](https://github.com/piroor/treestyletab/blob/trunk/.github/ISSUE_TEMPLATE/bug_report.md)? For example:

1. Start Firefox and install TST.
2. Give a permission to operate bookmarks to TST.
3. Prepare three tabs:
   * tab A: about:blank?1 (active)
   * tab B: about:blank?2
   * tab C: about:blank?3
4. Shift-left-click on the tab C to multiselect three tabs.
5. Right-left-click on TST's sidebar panel and choose "Bookmark Selected Tabs...".
6. Press "Save" in the dialog.
7. Confirm that a new bookmark folder is added to the bookmarks toolbar.
8. Middle-click on the bookmark folder created in the bookmarks toolbar.
9. ...

Please note that you should describe details of the action, for example an action is done by a keyboard shortcut, a mouse operation on TST's sidebar panel, or a mouse operation on Firefox's native horizontal tab bar. It is important because the difference may affect to the reproducibility of the problem you saw.

**Comment by Baerbeisser** [comment]
I noted this is already implemented, my bad.
