### ISSUE TITLE
[Bug] Pressing Ctrl+Shift+, rearranges all tabs in all windows

### ISSUE THREAD

**Issue by npjones101** [piroor/treestyletab#3656]
## Steps to reproduce

1. Create a set of nested tabs
2. Press Ctrl+Shift+, (comma)

## Expected result

Nothing should happen with no key combo mapped to TST.

## Actual result

A selection of tabs in all windows are extracted from their current position and moved up into their own tree.

This came up because for a long time I had that keyboard shortcut mapped to outdent a tab. No other extension has this key combination mapped.

## Environment

 * Platform (OS): macOS 14.7
 * Version of Firefox: 131.0.2
 * Version (or revision) of Tree Style Tab: 4.0.24

**Comment by piroor** [comment]
TST has no default shortcut with the key combination. Did you unexpectedly set that?

**Comment by npjones101** [comment]
I had originally set that as a shortcut for outdent and that worked fine for months. But when this started happening I cleared the shortcut and set it to a different key combo. That other key combo works fine to outdent but pressing Ctrl+Shift+, still causes the tree shuffle which makes me think it's an odd interaction with some new thing in Firefox.

I created this issue because I accidentally used the old key combo and messed up all my open trees. But one other thing I noticed when interacting with the messed up tabs is that TST behaved really oddly. With some of the tree, clicking the expand carat made tabs expand/collapse below the adjacent tab instead of immediately under the tab being expanded. I restarted Firefox which restored the tabs, but they were still messed up in that way until I started dragging them back to where they should be.

**Comment by piroor** [comment]
There is no keyboard shortcut slot about "outdent" on TST itself, it is a part ot "TST More Tree Commands". Could you check shrotcuts of all other addons about tab management? For example, tab-group features which switch sets of visible tabs may break TST's tree structure.

**Comment by munael** [comment]
I observed this behavior just today, but can't confirm all the changes that happened. It surely corrupted my entire session however.

I don't have TST More Tree Commands installed or any other similar extensions.

**Comment by piroor** [comment]
@munael Does the shortcut Ctrl-Shift-, still work, and there is no such shortcut slot for that in about:addons? It is possibly triggered by an obsolete shortcut information inaccessible anymore due to removals in past versions of TST. Please try resetting everything of TST with these steps:

1. Go to TST options page.
2. Scroll to the end of the optons page.
3. Expand the "Debug" section.
4. Click "Export" button to export all configs of TST.
5. Uninstall TST.
6. Restart Firefox.
7. Install TST again.
8. Go to TST options page.
9. Scroll to the end of the options page.
10. Import the configs file saved at the step 4.

**Comment by munael** [comment]
> @munael Does the shortcut Ctrl-Shift-, still work, and there is no such shortcut slot for that in about:addons? It is possibly triggered by an obsolete shortcut information inaccessible anymore due to removals in past versions of TST. Please try resetting everything of TST with these steps:
> 
> 1. Go to TST options page.
> 2. Scroll to the end of the optons page.
> 3. Expand the "Debug" section.
> 4. Click "Export" button to export all configs of TST.
> 5. Uninstall TST.
> 6. Restart Firefox.
> 7. Install TST again.
> 8. Go to TST options page.
> 9. Scroll to the end of the options page.
> 10. Import the configs file saved at the step 4.

Thanks for the steps. Does this preserve the session structure (tab nesting)?

**Comment by piroor** [comment]
Ah, these steps will reset all tree structure for restored tabs. Thus you need to save/restore tree structure manually. There are two ways:

* Save all tabs with tree structure to bookmarks before uninstalling of TST, and reopen tabs from saved bookmarks after TST reinstalled.
* Otherwise, save tree structure manually and restore it after TST's reinstallation. Steps:
  1. Go to `about:debugging`.
  2. Click "This Firefox" in the left pane.
  3. Find "Tree Style Tab" in the "Extensions" section.
  4. Click "Inspect".
  5. Select the "Console" tab.
  6. Select "/background/background.html" from the target windows list: ![image](https://github.com/piroor/treestyletab/assets/70062/4ebd2e02-1c7e-46fc-8eb4-bdb76fd6ad00)
  7. Run following script to export tree structure information.
     ```javascript
     (async () => {
       const TreeBehavior = await import('/common/tree-behavior.js');
       const Tree = await import('/background/tree.js');
       const tabs = await Tab.getAllTabs((await browser.windows.getCurrent()).id);
       const structure = TreeBehavior.getTreeStructureFromTabs(tabs);
       console.log(JSON.stringify(structure));
     })();
     ```
  8. Copy the output text. Assume that it is `[{"id":"tab-hoary-yak-1739328392617-791","parent":-1,"collapsed":false},...]`.
  9. Uninstall TST.
  10. Restart Firefox and restore tabs.
  11. Reinstall TST.
  12. Go to `about:debugging`.
  13. Click "This Firefox" in the left pane.
  14. Find "Tree Style Tab" in the "Extensions" section.
  15. Click "Inspect".
  16. Select the "Console" tab.
  17. Select "/background/background.html" from the target windows list.
  18. Run following script to export tree structure information.
      ```javascript
      (async () => {
        const TreeBehavior = await import('/common/tree-behavior.js');
        const Tree = await import('/background/tree.js');
        const tabs = await Tab.getAllTabs((await browser.windows.getCurrent()).id);
        const structure = [{"id":"tab-hoary-yak-1739328392617-791","parent":-1,"collapsed":false},...]; // the righthand is the text copied at the step 8.
        Tree.applyTreeStructureToTabs(tabs, structure);
      })();
      ```
