### ISSUE TITLE
[Enhancement] snapshot feature enhancements to make TreeStyleTab a better OneTab alternative

### ISSUE THREAD

**Issue by gaabora** [piroor/treestyletab#3685]
## Abstract

Many of you are likely familiar with OneTab extension - while it offers some great features, it also has limitations, such as lacking support for profile containers. 
![image](https://github.com/user-attachments/assets/16944a79-28ae-414f-8724-fc54c02054ac)

TreeStyleTab is an excellent tool, and to make it even more powerful, I propose several key enhancements to make it a full alternative to OneTab.
- add "Move To" > "New Snapshot" Option in Context Menu for Selected Tabs
This feature will allow users to move selected tabs into a new snapshot directly from the context menu.

![image](https://github.com/user-attachments/assets/74bd9afb-2903-4531-b4b3-3db6c89b5964)

- add icon-button for Quick Access to Snapshots via Extension's Toolbar
Adding an easy access button on the main extension toolbar to open the Snapshots page will streamline the user experience.
![image](https://github.com/user-attachments/assets/dd97845f-e271-4bad-9ad0-2b5a924cb02b)

- add Option to Delete Existing Snapshot Tabs
A simple and intuitive way to delete unwanted snapshots would further improve the flexibility and usability of the feature.
![image](https://github.com/user-attachments/assets/66fb22a1-1c6c-41a2-9852-7f205594fb5e)

Thanks to all the contributors for their continued efforts in improving this tool!

**Comment by gaabora** [comment]
oops, sorry, wrong repo

**Comment by SHHSSH** [comment]
Wth is a snapshot? I envision this as taking a quick "preview thumbnail" like latest Firefox versions have for tabs, but allowing the user to "snapshot" all selected tabs and locally store a preview thumbnail of all of them, that'd be nice. @piroor Do you think this thought process is worthy of a feature request or is this too complicated for you to bother? (I mean mine, not OPs, I didn't even understand OPs).

Since the preview thing doesn't work for me it'd be nice to manually force it so I could peruse those thumbnails either whilst AFK or just sometimes in an explorer to help mitigate excess tabs at times. Folders have helped over the years but sometimes I feel a quick visual briefing is necessary so I often find myself having to reload unloaded tabs, of course it's not the biggest of deals and is our current way of life, but I hope someways will be innovated for more unique methods in the future.
