### ISSUE TITLE
Show pinned tabs as normal

### ISSUE THREAD

**Issue by chuntley** [piroor/treestyletab#419]
Are there plans to include an option that allows the pinned tabs to display as normal tabs, just situated at the top? This allows the user to see if the title of the tab has changed, for example, to see how many new messages are in the inbox of a Gmail tab.

Another Firefox side tabs extension does this with a small horizontal line separating the pinned tabs from the non-pinned tabs.

**Comment by ivanatpr** [comment]
>Go to about:config and set extensions.treestyletab.pinnedTab.faviconized to false, then pinned tabs are shown with the width same to other tabs. Does it help you?

Awesome. Thanks piroor!

**Comment by piroor** [comment]
Does this still happen with the latest development build?
http://piro.sakura.ne.jp/xul/xpi/nightly/

Note: if you cannot install the development build with "unsigned" error, you'll have to disable the signature check. Go to `about:config` and turn `xpinstall.signatures.required` to `false`. The preference won't available on released versions of Firefox 44 and later, so you'll have to use Firefox Developer Edition or Nightly to try the development build of TST.

**Comment by piroor** [comment]
I close this for triage.

**Comment by hackerb9** [comment]
Since `extensions.treestyletab.pinnedTab.faviconized` no longer works, what is the workaround to get pinned tabs to act like normal tabs?

**Comment by irvinm** [comment]
Go in the TST options, expand "All configs" (at the bottom), find "faviconizePinnedTabs" and uncheck that box.

**Comment by hackerb9** [comment]
Thanks. It's not working for me. The pinned tabs look like normal tabs, but they don't act like them. In particular, when I open links from them, instead of the children opening up underneath the pinned tab, they are given a fake parent and put in there. Is this a bug or was there something else I was supposed to do (or not do)?

**Comment by wwp** [comment]
The pinned tabs acts like a flat subgroup, child tabs opened from pinned tabs won't open a subtree right in the middle of the flat pinned tab, and it's a good thing. What do you expect exactly?
BTW, the fake parent is a configurable thing, go check the preferences in New tab behaviour: auto-group tabs opened from same pinned tab

**Comment by hackerb9** [comment]
I had expected pinned tabs to have a row of icons on the top (as they do by default), but that those would be simply aliases for clicking on the tab in the tree. In the tree view, pinned tabs would be normal nodes. There would be no reason to create a fake parent for children of pinned tabs as they already have a parent. 

Here's a diagram of what I expected, where Alpha, Bravo, and Charlie are tabs with icons A, B, and C, respectively.

```
[A] [B] [C]     <-- Row of favicons
[Alpha]
[Bravo]
[Charlie]
```
After clicking on some links from within tab Alpha, the TST window might look like this:

```
[A] [B] [C]
[Alpha]
    [Child A1]
    [Child A2]  
        [Grandchild A2a]
        [Grandchild A2b]
    [Child A3]
[Bravo]
[Charlie]
```

Does that make sense? Am I missing something? For example, is there a reason tabs can't be shown both in the tree and above it as favicons?

**Comment by piroor** [comment]
Pinned tabs are managed in different context with fixed positions, and it is impossible to mix up regular tabs and pinned tabs. This design completely depends on the implementation design of Firefox itself - TST just provides different view for Firefox's tabs. If descendants of pinned tabs were placed next to pinned parent tab, they must be pinned also. A dummy tab aliased to a pinned tab is a workaround for this kind problems.

You looks to need a "locked tabs" feature instead of "pinned tabs". But sadly current Firefox doesn't provide ability to implement such an addon on WebExtensions API. TST allows third-party addons to cancel mouse events on the sidebar via its API, so you may be possible to simulate "lock tab" feature on TST's sideabr with an another addon which calls the API. However the addon must become incomplete because you cannot block keyboard shortcuts of Firefox itself like Ctrl-W (close current tab).

**Comment by hackerb9** [comment]
Thank you for the explanation. It sounds like WebExtensions rules out what I had expected. 

Would it be possible, instead, to have the fake parent that is created for children of pinned tabs be like the dummy tab you mentioned? That is, it'd have the same title and would be aliased to the pinned tab so clicking on it would work correctly.

**Comment by piroor** [comment]
I tried to move focus to the opener pinned tab when an alias group tab is clicked but I gave up to do that, due to compatibility with other various operations. Such a behavior may break regular tab operations. For examle, drag and drop of such a tab, collapse/expand tree by clicking on the tab, and more. So I won't implement the behavior as a built-in.

But I'm OK to extend the API of TST for other addons, to implement the behavior. For example: get the alias tab from the pinned tab / get the pinned tab from the alias tab.

**Comment by hackerb9** [comment]
Sounds like it's a lot more complex than I had imagined! Thank you for trying and for taking the time to explain. It's beyond my ability to create such an addon for TST, but perhaps if you add the get alias / get pinned API somebody else will be up to the challenge.

**Comment by piroor** [comment]
I've added a new property `bundledTabId` to tab objects returned via TST's API. See also: https://github.com/piroor/treestyletab/wiki/API-for-other-addons#data-format

Here is an example to implement an addon to switch back to the corresponding tab (a group tab for a pinned tab, or a pinned tab for a group tab) by single click on already active tab:

```javascript
const TST_ID = 'treestyletab@piro.sakura.ne.jp';
async function registerToTST() {
  try {
    await browser.runtime.sendMessage(TST_ID, {
      type: 'register-self',
      name: browser.i18n.getMessage('extensionName'),
      icons: browser.runtime.getManifest().icons,
      listeningTypes: ['tab-mouseup']
    });
  }
  catch(e) {
    // TST is not available
  }
}
browser.runtime.onMessageExternal.addListener((message, sender) => {
  switch (sender.id) {
    case TST_ID:
      switch (message.type) {
        case 'ready':
        case 'permissions-changed':
          registerToTST();
          break;

        case 'tab-mouseup':
          if (message.tab &&
              message.tab.active &&
              message.tab.bundledTabId > 0) {
            browser.tabs.update(message.tab.bundledTabId, { active: true });
            return Promise.resolve(true);
          }
          break;
      }
      break;
  }
});
registerToTST();
```
