### ISSUE TITLE
[Feature Req.] New-tab modifier shortcut for alternate new-tab placing

### ISSUE THREAD

**Issue by Coldblackice** [piroor/treestyletab#664]
A feature I've craved over a long period of time:

Ability to use a _modifier_ key on the "New tab" keyboard shortcut to start a new tab/tree somewhere else -- like as the next "ground-level" independent tab, rather than whatever the default "New tab" behavior is (like opening new tab right next to current tab).

Other "places" options could be a modified shortcut to open a tab as the very top/first tab of the entire window, or the very bottom/last tab of the window.

For example:

I'll be working deeply nested within a sub-tree of tabs on a certain subject, like "programming". Suddenly, I'll need to look up something unrelated, like "biology". I'll press CTRL-T and it opens a new tab within the current "programming" tree I'm in. I'll then start growing the "biology" tree (within the programming tree) for a little bit while I'm on the subject. However, this eventually causes a lot of tree disorganization and clutter, and the trees ordering begins to not make sense.

I realize that I could:

-Drag the new "biology" tab outside as its own independent tree
-Create a new window and start the "biology" tab there
-Set the default "New tab" behavior to open as their own ground-level independent tabs

However, each of these options is a bit tedious (relatively, and over time). 

Manually dragging a new tab elsewhere takes a manual effort every time there's a new subject, which additional time and difficulty dragging accumulates when there are many subjects to switch between. Creating a new window adds window clutter and takes a bit of time to start up. Changing the "new tab" behavior wouldn't work because the majority of the time I want to open a new tab right beside the current one.

So it'd be great if there was a feature that can open a new tab as something other than the default behavior -- like opening a new tab as the _next ground-level_ independent tree -- but while not changing the default "New tab" behavior entirely.

E.g., if "New tab" is CTRL-T, then "New tab as _next_ ground-level independent tab" is CTRL-ALT-T (for example -- I know that shortcut's already "duplicate tab").

Visual example:

```
A.
   1.
   2.
      i.
      ii. *I'm currently on this tab. I then press the modified new-tab-as-next-ground-level-tab shortcut*
      iii.
   3.
B.
C.
D.
```

```
A.
   1.
   2.
      i.
      ii. *previous tab*
      iii.
   3
E. *I'm now on a blank/fresh new ground-level tab right here*
B.
C.
D.
```

Even better is if this New-tab-modifier feature could be set for a number of possible places, like:

New tab as: 

**_-next independent ground-level tab**_ (most ideal)
-previous independent ground-level tab
-first/top independent tab of entire window
-last/bottom independent tab of entire window
-the next tab of the current tree's parent
-the previous tab of the current tree's parent

**Comment by joshgold22** [comment]
I'd very much like this capability too.  (if I understand the above correctly; the description is very long.)

I have new tab (command-T) set to "child of the current tab" in preferences, and I always want to be able to assign a keystroke to get a new independent tab at the end of the tablist when I change tasks, rather than having to mouse over and command-click the small icon.

**Comment by coldblackice** [comment]
Josh, what would you think about forking this ourselves? I've been thinking about forking a version to add this feature and others in on my own -- I really want the ability to open tabs into various locations, like child-tab, new-tree, next-tree, child-of-next-tree, etc.

**Comment by piroor** [comment]
It is not undocumented but there is an API: `gBrowser.treeStyleTab.readyToOpenNextSiblingTabNow()`. For example you can open new next sibling tab with the code:

~~~
gBrowser.treeStyleTab.readyToOpenNextSiblingTabNow();
gBrowser.selectedTab = gBrowser.addTab('about:blank');
~~~

And, "open next independent ground-level tab" is:

~~~
var root = gBrowser.treeStyleTab.getRootTab(gBrowser.selectedTab);
gBrowser.treeStyleTab.readyToOpenNextSiblingTabNow(root);
gBrowser.selectedTab = gBrowser.addTab('about:blank');
~~~

I think these samples will help you to define custom keyboard shortcuts with "keyconfig" or some known keycustomization addon.

**Comment by piroor** [comment]
Anyway, because Firefox already has too much keyboard shortcuts by itself, it is very hard to find out "free" keyboard shortcuts for new feature. And, I think it is out of TST's target that managing dynamic keyboard shortcuts. It should be done by another addon which is designed to manage custom keyboard shortcuts.

**Comment by piroor** [comment]
I close this because this is too old and not match to the latest maintained version of TST.

**Comment by joshgold22** [comment]
Wasn't this fixed a long time ago?  I've been using Cmd-Opt-T to make a child tab (and Cmd-T for independent) for a long time now.  In TST Preferences under Keyboard Shortcuts.  

Perhaps the implementation doesn't have all of the possible positionings in the original request (I'm not sure if I understood all of the complex description) but it has Independent, Child, Sibling and Next Sibling, all four that you can get with the mouse dropdown near the "+" add button, and that's sufficient for me.

**Comment by piroor** [comment]
I think too many options for positioning of new tabs will confuse most people. (To be honest, I think "next sibling" and "sibling" are already too much, especially for new blank tabs. These options were introduced for duplicated tabs, because it is reasonable that such tabs are placed next to the source tab.)

For advanced users, more flexible options will be provided via [extra addons extending TST itself via its API](https://github.com/piroor/treestyletab/blob/master/README.md#addons-that-extend-tst). Such an addon needs to be created and maintained by someone really want to use it.

**Comment by joshgold22** [comment]
oh, I agree, I don't think there should be more options by default in TST (and having only one Sibling is proabably a good idea).  I'd misunderstood and thought the main gist was about adding keyboard shortcuts, sorry.
