### ISSUE TITLE
Tab bar on the right side blocks WebRTC (Firefox Hello) confirmation window

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#753]
Config: Current Nightly (2014-08-02 build); TST nightly 0.14.2014072700a024334; Win8.1 64bit

STR:
1. Install TST and set the tab bar on the right side.
2. In Nightly, put the "Invite someone to talk" button (a chat bubble) on toolbar from Customize.
3. Initiate a call by clicking the button and visit the generated link from another tab, another firefox instance (22+), Chrome (23+), or Opera (18+).
4. In Nightly, try to press the buttons in the confirmation window that appears on lower right corner of Nightly.

Acutal result:
TST's tab bar is blocking the confirmation window. If the tab bar is wide enough, it may be impossible to press Decline.

Expected result:
TST should not block the window.

**Comment by jirutka** [comment]
I started using Firefox Hello and this issue really a major issue.

**Comment by piroor** [comment]
Confirmed. Hmm, this seems to be very hard issue to be fixed by TST itself...

 * Firefox: The chat box is shown at the layer same to Firefox's content area. It cannot be rendered in different layer by some reason (I don't know why, but actually we cannot do it.)
 * TST: To put vertical tab bar over the content area, the tab bar must have any z-index higher than the chat box.

The current rendering tree is like:

~~~
Behind

+--[base layer] (position:static)
|   +--[content area]
|   +--[chat box]
|       +--[iframe for the chat box]
|
+--[floating layer] (position:fixed, z-index:auto)
    +--[tab bar]

Front
~~~

So I've tried to put the chat box at another floating layer, like:

~~~
Behind

+--[base layer] (position:static)
|   +--[content area]
|
+--[floating layer] (position:fixed, z-index:10)
|   +--[tab bar]
|
+--[floating layer2] (position:fixed, z-index:100)
    +--[chat box]
|       +--[iframe for the chat box] => disappear!!

Front
~~~

However, after I changed the "display" of the chat box from "static" to "fixed", suddenly the contents of the chat box disappeared. I guess that Firefox doesn't support inline frame in a floating layer made by CSS positioin:fixed.

As above, we cannot put the chat box over the tab bar by easy way...

**Comment by piroor** [comment]
By the commit 4acdd4104b9351ba8e75a04a1c7af62e98aba2d7, tentatively Firefox Hello chat boxes won't be shown behind tabs. You can try new behavior with the development build: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by Fanolian** [comment]
Thanks!
