### ISSUE TITLE
Add skin with styling that matches FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by BrianGilbert** [piroor/treestyletab#788]
I'd like to do this, is there is anything I should know before starting?

**Comment by uberspot** [comment]
Here's another one 

![](http://i.imgur.com/BPdWcQh.png)

None of the themes match or color the sidebar with the corresponding theme dark gray color. It would be cool to have some user setting for the background color of the sidebar.

**Comment by piroor** [comment]
I close this issue because a new version of TST is released. If the problem still there, please comment here. Thanks.

**Comment by uberspot** [comment]
Problem still exists in 0.16.2015122501.
Same screenshot as above ^

**Comment by lv7777** [comment]
I just installed TST, and I confirm that unchanged skin on firefox dev edition 47. 
Indeed, recent firefox dev edition was enabled by default.
thus I think hard to see further more.

**Comment by lv7777** [comment]
-moz-dialog is fixing #F0F0F0
I complete thought color of firefox toolbar.
So,need to switching by firefox theme(e.g. whenever use devedition.css or import toolbar.xul css value )

**Comment by piroor** [comment]
Did you try to apply inline style rules dynamically? Is it just experimental? Because the button is a regular DOM node but an anonymous element inserted by XBL, you have to use `document.getAnonymousNodes()` or something to access the node itself from your JS codes.

Basically, all color and other visual definitions of TST are defined in static CSS files under the "skin" dir. The theme manager module just switches active CSS files. You don't need to embed specific color definitions in any JS file - in other words, you should not do it.

The recommended way in TST's design policy is: adding a new static CSS file and just load it from the manager.
