### ISSUE TITLE
Toggle sidebar breaks the tabbar position due to landing Bug 1123517

### ISSUE THREAD

**Issue by alice0775** [piroor/treestyletab#849]
Nightly 39.0a2(2015-02-26) + TST 0.15.2015022700a010002

Steps to reproduce
1. Open Sidebar (Ctrl+B) 
2. Close Sidebar (Ctrl+B) 

Actual Results:
TabBar overlaps Web content

**Comment by Daniellynet** [comment]
Can confirm the bug happening for me too.

**Comment by chronometric** [comment]
This is the issue I reported in issue #814

**Comment by alice0775** [comment]
@chronometric
No this is different bug.

**Comment by chronometric** [comment]
Well, ok. Opening the sidebar using either omnisidebar or CTRL+B results in exactly the same overlay as pictured in the screenshots in #814.

Perhaps if you understand why that issue is doing the same thing in a different way, you could provide more information here or in that thread? Been 3 months without any comment or confirmation...

**Comment by piroor** [comment]
Fixed by 5c323d143b3640676e69933d269c74a538a370d6. Thanks!
