### ISSUE TITLE
New Feature - Add color to the tabs as an option

### ISSUE THREAD

**Issue by jclavijo** [piroor/treestyletab#901]
It would be great if colors were added to the tabs to let you know they were not-loaded, visited, active, and with new content. I've seen this feature on Tab Mix Plus and it's a really good feature if you have a lot of tabs open.

**Comment by piroor** [comment]
TST is not an all-in-one style addon. Because it is not "tree" related feature, I never merge such a feature to TST. And, increasing of code size from features I never use will make TST less maintainable.

I've confirmed that the addon ColorfulTabs https://addons.mozilla.org/firefox/addon/colorfultabs/contribute/roadblock/?src=dp-btn-primary&version=27.5.1-signed works together with TST (you have to choose the "Default" skin at TST's configuration dialog), so I strongly recommend you to install both addons instead of making TST too fat.

**Comment by Frydac** [comment]
Was also looking for this functionality.

I found this repository, which specifically colors tabs for TST, but it does not do this in much of a meaningful manner (at least to me, at this point in time).
It would be a nice starting point to implement this kind behavior as it already did some work of hooking in to TST.
https://github.com/MurzNN/TST-Colored-tabs
Browsing the firefox api, I found following docs that should make it possible to get the state for the tabs and update colors depending on them:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab
I'm guessing that the `lastAccessed` field there could be used to know when a tab is visited or not.
I have virtually no experience with javascript, but I'm guessing for ppl that do, this would not take much time. (maybe one day :) )
