### ISSUE TITLE
[Feature Request] Switch tabs by scrolling with the mouse wheel

### ISSUE THREAD

**Issue by micsutka** [piroor/treestyletab#902]
I think it could improve productivity and user-friendliness when someone have to switch tabs by mouse often.
There is already a separate addon for this feature, but perhaps it could be included in TST also:
https://addons.mozilla.org/hu/firefox/addon/tab-wheel-scroll/
Source code at github: https://github.com/mthamil/Tab-Wheel-Scroll
Does it make any sense to include this functionality into TST in order to decrease the number of installed addons?

**Comment by piroor** [comment]
TST is not an all-in-one style addon. Because it is not "tree" related feature, I never merge it to TST. And, increasing of code size from features I never use will make TST less maintainable.

I've confirmed that the addon seems to work together with TST well, so I strongly recommend you to install both addons instead of making TST too fat.
