### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by Avi0** [piroor/treestyletab#927]
Please make this addon available for Pale Moon. It's currently not working.

Thanks.

**Comment by piroor** [comment]
Sorry, because I don't use Pale Moon, I have no motivation to maintain my addons for it. Because Pale Moon is based on old Firefox, supporting Pale Moon means supporting old Firefox. Then the number of version-specific hacky codes will increase and I cannot use new, clean, safer APIs introduced in new Firefox.

Instead, you can fork TST for Pale Moon. Because the forked version don't have to support newer Firefox, maintaining of it will more easier than this original project which follows changes of Firefox.

**Comment by littledude072** [comment]
in case anyones interested, im using the 0.14.2014.051101.1 version on pale moon 25.7 and its working just fine
