### ISSUE TITLE
More accessible settings/preferences?

### ISSUE THREAD

**Issue by SRGOM** [piroor/treestyletab#940]
Perhaps in the tab bar context menu itself? I find myself using the settings whenever my tab bar refuses to resize.
Thanks for the great add-on btw.

**Comment by piroor** [comment]
The configuration UI was removed in an old version, and I dithered to re-introduce it because 1) there are already too many configuration items, and 2) it was hard to work with single configuration UI and multiple existing windows. However, I knew that such a configuration UI will help some people to fix the size of unexpectedly expanded tab bar.

By recent commits, now the configuration UI is re-introduced and it always resets the size of the tab bar on all windows. You still can resize the tab bar for each window. You can try a development build: http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by SRGOM** [comment]
You're right, I mean just having a link in the context menu to the settings box, rather than one going to add ons -> TST -> preferences

**Comment by piroor** [comment]
Oops, I misunderstood...

I clearly dislike custom menuitem to go to the configuration dialog of the addon itself, because it is hard to be maintained for future versions of Firefox, and too many "configurations..." menutiems provided by various addons are ugly.

Instead, if a configuration item is need to be accessed too frequently, then the configuration should be controlled by a seamless operation like simple drag and drop of the separator between the tab bar and the content area, without any checkbox or textbox.

Which is the configuration item you want to access very frequently to?

**Comment by SRGOM** [comment]
Well, I hav

**Comment by piroor** [comment]
> Well, I have this problem where I am unable to unhide the sidebar after hiding it. So I go to config to change its' position to top first and then to left.

Did you mean the issue?: when you activate the "hide tab bar automatically" feature, sometimes (or always) the hidden tab bar does not reappear. Then, I think it must be tracked as an issue of the auto-hide-tab-bar feature itself, because the tab bar must be shown/hidden by moving of your mouse cursor.

**Comment by SRGOM** [comment]
Yes, that is an issue too. The issue I face though is that even manually hiding makes it hard to pull it back, sometimes at all, or sometimes to its complete width. The solution is to go to preferences.

**Comment by piroor** [comment]
> The issue I face though is that even manually hiding makes it hard to pull it back, sometimes at all, or sometimes to its complete width.

You told about clicking of the "grippy" of the splitter itself (or dragging the splitter to the edge of the window to collapse the tab bar)?

**Comment by piroor** [comment]
I've tried to click the grippy of the splitter, and the tab bar is collapsed as I expected. After that I clicked the grippy again, then the tab bar is expanded as I expected too. If your tab bar is not expanded by the operation, some other tabbar related addons (like Tab Mix Plus) can conflict with TST.

**Comment by SRGOM** [comment]
Hmm, I see. Got it, thanks.

**Comment by SRGOM** [comment]
https://github.com/piroor/treestyletab/pull/1080
