### ISSUE TITLE
not working correctly with FF42

### ISSUE THREAD

**Issue by Neve** [piroor/treestyletab#973]
tab tree do not show new opened tabs
styles do not applied
tree toolbar constantly size growing when you changing autohide options in config
FF42 OSX 10.11.1

**Comment by delpass** [comment]
FF42 Ubuntu linux, same problem.

**Comment by andreykurilin** [comment]
the same situation with KUbuntu 15.10 + FF42 and Ubuntu 14.04.3 + FF42

**Comment by StevenRudenko** [comment]
same FF42 Ubuntu 14.04.3. I've installed latest version and it works for me: http://piro.sakura.ne.jp/xul/xpi/confirm.cgi?treestyletab.xpi

**Comment by Hoernchen** [comment]
It's also completely broken for me: The bookmarks bar is empty until I disable & enable it, not even the Firefox menu button in the upper right corner works, clicking on it has no effect, tabs will not be restored after a restart, and opening certain files doesn't work - i can neither install an XPI file by opening it using the File->Open File menu, nor can i open pdf files in Firefox.
Disabling Tree Style Tabs fixes all of those issues.

**Comment by piroor** [comment]
Firefox 42 compatible version is already released on AMO but it is not pushed to user environments yet by some reason - possibly because it is a preliminary-reviewed addon. Anyway you can update TST to the latest released version by your hand: install it from the web page again.

Or, there is a development build based on this repository. http://piro.sakura.ne.jp/xul/xpi/nightly/ Even if you still see problems with the latest released version, it is possibly solved on the development version.

**Comment by Hoernchen** [comment]
I didn't try the other versions, but the nightly works.

**Comment by Grief** [comment]
@piroor For me, #933 is partly fixed in FF42 under kubuntu 15.10, so please don't break it again :)

**Comment by gdanov** [comment]
FF 42 on Mac works as before with the nightly.
Thanks!

**Comment by Neve** [comment]
Thx nightly looks good
Could you pls release, I guess lots of mac and nix users waiting for update :)

**Comment by piroor** [comment]
It's already released. https://addons.mozilla.org/ja/firefox/addon/tree-style-tab/versions/0.16.2015110701

**Comment by zuckel** [comment]
With FF 42 I am unable to open new tabs (via menu, shortcut or pressing the + in the tab bar). However, this only happens when a particular other addon is active (GMX Mailcheck, not available on AMO but via http://download.gmx.net/toolbar/firefox/download_w/gmx_mailcheck.xpi). I will just deactivate the Mailcheck addon, so this is no problem for me. Just letting you know.

**Comment by ggaussling** [comment]
The same with the web.de mailcheck 3.1.3
https://addons.mozilla.org/de/firefox/addon/webde-mailcheck/

**Comment by piroor** [comment]
Can I summarize this issue as: "TST doesn't work with web.de mailcheck https://addons.mozilla.org/de/firefox/addon/webde-mailcheck/ or GMX Mailcheck http://download.gmx.net/toolbar/firefox/download_w/gmx_mailcheck.xpi"? The title of this issue is too generic and there seems to be many reporters with their own unique situations.

**Comment by spaceone** [comment]
This is really annoying as it prevents using FF at all. I don't have any web.de/GMX mail plugin. Maybe it has to do with pinned tabs?!

**Comment by spaceone** [comment]
Related to https://github.com/piroor/treestyletab/issues/987. I deactivated all addons except TST, clsoed all tabs, restarted FF and the bug is still there.

**Comment by TheJJ** [comment]
@spaceone are you sure you have the latest firefox and TST version installed from addons.mozilla.org? None of the users I know have those problems. I'm on `FF43` with `0.16.2015122501` from mozilla and can use it as i expect. I guess you installed some version from piroor's website which doesn't auto-update now.

**Comment by spaceone** [comment]
I've got 44.0 with TST 0.15. I'll try to update to 0.16. now.

**Comment by spaceone** [comment]
@TheJJ Oh this (0.16) works again, thanks!

**Comment by TheJJ** [comment]
Glad I could help.
@piroor I think this issue is obsolete by now :)
