### ISSUE TITLE
Bug in "When a parent tab is closed -> Promote the first child tab as the new parent"

### ISSUE THREAD

**Issue by Tragen** [piroor/treestyletab#988]
Have a tree like
>Tab1
>>Tab1.1
>>>Tab1.1.1
>>>Tab1.1.2
>>>Tab1.1.3

When I close Tab1.1 I expect the tree to be

>Tab1
>>Tab1.1.1
>>>Tab1.1.2
>>>Tab1.1.3

Now I get

>Tab1
>>Tab1.1.1
>>Tab1.1.2
>>Tab1.1.3

I'm sure it was working already in an earlier version.

**Comment by piroor** [comment]
This is not an unexpected bug but a designed behavior - it's a special behavior on an edge case. The `Tab1` is the grandparent of `Tab1.1.x` tabs, and the parent `Tab1.1` is the *last child of the `Tab1`*. See also: https://github.com/piroor/treestyletab/blob/master/modules/browser.js#L5624

**Comment by Tragen** [comment]
Is there a reason to do it like this?
I don't see a hidden pref in the code. Is it possible that you add one to disable this special behavior?

**Comment by piroor** [comment]
Basically, I think that the "promote first child to the new parent" behavior is required to bundle child tabs as a group, after the parent is closed. If there is another tab `Tab1.2` beside the `Tab 1.1`, this behavior seems better than "promote all children to the parent level" behavior - because it will mix third-level `Tab1.1.x` tabs with existing second-level tab `Tab1.2`.

In other words, when there is no sibling like `Tab1.2` for the tab `Tab1.1`, we don't need to promote the `Tab1.1.1` to the new parent to bundle those third-level tabs, because they are already bundled under the grantparent `Tab1`. But, yes, if you open new tabs from `Tab1` after `Tab1.1` is closed, new second-level tabs will be mixed with old third-level tabs. Then, a new option to disable this special edge case behavior seems to be reasonable for such cases.

When I dig sources of Firefox itself via mxr.mozilla.org, I usually open 10 or more tabs from a search result tab. And, because I dig more and more for each source, there are usually too many, too deeply nested tabs. In such case, I often see too deeply nested tree like the tree with the new parent `Tab1.1.1`, after needless tabs are closed. I was very tired to close new parent tabs `Tab1.1.1`, `1.1.2`, `1.1.3`, and more, again and again. So this edge case behavior is very useful (and required) for me to keep tree of tabs shallowly.

**Comment by piroor** [comment]
The commit 3427845 introduces a new secret preference `extensions.treestyletab.closeParentBehavior.promoteAllChildrenWhenParentIsLastChild` (default:`true`) which controls the safeguard behavior on the edge case.

**Comment by Tragen** [comment]
Thank you very much. You are my hero. :)
