### ISSUE TITLE
sound indicator in collapse sub trees

### ISSUE THREAD

**Issue by ven-til** [piroor/treestyletab#992]
![sound_icon_in_collapse](https://cloud.githubusercontent.com/assets/15824183/11133030/6f5e1436-89a4-11e5-97f0-3933fc0f45e0.png)

**Comment by piroor** [comment]
Hmm, how do you think? I have an idea: an indicator in a parent tab to control child tab's one. I think it should work as:

 * If there is no sounding tab, the parent tab should have no indicator.
 * If there are one ore more sounding children, the parent tab should have an indicator.
   * When it is clicked, it toggles status of all sounding children.
   * When there are both "sounding" and "muted" children, the parent tab have only one "sounding" indicator. Clicking on it mutes both children. (Clicking again un-mutes them.)
   * If both the parent and any child are "sounding", same to above.

However this behavior seems very complex. It will introduce new compatibility issues to TST...

BTW, my another addon "Multiple Tab Handler" also should have functions to control the button.

**Comment by ven-til** [comment]
"However this behavior seems very complex. It will introduce new compatibility issues to TST..."

You can try this option:
Click on the indicator on the parent tab, mutes the parent tab (if there was)
a) and expand children's tab
or
b) expand the children's tabs, tabs with sound flash several times
or
c) only expand the children's tabs

**Comment by piroor** [comment]
By recent commits I simply did it:

 * If there is no sounding tab, the parent tab should have no indicator.
 * If there are one ore more sounding children *or the parent tab itself*, the parent tab has an indicator.
   * When the indicator icon is clicked, it toggles status of all sounding children *and itself*.
   * When there are both "sounding" and "muted" children *or itself*, the parent tab always have "sounding" indicator.
     * In other words, the "muted" indicator is shown only when all children and itself are muted.
     * Clicking on the "sounding" indicator, mutes all sounding children *and itself*. Already muted tabs are ignored.

Already muted children should not unmuted by clicking of the indicator, if there are mixed children: muted and sounding (not implemented yet.) I think this behavior is similar to toggling of visibility in Adobe Illustrator's layers and objects, except that visibility of AI's layer/group always affects to all descendants. And, I think I should not any option for this behavior except the master option to toggle all of them, because too detailed trivial options will confuse users.

**Comment by Vanav** [comment]
I use TST as flat vertical tabs (no indent). If one tab has sound, see multiple sound indicators on other tabs that has no sound, but maybe are parents. Maybe this bug is related to this issue?
I can suggest to not show extra sound indicators if tree is expanded or not indented.

**Comment by piroor** [comment]
Oh, I missed that. The commit 35783c647f74dc1dd2f72221039226ab928e91ba hides a sound indicator in uncollapsable parent tab. (However, by #1070, now TST never support flat vertical tab bar without indentation.)

**Comment by zeus2615** [comment]
This does not works well now. TST@0.19.2017061601   fx@54.0
click on parent will mute, but next click will not toggle status of children.

"If there are one ore more sounding children or the parent tab itself, the parent tab has an indicator.

    When the indicator icon is clicked, it toggles status of all sounding children and itself."

**Comment by piroor** [comment]
TST 0.19.x is already obsolete, so I close this.
